---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 'ONTAP System Manager 클래식 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 iSCSI 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESXi 호스트 컴퓨터에서 iSCSI 이니시에이터를 사용하여 LUN을 사용할 수 있습니다.' 
---
= VSC 개요를 사용한 ESXi용 iSCSI 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 iSCSI 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESXi 호스트 컴퓨터에서 iSCSI 이니시에이터를 사용하여 LUN을 사용할 수 있습니다.

다음 경우에 이 절차를 사용합니다.

* ESXi 5.x에서 기본 ESXi iSCSI 소프트웨어 이니시에이터를 사용하고 있습니다
* iSCSI에 대해 CHAP 인증을 사용하고 있지 않습니다.
* 지원되는 VSC(Virtual Storage Console for VMware vSphere)를 사용하여 ESX 호스트의 스토리지 설정을 구성하고 있습니다.
+
** VSC 7.0부터는 VSC가 의 일부입니다 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere용 ONTAP 툴"^] VSC, VASA(vStorage APIs for Storage Awareness) 공급자, VMware vSphere 기능을 위한 SRA(Storage Replication Adapter)를 포함하는 가상 어플라이언스
** 를 확인하십시오 https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^] 현재 ONTAP 및 VSC 릴리스 간의 호환성을 확인합니다.


* 네트워크는 IPv4 주소 지정을 사용합니다.
* 다음 방법 중 하나를 사용하여 논리 인터페이스에 주소를 할당하려고 합니다.
+
** 정의한 서브넷에서 자동으로
** 기존 서브넷에서 선택한 주소를 사용하여 수동으로 입력합니다
** 기존 서브넷에 추가할 주소를 사용하여 수동으로 입력합니다


* 클러스터의 각 노드에서 최소 2개의 고속 이더넷 포트(1GbE 최소, 10GbE 권장)를 사용할 수 있습니다.
+
온보드 UTA2(또는 `CNA`) 포트를 구성할 수 있습니다. ONTAP CLI에서 이러한 포트를 구성합니다. 이 프로세스는 HIS 절차에서 다루지 않습니다.

+
을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 관리"^] CLI를 사용하여 이더넷 포트 흐름 제어를 구성하는 데 사용됩니다.

* iSCSI SAN 부팅을 구성하지 않습니다.
* VM 내에서 iSCSI 이니시에이터를 실행하지 않고 ESXi 하이퍼바이저를 통해 VM에 스토리지를 제공하고 있습니다.


자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: ONTAP용 VMware vSphere"^] VSC 릴리즈에 대한 설명서를 제공합니다.
