---
permalink: online-help-96-97/concept_cifs_protocol.html 
sidebar: sidebar 
keywords: cif, protocol, system, manager, enable, configure, server, client, file, cluster, online, help, set up, general, properties, edit 
summary: System Manager를 사용하여 CIFS 클라이언트가 클러스터의 파일에 액세스할 수 있도록 CIFS 서버를 설정 및 구성할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 CIFS 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 CIFS 클라이언트가 클러스터의 파일에 액세스할 수 있도록 CIFS 서버를 설정 및 구성할 수 있습니다.



== CIFS를 설정합니다

System Manager를 사용하여 CIFS 클라이언트가 클러스터의 파일에 액세스할 수 있도록 CIFS 서버를 설정 및 구성할 수 있습니다.

.시작하기 전에
* CIFS 라이센스가 스토리지 시스템에 설치되어 있어야 합니다.
* Active Directory 도메인에서 CIFS를 구성하는 동안 다음 요구 사항이 충족되어야 합니다.
+
** DNS를 올바르게 설정 및 구성해야 합니다.
** 스토리지 시스템은 FQDN(정규화된 도메인 이름)을 사용하여 도메인 컨트롤러와 통신할 수 있어야 합니다.
** 클러스터와 도메인 컨트롤러 간의 시간 차이(클럭 차이)는 5분 이내여야 합니다.


* SVM(스토리지 가상 시스템)에서 CIFS가 구성된 유일한 프로토콜인 경우 다음 요구사항을 충족해야 합니다.
+
** 루트 볼륨 보안 스타일은 NTFS여야 합니다.
+
기본적으로 System Manager에서는 보안 스타일을 UNIX로 설정합니다.

** 고급 사용자 액세스를 로 설정해야 합니다 `Any` CIFS 프로토콜




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 구성 * 탭에서 * 설정 * 을 클릭합니다.
. CIFS 서버 설정 * 대화 상자의 * 일반 * 탭에서 NetBIOS 이름과 Active Directory 도메인 세부 정보를 지정합니다.
. 옵션 * 탭을 클릭한 후 다음 작업을 수행합니다.
+
** SMB 설정 영역에서 필요에 따라 SMB 서명 확인란 및 SMB 암호화 확인란을 선택하거나 선택 취소합니다.
** 기본 UNIX 사용자를 지정합니다.
** WINS 서버 영역에서 필요한 IP 주소를 추가합니다.


. 설정 * 을 클릭합니다.




== CIFS에 대한 일반 속성을 편집합니다

System Manager를 사용하여 기본 UNIX 사용자 및 기본 Windows 사용자와 같은 CIFS의 일반 속성을 수정할 수 있습니다. CIFS 서버에 대한 SMB 서명을 설정하거나 해제할 수도 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 구성 * 탭에서 * 옵션 * 을 클릭합니다.
. CIFS 옵션 * 대화 상자에서 필요에 따라 다음 CIFS 서버 속성을 수정합니다.
+
** Unix 사용자입니다
** Windows 사용자
** IP 주소입니다
** SMB 서명을 설정하거나 해제합니다
+
SMB 서명을 사용하면 데이터가 손상되는 것을 방지할 수 있습니다. 그러나 네트워크 트래픽은 동일하게 유지되지만 클라이언트와 서버 모두에서 CPU 사용량이 증가하는 형태로 성능이 저하될 수 있습니다. 재생 공격에 대한 보호가 필요하지 않은 모든 Windows 클라이언트에서 SMB 서명을 사용하지 않도록 설정할 수 있습니다.

+
Windows 클라이언트에서 SMB 서명을 사용하지 않도록 설정하는 방법에 대한 자세한 내용은 Microsoft Windows 설명서를 참조하십시오.

** SMB 3.0 암호화를 사용하거나 사용하지 않도록 설정합니다
+
SMB 3.0 세션과 전송 연결 간에 여러 채널을 설정할 수 있도록 SMB Multichannel을 설정해야 합니다.



. 저장 * 또는 * 저장 후 닫기 * 를 클릭합니다.


* 관련 정보 *

xref:task_creating_cifs_share.adoc[CIFS 공유를 생성하는 중입니다]

xref:reference_cifs_window.adoc[CIFS 창]

xref:task_editing_volume_properties.adoc[볼륨 속성 편집]

xref:task_modifying_export_policy_rules.adoc[엑스포트 정책 규칙을 수정합니다]

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS 관리"]
