---
permalink: online-help-96-97/concept_qtrees.html 
sidebar: sidebar 
keywords: system, manager, create, edit, delete, qtree, partition, data, policies, svm 
summary: System Manager에서 qtree를 생성, 편집, 삭제할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 qtree 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 qtree를 생성, 편집 및 삭제할 수 있습니다.



== qtree를 생성합니다

Qtree를 사용하면 볼륨 내에서 데이터를 관리하고 분할할 수 있습니다. System Manager의 Create Qtree 대화 상자를 사용하여 스토리지 시스템의 볼륨에 새 qtree를 추가할 수 있습니다.

.단계
. 스토리지 * > * qtree * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 qtree를 생성할 스토리지 가상 시스템(SVM)을 선택합니다.
. Create * 를 클릭합니다.
. Create Qtree * 대화 상자의 * Details * 탭에서 qtree의 이름을 입력합니다.
. qtree를 추가할 볼륨을 선택합니다.
+
볼륨 찾아보기 목록에는 온라인 상태인 볼륨만 포함됩니다.

. qtree에 대한 임시 잠금(oplocks)을 해제하려면 이 Qtree*에서 파일 및 디렉토리에 대한 oplocks 사용 확인란의 선택을 취소합니다.
+
기본적으로 각 qtree에 대해 oplocks가 설정됩니다.

. 상속된 기본 보안 스타일을 변경하려면 새 보안 스타일을 선택합니다.
+
qtree의 기본 보안 스타일은 qtree가 포함된 볼륨의 보안 스타일입니다.

. 상속된 기본 엑스포트 정책을 변경하려면 기존 엑스포트 정책을 선택하거나 엑스포트 정책을 생성하십시오.
+
qtree의 기본 엑스포트 정책은 qtree가 포함된 볼륨에 할당된 엑스포트 정책입니다.

. 디스크 공간 사용을 제한하려면 * Quotas * 탭을 클릭합니다.
+
.. qtree에 할당량을 적용하려면 * Qtree quota * 를 클릭한 다음 디스크 공간 한도를 지정합니다.
.. qtree의 모든 사용자에 대해 할당량을 적용하려면 * 사용자 할당량 * 을 클릭한 다음 디스크 공간 제한을 지정합니다.


. Create * 를 클릭합니다.
. 생성한 qtree가 * qtree * 창의 qtree 목록에 포함되어 있는지 확인합니다.




== qtree를 삭제합니다

System Manager를 사용하면 qtree를 삭제하고 볼륨 내에서 qtree가 사용하는 디스크 공간을 재확보할 수 있습니다. qtree를 삭제할 경우 해당 qtree에 해당하는 모든 할당량이 ONTAP에 의해 더 이상 적용되지 않습니다.

.시작하기 전에
* qtree 상태가 정상이어야 합니다.
* qtree에 LUN이 포함되지 않아야 합니다.


.단계
. 스토리지 * > * qtree * 를 클릭합니다.
. qtree * 창에서 삭제할 하나 이상의 qtree를 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.
. 삭제한 qtree가 * qtree * 창의 qtree 목록에 더 이상 포함되지 않는지 확인합니다.




== Qtree를 편집합니다

System Manager를 사용하여 보안 스타일, 임시 잠금(oplocks) 설정 또는 해제, 새 엑스포트 정책 또는 기존 엑스포트 정책과 같은 qtree의 속성을 수정할 수 있습니다.

.단계
. 스토리지 * > * qtree * 를 클릭합니다.
. 편집할 qtree를 선택한 다음 * 편집 * 을 클릭합니다.
. Qtree * 편집 대화 상자에서 필요에 따라 다음 속성을 편집합니다.
+
** oplocks
** 보안 스타일
** 엑스포트 정책


. 저장 * 을 클릭합니다.
. qtree * 창에서 선택한 qtree에 대한 변경 사항을 확인합니다.




== qtree에 엑스포트 정책을 할당합니다

전체 볼륨을 내보내는 대신, 볼륨에 있는 특정 qtree를 엑스포트하여 클라이언트에서 직접 액세스할 수 있습니다. System Manager를 사용하여 qtree에 엑스포트 정책을 지정하여 qtree를 내보낼 수 있습니다. Qtree 창에서 하나 이상의 qtree에 엑스포트 정책을 할당할 수 있습니다.

.단계
. 스토리지 * > * qtree * 를 클릭합니다.
. SVM 필드의 드롭다운 메뉴에서 내보낼 qtree가 있는 스토리지 가상 머신(SVM)을 선택합니다.
. 엑스포트 정책을 할당할 하나 이상의 qtree를 선택한 다음 * 엑스포트 정책 변경 * 을 클릭합니다.
. Export Policy * (정책 내보내기 *) 대화 상자에서 내보내기 정책을 생성하거나 기존 엑스포트 정책을 선택합니다.
+
link:task_creating_export_policy.html["엑스포트 정책 생성"]

. 저장 * 을 클릭합니다.
. qtree에 할당한 엑스포트 정책과 관련 엑스포트 규칙이 해당 qtree의 * Details * 탭에 표시되는지 확인합니다.




== qtree 정보를 봅니다

System Manager에서 qtree 창을 사용하여 qtree, 이름, 보안 스타일, qtree 상태 및 oplocks 상태가 포함된 볼륨을 볼 수 있습니다.

.단계
. 스토리지 * > * qtree * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 정보를 확인할 qtree가 있는 스토리지 가상 머신(SVM)을 선택합니다.
. 표시된 qtree 목록에서 qtree를 선택합니다.
. qtree * 창에서 qtree 세부 정보를 검토합니다.




== Qtree 옵션

qtree는 논리적으로 정의된 파일 시스템으로, FlexVol 볼륨 내의 루트 디렉토리에 있는 특수 하위 디렉토리로 존재할 수 있습니다. Qtree는 볼륨 내에서 데이터를 관리하고 파티셔닝하는 데 사용됩니다.

볼륨이 포함된 FlexVol에서 qtree를 생성하는 경우 qtree가 디렉토리로 표시됩니다. 따라서 볼륨을 삭제할 때 실수로 Qtree를 삭제하지 않도록 주의해야 합니다.

qtree를 생성할 때 다음 옵션을 지정할 수 있습니다.

* qtree의 이름입니다
* qtree가 상주할 볼륨입니다
* oplocks
+
기본적으로 qtree에 대해 oplocks가 설정됩니다. 전체 스토리지 시스템에 대해 oplocks를 해제하면 각 qtree에 대해 oplocks를 설정하더라도 oplocks가 설정되지 않습니다.

* 보안 스타일
+
보안 스타일은 UNIX, NTFS 또는 혼합(UNIX 및 NTFS)일 수 있습니다. 기본적으로 qtree의 보안 스타일은 선택한 볼륨의 보안 스타일과 동일합니다.

* 엑스포트 정책
+
새 엑스포트 정책을 생성하거나 기존 정책을 선택할 수 있습니다. 기본적으로 qtree의 엑스포트 정책은 선택한 볼륨의 엑스포트 정책과 동일합니다.

* qtree 및 사용자 할당량에 대한 공간 사용 제한




== Qtree 창

Qtree 창을 사용하여 Qtree에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
새 qtree를 생성할 수 있는 Create Qtree 대화 상자를 엽니다.

* * 편집 *
+
Qtree 편집 대화 상자를 엽니다. 이 대화 상자에서 보안 스타일을 변경하고 qtree에서 oplocks(편의적 잠금)를 설정하거나 해제할 수 있습니다.

* * 수출 정책 변경 *
+
하나 이상의 qtree를 새 엑스포트 정책 또는 기존 엑스포트 정책에 할당할 수 있는 엑스포트 정책 대화 상자를 엽니다.

* * 삭제 *
+
선택한 qtree를 삭제합니다.

+
선택한 qtree의 상태가 정상이 아닌 경우 이 버튼이 비활성화됩니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== qtree 목록

qtree 목록에는 qtree가 있는 볼륨과 qtree 이름이 표시됩니다.

* * 이름 *
+
qtree의 이름이 표시됩니다.

* * 볼륨 *
+
qtree가 상주하는 볼륨의 이름을 표시합니다.

* * 보안 스타일 *
+
qtree의 보안 유형을 지정합니다.

* * 상태 *
+
qtree의 현재 상태를 지정합니다.

* oplocks *
+
qtree에 대해 oplocks 설정을 사용할지 여부를 지정합니다.

* * 정책 내보내기 *
+
qtree가 할당된 엑스포트 정책의 이름을 표시합니다.





=== 세부 정보 영역

* * 세부 정보 탭 *
+
qtree가 포함된 볼륨의 마운트 경로, 엑스포트 정책에 대한 세부 정보, 엑스포트 정책 규칙 등 선택한 qtree에 대한 자세한 정보를 표시합니다.



* 관련 정보 *

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP 개념"^]

https://docs.netapp.com/us-en/ontap/volumes/index.html["논리적 스토리지 관리"^]

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 관리"^]

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS 관리"^]
