---
permalink: online-help-96-97/concept_network_interfaces.html 
sidebar: sidebar 
keywords: system, manager, network, interface, create, manage, online, help, create, lif, intercluster, svm, migrate, data 
summary: System Manager를 사용하여 네트워크 인터페이스를 생성하고 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 네트워크 인터페이스를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 네트워크 인터페이스를 생성하고 관리할 수 있습니다.



== 네트워크 인터페이스를 생성합니다

System Manager를 사용하면 네트워크 인터페이스 또는 LIF를 생성하여 SVM(스토리지 가상 머신)의 데이터에 액세스하고, SVM을 관리하고, 인터클러스터 연결을 위한 인터페이스를 제공할 수 있습니다.

.시작하기 전에
서브넷과 연결된 브로드캐스트 도메인에는 할당된 포트가 있어야 합니다.

.이 작업에 대해
* 동적 DNS(DDNS)는 LIF가 생성될 때 기본적으로 활성화됩니다.
+
하지만 iSCSI, NVMe 또는 FC/FCoE 프로토콜을 사용하거나 관리 액세스만 사용하도록 LIF를 인터클러스터 통신하도록 구성하는 경우 DDNS가 비활성화됩니다.

* 서브넷을 사용하거나 서브넷을 사용하지 않고 IP 주소를 지정할 수 있습니다.
* 포트의 성능이 저하된 경우 System Manager를 사용하여 네트워크 인터페이스를 생성할 수 없습니다.
+
이러한 경우 CLI(Command-Line Interface)를 사용하여 네트워크 인터페이스를 생성해야 합니다.

* SVM의 데이터 보호 LIF를 생성하려면 SVM에 NVMe 서비스가 이미 설치되어 있어야 하며, NVMeoF 가능 어댑터를 사용할 수 있어야 합니다.
* 선택한 SVM에 NVMe 서비스가 구성된 경우에만 NVMe 프로토콜이 활성화됩니다.


.단계
. Network * > * Network Interfaces * 를 클릭합니다.
. Create * 를 클릭합니다.
. 네트워크 인터페이스 만들기 * 대화 상자에서 인터페이스 이름을 지정합니다.
. 인터페이스 역할 지정:
+
|===
| 원하는 작업 | 그러면... 


 a| 
네트워크 인터페이스를 데이터 LIF와 연결합니다
 a| 
.. 데이터 서비스 * 를 선택합니다.
.. 네트워크 인터페이스를 위한 SVM을 선택합니다.




 a| 
네트워크 인터페이스를 인터클러스터 LIF와 연결합니다
 a| 
.. Intercluster Connectivity * 를 선택합니다.
.. 네트워크 인터페이스에 대한 IPspace를 선택합니다.


|===
. 적절한 프로토콜을 선택합니다.
+
인터페이스는 선택된 프로토콜을 사용하여 SVM의 데이터에 액세스합니다.

+
[NOTE]
====
NVMe 프로토콜을 선택하면 나머지 프로토콜이 비활성화됩니다. NAS(CIFS 및 NFS) 프로토콜이 지원되는 경우 계속 사용할 수 있습니다. NVMe 프로토콜을 선택하면 NVMe 전송 필드가 표시되고 FC-NVMe가 전송 프로토콜로 표시됩니다.

====
. 데이터 LIF에서 관리 액세스를 활성화하려면 * 관리 액세스 사용 * 확인란을 선택합니다.
+
FC/FCoE 또는 NVMe 프로토콜을 사용하는 인터클러스터 LIF 또는 LIF에 대한 관리 액세스를 설정할 수 없습니다.

. IP 주소 할당:
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 아직 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
... 대상 필드의 기본값을 사용하지 않으려면 새 대상 값을 지정합니다.
+
대상 값을 지정하지 않으면 대상 필드는 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.



+
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.

.. 확인 * 을 클릭합니다.


|===
. Port * 세부 정보 영역에서 필요한 포트를 선택합니다.
+
** 데이터 LIF의 경우 포트 세부 정보 영역에 SVM의 IPspace와 연결된 브로드캐스트 도메인의 모든 포트가 표시됩니다.
** 인터클러스터 LIF의 경우 포트 세부 정보 영역에 필요한 IPspace와 연결된 브로드캐스트 도메인의 모든 포트가 표시됩니다.
** NVMe 프로토콜을 선택한 경우 포트 세부 정보 영역에 NVMe 가능 어댑터만 표시됩니다.


. * 선택 사항: * DDNS(동적 DNS) * 확인란을 선택하여 DDNS를 활성화합니다.
. Create * 를 클릭합니다.




== 네트워크 인터페이스 설정을 편집합니다

System Manager를 사용하여 네트워크 인터페이스를 수정하여 데이터 LIF에 대한 관리 액세스를 설정할 수 있습니다.

.이 작업에 대해
* System Manager를 통해 클러스터 LIF, 클러스터 관리 LIF 또는 노드 관리 LIF의 네트워크 설정을 수정할 수 없습니다.
* 인터클러스터 LIF에 대한 관리 액세스를 활성화할 수 없습니다.


.단계
. Network * > * Network Interfaces * 를 클릭합니다.
. 수정할 인터페이스를 선택한 다음 * 편집 * 을 클릭합니다.
. 네트워크 인터페이스 편집 * 대화 상자에서 필요에 따라 네트워크 인터페이스 설정을 수정합니다.
. 저장 후 닫기 * 를 클릭합니다.




== 네트워크 인터페이스를 삭제합니다

System Manager를 사용하여 네트워크 인터페이스를 삭제하여 인터페이스의 IP 주소를 해제한 다음 다른 목적으로 IP 주소를 사용할 수 있습니다.

.시작하기 전에
네트워크 인터페이스의 상태를 비활성화해야 합니다.

.단계
. Network * > * Network Interfaces * 를 클릭합니다.
. 삭제할 인터페이스를 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== LIF 마이그레이션

소스 포트에 장애가 발생하거나 유지 관리가 필요한 경우 System Manager를 사용하여 데이터 LIF 또는 클러스터 관리 LIF를 동일한 노드의 다른 포트 또는 클러스터 내의 다른 노드로 마이그레이션할 수 있습니다.

.시작하기 전에
대상 노드와 포트가 작동 중이고 소스 포트와 동일한 네트워크에 액세스할 수 있어야 합니다.

.이 작업에 대해
* 노드에서 NIC를 제거하는 경우 NIC에 속한 포트에서 호스팅되는 LIF를 클러스터의 다른 포트로 마이그레이션해야 합니다.
* iSCSI LIF 또는 FC LIF는 마이그레이션할 수 없습니다.


.단계
. Network * > * Network Interfaces * 를 클릭합니다.
. 마이그레이션할 인터페이스를 선택하고 * migrate * 를 클릭합니다.
. 인터페이스 마이그레이션 * 대화 상자에서 LIF를 마이그레이션할 대상 포트를 선택합니다.
. * 선택 사항: * 대상 포트를 LIF의 새 홈 포트로 설정하려면 * Migrate permanently * 확인란을 선택합니다.
. 마이그레이션 * 을 클릭합니다.


* 관련 정보 *

xref:reference_network_window.adoc[네트워크 창]

xref:task_configuring_iscsi_protocol_on_svms.adoc[SVM에서 iSCSI 프로토콜 구성]

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP 개념"]

https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 관리"]
