---
permalink: online-help-96-97/concept_unix.html 
sidebar: sidebar 
keywords: system, manager, unix, svm, online, help, command, button, group, tab, storage, virtual, machine 
summary: 'System Manager를 사용하여 각 SVM(스토리지 가상 머신)에 대한 로컬 UNIX 사용자 및 그룹 목록을 관리할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하는 로컬 UNIX 사용자 및 그룹
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SVM(스토리지 가상 머신)별로 로컬 UNIX 사용자 및 그룹 목록을 유지할 수 있습니다.



== UNIX 창

UNIX 창을 사용하여 각 SVM(스토리지 가상 머신)에 대한 로컬 UNIX 사용자 및 그룹 목록을 유지할 수 있습니다. 로컬 UNIX 사용자 및 그룹을 인증 및 이름 매핑에 사용할 수 있습니다.



=== 그룹 탭

Groups 탭을 사용하여 SVM에 로컬인 UNIX 그룹을 추가, 편집 또는 삭제할 수 있습니다.



== 명령 버튼

* * 그룹 추가 *
+
Add Group 대화 상자를 엽니다. 이 대화 상자에서 SVM에 로컬인 UNIX 그룹을 생성할 수 있습니다. 로컬 UNIX 그룹은 로컬 UNIX 사용자와 함께 사용됩니다.

* * 편집 *
+
그룹 ID를 편집할 수 있는 그룹 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 그룹을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 그룹 목록

* * 그룹 이름 *
+
그룹의 이름을 표시합니다.

* * 그룹 ID *
+
그룹의 ID를 표시합니다.





=== 사용자 탭

사용자 * 탭을 사용하여 SVM에 로컬인 UNIX 사용자를 추가, 편집 및 삭제할 수 있습니다.



=== 명령 버튼

* * 사용자 추가 *
+
Add User 대화 상자를 엽니다. 이 대화 상자에서 SVM에 로컬인 UNIX 사용자를 생성할 수 있습니다.

* * 편집 *
+
사용자가 속한 사용자 ID, UNIX 그룹 및 사용자의 전체 이름을 편집할 수 있는 사용자 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 사용자를 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 사용자 목록

* * 사용자 이름 *
+
사용자의 이름을 표시합니다.

* * 사용자 ID *
+
사용자의 ID를 표시합니다.

* * 전체 이름 *
+
사용자의 전체 이름을 표시합니다.

* * 기본 그룹 ID *
+
사용자가 속한 그룹의 ID를 표시합니다.

* * 기본 그룹 이름 *
+
사용자가 속한 그룹의 이름을 표시합니다.


