---
permalink: online-help-96-97/concept_what_nvme_subsystem_is.html 
sidebar: sidebar 
keywords: nvme, subsystem, fc, rdma, transport, port, vserver, online, help, controller, cluster, table, settings, manage 
summary: 'NVMe 하위 시스템에는 하나 이상의 컨트롤러, 하나 이상의 네임스페이스, 하나 이상의 비휘발성 메모리(NVM) 하위 시스템 포트(FC-NVMe 또는 RDMA 전송 포트), NVM 스토리지 미디어, 컨트롤러와 NVM 스토리지 미디어 간의 인터페이스가 포함됩니다. 컨트롤러 매핑 및 관리를 위해 NVM 하위 시스템은 ONTAP의 가상 서버에 매핑됩니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 NVMe 하위 시스템을 관리하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 NVMe 하위 시스템을 생성하고 관리할 수 있습니다. SVM 내의 여러 호스트 및 네임스페이스와 NVMe 하위 시스템을 연결할 수 있습니다. 또한 각 가상 서버는 둘 이상의 NVMe 하위 시스템을 지원할 수 있습니다. 그러나 여러 SVM에서 사용하도록 NVMe 서브시스템을 구성할 수는 없습니다.



== NVMe 하위 시스템을 생성합니다

System Manager를 사용하여 NVMe 서브시스템을 생성할 수 있습니다.

.단계
. NVMe Subsystems * 창에서 * Create * 를 클릭합니다.
. 다음 필드에 * NVMe Subsystems:Create * 창에 항목을 제공합니다.
+
** * SVM *
+
드롭다운 메뉴에서 서브시스템을 생성할 SVM을 선택합니다.

** * 이름 *
+
하위 시스템의 이름을 입력합니다. SVM에 서브시스템 이름이 이미 존재할 수 없습니다. 이름은 대/소문자를 구분하며 96자로 제한됩니다. 특수 문자를 사용할 수 있습니다.

** * 호스트 OS *
+
드롭다운 메뉴에서 하위 시스템의 호스트 OS 유형을 선택합니다.

** * 호스트 NQN *
+
컨트롤러에 연결된 호스트 NQN을 입력합니다. 여러 호스트 NQN을 쉼표로 구분하여 입력할 수 있습니다.



. 저장 * 을 클릭합니다.
+
NVMe 하위 시스템이 생성되고 NVMe 하위 시스템 드린도 표시됩니다.





== NVMe 하위 시스템 세부 정보를 편집합니다

System Manager를 사용하여 NVMe 하위 시스템의 세부 정보를 편집할 수 있습니다.

.단계
. NVMe 하위 시스템 * 창에서 편집할 NVMe 하위 시스템을 찾으십시오.
. 편집할 하위 시스템 이름 왼쪽에 있는 확인란을 선택합니다.
. 편집 * 을 클릭합니다.
+
NVMe 하위 시스템의 현재 세부 정보가 NVMe Subsystems: Editwindow 에 표시됩니다.

. Host NQN * 필드의 정보만 수정할 수 있습니다.
+
** * 호스트 NQN *
+
컨트롤러에 연결된 호스트 NQN을 수정합니다. 여러 호스트 NQN을 쉼표로 구분하여 입력할 수 있습니다.



+
관련 NVMe 네임스페이스 * 테이블이 호스트 NQN 필드 아래에 표시됩니다. 각 네임스페이스에 대해 이 표에는 네임스페이스 경로 및 네임스페이스 ID가 나열됩니다.

. 저장 * 을 클릭합니다.
+
NVMe 하위 시스템의 세부 정보가 업데이트되고 NVMe 하위 시스템 창이 표시됩니다.





== NVMe 하위 시스템을 삭제합니다

System Manager를 사용하여 클러스터에서 NVMe 하위 시스템을 삭제할 수 있습니다.

.이 작업에 대해
NVMe 하위 시스템을 삭제할 때 다음 작업이 수행됩니다.

* NVMe 서브시스템에서 호스트를 구성한 경우 매핑된 호스트가 제거됩니다.
* NVMe 서브시스템에 매핑된 네임스페이스가 있는 경우 매핑 해제됩니다.


.단계
. NVMe 하위 시스템 * 창에서 삭제하려는 NVMe 하위 시스템을 찾으십시오.
. 삭제할 하위 시스템 이름 왼쪽에 있는 확인란을 선택합니다.
. 삭제 * 를 클릭합니다.
+
경고 메시지가 표시됩니다.

. 삭제를 확인하려면 * NVMe 하위 시스템 삭제 * 확인란을 클릭한 다음 * 예 * 를 클릭합니다.
+
NVMe 하위 시스템이 클러스터에서 삭제되고 NVMe 하위 시스템 창이 표시됩니다.





== NVMe 하위 시스템 창

NVMe 하위 시스템 창에는 기본적으로 클러스터의 NVMe 하위 시스템의 인벤토리 목록이 표시됩니다. 목록을 필터링하여 SVM과 관련된 하위 시스템만 표시할 수 있습니다. 이 창에서는 NVMe 서브시스템을 생성, 편집 또는 삭제할 수도 있습니다. 스토리지 * > * NVMe * > * 하위 시스템 * 을 선택하여 이 창에 액세스할 수 있습니다.

* <<NVMe 하위 시스템 표>>
* <<도구 모음>>




=== NVMe 하위 시스템 표

NVMe 하위 시스템 표에는 클러스터 내 NVMe 하위 시스템의 인벤토리가 나와 있습니다. SVM * 필드의 드롭다운 메뉴를 사용하여 SVM을 선택하여 해당 SVM과 관련된 NVMe 서브시스템만 표시되도록 목록을 개선할 수 있습니다. 검색 * 필드 및 * 필터링 * 드롭다운 메뉴를 사용하여 목록을 추가로 사용자 지정할 수 있습니다.

NVMe 하위 시스템 표에는 다음 열이 포함됩니다.

* * (확인란) *
+
작업을 수행할 하위 시스템을 지정할 수 있습니다.

+
확인란을 클릭하여 하위 시스템을 선택한 다음 수행할 도구 모음에서 작업을 클릭합니다.

* * 이름 *
+
하위 시스템의 이름을 표시합니다.

+
검색 * 필드에 하위 시스템의 이름을 입력하여 하위 시스템을 검색할 수 있습니다.

* * 호스트 OS *
+
서브시스템과 연결된 호스트 OS의 이름을 표시합니다.

* * 호스트 NQN *
+
컨트롤러에 연결된 NVMe 정규화된 이름(NQN)을 표시합니다. 여러 개의 NQN이 표시되면 쉼표로 구분됩니다.

* * 관련 NVMe 네임스페이스 *
+
하위 시스템과 연결된 NVM 네임스페이스의 수를 표시합니다. 숫자 위로 마우스를 가져가면 연결된 네임스페이스 경로가 표시됩니다. 경로를 클릭하여 Namespace Details 창을 표시합니다.





=== 도구 모음

도구 모음은 열 머리글 위에 있습니다. 도구 모음의 필드와 버튼을 사용하여 다양한 작업을 수행할 수 있습니다.

* * 검색 *
+
이름 * 열에 있는 값을 검색할 수 있습니다.

* * 필터링 *
+
목록을 필터링하는 다양한 방법이 나열된 드롭다운 메뉴에서 선택할 수 있습니다.

* * 생성 *
+
NVMe 하위 시스템을 생성할 수 있는 NVMe 하위 시스템 생성 대화 상자를 엽니다.

* * 편집 *
+
기존 NVMe 하위 시스템을 편집할 수 있는 Edit NVMe Subsystem(NVMe 하위 시스템 편집) 대화 상자를 엽니다.

* * 삭제 *
+
기존 NVMe 하위 시스템을 삭제할 수 있는 NVMe 하위 시스템 삭제 확인 대화 상자를 엽니다.


