---
permalink: online-help-96-97/concept_how_volume_guarantees_work_for_flexvol_volumes.html 
sidebar: sidebar 
keywords: volume, guarantee, work, flexvol, volume, space, preallocated, aggregate, online, help 
summary: '볼륨 보장(공간 보장이라고도 함)은 볼륨의 공간이 해당 애그리게이트에 할당될 때 공간을 미리 할당할지 여부를 결정합니다.' 
---
= System Manager-ONTAP 9.7 이하가 설치된 FlexVol 볼륨의 볼륨 보장에 대해 설명합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)으로 FlexVol 볼륨에 대한 볼륨 보장을 설정할 수 있습니다. 볼륨 보장(_space 보장 _ 이라고도 함)은 볼륨의 공간이 해당 포함하는 aggregate에서 할당되는 방식을 결정합니다. -- 공간이 볼륨에 사전 할당되었는지 여부를 결정합니다.

보증은 볼륨의 속성입니다.

새 볼륨을 생성할 때 보증을 설정합니다. 새 보장을 적용할 충분한 여유 공간이 있는 경우 기존 볼륨의 보장도 변경할 수 있습니다.

볼륨 보증 유형은 일 수 있습니다 `volume` (기본 유형) 또는 `none`.

* 보장 유형의 입니다 `volume` 볼륨을 생성할 때 해당 공간이 데이터에 사용되는지 여부와 관계없이 전체 볼륨에 대해 Aggregate의 공간을 할당합니다.
+
할당된 공간은 해당 애그리게이트의 다른 볼륨에 제공하거나 할당할 수 없습니다.

* 보장 `none` 볼륨에서 필요한 경우에만 애그리게이트에서 공간을 할당합니다.
+
이 보증 유형의 볼륨에서 사용하는 공간은 초기 볼륨 크기에 의해 결정되는 대신 추가되는 데이터로 인해 증가하므로 볼륨 데이터가 해당 크기로 확장되지 않으면 공간을 사용하지 않는 상태로 둘 수 있습니다. 보장이 적용되는 볼륨의 최대 크기입니다 `none` 는 애그리게이트에서 사용 가능한 공간의 양에 의해 제한되지 않습니다. 실제로 사용할 수 있는 공간의 양은 애그리게이트의 크기에 의해 제한되지만, 애그리게이트와 연결된 모든 볼륨의 총 크기는 애그리게이트의 여유 공간 크기를 초과할 수 있습니다.

+
포함된 애그리게이트에 쓰기를 수용할 수 있는 가용 공간이 충분하지 않은 경우, 해당 볼륨에 포함된 LUN 또는 파일(공간 예약 LUN 및 파일 포함)에 대한 쓰기가 실패할 수 있습니다.



Aggregate의 공간이 에 할당되는 경우 `volume` 기존 볼륨에 대한 보장 - 볼륨이 아직 공간을 사용하지 않더라도 애그리게이트에서 해당 공간이 더 이상 여유 공간으로 간주되지 않습니다. Aggregate의 여유 공간(예: Aggregate Snapshot 복사본 생성 또는 포함된 Aggregate의 새 볼륨 생성)을 사용하는 작업은 해당 애그리게이트에 충분한 가용 공간이 있는 경우에만 수행할 수 있습니다. 이러한 작업은 이미 다른 볼륨에 할당된 공간을 사용할 수 없습니다.

애그리게이트의 여유 공간이 소진되면 사전 할당된 공간이 있는 애그리게이트의 볼륨 또는 파일에 대한 쓰기만 성공할 수 있습니다.

보장 사항은 온라인 볼륨에만 적용됩니다. 볼륨을 오프라인으로 전환하면 이 애그리게이트에 있는 다른 볼륨에서 해당 볼륨에 할당되었지만 사용되지 않은 공간을 사용할 수 있게 됩니다. 이 볼륨을 다시 온라인으로 전환하려고 할 때 보장을 실현하기에는 애그리게이트에 사용 가능한 공간이 부족할 경우 오프라인 상태로 유지됩니다. 볼륨을 온라인으로 강제 설정해야 합니다. 그러면 볼륨 보장이 비활성화됩니다.

* 관련 정보 *

http://www.netapp.com/us/media/tr-3965.pdf["NetApp 기술 보고서 3965: NetApp 씬 프로비저닝 구축 및 구현 Data ONTAP 8.1(7-Mode)"^]
