---
permalink: online-help-96-97/concept_export_policies.html 
sidebar: sidebar 
keywords: system, manager, create, edit, manage, export, policy, online, help, volume, rules, svm, qtree, rename 
summary: System Manager를 사용하여 엑스포트 정책을 생성, 편집, 관리할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 엑스포트 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 엑스포트 정책을 생성, 편집, 관리할 수 있습니다.



== 엑스포트 정책을 생성합니다

System Manager를 사용하여 클라이언트가 특정 볼륨에 액세스할 수 있도록 엑스포트 정책을 생성할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. Create * 를 클릭합니다.
. 내보내기 정책 만들기 * 대화 상자에서 내보내기 정책의 이름을 지정합니다.
. 기존 엑스포트 정책의 규칙을 복사하여 엑스포트 정책을 생성하려면 * 다음에서 규칙 복사 * 확인란을 선택한 다음, SVM(스토리지 가상 머신) 및 엑스포트 정책을 선택합니다.
+
엑스포트 정책을 생성하려면 드롭다운 메뉴에서 재해 복구용 대상 SVM을 선택하면 안 됩니다.

. ** 내보내기 규칙** 영역에서 * 추가 * 를 클릭하여 엑스포트 정책에 규칙을 추가합니다.
. Create * 를 클릭합니다.
. 생성한 엑스포트 정책이 * Export Policies * 창에 표시되는지 확인합니다.




== 엑스포트 정책의 이름을 바꿉니다

시스템 관리를 사용하여 기존 엑스포트 정책의 이름을 바꿀 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. 이름을 바꿀 엑스포트 정책을 선택한 다음 * 정책 이름 바꾸기 * 를 클릭합니다.
. 이름 바꾸기 정책 * 대화 상자에서 새 정책 이름을 지정한 다음 * 수정 * 을 클릭합니다.
. Export Policies * (내보내기 정책 *) 창에서 변경한 내용을 확인합니다.




== 엑스포트 정책을 삭제합니다

System Manager를 사용하면 더 이상 필요하지 않은 엑스포트 정책을 삭제할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. 삭제할 엑스포트 정책을 선택한 다음 * 정책 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 엑스포트 정책에 규칙 추가

System Manager를 사용하여 엑스포트 정책에 규칙을 추가할 수 있으며, 이를 통해 데이터에 대한 클라이언트 액세스를 정의할 수 있습니다.

.시작하기 전에
엑스포트 규칙을 추가할 엑스포트 정책을 생성해야 합니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. 규칙을 추가할 엑스포트 정책을 선택하고 * 규칙 내보내기 * 탭에서 * 추가 * 를 클릭합니다.
. 내보내기 규칙 만들기 * 대화 상자에서 다음 단계를 수행하십시오.
+
.. 데이터에 액세스해야 하는 클라이언트를 지정합니다.
+
여러 클라이언트를 쉼표로 구분된 값으로 지정할 수 있습니다.

+
다음 형식 중 하나로 클라이언트를 지정할 수 있습니다.

+
*** 호스트 이름(예: host1)입니다
*** IPv4 주소(예: 10.1.12.24)입니다
*** 네트워크 마스크가 있는 IPv4 주소(예: 10.1.16.0/255.255.255.0)
*** IPv6 주소(예: FE80::0202:B3FF:FE1E:8329)입니다
*** 네트워크 마스크가 있는 IPv6 주소(예: 2001:DB8::/ 32)
*** 넷그룹으로, netgroup 이름 앞에 AT 기호(@)가 옵니다(예: @netgroup)
*** 앞에 마침표(.)가 오는 도메인 이름(예: .example.com


+
[NOTE]
====
10.1.12.10 ~ 10.1.12.70 등의 IP 주소 범위는 입력할 수 없습니다. 이 형식의 항목은 텍스트 문자열로 해석되며 호스트 이름으로 취급됩니다.

====
+
IPv4 주소를 입력할 수 있습니다 `0.0.0.0/0` 모든 호스트에 대한 액세스를 제공합니다.

.. 규칙 인덱스 번호를 수정하려면 적절한 규칙 인덱스 번호를 선택합니다.
.. 하나 이상의 액세스 프로토콜을 선택합니다.
+
액세스 프로토콜을 선택하지 않으면 기본값 ""모두""가 내보내기 규칙에 할당됩니다.

.. 하나 이상의 보안 유형 및 액세스 규칙을 선택합니다.


. 확인 * 을 클릭합니다.
. 추가한 내보내기 규칙이 선택한 내보내기 정책의 * 내보내기 규칙 * 탭에 표시되는지 확인합니다.




== 엑스포트 정책 규칙을 수정합니다

System Manager를 사용하여 지정된 클라이언트, 액세스 프로토콜 및 엑스포트 정책 규칙의 액세스 권한을 수정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. Export Policies * 창에서 내보내기 규칙을 편집할 엑스포트 정책을 선택하고 * Export Rules * 탭에서 편집할 규칙을 선택한 다음 * Edit * 를 클릭합니다.
. 필요에 따라 다음 매개 변수를 수정합니다.
+
** 클라이언트 사양
** 액세스 프로토콜
** 액세스 세부 정보


. 확인 * 을 클릭합니다.
. 내보내기 규칙에 대한 업데이트된 변경 사항이 * Export Rules *(규칙 내보내기) 탭에 표시되는지 확인합니다.




== 엑스포트 정책 규칙을 삭제합니다

System Manager를 사용하면 더 이상 필요하지 않은 엑스포트 정책 규칙을 삭제할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Export Policies * 를 클릭합니다.
. 엑스포트 규칙을 삭제할 엑스포트 정책을 선택합니다.
. Export Rules * (규칙 내보내기 *) 탭에서 삭제할 내보내기 규칙을 선택한 다음 * Delete * (삭제 *)를 클릭합니다.
. 확인 상자에서 * 삭제 * 를 클릭합니다.




== 엑스포트 정책이 볼륨 또는 qtree에 대한 클라이언트 액세스를 제어하는 방법

엑스포트 정책에는 각 클라이언트 액세스 요청을 처리하는 _export rules_이 하나 이상 포함되어 있습니다. 프로세스 결과에 따라 클라이언트가 거부되었는지, 액세스 권한이 부여되었는지, 액세스 수준이 결정됩니다. 클라이언트가 데이터에 액세스할 수 있도록 SVM(스토리지 가상 시스템)에 엑스포트 규칙과 함께 엑스포트 정책이 있어야 합니다.

볼륨 또는 qtree에 대한 클라이언트 액세스를 구성하기 위해 각 볼륨 또는 qtree에 정확히 하나의 엑스포트 정책을 연결합니다. SVM에는 여러 엑스포트 정책이 포함될 수 있습니다. 따라서 여러 볼륨 또는 qtree를 사용하는 SVM에 대해 다음을 수행할 수 있습니다.

* 개별 클라이언트 액세스 제어를 SVM의 각 볼륨 또는 qtree에 서로 다른 엑스포트 정책을 지정하여 각 볼륨 또는 qtree에 대한 볼륨 또는 qtree를 관리할 수 있습니다.
* 각 볼륨 또는 qtree에 대해 새로운 엑스포트 정책을 생성할 필요 없이 동일한 클라이언트 액세스 제어를 위해 SVM의 여러 볼륨 또는 qtree에 동일한 엑스포트 정책을 할당합니다.


클라이언트가 해당 엑스포트 정책에서 허용하지 않는 액세스 요청을 하는 경우 권한 거부 메시지와 함께 요청이 실패합니다. 클라이언트가 엑스포트 정책의 규칙과 일치하지 않으면 액세스가 거부됩니다. 내보내기 정책이 비어 있으면 모든 액세스가 암시적으로 거부됩니다.

ONTAP를 실행하는 시스템에서 엑스포트 정책을 동적으로 수정할 수 있습니다.



== 엑스포트 정책 창

엑스포트 정책 창을 사용하면 엑스포트 정책과 관련 엑스포트 규칙에 대한 정보를 생성, 보기, 관리할 수 있습니다.



=== 엑스포트 정책

엑스포트 정책 창에서는 SVM(스토리지 가상 머신)에 대해 생성된 엑스포트 정책을 확인하고 관리할 수 있습니다.

* * 명령 버튼 *
+
** 생성
+
엑스포트 정책을 생성하고 엑스포트 규칙을 추가할 수 있는 엑스포트 정책 생성 대화 상자를 엽니다. 기존 SVM에서 엑스포트 규칙을 복사할 수도 있습니다.

** 이름 바꾸기
+
선택한 엑스포트 정책의 이름을 바꿀 수 있는 정책 이름 바꾸기 대화 상자를 엽니다.

** 삭제
+
선택한 엑스포트 정책을 삭제할 수 있는 엑스포트 정책 삭제 대화 상자를 엽니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.







=== 규칙 내보내기 탭

규칙 내보내기 탭에서는 특정 엑스포트 정책에 대해 생성된 엑스포트 규칙에 대한 정보를 볼 수 있습니다. 규칙을 추가, 편집 및 삭제할 수도 있습니다.

* * 명령 버튼 *
+
** 추가
+
선택한 엑스포트 정책에 엑스포트 규칙을 추가할 수 있는 엑스포트 규칙 생성 대화 상자를 엽니다.

** 편집
+
선택한 내보내기 규칙의 특성을 수정할 수 있는 내보내기 규칙 수정 대화 상자를 엽니다.

** 삭제
+
선택한 내보내기 규칙을 삭제할 수 있는 내보내기 규칙 삭제 대화 상자를 엽니다.

** 위로 이동
+
선택한 내보내기 규칙의 규칙 인덱스를 위로 이동합니다.

** 아래로 이동합니다
+
선택한 내보내기 규칙의 규칙 인덱스를 아래로 이동합니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.



* * 규칙 목록 내보내기 *
+
** 규칙 색인
+
내보내기 규칙이 처리되는 우선 순위를 지정합니다. 위로 이동 및 아래로 이동 단추를 사용하여 우선 순위를 선택할 수 있습니다.

** 클라이언트
+
규칙을 적용할 클라이언트를 지정합니다.

** 액세스 프로토콜
+
내보내기 규칙에 지정된 액세스 프로토콜을 표시합니다.

+
액세스 프로토콜을 지정하지 않은 경우 기본값 ""Any""가 고려됩니다.

** 읽기 전용 규칙입니다
+
읽기 전용 액세스에 대해 하나 이상의 보안 유형을 지정합니다.

** 읽기/쓰기 규칙
+
읽기/쓰기 액세스에 사용할 보안 유형을 하나 이상 지정합니다.

** 고급 사용자 액세스
+
고급 사용자 액세스에 대한 보안 유형을 지정합니다.







=== 할당된 개체 탭

Assigned Objects 탭에서는 선택한 엑스포트 정책에 할당된 볼륨 및 qtree를 볼 수 있습니다. 볼륨이 암호화되었는지 여부를 확인할 수도 있습니다.

* 관련 정보 *

xref:task_setting_up_cifs.adoc[CIFS를 설정하는 중입니다]
