---
permalink: online-help-96-97/concept_system_alerts.html 
sidebar: sidebar 
keywords: system, manager, monitor, cluster, health, alerts, delete, 
summary: System Manager를 사용하여 클러스터의 다양한 부분을 모니터링할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 시스템 경고를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 클러스터의 여러 부분을 모니터링할 수 있습니다.



== 시스템 상태 알림을 확인합니다

System Manager를 사용하여 서브시스템에 대한 시스템 상태 경고를 확인하고 응답할 수 있습니다. 표시된 정보를 사용하여 권장 조치를 취하고 경고에 보고된 문제를 해결할 수 있습니다.

.단계
. 이벤트 및 작업 * > * 시스템 알림 * 을 클릭합니다.
. 시스템 경고* 창에서 하위 시스템 이름 옆에 있는 화살표 아이콘을 클릭합니다.
. 확인할 경고를 선택한 다음 * 확인 * 을 클릭합니다.
. 이름을 입력한 다음 * 확인 * 을 클릭합니다.




== 시스템 상태 알림을 표시하지 않습니다

System Manager를 사용하면 사용자 개입이 필요 없는 시스템 상태 알림을 표시하지 않을 수 있습니다.

.단계
. 이벤트 및 작업 * > * 시스템 알림 * 을 클릭합니다.
. 시스템 경고* 창에서 하위 시스템 이름 옆에 있는 화살표 아이콘을 클릭합니다.
. 기능 억제하려는 알림을 선택한 다음 * 기능 억제 * 를 클릭합니다.
. 이름을 입력한 다음 * 기능 억제 * 를 클릭합니다.




== 시스템 상태 알림을 삭제합니다

System Manager를 사용하면 이미 응답한 시스템 상태 알림을 삭제할 수 있습니다.

.단계
. 이벤트 및 작업 * > * 시스템 알림 * 을 클릭합니다.
. 시스템 경고* 창에서 하위 시스템 이름 옆에 있는 화살표 아이콘을 클릭합니다.
. 삭제할 알림을 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 * 을 클릭합니다.




== 사용 가능한 클러스터 상태 모니터

클러스터의 여러 부분을 모니터링하는 상태 모니터가 여러 개 있습니다. 상태 모니터는 이벤트를 감지하고, 사용자에게 경고를 보내고, 이벤트를 삭제하여 ONTAP 시스템 내의 오류를 복구할 수 있도록 도와줍니다.

[cols="1a,1a,1a"]
|===
| 상태 모니터 이름(식별자) | 하위 시스템 이름(식별자) | 목적 


 a| 
클러스터 스위치(클러스터 스위치)
 a| 
스위치(스위치 - 상태)
 a| 
클러스터 네트워크 스위치 및 관리 네트워크 스위치에서 온도, 사용률, 인터페이스 구성, 이중화(클러스터 네트워크 스위치만 해당) 및 팬 및 전원 공급 장치 작동을 모니터링합니다. 클러스터 스위치 상태 모니터는 SNMP를 통해 스위치와 통신합니다. SNMPv2c가 기본 설정입니다.

[NOTE]
====
ONTAP 9.2부터는 이 모니터가 마지막 폴링 기간 이후 클러스터 스위치가 재부팅된 경우를 감지하여 보고할 수 있습니다.

====


 a| 
MetroCluster 패브릭
 a| 
스위치
 a| 
MetroCluster 구성 백엔드 Fabric 토폴로지를 모니터링하고 잘못된 케이블 연결 및 조닝, ISL 장애 등의 잘못된 구성을 감지합니다.



 a| 
MetroCluster 상태
 a| 
상호 연결, RAID 및 스토리지
 a| 
FC-VI 어댑터, FC 이니시에이터 어댑터, 좌측 애그리게이트 및 디스크, 클러스터 간 포트를 모니터링합니다



 a| 
노드 연결(노드 연결)
 a| 
CIFS 무중단 운영(CIFS-NDO)
 a| 
SMB 연결을 모니터링하여 Hyper-V 애플리케이션의 무중단 운영을 지원합니다.



 a| 
스토리지(SAS-connect)
 a| 
노드 레벨에서 쉘프, 디스크, 어댑터를 모니터링하여 적절한 경로와 연결을 설정합니다.



 a| 
시스템
 a| 
해당 없음
 a| 
다른 상태 모니터의 정보를 집계합니다.



 a| 
시스템 연결(시스템 연결)
 a| 
스토리지(SAS-connect)
 a| 
2개의 HA 클러스터 노드에 대한 적절한 경로에 대해 클러스터 레벨의 쉘프를 모니터링합니다.

|===


== 시스템 상태 알림에 응답하는 방법

시스템 상태 경고가 발생하면 이를 확인하고, 자세히 알아보고, 기본 상태를 수리하고, 문제가 다시 발생하지 않도록 할 수 있습니다.

상태 모니터에서 알림을 발생시키면 다음 방법 중 하나를 사용하여 응답할 수 있습니다.

* 영향을 받는 리소스, 경고 심각도, 가능한 원인, 가능한 영향 및 수정 조치가 포함된 알림에 대한 정보를 얻을 수 있습니다.
* 알림이 발생한 시간, 다른 사용자가 이미 알림을 확인했는지 여부 등 알림에 대한 자세한 정보를 확인합니다.
* 특정 쉘프 또는 디스크와 같은 영향을 받는 리소스 또는 하위 시스템의 상태에 대한 상태 관련 정보를 가져옵니다.
* 누군가 문제를 해결하고 있음을 알리고 자신을 "확인자"로 식별합니다.
* 연결 문제를 해결하기 위해 케이블 연결 문제 해결 등 알림에 제공된 수정 조치를 수행하여 문제를 해결합니다.
* 시스템에서 자동으로 경고를 지우지 않은 경우 해당 경고를 삭제합니다.
* 알림을 표시하지 않도록 하여 하위 시스템의 상태에 영향을 주지 않도록 합니다.
+
기능 억제는 문제를 이해할 때 유용합니다. 경고를 표시하지 않으면 알림이 계속 발생할 수 있지만 하위 시스템 상태가 "ok-with-suppressed"로 표시됩니다.





== 시스템 경고 창

시스템 알림 창을 사용하여 시스템 상태 알림에 대해 자세히 알아볼 수 있습니다. 창에서 경고를 확인, 삭제 및 억제할 수도 있습니다.



=== 명령 버튼

* * 확인 *
+
선택한 경고를 확인하여 문제가 해결되고 있음을 알리고 단추를 클릭한 사람을 ""확인자"로 식별할 수 있습니다.

* * 기능 억제 *
+
선택한 경고를 억제하여 시스템이 사용자에게 동일한 경고를 다시 알리지 않고 사용자를 "서프레서"로 식별할 수 있습니다.

* * 삭제 *
+
선택한 경고를 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 알림 목록

* 하위 시스템(번호 알림 수) *
+
알림이 생성된 SAS 연결, 스위치 상태, CIFS NDO 또는 MetroCluster와 같은 서브시스템의 이름을 표시합니다.

* * 경고 ID *
+
경고 ID를 표시합니다.

* * 노드 *
+
알림이 생성된 노드의 이름을 표시합니다.

* * 심각도 *
+
알림의 심각도를 알 수 없음, 기타, 정보, 성능 저하, 경미함, 중대, 중대 또는 치명적

* * 리소스 *
+
알림을 생성한 리소스(예: 특정 쉘프 또는 디스크)를 표시합니다.

* 시간 *
+
알림이 생성된 시간을 표시합니다.





=== 세부 정보 영역

세부 정보 영역에는 경고가 생성된 시간 및 경고가 확인되었는지 여부와 같은 알림에 대한 자세한 정보가 표시됩니다. 이 영역에는 경고에 의해 생성된 조건의 가능한 원인 및 가능한 영향에 대한 정보와 경고에 의해 보고된 문제를 해결하기 위한 권장 조치가 포함됩니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap/system-admin/index.html["시스템 관리"]
