---
permalink: online-help-96-97/concept_configuration_update.html 
sidebar: sidebar 
keywords: configuration, update, system, manager, administration, detail, storage, virtual, machine, svm, online, help, window, tab, node, command, button 
summary: 'System Manager를 사용하여 SVM(스토리지 가상 머신)의 관리 세부 정보를 구성할 수 있습니다.' 
---
= System Manager를 사용한 구성 업데이트 - ONTAP 9.7 이전 버전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하여 SVM(스토리지 가상 머신)의 관리 세부 정보를 구성할 수 있습니다.



== SVM의 관리 세부 정보를 구성합니다

System Manager를 사용하면 SVM(스토리지 가상 시스템)의 관리 세부 정보를 빠르게 구성할 수 있습니다. 선택적으로 SVM 관리자에게 SVM 관리 권한을 위임할 수 있습니다.

.이 작업에 대해
SVM 관리자는 System Manager를 사용하여 위임된 SVM을 관리할 수 없습니다. CLI(Command-Line Interface)를 사용해서만 SVM을 관리할 수 있습니다.

.단계
. 구성 * > * 클러스터 * > * 구성 업데이트 * 를 클릭합니다.
. SVM * 탭에서 노드를 선택한 다음 * 관리 세부 정보 구성 * 을 클릭합니다.
. 관리자 세부 정보 * 섹션에서 에 대한 암호를 설정합니다 `vsadmin` 사용자 계정.
. SVM 관리를 위한 전용 LIF를 원하는 경우 * SVM 관리를 위한 LIF 생성 * 을 선택하고 네트워크 세부 정보를 지정합니다.
+
SAN 프로토콜에는 데이터 및 관리 프로토콜이 동일한 LIF를 공유할 수 없는 전용 SVM 관리 LIF가 필요합니다. SVM 관리 LIF는 데이터 포트에만 생성할 수 있습니다.

. 네트워크 세부 정보를 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
+
대상 필드는 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.

... 기본값을 사용하지 않으려면 새 목적지 값을 지정하십시오.
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.


.. 확인 * 을 클릭합니다.


|===
. 데이터 LIF를 생성할 포트를 지정합니다.
+
.. 찾아보기 * 를 클릭합니다.
.. 네트워크 포트 또는 어댑터 선택 * 대화 상자에서 포트를 선택한 다음 * 확인 * 을 클릭합니다.






== 구성 업데이트 창

구성 업데이트 창을 사용하여 클러스터, SVM(스토리지 가상 시스템) 및 노드의 구성 세부 정보를 업데이트할 수 있습니다.



=== 탭

* * 노드 *
+
노드의 세부 정보를 구성할 수 있습니다.

* SVM *
+
SVM의 세부 정보를 구성할 수 있습니다.





=== 노드 탭



=== 명령 버튼

* * 노드 이름 편집 *
+
노드 이름을 수정할 수 있는 노드 이름 편집 대화 상자를 엽니다.

* * 노드 관리 LIF를 생성합니다 *
+
노드 관리 LIF 생성 대화 상자를 엽니다. 이 대화 상자에서 특정 노드를 관리할 노드 관리 LIF를 생성할 수 있습니다.

* * AutoSupport 편집 *
+
AutoSupport 설정 편집 대화 상자를 엽니다. 이 대화 상자에서 이메일 알림을 보낼 이메일 주소를 지정하고 호스트 이름의 이메일 주소를 여러 개 추가할 수 있습니다.





=== SVM 탭



=== 명령 단추

* * 관리 세부 정보 구성 *
+
SVM의 관리 세부 정보를 구성할 수 있는 관리 세부 정보 구성 대화 상자를 엽니다.



* 관련 정보 *

xref:task_creating_cluster.adoc[클러스터 생성]

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[IP 주소 범위가 비활성화된 경우 네트워크 설정]
