---
permalink: online-help-96-97/concept_protection_policies.html 
sidebar: sidebar 
keywords: online, help, protection, policy, system, manager, create, edit, delete 
summary: System Manager를 사용하여 보호 정책을 생성, 편집 및 삭제할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 보호 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 보호 정책을 생성, 편집 및 삭제할 수 있습니다.



== 보호 정책을 생성합니다

System Manager를 사용하여 클러스터 레벨 비동기식 미러 정책, 볼트 정책 또는 미러 및 볼트 정책을 생성하고 이러한 정책을 클러스터 레벨 데이터 보호 관계에 적용할 수 있습니다.

.단계
. 보호 * > * 보호 정책 * 을 클릭합니다.
. Create * 를 클릭합니다.
. Create Policy * 대화 상자에서 만들려는 정책 유형을 선택합니다.
. 정책 이름 및 전송 우선 순위를 지정합니다.
+
낮음이란 전송 우선 순위가 가장 낮음을 나타냅니다. 우선 순위가 낮은 전송은 일반적으로 일반 우선 순위 전송 후에 예약됩니다. 기본적으로 전송 우선 순위는 보통으로 설정됩니다.

. * 선택 사항: * 데이터 전송 중에 전송되는 데이터를 압축하려면 * 네트워크 압축 사용 * 확인란을 선택합니다.
. * 선택 사항: * 비동기식 미러 정책의 경우 * 모든 소스 스냅샷 복사본 전송 * 확인란을 선택하여 소스 볼륨의 모든 스냅샷 복사본을 백업하는 미러 정책에 "'all_source_snapshots" 규칙을 포함시킵니다.
. * 선택 사항: * 정책에 대한 추가 설명을 추가하려면 * 의견 추가 * 를 클릭합니다.
. 볼트 정책 또는 미러 볼트 정책의 경우 SnapMirror 레이블과 대상 보존 수를 지정합니다.
. Create * 를 클릭합니다.




== 보호 정책 창

보호 정책 창을 사용하여 미러, 볼트 및 미러 볼트 정책에 대한 정보를 생성, 관리 및 표시할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
미러, 볼트 또는 미러 볼트 정책을 작성할 수 있는 정책 작성 대화 상자를 엽니다.

* * 편집 *
+
정책을 편집할 수 있는 정책 편집 대화 상자를 엽니다.

* * 삭제 *
+
정책을 삭제할 수 있는 정책 삭제 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 보호 정책 목록

* * 이름 *
+
보호 정책의 이름을 표시합니다.

* * 유형 *
+
볼트, 볼트, 비동기식 미러일 수 있는 정책 유형을 표시합니다.

* * 설명 *
+
정책에 지정된 설명을 표시합니다.

* * 전송 우선순위 *
+
보통 또는 낮음과 같은 데이터 전송 우선 순위를 표시합니다.





=== 세부 정보 영역

* * 정책 세부 정보 탭 *
+
정책을 생성한 사용자, 규칙 수, 보존 수 및 네트워크 압축 상태와 같은 보호 정책의 세부 정보를 표시합니다.

* * 정책 규칙 탭 *
+
정책에 적용되는 규칙의 세부 정보를 표시합니다. 정책 규칙 탭은 선택한 정책에 규칙이 포함된 경우에만 표시됩니다.


