---
permalink: online-help-96-97/concept_jobs.html 
sidebar: sidebar 
keywords: jobs, system, manager, job, task, display, information, progress, asynchronous, volume, operation, copy, move, mirror, data, queue, cluster, administrator, online, help 
summary: System Manager를 사용하면 작업 정보 표시 및 작업 진행률 모니터링과 같은 작업 작업을 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 작업을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 작업 정보 표시 및 작업 진행 상황 모니터링과 같은 작업 작업을 관리할 수 있습니다.



== 작업

_Jobs_는 비동기 작업이며 일반적으로 데이터를 복사, 이동 또는 미러링하는 등 오래 실행되는 볼륨 작업입니다. 작업은 작업 대기열에 배치되며 자원을 사용할 수 있을 때 실행됩니다. 클러스터 관리자는 작업 관리와 관련된 모든 작업을 수행할 수 있습니다.

작업은 다음 범주 중 하나일 수 있습니다.

* server-ac계열_job은 특정 노드에서 실행될 관리 프레임워크에서 대기열에 배치됩니다.
* 클러스터 관련_작업은 관리 프레임워크에서 대기열에 배치되고 클러스터의 모든 노드에서 실행됩니다.
* private_job은 특정 노드에 특정하며 복제된 데이터베이스(RDB) 또는 다른 클러스터 메커니즘을 사용하지 않습니다.
+
비공개 작업을 관리하기 위해 명령을 실행하려면 고급 권한 수준 이상이 필요합니다.



다음과 같은 방법으로 작업을 관리할 수 있습니다.

* 다음을 포함한 작업 정보 표시:
+
** 노드별 작업
** 클러스터 관련 작업
** 완료된 작업
** 작업 기록


* 작업 진행 상황 모니터링
* 작업 관리자의 초기화 상태에 대한 정보를 표시합니다.


이벤트 로그를 확인하여 완료된 작업의 결과를 확인할 수 있습니다.



== 작업 창

작업 창을 사용하여 작업 정보 표시 및 작업 진행률 모니터링과 같은 작업 작업을 관리할 수 있습니다.



=== 명령 단추

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 탭

* * 현재 작업 *
+
이 탭은 진행 중인 작업 작업에 대한 정보를 표시합니다.

* * 작업 내역 *
+
이 탭은 모든 작업에 대한 정보를 표시합니다.





=== 작업 목록

* * 작업 ID *
+
작업의 ID를 표시합니다.

* * 시작 시간 *
+
작업의 시작 시간을 표시합니다.

* * 작업 이름 *
+
작업 이름을 표시합니다.

* * 노드 *
+
노드의 이름을 표시합니다.

* * 시/도 *
+
작업의 상태를 표시합니다.

* * 직무 설명 *
+
작업에 대한 설명을 표시합니다.

* * 진행률 *
+
작업의 상태를 표시합니다.

* 별표 이름 *
+
스케줄의 이름을 표시합니다.


