---
permalink: online-help-96-97/concept_events.html 
sidebar: sidebar 
keywords: event, log, notification, system, manager, online, help, view 
summary: System Manager를 사용하여 이벤트 로그 및 이벤트 알림을 볼 수 있습니다. 
---
= System Manager로 이벤트 관리 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 이벤트 로그 및 이벤트 알림을 볼 수 있습니다.



== 이벤트 창

이벤트 창을 사용하여 이벤트 로그 및 이벤트 알림을 볼 수 있습니다.



=== 명령 버튼

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 이벤트 목록

* 시간 *
+
이벤트가 발생한 시간을 표시합니다.

* * 노드 *
+
이벤트가 발생한 노드와 클러스터를 표시합니다.

* * 심각도 *
+
이벤트의 심각도를 표시합니다. 가능한 심각도 수준은 다음과 같습니다.

+
** 비상 상황
+
이벤트 소스가 예기치 않게 중지되고 시스템에서 복구할 수 없는 데이터 손실이 발생하도록 지정합니다. 다운타임을 방지하려면 수정 조치를 즉시 취해야 합니다.

** 경고
+
이벤트 소스에 알림이 있고 다운타임을 방지하기 위해 조치를 취해야 함을 지정합니다.

** 심각
+
이벤트 소스가 중요하며 수정 조치가 즉시 수행되지 않을 경우 서비스가 중단될 수 있음을 지정합니다.

** 오류
+
이벤트 소스가 여전히 수행되고 있으며 서비스 중단을 방지하기 위해 수정 조치가 필요함을 지정합니다.

** 경고
+
이벤트 소스에서 인식해야 하는 상황이 발생하도록 지정합니다. 이러한 심각도 때문에 서비스 중단이 발생할 수 있지만, 수정 조치가 필요할 수 있습니다.

** 주의
+
이벤트 소스가 정상이지만 심각도를 알아야 하는 중요한 조건임을 지정합니다.

** 정보 제공
+
이벤트 소스에 인식해야 하는 항목이 있음을 지정합니다. 수정 조치가 필요하지 않을 수 있습니다.

** 디버그
+
이벤트 소스에 디버깅 메시지가 포함되도록 지정합니다.



+
기본적으로 알림 심각도 유형, 긴급 심각도 유형 및 오류 심각도 유형이 표시됩니다.

* * 출처 *
+
이벤트 소스를 표시합니다.

* * 이벤트 *
+
이벤트에 대한 설명을 표시합니다.





=== 세부 정보 영역

선택한 이벤트에 대한 이벤트 설명, 메시지 이름, 시퀀스 번호, 메시지 설명, 수정 조치를 비롯한 이벤트 세부 정보를 표시합니다.
