---
permalink: online-help-96-97/concept_nfs_protocol.html 
sidebar: sidebar 
keywords: nfs, protocol, system, manager, authenticate, client, asses, data, svm, online, help 
summary: System Manager를 사용하여 NFS 클라이언트를 인증하여 SVM의 데이터에 액세스할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 NFS 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 NFS 클라이언트를 인증하여 SVM에서 데이터에 액세스할 수 있습니다.



== NFS 설정을 편집합니다

System Manager를 사용하여 NFSv3, NFSv4 및 NFSv4.1에서 설정 또는 해제, NFSv4 클라이언트에 대한 읽기 및 쓰기 위임 설정 또는 해제, NFSv4 ACL 설정 등의 NFS 설정을 편집할 수 있습니다. 기본 Windows 사용자도 편집할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * NFS * 를 클릭합니다.
. NFS * 창에서 * Edit * 를 클릭합니다.
. NFS 설정 편집 * 대화 상자에서 필요한 사항을 변경합니다.
. 저장 후 닫기 * 를 클릭합니다.




== NFS 창

NFS 창을 사용하여 NFS 설정을 표시하고 구성할 수 있습니다.

* * 서버 상태 *
+
NFS 서비스의 상태를 표시합니다. SVM(스토리지 가상 머신)에서 NFS 프로토콜을 구성하면 서비스가 활성화됩니다.

+
[NOTE]
====
Data ONTAP 8.1.x를 실행하는 NFS 지원 스토리지 시스템에서 ONTAP 8.3 이상으로 업그레이드한 경우, ONTAP 8.3 이상에서 NFS 서비스를 사용할 수 있습니다. 하지만 NFSv2가 더 이상 지원되지 않으므로 NFSv3 또는 NFSv4에 대한 지원을 설정해야 합니다.

====




=== 명령 버튼

* * 활성화 *
+
NFS 서비스를 설정합니다.

* * 비활성화 *
+
NFS 서비스를 해제합니다.

* * 편집 *
+
NFS 설정을 편집할 수 있는 NFS 설정 편집 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.



* 관련 정보 *

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 관리"^]
