---
permalink: online-help-96-97/concept_snapshot_policies.html 
sidebar: sidebar 
keywords: snapshot, manager, system, create, manage, policy, storage, online, help 
summary: System Manager를 사용하여 스토리지 시스템에서 스냅샷 정책을 생성하고 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 스냅샷 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 방식을 사용하여 스토리지 시스템에서 스냅샷 정책을 생성하고 관리할 수 있습니다.



== 스냅샷 정책에 대해서 설명합니다

볼륨에 적용할 경우 스냅샷 정책은 스냅샷 복사본이 생성되는 일정을 지정하고 각 일정에서 만들 수 있는 최대 스냅샷 복사본 수를 지정합니다. 스냅샷 정책에는 최대 5개의 일정을 포함할 수 있습니다.

볼트 관계의 경우 SnapMirror 레이블 속성을 사용하여 소스 볼륨의 스냅샷 복사본을 선택합니다. 볼트 정책 규칙에 구성된 라벨이 있는 스냅샷 복사본만 백업 볼트 작업에 복제됩니다. 소스 볼륨에 할당된 스냅샷 정책에는 SnapMirror 레이블 특성이 포함되어야 합니다.



== 스냅샷 정책 생성

System Manager에서 스냅샷 정책을 생성하여 자동으로 생성할 수 있는 최대 스냅샷 복사본의 수와 생성 빈도를 지정할 수 있습니다.

.단계
. 보호 * > * 스냅샷 정책 * 을 클릭합니다.
. Create * 를 클릭합니다.
. 스냅샷 정책 생성 * 대화 상자에서 정책 이름을 지정합니다.
. 추가 * 를 클릭하고 일정 이름, 유지할 스냅샷 복사본의 최대 수 및 SnapMirror 레이블 이름을 지정합니다.
+
지정된 스케줄에 따라 보존할 수 있는 스냅샷 복사본의 최대 수는 254개를 초과할 수 없습니다.

. OK * 를 클릭한 다음 * Create * 를 클릭합니다.




== 스냅샷 정책을 편집합니다

System Manager의 스냅샷 정책 편집 대화 상자를 사용하여 예약 이름, SnapMirror 레이블 또는 생성되는 최대 스냅샷 복사본 수와 같은 기존 스냅샷 정책의 세부 정보를 수정할 수 있습니다.

.단계
. 보호 * > * 스냅샷 정책 * 을 클릭합니다.
. Snapshot Policies * 창에서 수정할 스냅샷 정책을 선택하고 * Edit * 를 클릭합니다.
. 스냅샷 정책 편집 * 대화 상자에서 수정할 일정을 선택하고 * 편집 * 을 클릭합니다.
. 확인 * 을 클릭합니다.
. 스냅샷 정책 편집 * 대화 상자에서 선택한 스냅샷 정책의 변경 사항을 확인하고 * 저장 * 을 클릭합니다.




== 스냅샷 정책을 삭제합니다

System Manager를 사용하여 스냅샷 정책을 삭제할 수 있습니다. 하나 이상의 볼륨에서 사용 중인 스냅샷 정책을 삭제하면 삭제된 정책에 따라 볼륨 또는 볼륨의 스냅샷 복사본이 더 이상 생성되지 않습니다.

.시작하기 전에
스냅샷 정책을 사용하는 각 볼륨에서 분리해야 합니다.

.단계
. 보호 * > * 스냅샷 정책 * 을 클릭합니다.
. 스냅샷 정책을 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 스냅샷 정책 창

스냅샷 정책 창을 사용하여 스냅샷 정책 추가, 편집, 삭제 등의 스냅샷 정책 작업을 관리할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
백업 일정을 추가하고 정책에 보존할 최대 스냅샷 복사본 수를 지정할 수 있는 스냅샷 정책 생성 대화 상자를 엽니다.

* * 편집 *
+
스냅샷 복사본 생성 빈도 및 유지할 스냅샷 복사본의 최대 수를 수정할 수 있는 스냅샷 정책 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 스냅샷 정책을 삭제할 수 있는 삭제 대화 상자를 엽니다.

* * 다른 것으로 보기 *
+
스냅샷 정책을 목록 또는 트리로 볼 수 있습니다.

* * 상태 *
+
선택한 스냅샷 정책을 설정하거나 해제하는 데 사용할 수 있는 메뉴를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 스냅샷 정책 목록입니다

* * 정책/일정 이름 *
+
스냅샷 정책의 이름과 정책의 일정을 지정합니다.

* * 스토리지 가상 머신 *
+
스냅샷 복사본이 속할 스토리지 가상 시스템(SVM)의 이름을 지정합니다.

* * 상태 *
+
스냅샷 정책의 상태를 Enabled 또는 Disabled로 지정합니다.

* * 보존할 최대 스냅샷 *
+
보존할 최대 스냅샷 복사본 수를 지정합니다.

* * SnapMirror 레이블 *
+
백업 스케줄에 따라 생성된 스냅샷 복사본의 SnapMirror 레이블 속성 이름을 지정합니다.


