---
permalink: online-help-96-97/concept_iscsi_protocol.html 
sidebar: sidebar 
keywords: iscsi, protocol, system, manager, configure, block, data, host, tcp, ip, online, help, initiate, disable, enable, dialog, box, security, authentication, default 
summary: System Manager를 사용하여 TCP/IP를 통해 SCSI 프로토콜을 사용하여 블록 데이터를 호스트로 전송할 수 있는 iSCSI 프로토콜을 구성할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 iSCSI 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 TCP/IP를 통해 SCSI 프로토콜을 사용하여 블록 데이터를 호스트로 전송할 수 있도록 iSCSI 프로토콜을 구성할 수 있습니다.



== iSCSI 별칭을 생성합니다

iSCSI 별칭은 사용자 인터페이스에서 대상 디바이스를 더 쉽게 식별할 수 있도록 iSCSI 타겟 디바이스(이 경우 스토리지 시스템)에 할당하는 사용자 친화적인 식별자입니다. System Manager를 사용하여 iSCSI 별칭을 생성할 수 있습니다.

.이 작업에 대해
iSCSI 별칭은 인쇄 가능한 문자를 1-128자로 하는 문자열입니다. iSCSI 별칭에는 공백을 포함할 수 없습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. iSCSI * 창의 * 서비스 * 탭에서 * 편집 * 을 클릭합니다.
. iSCSI 서비스 구성 편집 * 대화 상자의 * 대상 별칭 * 필드에 iSCSI 별칭을 입력한 다음 * 확인 * 을 클릭합니다.




== 스토리지 시스템 인터페이스에서 iSCSI 서비스를 설정하거나 해제합니다

System Manager를 사용하면 인터페이스를 활성화 또는 비활성화하여 iSCSI 통신에 사용되는 네트워크 인터페이스를 제어할 수 있습니다. iSCSI 서비스가 활성화되면 iSCSI에 대해 활성화되었지만 비활성화된 인터페이스를 통해 활성화되지 않은 네트워크 인터페이스를 통해 iSCSI 연결 및 요청이 허용됩니다.

.시작하기 전에
현재 인터페이스를 사용 중인 미처리 iSCSI 연결 및 세션을 종료해야 합니다. 기본적으로 iSCSI 라이센스를 활성화한 후에는 모든 이더넷 인터페이스에서 iSCSI 서비스가 활성화됩니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. iSCSI 인터페이스 * 영역에서 iSCSI 서비스를 활성화하거나 비활성화할 인터페이스를 선택합니다.
. 필요에 따라 * 활성화 * 또는 * 비활성화 * 를 클릭합니다.




== iSCSI 이니시에이터에 대한 보안 방법을 추가합니다

System Manager를 사용하여 이니시에이터를 추가하고 이니시에이터를 인증하는 데 사용되는 보안 방법을 지정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. iSCSI * 창에서 * 초기자 보안 * 탭을 클릭합니다.
. 초기자 보안 * 영역에서 * 추가 * 를 클릭합니다.
. 이니시에이터 이름과 이니시에이터를 인증하는 보안 방법을 지정합니다.
+
CHAP 인증의 경우 사용자 이름과 암호를 입력한 다음 인바운드 설정에 대한 암호를 확인해야 합니다. 아웃바운드 설정의 경우 이 로그인 정보는 선택 사항입니다.

. 확인 * 을 클릭합니다.




== 기본 보안 설정을 편집합니다

System Manager의 기본 보안 편집 대화 상자를 사용하여 스토리지 시스템에 접속된 iSCSI 이니시에이터에 대한 기본 보안 설정을 편집할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. 초기자 보안 * 탭의 * 기본 보안 * 영역에서 * 편집 * 을 클릭합니다.
. 기본 보안 편집 * 대화 상자에서 보안 유형을 변경합니다.
+
CHAP 인증의 경우 사용자 이름과 암호를 입력한 다음 인바운드 설정에 대한 암호를 확인해야 합니다. 아웃바운드 설정의 경우 이 로그인 정보는 선택 사항입니다.

. 확인 * 을 클릭합니다.




== 기본 iSCSI 초기자 인증 방법을 변경합니다

System Manager를 사용하여 특정 인증 방법으로 구성되지 않은 이니시에이터에 사용되는 인증 방법인 기본 iSCSI 인증 방법을 변경할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. 초기자 보안 * 탭의 * 기본 보안 * 영역에서 * 편집 * 을 클릭합니다.
. 보안 유형을 변경합니다.
+
CHAP 인증의 경우 사용자 이름과 암호를 입력한 다음 인바운드 설정에 대한 암호를 확인해야 합니다. 아웃바운드 설정의 경우 이 로그인 정보는 선택 사항입니다.

. 확인 * 을 클릭합니다.




== iSCSI 이니시에이터에 대한 기본 보안을 설정합니다

System Manager를 사용하여 이니시에이터의 인증 설정을 제거하고 기본 보안 방법을 사용하여 이니시에이터를 인증할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. 초기자 보안 * 탭에서 보안 설정을 변경할 초기자를 선택합니다.
. 초기자 보안 * 영역에서 * 기본값 설정 * 을 클릭한 다음 확인 대화 상자에서 * 기본값 설정 * 을 클릭합니다.




== iSCSI 서비스를 시작하거나 중지합니다

System Manager를 사용하여 스토리지 시스템에서 iSCSI 서비스를 시작하거나 중지할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. 필요에 따라 * 시작 * 또는 * 중지 * 를 클릭합니다.




== 이니시에이터 보안 정보를 봅니다

System Manager를 사용하면 기본 인증 정보와 모든 이니시에이터별 인증 정보를 볼 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. iSCSI * 창의 * 초기자 보안 * 탭에서 세부 정보를 검토합니다.




== iSCSI 창

iSCSI 창을 사용하여 iSCSI 서비스를 시작 또는 중지하고, 스토리지 시스템 iSCSI 노드 이름을 변경하고, 스토리지 시스템의 iSCSI 별칭을 생성하거나 변경할 수 있습니다. 스토리지 시스템에 접속된 iSCSI 이니시에이터의 이니시에이터 보안 설정을 추가하거나 변경할 수도 있습니다.



=== 탭

* * 서비스 *
+
서비스 * 탭을 사용하여 iSCSI 서비스를 시작 또는 중지하고, 스토리지 시스템 iSCSI 노드 이름을 변경하고, 스토리지 시스템의 iSCSI 별칭을 만들거나 변경할 수 있습니다.

* * 초기자 보안 *
+
이니시에이터 보안 * 탭을 사용하여 스토리지 시스템에 접속된 iSCSI 이니시에이터의 이니시에이터 보안 설정을 추가하거나 변경할 수 있습니다.





=== 명령 버튼

* * 편집 *
+
스토리지 시스템의 iSCSI 노드 이름 및 iSCSI 별칭을 변경할 수 있는 Edit iSCSI Service Configurations(iSCSI 서비스 구성 편집) 대화 상자를 엽니다.

* * 시작 *
+
iSCSI 서비스를 시작합니다.

* * 중지 *
+
iSCSI 서비스를 중지합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 세부 정보 영역

세부 정보 영역에는 iSCSI 서비스, iSCSI 타겟 노드 이름 및 iSCSI 타겟 별칭의 상태에 대한 정보가 표시됩니다. 이 영역을 사용하여 네트워크 인터페이스에서 iSCSI 서비스를 활성화 또는 비활성화할 수 있습니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 관리"^]
