---
permalink: online-help-96-97/concept_array_luns.html 
sidebar: sidebar 
keywords: system, manager, array, lun, aggregate, assign, online, help, classic 
summary: System Manager를 사용하여 어레이 LUN을 기존 애그리게이트에 할당하고 어레이 LUN을 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 스토리지 LUN 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 방식을 사용하여 어레이 LUN을 기존 애그리게이트에 할당하고 어레이 LUN을 관리할 수 있습니다.



== 스토리지 LUN을 할당합니다

System Manager를 사용하면 할당되지 않은 어레이 LUN을 기존 애그리게이트에 할당하여 애그리게이트 크기를 늘릴 수 있습니다.

.이 작업에 대해
* 다음 조건이 맞으면 스토리지 LUN을 할당할 수 있습니다.
+
** 선택한 스토리지 LUN의 컨테이너 유형은 ""할당되지 않음""이어야 합니다.
** HA Pair의 노드에 디스크를 연결해야 합니다.
** 디스크가 노드에 표시되어야 합니다.


* MetroCluster 구성의 경우 System Manager를 사용하여 어레이 LUN을 스페어로 할당할 수 없습니다.
+
대신 명령줄 인터페이스를 사용해야 합니다.



.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 어레이 LUN * 을 클릭합니다.
. 스토리지 LUN을 선택한 다음 * 할당 * 을 클릭합니다.
. 스토리지 LUN 할당 * 대화 상자에서 스토리지 LUN을 할당할 노드를 선택합니다.
. 할당 * 을 클릭합니다.




== 스페어 어레이 LUN을 노드에 재할당합니다

System Manager를 사용하여 스페어 어레이 LUN의 소유권을 한 노드에서 다른 노드로 재할당하여 애그리게이트의 용량을 늘릴 수 있습니다.

.이 작업에 대해
* 다음 조건에 해당하는 경우 어레이 LUN을 재할당할 수 있습니다.
+
** 선택한 스토리지 LUN의 컨테이너 유형은 "s are"여야 합니다.
** HA Pair의 노드에 디스크를 연결해야 합니다.
** 디스크가 노드에 표시되어야 합니다.


* MetroCluster 구성의 경우 System Manager를 사용하여 어레이 LUN을 스페어로 재할당할 수 없습니다.
+
대신 명령줄 인터페이스를 사용해야 합니다.



.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 어레이 LUN * 을 클릭합니다.
. 재할당할 스페어 어레이 LUN을 선택하고 * 할당 * 을 클릭합니다.
. 경고 * 대화 상자에서 * 계속 * 을 클릭합니다.
. 스토리지 LUN 할당 * 대화 상자에서 스페어 어레이 LUN을 재할당할 노드를 선택합니다.
. 할당 * 을 클릭합니다.




== 스페어 스토리지 LUN 제로화

System Manager를 사용하면 모든 데이터를 지우고 어레이 LUN에 0을 작성하여 스페어 어레이 LUN을 포맷할 수 있습니다. 그런 다음 이러한 어레이 LUN을 새 애그리게이트에서 사용할 수 있습니다.

.이 작업에 대해
스페어 어레이 LUN을 제로화하면 디스크를 포함하여 클러스터의 모든 스페어가 제로화됩니다. 특정 노드나 전체 클러스터에 대해 스페어 어레이 LUN을 0으로 설정할 수 있습니다.

.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 어레이 LUN * 을 클릭합니다.
. Zero Spares*를 클릭합니다.
. Zero Spares* 대화 상자에서 어레이 LUN을 제로화하려는 노드 또는 ""모든 노드""를 선택합니다.
. Zero All Non-Zeroed Spare * 확인란을 선택하여 제로화 작업을 확인합니다.
. Zero Spares*를 클릭합니다.




== 디스크 및 어레이 LUN 정보

디스크는 ONTAP 소프트웨어를 사용하여 네이티브 디스크 쉘프에 액세스하는 스토리지 시스템을 위한 기본 스토리지 단위입니다. 어레이 LUN은 타사 스토리지 어레이가 ONTAP 소프트웨어를 실행하는 스토리지 시스템에 제공하는 스토리지의 기본 단위입니다.

ONTAP 소프트웨어를 사용하면 디스크 및 어레이 LUN에 소유권을 할당하고 이를 Aggregate에 추가할 수 있습니다. ONTAP 소프트웨어는 또한 디스크를 제거, 교체 및 삭제하는 등 다양한 방법으로 디스크를 관리할 수 있습니다. 어레이 LUN은 타사 스토리지 어레이에서 제공하기 때문에 어레이 LUN에 대한 다른 모든 관리 작업에는 타사 스토리지 시스템을 사용합니다.

디스크 또는 어레이 LUN을 사용하여 애그리게이트를 생성할 수 있습니다. Aggregate를 생성한 후에는 ONTAP 소프트웨어를 사용하여 디스크 또는 어레이 LUN에서 생성된 것과 동일한 방식으로 Aggregate를 관리할 수 있습니다.



== Array LUNs 창

어레이 LUN 창에서는 어레이 LUN에 소유권을 할당하고 이를 애그리게이트에 추가할 수 있습니다.

왼쪽 탐색 창의 Array LUNs 링크는 스페어 스토리지 LUN이 있거나 V_StorageAttach 라이센스가 설치된 경우에만 표시됩니다.



=== 명령 버튼

* * 배정 *
+
어레이 LUN의 소유권을 노드에 할당 또는 재할당할 수 있습니다.

* * 예비 부품 없음*
+
모든 데이터를 지우고 스페어 어레이 LUN 및 디스크를 포맷합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 스토리지 LUN 목록입니다

각 스토리지 LUN의 이름, 상태 및 공급업체와 같은 정보를 표시합니다.

* * 이름 *
+
스토리지 LUN의 이름을 지정합니다.

* * 시/도 *
+
스토리지 LUN의 상태를 지정합니다.

* * 공급업체 *
+
공급업체의 이름을 지정합니다.

* * 사용된 공간 *
+
스토리지 LUN에서 사용하는 공간을 지정합니다.

* * 총 크기 *
+
스토리지 LUN의 크기를 지정합니다.

* * 컨테이너 *
+
어레이 LUN이 속할 Aggregate를 지정합니다.

* * 노드 이름 *
+
스토리지 LUN이 속한 노드의 이름을 지정합니다.

* * 홈 소유자 *
+
어레이 LUN이 할당된 홈 노드의 이름을 표시합니다.

* * 현재 소유자 *
+
현재 스토리지 LUN을 소유하는 노드의 이름을 표시합니다.

* * 배열 이름 *
+
배열의 이름을 지정합니다.

* * 풀 *
+
선택한 스토리지 LUN이 할당된 풀의 이름을 표시합니다.





=== 세부 정보 영역

Array LUNs 목록 아래의 영역에는 선택한 스토리지 LUN에 대한 자세한 정보가 표시됩니다.

* 관련 정보 *

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 가상화 설치 요구 사항 및 참조 자료"]
