---
permalink: online-help-96-97/concept_hardware_cache.html 
sidebar: sidebar 
keywords: hardware, cache, system, manager, manage, online, help, flash, 
summary: System Manager를 사용하여 하드웨어 캐시 모듈을 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 하드웨어 캐시를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하여 하드웨어 캐시 모듈을 관리할 수 있습니다.

[NOTE]
====
Flash Cache는 System Manager의 하드웨어 캐시라고 합니다.

====


== Flash Cache 모듈을 사용하거나 사용하지 않도록 설정합니다

System Manager를 사용하여 Flash Cache 모듈이 설치된 스토리지 시스템에 대해 외부 캐시 기능을 설정하거나 해제할 수 있습니다. 스토리지 시스템의 워크로드 요구사항에 따라 Flash Cache 모듈을 사용하도록 설정할 수 있습니다.

.단계
. 구성 * > * 하드웨어 캐시 * 를 클릭합니다
. 모듈이나 모듈을 수정하려면 필요에 따라 슬라이더 버튼을 움직여 각 모듈을 활성화 또는 비활성화합니다.




== Flash Cache 모듈의 작동 방식

Flash Cache 모듈을 사용하면 스토리지 시스템의 성능이 향상됩니다. Flash Cache 모듈을 사용할 때의 영향이 하드웨어 캐시 창에 표시됩니다.

스토리지 시스템의 워크로드 요구사항에 따라 Flash Cache 모듈과 디스크를 구성할 수 있습니다. Flash Cache 모듈과 디스크가 제공하는 읽기 워크로드(읽기 작업 수)를 확인하여 스토리지 시스템의 성능을 분석할 수 있습니다.

스토리지 시스템 부팅 중에 또는 테이크오버 이벤트 후 제어가 스토리지 시스템으로 반환되는 경우에는 Flash Cache 모듈에 데이터가 없습니다. 따라서 디스크는 스토리지 시스템의 모든 데이터 읽기 요청을 처리합니다.

데이터 읽기 요청이 처리되면 Flash Cache 모듈이 서서히 데이터로 채워집니다. Flash Cache 모듈이 제공하는 데이터 읽기 요청이 디스크에서 제공하는 것보다 빠르기 때문에 스토리지 시스템의 성능이 향상됩니다.

Flash Cache 모듈이 제공하는 데이터 읽기 요청은 디스크에서 제공되는 데이터 읽기 요청을 대체하므로 스토리지 시스템의 성능 향상 기능은 교체된 디스크 읽기와 직접 연결됩니다. Flash Cache 모듈이 스토리지 시스템 성능에 미치는 영향을 이해하려면 Flash Cache 모듈에 데이터가 포함되어 있을 때 하드웨어 캐시 창에서 읽기 워크로드 그래프를 확인해야 합니다.



== 하드웨어 캐시 창

하드웨어 캐시 창을 사용하여 Flash Cache 모듈이 설치된 스토리지 시스템에 대해 Flash Cache 모듈을 사용하거나 사용하지 않도록 설정할 수 있습니다. 읽기 워크로드 통계를 볼 수도 있습니다.



=== 모듈 정보

* * 스토리지 시스템 이름 *
+
Flash Cache 모듈이 설치된 스토리지 시스템의 이름이 그래픽 아래에 표시됩니다.

* * 토글 버튼 활성화/비활성화 *
+
토글 버튼을 움직여 모듈을 활성화 또는 비활성화합니다.

* * 크기 *
+
모듈 크기(GB)입니다. Flash Cache 모듈 카드가 여러 개인 경우 모든 카드의 총 캐시 크기가 표시됩니다.

+
[NOTE]
====
표시되는 Flash Cache 모듈 크기는 다음과 같은 이유로 실제 크기와 다릅니다.
    - System Manager는 ONTAP에서 제공하는 가용 용량만 보고합니다.
    - 전체 용량의 일부는 메타데이터를 저장하기 위해 예약됩니다.

====
* * 모델 이름 *
+
모듈의 모델 이름입니다.

* * 시스템 읽기 지연 시간 *
+
평균 읽기 지연 시간을 밀리초 단위로 표시합니다.





=== 캐시 읽기 작업 부하

디스크와 Flash Cache 모듈이 제공하는 읽기 워크로드의 속도를 지정하는 그래프를 표시하여 스토리지 시스템의 성능을 나타냅니다.
