---
permalink: online-help-96-97/concept_cluster_expansion.html 
sidebar: sidebar 
keywords: cluster, expanision, system, manager, storage, size, capabilities, add, node, configure, network, online, help 
summary: System Manager를 사용하면 클러스터에 호환되는 노드를 추가하고 노드 네트워크 세부 정보를 구성하여 스토리지의 크기와 기능을 높일 수 있습니다. 노드의 요약을 볼 수도 있습니다. 
---
= System Manager로 클러스터 확장 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 클러스터에 호환되는 노드를 추가하고 노드 네트워크 세부 정보를 구성하여 스토리지의 크기와 기능을 확장할 수 있습니다. 노드의 요약을 볼 수도 있습니다.

System Manager에 로그인하면 System Manager가 케이블로 연결되었지만 클러스터에 추가되지 않은 호환 노드를 자동으로 감지하여 노드를 추가하라는 메시지를 표시합니다. 호환 노드를 추가하거나 System Manager가 노드를 감지할 때 또는 나중에 노드를 수동으로 추가할 수 있습니다.



== 클러스터에 노드 추가

System Manager를 사용하면 기존 클러스터에 노드를 추가하여 스토리지 시스템의 크기와 기능을 높일 수 있습니다.

.시작하기 전에
* 호환되는 새 노드를 클러스터에 케이블로 연결해야 합니다.
+
기본 브로드캐스트 도메인에 있는 포트만 네트워크 창에 나열됩니다.

* 클러스터의 모든 노드가 실행 중이어야 합니다.
* 모든 노드의 버전은 동일해야 합니다.


.단계
. 클러스터에 호환되는 새 노드를 추가합니다.
+
|===
| 만약... | 수행할 작업... 


 a| 
System Manager에 로그인하지 않았습니다
 a| 
.. System Manager에 로그인합니다.
+
[NOTE]
====
로그인 시 System Manager에서 호환되는 새 노드를 자동으로 감지합니다. System Manager에서 클러스터에 호환되는 새 노드를 추가하라는 메시지가 표시됩니다.

====
.. 클러스터에 노드 추가 * 를 클릭합니다.
.. 노드의 이름을 수정합니다.
.. 노드 라이센스를 지정합니다.
.. 제출 및 진행 * 을 클릭합니다.




 a| 
System Manager에 로그인했습니다
 a| 
.. 구성 * > * 클러스터 * > * 확장 * 을 클릭합니다.
+
System Manager에서 새로 추가된 노드를 검색합니다. 경고가 표시되면 계속하기 전에 이를 수정해야 합니다. 호환되는 새 노드가 검색되면 다음 단계를 진행하십시오.

.. 노드의 이름을 수정합니다.
.. 노드 라이센스를 지정합니다.
.. 제출 및 진행 * 을 클릭합니다.


|===




== 노드의 네트워크 세부 정보를 구성합니다

System Manager를 사용하여 노드 관리 LIF 및 새로 추가된 노드의 서비스 프로세서 설정을 구성할 수 있습니다.

.시작하기 전에
* LIF 생성을 위한 기본 IPspace에 충분한 포트 수가 있어야 합니다.
* 모든 포트가 실행 중이어야 합니다.


.단계
. 노드 관리 구성:
+
.. IP 주소 * 필드에 IP 주소를 입력합니다.
.. Port * 필드에서 노드 관리용 포트를 선택합니다.
.. 넷마스크 및 게이트웨이 세부 정보를 입력합니다.


. 서비스 프로세서 설정 구성:
+
.. 기본값을 무시하려면 * Override defaults * 확인란을 선택합니다.
.. IP 주소, 넷마스크 및 게이트웨이 세부 정보를 입력합니다.


. Submit을 클릭하고 계속 * 을 클릭하여 노드의 네트워크 구성을 완료합니다.
. 요약 * 페이지에서 노드의 세부 정보를 확인합니다.




=== 다음 단계

* 클러스터가 보호되는 경우 부분 피어링과 비정상적인 보호를 방지하기 위해 새로 추가된 노드에 필요한 수의 인터클러스터 LIF를 생성해야 합니다.
* 클러스터에서 SAN 데이터 프로토콜이 활성화되어 있는 경우 데이터를 제공하는 데 필요한 수의 SAN 데이터 LIF를 생성해야 합니다.


* 관련 정보 *

xref:task_creating_network_interfaces.adoc[네트워크 인터페이스를 생성하는 중입니다]
