---
permalink: online-help-96-97/concept_storage_pools.html 
sidebar: sidebar 
keywords: system, manager, storage, pools, ssd, flash, pool, aggregates, online, help, create, 
summary: System Manager를 사용하면 스토리지 풀을 생성하여 여러 Flash Pool 애그리게이트에서 SSD를 공유할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 스토리지 풀을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 스토리지 풀을 생성하여 여러 Flash Pool 애그리게이트에서 SSD를 공유할 수 있습니다.



== 스토리지 풀을 생성합니다

스토리지 풀은 SSD(캐시 디스크)의 모음입니다. System Manager를 사용하면 SSD를 결합하여 스토리지 풀을 생성할 수 있습니다. 이 경우 HA 쌍 간에 SSD와 SSD 스페어를 공유하여 동시에 2개 이상의 Flash Pool 애그리게이트에 할당될 수 있습니다.

.시작하기 전에
* 스토리지 풀을 통해 SSD와 SSD 스페어를 할당하려면 HA 쌍의 두 노드가 모두 가동 및 실행 중이어야 합니다.
* 스토리지 풀에는 최소 3개의 SSD가 있어야 합니다.
* 스토리지 풀의 모든 SSD는 동일한 HA 쌍이 소유해야 합니다.


.이 작업에 대해
System Manager에서는 SSD를 사용하여 스토리지 풀에 디스크를 추가할 때 SSD RAID 그룹에 핫 스페어 규칙을 적용합니다. 예를 들어, SSD RAID 그룹에 10개의 SSD와 옵션이 있는 경우 `raid.min_spare_count` 가 로 설정되어 있습니다 `1` System Manager는 노드 레벨에서 SSD 1개를 핫 스페어로 남겨 두고 다른 9개의 SSD를 SSD 관련 작업에 사용합니다.

System Manager를 사용하여 스토리지 풀을 생성할 때는 파티션이 설정된 SSD를 사용할 수 없습니다.

.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 스토리지 풀 * 을 클릭합니다.
. Storage Pools * 창에서 * Create * 를 클릭합니다.
. Create Storage Pool * 대화 상자에서 스토리지 풀의 이름, 디스크 크기 및 디스크 수를 지정합니다.
. Create * 를 클릭합니다.




== 스토리지 풀에 디스크를 추가합니다

System Manager를 사용하면 기존 스토리지 풀에 SSD를 추가하고 캐시 크기를 늘릴 수 있습니다.

.시작하기 전에
스토리지 풀을 통해 SSD와 SSD 스페어를 할당하려면 HA 쌍의 두 노드가 모두 가동 및 실행 중이어야 합니다.

.이 작업에 대해
* 스토리지 풀에 추가하는 SSD는 스토리지 풀 캐시를 사용하는 애그리게이트 및 스토리지 풀의 여유 공간에 비례하여 분산됩니다.
* System Manager에서는 SSD를 사용하여 스토리지 풀에 디스크를 추가할 때 SSD RAID 그룹에 핫 스페어 규칙을 적용합니다.
+
예를 들어, SSD RAID 그룹에 10개의 SSD와 옵션이 있는 경우 `raid.min_spare_count` 가 로 설정되어 있습니다 `1` System Manager는 노드 레벨에서 SSD 1개를 핫 스페어로 남겨 두고 다른 9개의 SSD를 SSD 관련 작업에 사용합니다.

* System Manager를 사용하여 스토리지 풀에 디스크를 추가할 때는 파티션이 설정된 SSD를 사용할 수 없습니다.


.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 스토리지 풀 * 을 클릭합니다.
. Storage Pools * 창에서 스토리지 풀을 선택한 다음 * Add Disks * 를 클릭합니다.
. 디스크 추가 * 대화 상자에서 추가할 디스크 수를 지정합니다.
. 다음 * 을 클릭합니다.
. Summary * 대화 상자에서 다양한 Aggregate와 스토리지 풀의 사용 가능한 공간 간에 캐시가 어떻게 분산되는지 검토합니다.
. 추가 * 를 클릭합니다.




== 스토리지 풀을 삭제합니다

스토리지 풀의 캐시가 최적화되지 않았거나 aggregate 또는 Flash Pool 애그리게이트에서 더 이상 사용되지 않는 경우 스토리지 풀을 삭제할 수 있습니다. System Manager에서 스토리지 풀 삭제 대화 상자를 사용하여 스토리지 풀을 삭제할 수 있습니다.

.시작하기 전에
스토리지 풀은 어떠한 애그리게이트에서도 사용할 수 없습니다.

.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 스토리지 풀 * 을 클릭합니다.
. Storage Pools * 창에서 삭제할 스토리지 풀을 선택한 다음 * Delete * 를 클릭합니다.
. 스토리지 풀 삭제 * 대화 상자에서 * 삭제 * 를 클릭합니다.




== SSD 스토리지 풀을 사용합니다

여러 Flash Pool 애그리게이트에서 SSD를 공유하려면 SSD를 _storage pool_에 추가하면 됩니다. 스토리지 풀에 SSD를 추가한 후에는 SSD를 더 이상 독립 실행형 엔터티로 관리할 수 없습니다. 스토리지 풀을 사용하여 SSD에서 제공하는 스토리지를 할당하거나 할당해야 합니다.

특정 HA(고가용성) 쌍에 대한 스토리지 풀을 생성할 수 있습니다. 그런 다음, 해당 스토리지 풀의 할당 유닛을 동일한 HA 쌍이 소유한 하나 이상의 Flash Pool 애그리게이트에 추가할 수 있습니다. 디스크를 애그리게이트에 속해 있는 동일한 노드에서 디스크를 소유해야 디스크를 할당할 수 있기 때문에 스토리지 풀은 스토리지 풀을 소유한 노드 중 하나가 소유한 Flash Pool 애그리게이트에만 스토리지를 제공할 수 있습니다.

시스템에서 Flash Pool 캐시의 양을 늘려야 하는 경우 스토리지 풀을 사용 중인 Flash Pool 캐시의 RAID 유형에 대한 최대 RAID 그룹 크기까지 스토리지 풀에 SSD를 더 추가할 수 있습니다. 기존 스토리지 풀에 SSD를 추가하면 Flash Pool 애그리게이트에 이미 할당된 할당 유닛을 비롯하여 스토리지 풀의 할당 유닛 크기가 증가합니다.

스토리지 풀에는 하나의 예비 SSD만 사용할 수 있으므로 해당 스토리지 풀의 SSD를 사용할 수 없게 되면 ONTAP는 예비 SSD를 사용하여 장애가 발생한 SSD의 파티션을 재구성할 수 있습니다. 여유 용량으로 할당 유닛을 예약할 필요는 없습니다. ONTAP에서는 파티셔닝되지 않은 전체 SSD만 스토리지 풀의 SSD용 스페어로 사용할 수 있습니다.

스토리지 풀에 SSD를 추가한 후에는 애그리게이트에서 디스크를 제거할 수 없으므로 SSD를 제거할 수 없습니다. 스토리지 풀의 SSD를 개별 드라이브로 다시 사용하려면 스토리지 풀의 할당 유닛이 할당된 모든 Flash Pool 애그리게이트를 제거한 다음 스토리지 풀을 제거해야 합니다.



== SSD 스토리지 풀 사용에 대한 요구사항 및 모범 사례

일부 기술은 SSD 스토리지 풀을 사용하는 Flash Pool 애그리게이트와 결합할 수 없습니다.

캐시 스토리지에 SSD 스토리지 풀을 사용하는 Flash Pool 애그리게이트에는 다음 기술을 사용할 수 없습니다.

* MetroCluster
* SyncMirror 기능
+
미러링된 애그리게이트는 스토리지 풀을 사용하는 Flash Pool 애그리게이트와 공존할 수 있지만 Flash Pool 애그리게이트는 미러링할 수 없습니다.

* 물리적 SSD
+
Flash Pool 애그리게이트는 SSD 스토리지 풀 또는 물리적 SSD를 사용할 수 있지만 둘 다 사용할 수는 없습니다.



SSD 스토리지 풀은 다음 규칙을 준수해야 합니다.

* SSD 스토리지 풀에는 SSD만 포함될 수 있으며 HDD는 SSD 스토리지 풀에 추가할 수 없습니다.
* SSD 스토리지 풀에 있는 모든 SSD는 동일한 HA(고가용성) 쌍이 소유해야 합니다.
* 스토리지 풀에서 루트 데이터 파티셔닝으로 분할된 SSD는 사용할 수 없습니다.


단일 스토리지 풀에서 다른 RAID 유형의 두 개의 캐시로 스토리지를 제공하고 스토리지 풀의 크기를 RAID4의 최대 RAID 그룹 크기 이상으로 확장하는 경우 RAID4 할당 유닛의 추가 파티션은 사용되지 않습니다. 따라서 캐시 RAID 유형을 스토리지 풀에 대해 동일하게 유지하는 것이 가장 좋습니다.

스토리지 풀에서 할당된 캐시 RAID 그룹의 RAID 유형은 변경할 수 없습니다. 첫 번째 할당 유닛을 추가하기 전에 캐시에 대한 RAID 유형을 설정하며 나중에 RAID 유형을 변경할 수 없습니다.

스토리지 풀을 생성하거나 기존 스토리지 풀에 SSD를 추가할 때 동일한 크기의 SSD를 사용해야 합니다. 장애가 발생하고 올바른 크기의 스페어 SSD가 존재하지 않는 경우, ONTAP는 더 큰 SSD를 사용하여 장애가 발생한 SSD를 대체할 수 있습니다. 하지만 이보다 큰 SSD의 크기는 스토리지 풀의 다른 SSD 크기와 일치하도록 적당한 크기이므로 SSD 용량이 손실될 수 있습니다.

스토리지 풀에는 하나의 예비 SSD만 사용할 수 있습니다. 스토리지 풀에서 HA 쌍의 두 노드가 소유한 Flash Pool 애그리게이트에 할당 유닛을 제공하는 경우, 두 노드 중 하나의 스페어 SSD를 소유할 수 있습니다. 하지만 스토리지 풀에서 HA 쌍의 노드 중 하나가 소유하는 Flash Pool 애그리게이트에만 할당 유닛을 제공하는 경우, SSD 스페어는 동일한 노드에서 소유해야 합니다.



== SSD 스토리지 풀을 사용할 때의 고려 사항

SSD 스토리지 풀은 많은 이점을 제공하지만 SSD 스토리지 풀 또는 전용 SSD를 사용할지 결정할 때 유의해야 할 몇 가지 제한 사항이 있습니다.

SSD 스토리지 풀은 캐시를 두 개 이상의 Flash Pool 애그리게이트에 제공하는 경우에만 적합합니다. SSD 스토리지 풀은 다음과 같은 이점을 제공합니다.

* Flash Pool 애그리게이트에 사용되는 SSD의 스토리지 활용률을 높입니다
+
SSD 스토리지 풀은 두 개 이상의 Flash Pool 애그리게이트 간에 패리티 SSD를 공유할 수 있도록 지원하여 패리티에 필요한 SSD의 전체 비율을 줄입니다.

* HA 파트너 간에 스페어 공유 가능
+
스토리지 풀은 HA 쌍이 효과적으로 소유하기 때문에 HA 파트너 중 하나에서 소유하는 하나의 스페어는 필요한 경우 전체 SSD 스토리지 풀을 위한 스페어로 사용할 수 있습니다.

* SSD 성능을 더욱 효과적으로 활용
+
SSD에서 제공하는 고성능을 활용하면 HA 2노드의 두 컨트롤러에 대한 액세스를 지원할 수 있습니다.



이러한 이점은 다음과 같은 항목이 포함된 SSD 스토리지 풀 사용 비용에 대해 가중치를 두어야 합니다.

* 장애 격리 감소
+
단일 SSD가 손실되면 해당 파티션 중 하나가 포함된 모든 RAID 그룹에 영향을 미칩니다. 이 경우 영향을 받는 SSD를 포함하는 SSD 스토리지 풀에서 할당된 캐시가 있는 모든 Flash Pool 애그리게이트에 1개 이상의 RAID 그룹이 재구성 중입니다.

* 성능 격리 감소
+
Flash Pool 캐시의 크기가 올바르게 조정되지 않은 경우, Flash Pool 애그리게이트 간에 공유 중인 캐시의 경합이 발생할 수 있습니다. 이러한 위험은 적절한 캐시 사이징 및 QoS 제어를 통해 완화할 수 있습니다.

* 관리 유연성 감소
+
스토리지 풀에 스토리지를 추가하면 해당 스토리지 풀에서 하나 이상의 할당 유닛이 포함된 All Flash Pool 캐시의 크기가 늘어나며, 추가 용량이 어떻게 배포되는지 확인할 수 없습니다.





== 기존 스토리지 풀에 SSD를 추가하는 경우와 새 스토리지 풀을 생성할 때의 고려 사항

기존 SSD 스토리지 풀에 SSD를 추가하거나 새 SSD 스토리지 풀을 생성하여 두 가지 방법으로 SSD 캐시의 크기를 늘릴 수 있습니다. 가장 적합한 방법은 스토리지 구성 및 계획에 따라 달라집니다.

새 스토리지 풀을 생성하고 기존 풀에 스토리지 용량을 추가하는 것은 새 RAID 그룹을 생성할지 기존 그룹에 스토리지를 추가할지 여부를 결정하는 것과 비슷합니다.

* 많은 수의 SSD를 추가하는 경우 새 스토리지 풀을 생성하면 기존 스토리지 풀과 달리 새 스토리지 풀을 할당할 수 있으므로 유연성이 향상됩니다.
* SSD를 몇 개만 추가하고 기존 Flash Pool 캐시의 RAID 그룹 크기를 늘리는 것이 문제가 아닌 경우, 기존 스토리지 풀에 SSD를 추가해도 예비 비용과 패리티 비용을 낮게 유지하고 새 스토리지를 자동으로 할당합니다.


스토리지 풀에서 RAID 유형이 서로 다른 캐시를 사용하는 Flash Pool 애그리게이트에 할당 유닛을 제공하고, 최대 RAID4 RAID 그룹 크기를 초과하여 스토리지 풀의 크기를 확장하는 경우, RAID4 할당 유닛에 새로 추가된 파티션은 사용되지 않습니다.



== 스토리지 풀에 디스크를 추가하는 이유

기존 스토리지 풀에 SSD를 추가하고 캐시 크기를 늘릴 수 있습니다. 할당 유닛이 이미 Flash Pool 애그리게이트에 할당된 스토리지 풀에 SSD를 추가할 경우, 각 애그리게이트의 캐시 크기와 스토리지 풀의 총 캐시가 증가합니다.

스토리지 풀의 할당 유닛이 아직 할당되지 않은 경우 해당 스토리지 풀에 SSD를 추가해도 SSD 캐시 크기는 영향을 받지 않습니다.

기존 스토리지 풀에 SSD를 추가할 경우 SSD는 스토리지 풀에서 기존 SSD를 소유한 동일한 HA 쌍 중 하나 또는 둘 이상이 SSD를 소유해야 합니다. HA Pair의 노드 중 하나에서 소유하는 SSD를 추가할 수 있습니다.



== 스토리지 풀의 작동 방식

a_storage pool_은 SSD의 모음입니다. SSD를 결합하여 스토리지 풀을 생성할 수 있습니다. 이를 통해 여러 Flash Pool 애그리게이트 간에 SSD 및 SSD 스페어를 동시에 공유할 수 있습니다.

스토리지 풀은 SSD 및 SSD 스페어를 제공하거나 기존 SSD 크기를 늘리는 데 사용할 수 있는 할당 유닛으로 구성됩니다.

스토리지 풀에 SSD를 추가한 후에는 SSD를 더 이상 개별 디스크로 사용할 수 없습니다. 스토리지 풀을 사용하여 SSD에서 제공하는 스토리지를 할당하거나 할당해야 합니다.



== Storage Pools 창

스토리지 풀 창을 사용하여 _스토리지 풀_라고도 하는 SSD 전용 캐시를 생성, 표시 및 관리할 수 있습니다. 이러한 스토리지 풀은 비루트 애그리게이트와 연결되어 SSD 캐시를 제공하고 Flash Pool 애그리게이트로 크기를 늘릴 수 있습니다.

All-Flash 최적화 속성을 가진 노드가 포함된 클러스터에서는 이 페이지를 사용할 수 없습니다.



=== 명령 버튼

* * 생성 *
+
스토리지 풀 생성 대화 상자를 엽니다. 이 대화 상자에서 스토리지 풀을 생성할 수 있습니다.

* * 디스크 추가 *
+
스토리지 풀에 캐시 디스크를 추가할 수 있는 디스크 추가 대화 상자를 엽니다.

* * 삭제 *
+
선택한 스토리지 풀을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 스토리지 풀 목록입니다

* * 이름 *
+
스토리지 풀의 이름을 표시합니다.

* * 총 캐시 *
+
스토리지 풀의 총 캐시 크기를 표시합니다.

* * 스페어 캐시 *
+
스토리지 풀의 사용 가능한 스페어 캐시 크기를 표시합니다.

* * 사용된 캐시(%) *
+
스토리지 풀의 사용된 캐시 크기 비율을 표시합니다.

* * 할당 단위 *
+
스토리지 풀의 크기를 늘리는 데 사용할 수 있는 총 캐시 크기의 최소 할당 단위를 표시합니다.

* * 소유자 *
+
스토리지 풀이 연결된 HA 쌍 또는 노드의 이름을 표시합니다.

* * 시/도 *
+
스토리지 풀의 상태가 정상, 성능 저하, 생성, 삭제, 재할당, 있습니다.

* * 은(는) 건강합니다 *
+
스토리지 풀이 정상 상태인지 여부를 표시합니다.





=== 세부 정보 탭

선택한 스토리지 풀에 대한 이름, 상태, 스토리지 유형, 디스크 수, 총 캐시, 스페어 캐시, 사용된 캐시 크기(백분율) 및 할당 유닛입니다. 이 탭에는 스토리지 풀이 프로비저닝한 애그리게이트의 이름도 표시됩니다.



=== 디스크 탭을 클릭합니다

이름, 디스크 유형, 사용 가능한 크기 및 총 크기와 같이 선택한 스토리지 풀의 디스크에 대한 세부 정보를 표시합니다.

* 관련 정보 *

xref:task_provisioning_storage_by_creating_flash_pool_aggregate_manually.adoc[Flash Pool Aggregate를 수동으로 생성하여 스토리지 프로비저닝]

xref:task_provisioning_cache_by_adding_disks.adoc[SSD를 추가하여 캐시 프로비저닝]

https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["디스크 및 애그리게이트 관리"]
