---
permalink: online-help-96-97/concept_managing_network.html 
sidebar: sidebar 
keywords: system, manager, storage, create, manage, ipspace, broadcast, domain, subnet, network, interface, ethernet, port, fc, fcoe, adapter, online, help 
summary: System Manager를 사용하여 IPspace, 브로드캐스트 도메인, 서브넷, 네트워크 인터페이스, 이더넷 포트 를 생성 및 관리하여 스토리지 시스템 네트워크를 관리할 수 있습니다. 및 FC/FCoE 어댑터. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 네트워크를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IPspace, 브로드캐스트 도메인, 서브넷, 네트워크 인터페이스, 이더넷 포트 등을 생성 및 관리하여 ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 스토리지 시스템의 네트워크를 및 FC/FCoE 어댑터.



== 네트워크 창

[role="lead"]
네트워크 창을 사용하여 서브넷, 네트워크 인터페이스, 이더넷 포트, 브로드캐스트 도메인 등의 네트워크 구성 요소 목록을 볼 수 있습니다. FC/FCoE 및 NVMe 어댑터, IPspace, 스토리지 시스템에서 이러한 구성요소를 생성, 편집 또는 삭제할 수 있습니다.



=== 탭

* * 서브넷 *
+
서브넷 목록을 보고 스토리지 시스템에서 서브넷을 생성, 편집 또는 삭제할 수 있습니다.

* * 네트워크 인터페이스 *
+
네트워크 인터페이스 목록을 보고, 스토리지 시스템에서 인터페이스를 생성, 편집 또는 삭제하고, LIF를 마이그레이션하고, 인터페이스 상태를 변경하고, 인터페이스를 홈 포트로 다시 전송할 수 있습니다.

* 이더넷 포트 *
+
클러스터의 포트를 확인 및 편집하고 인터페이스 그룹 및 VLAN 포트를 생성, 편집 또는 삭제할 수 있습니다.

* * 브로드캐스트 도메인 *
+
브로드캐스트 도메인 목록을 보고 스토리지 시스템에서 도메인을 생성, 편집 또는 삭제할 수 있습니다.

* * FC/FCoE 및 NVMe 어댑터 *
+
클러스터의 포트를 보고 FC/FCoE 및 NVMe 어댑터 설정을 편집할 수 있습니다.

* IPspace *
+
IPspace 및 브로드캐스트 도메인 목록을 표시하고 스토리지 시스템에서 IPspace를 생성, 편집 또는 삭제할 수 있습니다.





=== Subnet 탭



=== 명령 버튼

* * 생성 *
+
네트워크 인터페이스를 생성하기 위한 구성 정보가 포함된 새 서브넷을 생성할 수 있는 서브넷 생성 대화 상자를 엽니다.

* * 편집 *
+
이름, 서브넷 주소, IP 주소 범위 및 게이트웨이 세부 정보와 같은 서브넷의 특정 속성을 수정할 수 있는 서브넷 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 서브넷을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 서브넷 목록

* * 이름 *
+
서브넷의 이름을 지정합니다.

* * 서브넷 IP/서브넷 마스크 *
+
서브넷 주소 세부 정보를 지정합니다.

* * 게이트웨이 *
+
게이트웨이의 IP 주소를 지정합니다.

* * 이용 가능 *
+
서브넷에서 사용할 수 있는 IP 주소의 수를 지정합니다.

* * 사용됨 *
+
서브넷에서 사용되는 IP 주소의 수를 지정합니다.

* * 총 개수 *
+
서브넷의 총 IP 주소 수(사용 가능 및 사용)를 지정합니다.

* * 브로드캐스트 도메인 *
+
서브넷이 속한 브로드캐스트 도메인을 지정합니다.

* IPspace *
+
서브넷이 속한 IPspace를 지정합니다.





=== 세부 정보 영역

서브넷 목록 아래의 영역에는 서브넷 범위와 사용 가능, 사용된 IP 주소 및 총 IP 주소 수를 보여주는 그래프를 포함하여 선택한 서브넷에 대한 자세한 정보가 표시됩니다.



=== 네트워크 인터페이스 탭의 제한 사항

* 클러스터 LIF, 노드 관리 LIF, VIP LIF 및 BGP LIF의 경우 System Manager를 사용하여 다음 작업을 수행할 수 없습니다.
+
** LIF를 생성, 편집, 삭제, 설정 또는 비활성화합니다
** LIF를 마이그레이션하거나 LIF를 홈 포트로 다시 전송하십시오


* 클러스터 관리 LIF의 경우 System Manager를 사용하여 LIF를 마이그레이션하거나 LIF를 홈 포트로 다시 전송할 수 있습니다.
+
그러나, 다음을 생성, 편집, 삭제, 활성화할 수는 없습니다. 또는 LIF를 비활성화합니다.

* 인터클러스터 LIF의 경우 System Manager를 사용하여 LIF를 생성, 편집, 삭제, 사용 또는 사용하지 않도록 설정할 수 있습니다.
+
그러나 LIF를 마이그레이션하거나 LIF를 홈 포트로 다시 전송할 수 없습니다.

* 다음 구성에서는 네트워크 인터페이스를 생성, 편집 또는 삭제할 수 없습니다.
+
** MetroCluster 구성
** DR(재해 복구)에 대해 SVM이 구성됩니다.






=== 명령 버튼

* * 생성 *
+
네트워크 인터페이스 생성 대화 상자를 엽니다. 이 대화 상자에서 네트워크 인터페이스를 생성하고 인터클러스터 LIF를 생성하여 데이터를 제공하고 SVM을 관리할 수 있습니다.

* * 편집 *
+
데이터 LIF에 대한 관리 액세스를 설정할 수 있는 네트워크 인터페이스 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 네트워크 인터페이스를 삭제합니다.

+
데이터 LIF가 비활성화된 경우에만 이 버튼이 활성화됩니다.

* * 상태 *
+
선택한 네트워크 인터페이스를 활성화 또는 비활성화하는 옵션을 제공하는 드롭다운 메뉴를 엽니다.

* * 마이그레이션 *
+
데이터 LIF 또는 클러스터 관리 LIF를 클러스터 내의 동일한 노드 또는 다른 노드의 다른 포트로 마이그레이션할 수 있습니다.

* * 홈으로 전송 *
+
LIF를 홈 포트에 다시 호스팅할 수 있습니다.

+
이 명령 단추는 선택한 인터페이스가 홈 포트가 아닌 포트에서 호스팅되는 경우 및 홈 포트를 사용할 수 있는 경우에만 활성화됩니다.

+
이 명령 버튼은 클러스터의 노드가 다운된 경우 비활성화됩니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 인터페이스 목록

색상 코드로 표시된 아이콘 위로 포인터를 이동하면 인터페이스의 작동 상태를 볼 수 있습니다.

* 녹색은 인터페이스가 활성화되도록 지정합니다.
* 빨간색은 인터페이스가 비활성화됨을 나타냅니다.
* * 인터페이스 이름 *
+
네트워크 인터페이스의 이름을 지정합니다.

* * 스토리지 가상 머신 *
+
인터페이스가 속하는 SVM을 지정합니다.

* * IP 주소/WWPN *
+
인터페이스의 IP 주소 또는 WWPN(Worldwide Port Name)을 지정합니다.

* * 현재 포트 *
+
인터페이스가 호스팅되는 노드 및 포트의 이름을 지정합니다.

* * 데이터 프로토콜 액세스 *
+
데이터에 액세스하는 데 사용되는 프로토콜을 지정합니다.

* * 관리 액세스 *
+
인터페이스에서 관리 액세스를 설정할지 여부를 지정합니다.

* * 서브넷 *
+
인터페이스가 속한 서브넷을 지정합니다.

* * MX 역할 *
+
데이터, 인터클러스터, 클러스터, 클러스터 관리 또는 노드 관리가 될 수 있는 인터페이스의 운영 역할을 지정합니다.





=== 세부 정보 영역

인터페이스 목록 아래의 영역에는 홈 포트, 현재 포트, 포트의 속도, 페일오버 정책, 페일오버 그룹, 페일오버 상태와 같은 페일오버 속성, 관리 상태, 역할, IPspace, 브로드캐스트 도메인, 네트워크 마스크 등의 일반 속성에 대한 자세한 정보가 표시됩니다. 게이트웨이 및 DDNS 상태입니다.



=== 이더넷 포트 탭



=== 명령 버튼

* * 인터페이스 그룹 생성 *
+
포트를 선택하고 포트 및 네트워크 트래픽 배포의 사용을 결정하여 인터페이스 그룹을 생성할 수 있는 인터페이스 그룹 생성 대화 상자를 엽니다.

* * VLAN 생성 *
+
이더넷 포트 또는 인터페이스 그룹을 선택하고 VLAN 태그를 추가하여 VLAN을 생성할 수 있는 VLAN 생성 대화 상자를 엽니다.

* * 편집 *
+
다음 대화 상자 중 하나를 엽니다.

+
** 이더넷 포트 편집 대화 상자: 이더넷 포트 설정을 수정할 수 있습니다.
** VLAN 편집 대화 상자: VLAN 설정을 수정할 수 있습니다.
** 인터페이스 그룹 편집 대화 상자: 인터페이스 그룹을 수정할 수 있습니다.


+
브로드캐스트 도메인과 연결되지 않은 VLAN만 편집할 수 있습니다.

* * 삭제 *
+
다음 대화 상자 중 하나를 엽니다.

+
** VLAN 삭제 대화 상자: VLAN을 삭제할 수 있습니다.
** 인터페이스 그룹 삭제 대화 상자: 인터페이스 그룹을 삭제할 수 있습니다.


* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 포트 목록

컬러 코딩된 아이콘 위로 포인터를 이동하여 포트의 작동 상태를 확인할 수 있습니다.

* 녹색은 포트가 활성화되도록 지정합니다.
* 빨간색은 포트가 비활성화됨을 나타냅니다.
* * 포트 *
+
물리적 포트, VLAN 포트 또는 인터페이스 그룹의 포트 이름을 표시합니다.

* * 노드 *
+
물리적 인터페이스가 있는 노드를 표시합니다.

* * 브로드캐스트 도메인 *
+
포트의 브로드캐스트 도메인을 표시합니다.

* IPspace *
+
포트가 속한 IPspace를 표시한다.

* * 유형 *
+
인터페이스 그룹, 물리적 인터페이스, VIP 또는 VLAN과 같은 인터페이스 유형을 표시합니다.





=== 세부 정보 영역

포트 목록 아래의 영역에는 포트 속성에 대한 자세한 정보가 표시됩니다.

* * 세부 정보 탭 *
+
관리 세부 정보 및 운영 세부 정보를 표시합니다.

+
작업 세부 정보의 일부로 탭에는 포트의 상태가 표시됩니다. 포트가 정상 또는 성능 저하 상태일 수 있습니다. 성능이 저하된 포트는 지속적인 네트워크 변동이 발생하는 포트 또는 동일한 브로드캐스트 도메인의 다른 포트에 대한 연결이 없는 포트입니다.

+
또한 이 탭에는 선택된 포트에서 호스팅되는 네트워크 인터페이스의 인터페이스 이름, SVM 세부 정보 및 IP 주소 세부 정보가 표시됩니다. 인터페이스가 홈 포트에 있는지 여부도 나타냅니다.

* * 성능 탭 *
+
오류율 및 처리량을 비롯한 이더넷 포트의 성능 메트릭 그래프를 표시합니다.

+
클라이언트 시간대 또는 클러스터 시간대를 변경하면 성능 메트릭 그래프에 영향을 줍니다. 업데이트된 그래프를 보려면 브라우저를 새로 고쳐야 합니다.





=== 브로드캐스트 도메인 탭



=== 명령 버튼

* * 생성 *
+
포트를 포함할 새 브로드캐스트 도메인을 만들 수 있는 브로드캐스트 도메인 생성 대화 상자를 엽니다.

* * 편집 *
+
이름, MTU 크기 및 연결된 포트와 같은 브로드캐스트 도메인의 속성을 수정할 수 있는 브로드캐스트 도메인 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 브로드캐스트 도메인을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 브로드캐스트 도메인 목록

* * 브로드캐스트 도메인 *
+
브로드캐스트 도메인의 이름을 지정합니다.

* * MTU *
+
MTU 크기를 지정합니다.

* IPspace *
+
IPspace를 지정합니다.

* * 결합된 포트 업데이트 상태 *
+
브로드캐스트 도메인을 만들거나 편집할 때 포트 업데이트의 상태를 지정합니다. 포트 업데이트의 모든 오류는 별도의 창에 표시되며, 연결된 링크를 클릭하여 열 수 있습니다.





=== 세부 정보 영역

브로드캐스트 도메인 목록 아래의 영역에는 브로드캐스트 도메인의 모든 포트가 표시됩니다. 비 기본 IPspace에서 브로드캐스트 도메인에 업데이트 오류가 있는 포트가 있는 경우 해당 포트는 세부 정보 영역에 표시되지 않습니다. 컬러 코딩된 아이콘 위로 포인터를 이동하여 포트의 작동 상태를 확인할 수 있습니다.

* 녹색은 포트가 활성화되도록 지정합니다.
* 빨간색은 포트가 비활성화됨을 나타냅니다.




=== FC/FCoE 및 NVMe Adapters 탭



=== 명령 버튼

* * 편집 *
+
어댑터의 속도를 수정할 수 있는 FC/FCoE 및 NVMe 설정 편집 대화 상자를 엽니다.

* * 상태 *
+
어댑터를 온라인 상태로 전환하거나 오프라인 상태로 전환할 수 있습니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== FC/FCoE 및 NVMe 어댑터 목록

* WWNN *
+
FC/FCoE 및 NVMe 어댑터의 고유 식별자를 지정합니다.

* * 노드 이름 *
+
어댑터를 사용하는 노드의 이름을 지정합니다.

* * 슬롯 *
+
어댑터를 사용하는 슬롯을 지정합니다.

* WWPN *
+
어댑터의 FC WWPN(Worldwide Port Name)을 지정합니다.

* * 상태 *
+
어댑터의 상태가 온라인인지 오프라인인지 지정합니다.

* * 속도 *
+
속도 설정이 자동 또는 수동인지 여부를 지정합니다.





=== 세부 정보 영역

FC/FCoE 및 NVMe 어댑터 목록 아래의 영역에는 선택한 어댑터에 대한 자세한 정보가 표시됩니다.

* * 세부 정보 탭 *
+
미디어 유형, 포트 주소, 데이터 링크 속도, 연결 상태, 작동 상태 등과 같은 어댑터 세부 정보를 표시합니다. 패브릭 상태 및 어댑터의 속도입니다.

* * 성능 탭 *
+
IOPS 및 응답 시간을 포함하여 FC/FCoE 및 NVMe 어댑터의 성능 메트릭 그래프를 표시합니다.

+
클라이언트 시간대 또는 클러스터 시간대를 변경하면 성능 메트릭 그래프에 영향을 줍니다. 업데이트된 그래프를 보려면 브라우저를 새로 고쳐야 합니다.





=== IPspace 탭



=== 명령 버튼

* * 생성 *
+
새 IPspace를 생성할 수 있는 IPspace 생성 대화 상자를 엽니다.

* * 편집 *
+
기존 IPspace의 이름을 바꿀 수 있는 IPspace 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 IPspace를 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== IPspace 목록

* * 이름 *
+
IPspace의 이름을 지정합니다.

* * 브로드캐스트 도메인 *
+
브로드캐스트 도메인을 지정합니다.





=== 세부 정보 영역

IPspace 목록 아래의 영역에는 선택한 IPspace의 SVM(스토리지 가상 머신) 목록이 표시됩니다.
