---
permalink: online-help-96-97/concept_service_processors.html 
sidebar: sidebar 
keywords: service, processors, monitor, manage, storage, system, manager, temperature, voltage, current, fan, speed, online, help, isolate, management, network, traffic, sp, bmc, e0m, interface, subnet, performance, routing, ip, address, edit 
summary: 서비스 프로세서를 사용하여 System Manager를 통해 온도, 전압, 전류 및 팬 속도와 같은 스토리지 시스템 매개 변수를 모니터링하고 관리할 수 있습니다. 
---
= 시스템 관리자 - ONTAP 9.7 이하가 설치된 서비스 프로세서를 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)이 지원되는 서비스 프로세서를 사용하여 온도, 전압, 전류 및 팬 속도와 같은 스토리지 시스템 매개 변수를 모니터링하고 관리할 수 있습니다.



== 관리 네트워크 트래픽을 격리합니다

관리 트래픽 전용 서브넷에 SP/BMC 및 e0M 관리 인터페이스를 구성하는 것이 좋습니다. 관리 네트워크를 통해 데이터 트래픽을 실행하면 성능 저하 및 라우팅 문제가 발생할 수 있습니다.

대부분의 스토리지 컨트롤러의 관리 이더넷 포트(섀시 뒤쪽에 렌치 아이콘으로 표시됨)는 내부 이더넷 스위치에 연결됩니다. 내부 스위치는 SP/BMC 및 e0M 관리 인터페이스에 대한 연결을 제공하며, 이 인터페이스를 사용하여 텔넷, SSH 및 SNMP와 같은 TCP/IP 프로토콜을 통해 스토리지 시스템에 액세스할 수 있습니다.

원격 관리 장치와 e0M을 모두 사용하려는 경우 동일한 IP 서브넷에 구성해야 합니다. 이러한 인터페이스는 대역폭이 낮은 인터페이스이므로 관리 트래픽 전용 서브넷에 SP/BMC 및 e0M을 구성하는 것이 좋습니다.

관리 트래픽을 격리할 수 없거나 전용 관리 네트워크가 비정상적으로 큰 경우 네트워크 트래픽 볼륨을 가능한 낮게 유지해야 합니다. 브로드캐스트 또는 멀티캐스트 트래픽이 과도하게 유입될 경우 SP/BMC 성능이 저하될 수 있습니다.

[NOTE]
====
AFF A800과 같은 일부 스토리지 컨트롤러에는 BMC용 포트 2개와 e0M용 포트 1개가 있습니다. 이러한 컨트롤러의 경우 동일한 IP 서브넷에 BMC 및 e0M을 구성할 필요가 없습니다.

====


== 서비스 프로세서에 IP 주소를 할당합니다

System Manager를 사용하여 모든 서비스 프로세서에 IP 주소를 동시에 할당하고 이러한 서비스 프로세서를 사용하여 스토리지 시스템의 다양한 시스템 매개 변수를 모니터링 및 관리할 수 있습니다.

.단계
. 구성 * > * 클러스터 * > * 구성 업데이트 * 를 클릭합니다.
. 서비스 프로세서* 창에서 * 글로벌 설정 * 을 클릭합니다.
. 글로벌 설정 * 대화 상자에서 IP 주소를 할당할 소스를 선택합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
DHCP 서버에서 자동으로 IP 주소를 할당합니다
 a| 
DHCP * 를 선택합니다.



 a| 
서브넷에서 IP 주소를 할당합니다
 a| 
Subnet * 을 선택합니다.



 a| 
수동으로 IP 주소를 입력합니다
 a| 
수동 할당 * 을 선택합니다.

|===
. 저장 * 을 클릭합니다.




== 서비스 프로세서 설정을 편집합니다

System Manager를 사용하여 IP 주소, 네트워크 마스크 또는 접두사 길이, 게이트웨이 주소 등과 같은 서비스 프로세서 속성을 수정할 수 있습니다. IP 주소가 할당되지 않은 서비스 프로세서에 IP 주소를 할당할 수도 있습니다.

.이 작업에 대해
* IP 주소가 할당된 서비스 프로세서의 설정을 수동으로 편집할 수 있습니다.
* DHCP 서버 또는 서브넷을 통해 IP 주소가 할당된 서비스 프로세서의 설정은 편집할 수 없습니다.


.단계
. 구성 * > * 클러스터 * > * 서비스 프로세서 * 를 클릭합니다.
. 서비스 프로세서* 창에서 수정할 서비스 프로세서를 선택한 다음 * 편집 * 을 클릭합니다.
. [서비스 프로세서 편집] * 대화 상자에서 필요한 사항을 변경한 다음 [저장 후 닫기]를 클릭합니다.




== 서비스 프로세서를 파악합니다

서비스 프로세서는 스토리지 시스템에서 시스템에 독립적인 리소스로, 온도, 전압, 전류 및 팬 속도와 같은 스토리지 시스템 매개 변수를 모니터링하고 관리하는 데 도움을 줍니다.

서비스 프로세서가 스토리지 시스템 매개 변수에서 비정상적인 조건을 감지하면 서비스 프로세서가 이벤트를 기록하고 ONTAP에 문제를 알리고 e-메일 또는 SNMP 트랩을 통해 AutoSupport 메시지를 생성합니다.

서비스 프로세서는 감시 메커니즘을 통해 ONTAP를 모니터링하며 파트너 노드로 신속하게 페일오버할 수 있도록 합니다. 또한 서비스 프로세서는 여러 시스템 이벤트를 추적하고 이벤트를 로그 파일에 저장합니다. 이 이벤트에는 부팅 진행률, 현장 교체 장치(FRU) 변경, ONTAP 생성 이벤트 및 사용자 트랜잭션 기록이 포함됩니다.

서비스 프로세서는 스토리지 시스템에 원격으로 로그인 및 관리할 수 있으며 스토리지 시스템의 상태에 관계없이 시스템을 진단, 종료, 전원 껐다 켜기 또는 재부팅할 수 있습니다. 또한 서비스 프로세서는 원격 진단 기능을 제공합니다.

서비스 프로세서의 통합 모니터링 및 관리 기능을 사용하면 문제 발생 시 스토리지 시스템을 평가한 다음, 즉시 효율적인 서비스 작업을 수행할 수 있습니다.



== 서비스 프로세서 창

서비스 프로세서 창을 사용하여 IP 주소, 네트워크 마스크(IPv4) 또는 접두사 길이(IPv6) 및 게이트웨이와 같은 서비스 프로세서 속성을 확인 및 수정하고 서비스 프로세서에 대한 IP 소스를 구성할 수 있습니다.



=== 명령 버튼

* * 편집 *
+
서비스 프로세서의 IP 주소, 네트워크 마스크(IPv4) 또는 접두사 길이(IPv6) 및 게이트웨이 정보를 수정할 수 있는 서비스 프로세서 편집 대화 상자를 엽니다.

* * 전역 설정 *
+
모든 서비스 프로세서의 IP 주소 소스를 DHCP, 서브넷 또는 설명서 중 하나로 구성할 수 있는 전역 설정 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 서비스 프로세서 목록

* * 노드 *
+
서비스 프로세서가 있는 노드를 지정합니다.

* * IP 주소 *
+
서비스 프로세서의 IP 주소를 지정합니다.

* * 상태 *
+
서비스 프로세서의 상태를 지정합니다. 이 상태는 온라인, 오프라인, 데몬 오프라인, 노드 오프라인, 성능 저하 등이 있습니다. 재부팅 또는 알 수 없음

* * MAC 주소 *
+
서비스 프로세서의 MAC 주소를 지정합니다.





=== 세부 정보 영역

서비스 프로세서 목록 아래의 영역에는 IP 주소, 네트워크 마스크(IPv4) 또는 접두사 길이(IPv6), 게이트웨이, IP 소스 등의 네트워크 세부 정보를 비롯하여 서비스 프로세서에 대한 자세한 정보가 표시됩니다. 펌웨어 버전 및 펌웨어 자동 업데이트 사용 여부와 같은 일반 세부 사항 및 MAC 주소입니다.

* 관련 정보 *

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[IP 주소 범위가 비활성화된 경우 네트워크 설정]
