---
permalink: online-help-96-97/concept_setting_up_network.html 
sidebar: sidebar 
keywords: online, help, set, up, network, ipspace, broadcast, domain, subnet, system, manager, cluster, range 
summary: 네트워크 설정은 IPspace 생성, 브로드캐스트 도메인 및 서브넷으로 구성됩니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 네트워크를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 네트워크를 설정할 수 있습니다. 네트워크 설정은 IPspace 생성, 브로드캐스트 도메인 및 서브넷으로 구성됩니다.



== IPspace 생성

System Manager를 사용하여 IPspace를 생성할 수 있습니다. 이 경우 클라이언트가 동일한 IP 주소 서브넷 범위를 사용하는 경우에도 두 개 이상의 별도 관리 네트워크 도메인에서 클라이언트 액세스를 위한 단일 ONTAP 클러스터를 구성할 수 있습니다. 이를 통해 개인 정보 보호와 보안을 위해 클라이언트 트래픽을 분리할 수 있습니다.

.이 작업에 대해
모든 IPspace 이름은 클러스터 내에서 고유해야 하며 ""local" 또는 ""localhost""와 같이 시스템에서 예약한 이름으로 구성될 수 없습니다.

.단계
. 네트워크 * 탭을 클릭합니다.
. IPspace * 탭에서 * 생성 * 을 클릭합니다.
. IPspace 생성 * 대화 상자에서 생성할 IPspace의 이름을 지정합니다.
. Create * 를 클릭합니다.




== 브로드캐스트 도메인을 생성합니다

System Manager를 사용하여 컴퓨터 네트워크의 논리적 부서를 제공하여 브로드캐스트 도메인을 생성할 수 있습니다. 브로드캐스트 도메인에서 데이터링크 계층에서 브로드캐스트를 통해 모든 관련 노드에 연결할 수 있습니다

.단계
. 네트워크 * 탭을 클릭합니다.
. [브로드캐스트 도메인*] 탭에서 [작성]을 클릭합니다.
. 브로드캐스트 도메인 생성 * 대화 상자에서 만들려는 브로드캐스트 도메인의 이름, MTU 크기, IPspace 및 포트를 지정합니다.
. Create * 를 클릭합니다.




== 서브넷을 생성합니다

System Manager를 사용하여 IP 네트워크의 논리적 하위 부서를 제공하여 IP 주소를 미리 할당할 수 있습니다. 서브넷을 사용하면 각 새 인터페이스에 대한 IP 주소 및 네트워크 마스크 값 대신 서브넷을 지정하여 인터페이스를 보다 쉽게 만들 수 있습니다.

.시작하기 전에
서브넷이 사용되는 브로드캐스트 도메인을 만들어야 합니다.

.이 작업에 대해
서브넷을 생성할 때 게이트웨이를 지정하면 해당 서브넷을 사용하여 LIF가 생성될 때 게이트웨이에 대한 기본 경로가 SVM에 자동으로 추가됩니다.

.단계
. 네트워크 * 탭을 클릭합니다.
. Subnets * 탭에서 * Create * 를 클릭합니다.
. 서브넷 생성 * 대화 상자에서 이름, 서브넷 IP 주소 또는 서브넷 마스크, IP 주소 범위, 게이트웨이 주소, 브로드캐스트 도메인 등의 서브넷 세부 정보를 지정합니다.
+
IP 주소를 쉼표로 구분된 여러 주소로 범위 또는 두 주소의 혼합으로 지정할 수 있습니다.

. Create * 를 클릭합니다.


* 관련 정보 *

xref:reference_network_window.adoc[네트워크 창]
