---
permalink: online-help-96-97/concept_schedules.html 
sidebar: sidebar 
keywords: online, help, system, manager, manage, schedule, storage 
summary: System Manager를 사용하여 스토리지 시스템에서 스케줄을 생성하고 관리할 수 있습니다. 
---
= System Manager로 스케줄 관리 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 스토리지 시스템에서 스케줄을 생성하고 관리할 수 있습니다.



== 일정을 생성합니다

System Manager를 사용하면 특정 시간이나 정기적으로 작업을 실행하도록 스케줄을 생성할 수 있습니다.

.이 작업에 대해
MetroCluster 구성에서 일정을 생성하는 경우 정상 작동하는 사이트의 클러스터에서 동일한 일정을 만드는 것이 좋습니다.

.단계
. Protection * > * Schedules * 를 클릭합니다.
. Create * 를 클릭합니다.
. Create Schedule * 대화 상자에서 스케줄 이름을 지정합니다.
. 요구 사항에 따라 일정을 작성합니다.
+
|===
| 만들려는 경우... | 수행할 작업... 


 a| 
특정 요일의 일별 또는 특정 일정
 a| 
기본 * 을 선택하고 일정 및 반복 세부 정보(시간 및 분)를 지정합니다.



 a| 
특정 간격으로 실행되는 스케줄입니다
 a| 
간격 * 을 선택하고 일정 및 반복 세부 정보(일, 시간 및 분 단위)를 지정합니다.



 a| 
특정 기간에 실행되는 스케줄입니다
 a| 
고급 * 을 선택하고 일정 및 반복 세부 정보(월, 일, 요일, 시, 분)를 지정합니다.

|===
. Create * 를 클릭합니다.




== 일정을 편집합니다

System Manager를 사용하여 이전에 생성한 cron 일정 또는 필요 사항을 충족하지 않는 경우 일정 간격을 변경할 수 있습니다. 반복 일 및 시간, 간격 옵션 및 고급 cron 옵션과 같은 일정 세부 정보를 수정할 수 있습니다.

.이 작업에 대해
MetroCluster 구성에서 일정을 편집할 때는 정상적인 사이트 클러스터에서 동일한 일정을 편집하는 것이 좋습니다.

.단계
. Protection * > * Schedules * 를 클릭합니다.
. 수정할 일정을 선택하고 * 편집 * 을 클릭합니다.
. [일정 편집] * 대화 상자에서 적절한 작업을 수행하여 일정을 수정합니다.
+
|===
| 일정 옵션을 다음과 같이 선택하는 경우... | 이렇게 하십시오. 


 a| 
기본
 a| 
반복 요일 및 반복 일정 세부 정보를 지정합니다.



 a| 
간격
 a| 
간격 옵션을 일, 시간 및 분으로 지정합니다.



 a| 
고급
 a| 
월, 일, 주(해당되는 경우), 시간 및 분 단위로 고급 cron 옵션을 지정합니다.

|===
. 확인 * 을 클릭합니다.




== 일정을 삭제합니다

[role="lead"]
System Manager를 사용하여 특정 스토리지 관리 작업을 실행하는 스케줄을 삭제할 수 있습니다.

.단계
. Protection * > * Schedules * 를 클릭합니다.
. 삭제할 일정을 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 일정을 관리합니다

지정된 스케줄에 따라 실행되도록 여러 작업(예: 볼륨 스냅샷 복사본 및 미러 복제)을 구성할 수 있습니다. 지정된 스케줄에서 실행되는 스케줄은 UNIX와 유사하기 때문에 _cron_schedules라고 합니다 `cron` 스케줄. 일정 간격으로 실행되는 스케줄을 _INTERVAL_schedules 라고 합니다.

다음과 같은 방법으로 일정을 관리할 수 있습니다.

* cron 일정 또는 간격 일정을 생성합니다
* 모든 스케줄에 대한 정보 표시
* cron 일정 또는 간격 일정을 수정합니다
* cron 일정 또는 간격 일정을 삭제합니다
+
실행 중인 작업에서 현재 사용 중인 스케줄은 삭제할 수 없습니다.



클러스터 관리자는 모든 스케줄 관리 작업을 수행할 수 있습니다.



== 스케줄 창

스케줄 창을 사용하여 스케줄 생성, 정보 표시, 수정 및 삭제 등의 예약된 작업을 관리할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
시간 기반 및 간격 일정을 생성할 수 있는 일정 생성 대화 상자를 엽니다.

* * 편집 *
+
선택한 스케줄을 편집할 수 있는 스케줄 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 스케줄을 삭제할 수 있는 스케줄 삭제 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 스케줄 목록

* * 이름 *
+
스케줄의 이름을 지정합니다.

* * 유형 *
+
스케줄 - 시간 기반 또는 간격 기반 유형을 지정합니다.





=== 세부 정보 영역

세부 정보 영역에는 선택한 일정이 실행되는 시간에 대한 정보가 표시됩니다.
