---
permalink: online-help-96-97/concept_why_you_use_svms.html 
sidebar: sidebar 
keywords: svm, data, access, nondisruptive, operation, scalability, security, online, help 
summary: SVM은 스토리지 시스템과 유사하게 물리적 스토리지 또는 컨트롤러에 관계없이 클라이언트에 데이터 액세스를 제공합니다. SVM은 무중단 운영, 확장성, 보안, 유니파이드 스토리지와 같은 이점을 제공합니다. 
---
= System Manager와 SVM 정보 - ONTAP 9.7 이전 버전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM을 ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)과 함께 사용하여 물리적 스토리지 또는 컨트롤러와 상관없이 클라이언트에 데이터 액세스를 제공할 수 있습니다. SVM은 무중단 운영, 확장성, 보안, 유니파이드 스토리지와 같은 이점을 제공합니다.

SVM은 다음과 같은 이점을 제공합니다.

* 멀티 테넌시
+
SVM은 시큐어 멀티 테넌시(multi-tenancy)의 기본 단위로서, 스토리지 인프라를 분할하여 여러 개의 독립적인 스토리지 시스템으로 나타나도록 합니다. 이러한 파티션은 데이터와 관리를 격리합니다.

* 무중단 운영
+
SVM은 필요한 한 운영 중단 없이 지속적으로 운영할 수 있습니다. SVM은 소프트웨어 및 하드웨어 업그레이드, 노드 추가 및 제거, 모든 관리 작업 중에 클러스터가 지속적으로 운영될 수 있도록 지원합니다.

* 확장성
+
SVM은 온디맨드 데이터 처리량 및 기타 스토리지 요구사항을 충족합니다.

* 보안
+
각 SVM은 하나의 독립 서버로 표시되므로 하나의 클러스터에 여러 SVM을 공존하고 클러스터 간에 데이터 흐름을 유지할 수 있습니다.

* 유니파이드 스토리지
+
SVM은 여러 데이터 액세스 프로토콜을 통해 데이터를 동시에 제공할 수 있습니다. SVM은 CIFS 및 NFS와 같은 NAS 프로토콜을 통해 파일 레벨 데이터 액세스를 지원하고, iSCSI, FC/FCoE, NVMe와 같은 SAN 프로토콜을 통해 블록 레벨 데이터 액세스를 제공합니다. SVM은 SAN 및 NAS 클라이언트에 데이터를 동시에 독립적으로 제공할 수 있습니다.

* 관리 위임
+
SVM 관리자는 클러스터 관리자에 의해 할당된 권한을 가집니다.


