---
permalink: online-help-96-97/concept_svm_user_accounts.html 
sidebar: sidebar 
keywords: system, manager, create, manage, online, help, storage, virtual, machine, svm, user, account, password, change, lock, unlock , command, button 
summary: 'System Manager를 사용하여 SVM(스토리지 가상 시스템) 사용자 계정을 만들고 관리할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM 사용자 계정을 생성하고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SVM(스토리지 가상 시스템) 사용자 계정을 만들고 관리할 수 있습니다.



== SVM 사용자 계정 추가

System Manager를 사용하여 SVM(스토리지 가상 머신) 사용자 계정을 추가하고 스토리지 시스템 액세스를 위한 사용자 로그인 방법을 지정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 사용자 * 를 클릭합니다.
. 추가 * 를 클릭합니다.
. 스토리지 시스템에 접속하기 위한 사용자 이름과 암호를 지정하고 암호를 확인합니다.
. 하나 이상의 사용자 로그인 방법을 추가한 다음 * 추가 * 를 클릭합니다.
+
새 vsadmin 계정에 대한 로그인 방법은 HTTP를 애플리케이션으로 사용하고 인증서를 통해 인증되는 자동으로 포함됩니다.





== SVM 사용자 계정의 암호를 변경합니다

System Manager를 사용하여 SVM(스토리지 가상 시스템) 사용자 계정의 암호를 재설정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 사용자 * 를 클릭합니다.
. 암호를 수정할 사용자 계정을 선택한 다음 * 암호 재설정 * 을 클릭합니다.
. 암호 재설정 * 대화 상자에서 새 암호를 입력하고 새 암호를 확인한 다음 * 변경 * 을 클릭합니다.




== SVM 사용자 계정을 편집합니다

System Manager를 사용하면 스토리지 시스템에 액세스하기 위한 사용자 로그인 방법을 수정하여 SVM(스토리지 가상 시스템) 사용자 계정을 편집할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 사용자 * 를 클릭합니다.
. 편집할 사용자 계정을 선택한 다음 * 편집 * 을 클릭합니다.
. 하나 이상의 사용자 로그인 방법을 수정한 다음 * 수정 * 을 클릭합니다.




== SVM 사용자 계정 잠금 또는 잠금 해제

System Manager를 사용하여 SVM(스토리지 가상 시스템) 사용자 계정을 잠그거나 잠금 해제할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. SVM 사용자 세부 정보 * 창에서 * 사용자 * 를 클릭합니다.
. 사용자 * 창에서 계정 상태를 수정할 사용자 계정을 선택한 다음 필요에 따라 * 잠금 * 또는 * 잠금 해제 * 를 클릭합니다.




== 사용자 창

사용자 창을 사용하여 사용자 계정을 관리하고, 사용자의 암호를 재설정하고, 모든 사용자 계정에 대한 정보를 볼 수 있습니다.



=== 명령 버튼

* * 추가 *
+
사용자 계정을 추가할 수 있는 사용자 추가 대화 상자를 엽니다.

* * 편집 *
+
사용자 로그인 방법을 수정할 수 있는 사용자 수정 대화 상자를 엽니다.

+
[NOTE]
====
사용자 계정의 모든 액세스 및 인증 방법에 대해 단일 역할을 사용하는 것이 가장 좋습니다.

====
* * 삭제 *
+
선택한 사용자 계정을 삭제할 수 있습니다.

* * 암호 변경 *
+
선택한 사용자의 암호를 재설정할 수 있는 암호 변경 대화 상자를 엽니다.

* * 잠금 *
+
사용자 계정을 잠급니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 사용자 목록

사용자 목록 아래의 영역에는 선택한 사용자에 대한 자세한 정보가 표시됩니다.

* * 사용자 *
+
사용자 계정의 이름을 표시합니다.

* * 계정 잠김 *
+
사용자 계정이 잠겨 있는지 여부를 표시합니다.





=== 사용자 로그인 방법 영역

* * 응용 프로그램 *
+
사용자가 스토리지 시스템을 액세스하는 데 사용할 수 있는 액세스 방법을 표시합니다. 지원되는 액세스 방법은 다음과 같습니다.

+
** 시스템 콘솔(콘솔)
** HTTP(S)(http)
** ONTAP API(ontapi)
** 서비스 프로세서(서비스 프로세서)
** SSH(ssh)


* * 인증 *
+
기본 지원 인증 방법, 즉 ""password""를 표시합니다.

* * 역할 *
+
선택한 사용자의 역할을 표시합니다.


