---
permalink: online-help-96-97/concept_quotas.html 
sidebar: sidebar 
keywords: system, manager, quota, online, help, view, activate, deactivate, information, types, targets, default, limits, space, files, manage, tree, group 
summary: System Manager를 사용하여 할당량을 생성, 편집, 삭제할 수 있습니다. 
---
= 시스템 관리자 - ONTAP 9.7 이하를 사용하여 할당량을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 할당량을 생성, 편집, 삭제할 수 있습니다.



== 할당량을 생성합니다

할당량을 통해 사용자, 그룹 또는 qtree가 사용하는 파일 수와 디스크 공간을 제한하거나 추적할 수 있습니다. System Manager에서 할당량 추가 마법사를 사용하여 할당량을 생성하고 특정 볼륨 또는 qtree에 할당량을 적용할 수 있습니다.

.이 작업에 대해
System Manager를 사용하면 할당량이 소유할 수 있는 파일 수에 대한 하드 제한값과 소프트 제한값을 지정할 수 있는 최소값이 1000입니다. 1000보다 작은 값을 지정하려면 CLI(Command-Line Interface)를 사용해야 합니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 할당량을 생성하려는 SVM(스토리지 가상 머신)을 선택합니다.
. 사용자 정의 할당량 * 탭에서 * 생성 * 을 클릭합니다.
+
할당량 생성 마법사가 표시됩니다.

. 마법사의 지시에 따라 정보를 입력하거나 선택합니다.
. 세부 정보를 확인한 다음 * 마침 * 을 클릭하여 마법사를 완료합니다.




=== 다음 단계

로컬 사용자 이름을 사용하거나 RID를 사용하여 사용자 할당량을 생성할 수 있습니다. 사용자 이름 또는 그룹 이름을 사용하여 사용자 할당량 또는 그룹 할당량을 생성하는 경우 이 표시됩니다 ``/etc/passwd``파일 및``/etc/group``파일을 각각 업데이트해야 합니다.



== 할당량을 삭제합니다

System Manager를 사용하면 사용자와 스토리지 요구 사항 및 제한 사항이 변경될 때 하나 이상의 할당량을 삭제할 수 있습니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 삭제할 할당량이 있는 SVM(스토리지 가상 머신)을 선택합니다.
. 삭제할 할당량을 하나 이상 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 할당량 제한을 편집합니다

System Manager를 사용하여 디스크 공간 임계값, 할당량 대상이 사용할 수 있는 디스크 공간의 하드 제한값 및 소프트 제한값, 할당량 대상이 소유할 수 있는 파일의 하드 제한값 및 소프트 제한값을 편집할 수 있습니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 편집할 할당량이 있는 SVM(스토리지 가상 시스템)을 선택합니다.
. 편집할 할당량을 선택하고 * 제한 편집 * 을 클릭합니다.
. 제한 편집 * 대화 상자에서 필요에 따라 할당량 설정을 편집합니다.
+
100은 할당량이 소유할 수 있는 파일 수에 대한 하드 제한값과 소프트 제한값을 지정할 수 있는 최소값입니다. 100보다 작은 값을 지정하려면 CLI(명령줄 인터페이스)를 사용해야 합니다.

. 저장 후 닫기 * 를 클릭합니다.
. 사용자 정의 할당량 * 탭에서 선택한 할당량의 변경 사항을 확인합니다.




== 할당량을 설정하거나 해제합니다

System Manager를 사용하여 스토리지 시스템에서 선택한 하나 이상의 볼륨에서 할당량을 설정하거나 해제할 수 있습니다. 사용자 및 스토리지 요구 사항과 제한 사항이 변경될 때 할당량을 설정하거나 해제할 수 있습니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. SVM 필드의 드롭다운 메뉴에서 활성화 또는 비활성화할 할당량이 있는 SVM(스토리지 가상 머신)을 선택합니다.
. 볼륨 * 의 * 할당량 상태 탭에서 할당량을 활성화하거나 비활성화할 볼륨을 하나 이상 선택합니다.
. 필요에 따라 * 활성화 * 또는 * 비활성화 * 를 클릭합니다.
. 할당량을 비활성화하는 경우 확인 확인란을 선택한 다음 * 확인 * 을 클릭합니다.
. Status * 열에서 볼륨의 할당량 상태를 확인합니다.




== 할당량 크기 조정

System Manager의 할당량 크기 조정 대화 상자를 사용하여 지정된 볼륨의 활성 할당량을 조정하여 할당량에 대한 변경 사항을 반영할 수 있습니다.

.시작하기 전에
할당량의 크기를 조정할 볼륨에 대해 할당량을 설정해야 합니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. Quotas* 창의 * Quota Status On Volumes * 탭에서 할당량의 크기를 조정할 볼륨을 하나 이상 선택합니다.
. 크기 조정 * 을 클릭합니다.




== 할당량 정보를 봅니다

System Manager의 Quotas 창을 사용하면 할당량이 적용되는 볼륨 및 Qtree, 할당량 유형, 할당량이 적용되는 사용자 또는 그룹, 공간 및 파일 사용률과 같은 할당량 세부 정보를 볼 수 있습니다.

.단계
. 스토리지 * > * 할당량 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 정보를 확인할 할당량이 있는 SVM(스토리지 가상 시스템)을 선택합니다.
. 적절한 작업을 수행합니다.
+
[cols="1a,1a"]
|===
| 만약... | 그러면... 


 a| 
생성한 모든 할당량에 대한 세부 정보를 확인할 수 있습니다
 a| 
사용자 정의 할당량 * 탭을 클릭합니다.



 a| 
현재 활성 상태인 할당량에 대한 세부 정보를 보려는 경우
 a| 
Quota Report * 탭을 클릭합니다.

|===
. 표시된 할당량 목록에서 정보를 확인할 할당량을 선택합니다.
. 할당량 세부 정보를 검토합니다.




== 할당량 유형입니다

할당량은 적용되는 타겟을 기준으로 분류할 수 있습니다.

다음은 할당량이 적용되는 대상을 기준으로 하는 할당량의 유형입니다.

* * 사용자 할당량 *
+
타겟이 사용자입니다.

+
사용자는 UNIX 사용자 이름, UNIX UID, Windows SID, UID가 사용자와 일치하는 파일 또는 디렉토리, Windows 2000 이전 형식의 Windows 사용자 이름, 사용자 SID가 소유한 ACL이 있는 파일 또는 디렉토리로 나타낼 수 있습니다. 볼륨 또는 qtree에 적용할 수 있습니다.

* * 그룹 할당량 *
+
타겟이 그룹입니다.

+
그룹은 UNIX 그룹 이름, GID 또는 GID가 그룹과 일치하는 파일 또는 디렉토리로 표시됩니다. ONTAP는 Windows ID를 기준으로 그룹 할당량을 적용하지 않습니다. 볼륨 또는 qtree에 할당량을 적용할 수 있습니다.

* * Qtree 할당량 *
+
타겟은 qtree로, qtree에 대한 경로 이름으로 지정됩니다.

+
타겟 qtree의 크기를 결정할 수 있습니다.

* * 기본 할당량 *
+
각 타겟에 대해 별도의 할당량을 생성하지 않고 할당량 제한을 대규모 할당량 타겟 세트에 자동으로 적용합니다.

+
기본 할당량은 세 가지 유형의 할당량 대상(사용자, 그룹 및 qtree)에 모두 적용될 수 있습니다. 할당량 유형은 유형 필드의 값에 의해 결정됩니다.





== 할당량 제한입니다

디스크 공간 제한을 적용하거나 각 할당량 유형의 파일 수를 제한할 수 있습니다. 할당량에 대한 제한을 지정하지 않으면 적용되지 않습니다.

할당량은 소프트 또는 하드일 수 있습니다. 소프트 할당량을 사용하면 Data ONTAP에서 지정된 제한을 초과할 때 알림을 보내고, 하드 할당량을 사용하면 지정된 제한을 초과할 때 쓰기 작업이 성공하지 못합니다.

하드 할당량은 시스템 리소스에 엄격한 제한을 부과하며, 제한을 초과하는 작업은 모두 실패합니다. 다음 설정은 하드 할당량을 생성합니다.

* Disk Limit 매개 변수입니다
* 파일 제한 매개 변수


소프트 할당량은 리소스 사용량이 특정 수준에 도달해도 데이터 액세스 작업에는 영향을 주지 않으므로 할당량이 초과되기 전에 적절한 조치를 취할 수 있도록 경고 메시지를 보냅니다. 다음 설정은 소프트 할당량을 생성합니다.

* Disk Limit 매개 변수의 임계값입니다
* 소프트 디스크 제한 매개 변수입니다
* 소프트 파일 제한 매개 변수


임계값 및 소프트 디스크 할당량을 통해 관리자는 할당량에 대한 알림을 두 개 이상 받을 수 있습니다. 일반적으로 관리자는 디스크 한계 임계값을 디스크 한계보다 약간 작은 값으로 설정하여 쓰기 시작 전에 임계값이 "최종 경고"를 제공할 수 있도록 합니다.

* * 디스크 공간 하드 제한값 *
+
하드 할당량에 적용되는 디스크 공간 제한입니다.

* * 디스크 공간 소프트 제한값 *
+
소프트 할당량에 적용되는 디스크 공간 제한입니다.

* * 임계값 제한 *
+
임계값 할당량에 적용되는 디스크 공간 제한입니다.

* * 파일 하드 제한값 *
+
하드 할당량에 있는 최대 파일 수입니다.

* * 파일 소프트 제한값 *
+
소프트 할당량에 있는 최대 파일 수입니다.





== 할당량 관리

System Manager에는 할당량을 생성, 편집 또는 삭제하는 데 도움이 되는 몇 가지 기능이 있습니다. 사용자, 그룹 또는 트리 할당량을 생성하고 디스크 및 파일 레벨에서 할당량 제한을 지정할 수 있습니다. 모든 할당량은 볼륨별로 설정됩니다.

할당량을 생성한 후 다음 작업을 수행할 수 있습니다.

* 할당량을 설정 및 해제합니다
* 할당량 크기 조정




== 할당량 창

Quotas 창을 사용하여 할당량에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



=== 탭

* * 사용자 정의 할당량 *
+
사용자 정의 할당량 * 탭을 사용하여 생성한 할당량에 대한 세부 정보를 보고 할당량을 생성, 편집 또는 삭제할 수 있습니다.

* * 할당량 보고서 *
+
할당량 보고서 탭을 사용하여 공간과 파일 사용량을 확인하고 활성 할당량의 공간 및 파일 한도를 편집할 수 있습니다.

* * 볼륨의 할당량 상태 *
+
볼륨 탭의 할당량 상태 탭을 사용하여 할당량 상태를 확인하고 할당량을 설정하거나 해제할 수 있으며 할당량 크기를 조정할 수 있습니다.





=== 명령 버튼

* * 생성 *
+
할당량을 생성할 수 있는 할당량 생성 마법사를 엽니다.

* * 한도 편집 *
+
선택한 할당량의 설정을 편집할 수 있는 제한 편집 대화 상자를 엽니다.

* * 삭제 *
+
할당량 목록에서 선택한 할당량을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 사용자 정의 할당량 목록

할당량 목록에 각 할당량의 이름과 스토리지 정보가 표시됩니다.

* * 볼륨 *
+
할당량이 적용되는 볼륨을 지정합니다.

* * Qtree *
+
할당량과 연결된 qtree를 지정합니다. ""모든 qtree""는 할당량이 모든 qtree와 연결됨을 나타냅니다.

* * 유형 *
+
할당량 유형(사용자, 그룹 또는 트리)을 지정합니다.

* * 사용자/그룹 *
+
할당량과 연결된 사용자 또는 그룹을 지정합니다. "모든 사용자"는 할당량이 모든 사용자와 연결되어 있음을 나타냅니다. "모든 그룹"은 할당량이 모든 그룹에 연결되었음을 나타냅니다.

* * 할당량 타겟 *
+
할당량이 할당된 타겟의 유형을 지정합니다. 타겟은 qtree, 사용자 또는 그룹이 될 수 있습니다.

* * 공간 하드 제한값 *
+
하드 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 공간 소프트 제한값 *
+
소프트 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 임계값 *
+
임계값 할당량에 적용되는 디스크 공간 제한을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 파일 하드 제한값 *
+
하드 할당량의 최대 파일 수를 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 파일 소프트 제한값 *
+
소프트 할당량의 최대 파일 수를 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.





=== 세부 정보 영역

할당량 목록 아래의 영역에는 할당량 오류, 공간 사용량 및 제한, 파일 사용량 및 제한과 같은 할당량 세부 정보가 표시됩니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap/volumes/index.html["논리적 스토리지 관리"^]
