---
permalink: online-help-96-97/concept_kerberos_realm_services.html 
sidebar: sidebar 
keywords: online, help, kerberos, realm, service, system, manager, svm, edit, security, strong, nfs, authentication, microsoft, ntlm, ntlm v2, client 
summary: System Manager를 사용하여 Kerberos 영역 서비스를 만들고 관리할 수 있습니다. 
---
= 시스템 관리자 - ONTAP 9.7 이하를 사용하여 Kerberos 영역 서비스를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 Kerberos 영역 서비스를 만들고 관리할 수 있습니다.



== Kerberos 영역 구성을 만듭니다

클라이언트 액세스에 Kerberos 인증을 사용하려면 기존 Kerberos 영역을 사용하도록 SVM(스토리지 가상 시스템)을 구성해야 합니다. System Manager를 사용하여 Kerberos 영역 구성을 생성할 수 있습니다. 이 구성을 사용하면 SVM에서 NFS에 Kerberos 보안 서비스를 사용할 수 있습니다.

.시작하기 전에
* CIFS 공유를 사용하는 경우 CIFS 라이센스를 설치해야 하며 LDAP 서버를 사용하는 경우 NFS 라이센스를 설치해야 합니다.
* DES MD5 암호화 기능이 있는 Active Directory(Windows 2003 또는 Windows 2008)를 사용할 수 있어야 합니다.
* NTP를 구성하여 표준 시간대를 설정하고 클러스터 전체에서 시간을 동기화해야 합니다.
+
이렇게 하면 인증 오류가 방지되고 로그 파일의 타임스탬프가 클러스터 전체에서 일관되도록 할 수 있습니다.



.이 작업에 대해
Kerberos 영역을 만드는 동안 Kerberos 영역 만들기 마법사에서 다음 속성을 설정해야 합니다.

* Kerberos 영역
* KDC IP 주소 및 포트 번호입니다
+
기본 포트 번호는 88입니다.

* Kerberos KDC(키 배포 센터) 공급업체
* KDC 공급업체가 Microsoft가 아닌 경우 관리 서버 IP 주소입니다
* 암호 서버 IP 주소입니다
* KDC 공급업체가 Microsoft인 경우 Active Directory 서버 이름 및 IP 주소


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 서비스 * 창에서 * Kerberos 영역 * 을 클릭합니다.
. Kerberos Realm* 창에서 * 생성 * 을 클릭합니다.
. 마법사의 지시에 따라 정보를 입력하거나 선택합니다.
. 세부 정보를 확인한 다음 * 마침 * 을 클릭하여 마법사를 완료합니다.




== Kerberos 영역 구성을 편집합니다

System Manager를 사용하여 SVM(스토리지 가상 시스템) 레벨에서 Kerberos 영역 구성을 편집할 수 있습니다.

.이 작업에 대해
Kerberos 영역 편집 마법사를 사용하여 다음 속성을 수정할 수 있습니다.

* KDC IP 주소 및 포트 번호입니다
* KDC 공급업체가 Microsoft가 아닌 경우 관리 서버의 IP 주소입니다
* 암호 서버의 IP 주소입니다
* KDC 공급업체가 Microsoft인 경우 Active Directory 서버 이름 및 IP 주소입니다


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 서비스 * 창에서 * Kerberos 영역 * 을 클릭합니다.
. Kerberos Realm* 창에서 수정할 Kerberos 영역 구성을 선택한 다음 * 편집 * 을 클릭합니다.
. 마법사의 지시에 따라 정보를 입력하거나 선택합니다.
. 세부 정보를 확인한 다음 * 마침 * 을 클릭하여 마법사를 완료합니다.




== Kerberos 영역 구성을 삭제합니다

System Manager를 사용하여 Kerberos 영역 구성을 삭제할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 서비스 * 창에서 * Kerberos 영역 * 을 클릭합니다.
. Kerberos Realm* 창에서 삭제할 Kerberos 영역 구성을 하나 이상 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 강력한 보안을 위해 NFS와 Kerberos 사용

Kerberos를 사용하여 SVM과 NFS 클라이언트 간에 강력한 인증을 제공하여 안전한 NFS 통신을 제공할 수 있습니다. Kerberos를 사용하여 NFS를 구성하면 스토리지 시스템과의 NFS 클라이언트 통신의 무결성과 보안이 강화됩니다.



== CIFS에 대한 Kerberos 인증

Kerberos 인증을 사용하면 CIFS 서버에 연결할 때 클라이언트가 가장 높은 보안 수준을 협상합니다. 그러나 클라이언트가 Kerberos 인증을 사용할 수 없는 경우 CIFS 서버를 인증하는 데 Microsoft NTLM 또는 NTLM V2가 사용됩니다.



== Kerberos 영역 창

Kerberos Realm 창을 사용하여 SVM(Storage Virtual Machine)과 NFS 클라이언트 간에 인증을 제공하여 안전한 NFS 통신을 보장할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
Kerberos 영역 만들기 마법사를 엽니다. 이 마법사를 사용하면 사용자 정보를 검색할 Kerberos 영역을 구성할 수 있습니다.

* * 편집 *
+
Kerberos 영역 편집 마법사를 엽니다. 이 마법사를 사용하면 SVM 인증 및 권한 부여 요구 사항에 따라 Kerberos 영역 구성을 편집할 수 있습니다.

* * 삭제 *
+
Kerberos 영역 삭제 대화 상자를 엽니다. 이 대화 상자에서 Kerberos 영역 구성을 삭제할 수 있습니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== Kerberos 영역 목록

Kerberos 영역에 대한 자세한 내용은 표 형식 을 참조하십시오.

* * 영역 *
+
Kerberos 영역의 이름을 지정합니다.

* * KDC 공급업체 *
+
Kerberos Distribution Center(KDC) 공급업체의 이름을 지정합니다.

* * KDC IP 주소 *
+
구성에 사용되는 KDC IP 주소를 지정합니다.





=== 세부 정보 영역

세부 정보 영역에는 KDC IP 주소 및 포트 번호, KDC 공급업체, 관리 서버 IP 주소 및 포트 번호, Active Directory 서버 및 선택한 Kerberos 영역 구성의 서버 IP 주소와 같은 정보가 표시됩니다.

* 관련 정보 *

xref:task_setting_time_zone_for_cluster.adoc[클러스터의 시간대 설정]

link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NetApp 기술 보고서 4067: NetApp ONTAP의 NFS"^]

link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp 기술 보고서 4616: ONTAP에서 Microsoft Active Directory와 NFS Kerberos"^]

link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp 기술 보고서 4835: ONTAP에서 LDAP를 구성하는 방법"^]

https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS 관리"^]
