---
permalink: online-help-96-97/concept_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policy, system, manager, create, edit, delete, online, help, flexvol, window 
summary: System Manager를 사용하여 효율성 정책을 생성, 편집 및 삭제할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 효율성 정책을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 방식을 사용하여 효율성 정책을 생성, 편집 및 삭제할 수 있습니다.



== 효율성 정책 추가

System Manager를 사용하면 지정된 일정에 따라 볼륨의 중복제거 작업을 실행하거나 볼륨 데이터의 변경 사항이 지정된 임계값에 도달하는 경우 효율성 정책을 추가할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Efficiency Policies * 를 클릭합니다.
. 추가 * 를 클릭한 다음 정책 이름을 지정합니다.
. 스토리지 효율성 정책을 실행하는 방법 지정:
+
** 스케줄 * 을 선택하고 스케줄 이름과 스케줄 세부 정보를 지정합니다.
+
필요한 경우 효율성 정책의 최대 실행 시간을 지정할 수 있습니다.

** ChangeLog Threshold * 를 선택하고 볼륨 데이터 변경에 대한 임계값(백분율)을 지정합니다.


. * 선택 사항: * QoS 정책을 백그라운드로 설정 * 확인란을 선택하여 클라이언트 작업에 대한 성능 영향을 줄입니다.
. 추가 * 를 클릭합니다.




== 효율성 정책을 편집합니다

System Manager를 사용하여 정책 이름, 스케줄 이름 및 최대 런타임 같은 효율성 정책의 특성을 수정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Efficiency Policies * 를 클릭합니다.
. 효율성 정책 * 창에서 편집할 정책을 선택한 다음 * 편집 * 을 클릭합니다.
. [효율성 정책 편집] * 대화 상자에서 필요한 사항을 변경합니다.
. 저장 * 을 클릭합니다.




== 효율성 정책을 삭제합니다

System Managerto를 사용하면 더 이상 필요하지 않은 효율성 정책을 삭제할 수 있습니다.

.시작하기 전에
효율성 정책을 사용하지 않도록 설정해야 합니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Efficiency Policies * 를 클릭합니다.
. 삭제할 효율성 정책을 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 효율성 정책을 사용하거나 사용하지 않도록 설정합니다

System Manager를 사용하여 효율성 정책을 사용하거나 사용하지 않도록 설정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. Policies * 창에서 * Efficiency Policies * 를 클릭합니다.
. 활성화 또는 비활성화할 효율성 정책을 하나 이상 선택합니다.
. 필요에 따라 * 상태 * > * 활성화 * 또는 * 상태 * > * 비활성화 * 를 클릭합니다.
. 효율성 정책을 사용하지 않으려면 확인 확인란을 선택한 다음 * 확인 * 을 클릭합니다.




== 효율성 정책이란 무엇일까요

효율성 정책은 FlexVol 볼륨의 중복제거 작업에 대한 작업 스케줄입니다.

FlexVol 볼륨에서 중복제거를 실행하려면 작업을 특정 시간에 시작하도록 예약하거나 임계값 비율이 초과될 경우 작업이 트리거되도록 지정합니다. 효율성 정책에 포함된 작업 일정을 생성하여 중복제거 작업을 예약할 수 있습니다. 볼륨 효율성 정책은 cron 유형의 작업 스케줄만 지원합니다. 또는 임계값 비율을 지정할 수 있습니다. 새 데이터가 지정된 비율을 초과하면 중복 제거 작업이 시작됩니다.



== 사전 정의된 효율성 정책 이해

효율성 정책으로 볼륨을 구성하여 추가적인 공간 절약을 달성할 수 있습니다. 볼륨에 대해 구성된 백그라운드 효율성 작업을 예약을 통해 또는 수동으로 시작하지 않고도 인라인 압축을 실행하도록 볼륨을 구성할 수 있습니다.

SVM을 생성할 때 다음 효율성 정책이 자동으로 생성되어 삭제될 수 없습니다.

* 기본값
+
효율성 정책을 사용하여 볼륨에 대해 예약된 중복제거 작업을 실행하도록 볼륨을 구성할 수 있습니다.

* 인라인만 해당
+
인라인만 지원하는 효율성 정책을 사용하여 볼륨을 구성한 후, 백그라운드 효율성 작업을 예약을 통해 또는 수동으로 시작하지 않고도 해당 볼륨에 대해 인라인 압축을 실행하도록 설정할 수 있습니다.



인라인만 지원하는 기본 효율성 정책에 대한 자세한 내용은 man 페이지를 참조하십시오.



== 효율성 정책 창

효율성 정책 창을 사용하여 효율성 정책에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



=== 명령 버튼

* * 추가 *
+
지정된 기간(스케줄 기반) 또는 볼륨 데이터의 변경이 지정된 임계값(임계값 기반)에 도달할 때 볼륨에 대해 중복 제거 작업을 실행할 수 있는 효율성 정책 추가 대화 상자를 엽니다.

* * 편집 *
+
효율성 정책 편집 대화 상자를 엽니다. 이 대화 상자에서 중복제거 작업의 스케줄, 임계값, QoS 유형, 최대 실행 시간을 수정할 수 있습니다.

* * 삭제 *
+
선택한 효율성 정책을 삭제할 수 있는 효율성 정책 삭제 대화 상자를 엽니다.

* * 상태 *
+
선택한 효율성 정책을 활성화 또는 비활성화하는 옵션을 제공하는 드롭다운 메뉴를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 효율성 정책 목록

* * 자동 *
+
백그라운드에서 중복 제거가 지속적으로 수행되도록 지정합니다. 이 정책은 새로 생성된 모든 볼륨과 백그라운드 중복제거를 위해 수동으로 구성되지 않은 업그레이드된 모든 볼륨에 대해 설정됩니다. 정책을 "기본값" 또는 다른 정책으로 변경하면 "자동" 정책이 비활성화됩니다.

+
볼륨이 비 AFF 시스템에서 AFF 시스템으로 이동하는 경우 기본적으로 타겟 노드에서 ""자동"" 정책이 활성화되어 있습니다. 볼륨이 AFF 노드에서 비 AFF 노드로 이동하는 경우 대상 노드의 "자동" 정책은 기본적으로 "인라인 전용" 정책으로 대체됩니다.

* * 정책 *
+
효율성 정책의 이름을 지정합니다.

* * 상태 *
+
효율성 정책의 상태를 지정합니다. 상태는 다음 중 하나일 수 있습니다.

+
** 활성화됨
+
중복 제거 작업에 효율성 정책을 할당할 수 있도록 지정합니다.

** 사용 안 함
+
효율성 정책이 비활성화되도록 지정합니다. 상태 드롭다운 메뉴를 사용하여 정책을 사용하도록 설정하고 나중에 중복 제거 작업에 할당할 수 있습니다.



* * 실행 기준 *
+
스토리지 효율성 정책을 스케줄에 따라 실행할지 또는 임계값(변경 로그 임계값)을 기반으로 실행할지 여부를 지정합니다.

* * QoS 정책 *
+
스토리지 효율성 정책의 QoS 유형을 지정합니다. QoS 유형은 다음 중 하나일 수 있습니다.

+
** 배경
+
QoS 정책이 백그라운드에서 실행되고 있음을 지정함으로써 클라이언트 작업에 대한 잠재적인 성능 영향을 줄입니다.

** 최선의 노력
+
QoS 정책이 최선 노력 기반으로 실행되도록 지정합니다. 이를 통해 시스템 리소스 활용률을 최대화할 수 있습니다.



* * 최대 런타임 *
+
효율성 정책의 최대 런타임 기간을 지정합니다. 이 값을 지정하지 않으면 작업이 완료될 때까지 효율성 정책이 실행됩니다.





=== 세부 정보 영역

효율성 정책 목록 아래의 영역에는 일정 이름, 일정 기반 정책의 일정 세부 정보, 임계값 기반 정책의 임계값 등 선택한 효율성 정책에 대한 추가 정보가 표시됩니다.
