---
permalink: online-help-96-97/concept_namespace.html 
sidebar: sidebar 
keywords: junction, path, window, system, manager, mount, unmount, flexvol, volume, svm, namespace, online, help, policies, export 
summary: System Manager의 Junction Path 창을 사용하여 FlexVol 볼륨을 SVM 네임스페이스의 교차점에 마운트하거나 마운트 해제할 수 있습니다. 
---
= System Manager - ONTAP 9.7 및 그 이전 버전의 Junction Path 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)의 Junction Path 창을 사용하여 SVM 네임스페이스의 교차점에 FlexVol 볼륨을 마운트하거나 마운트 해제할 수 있습니다.



== 볼륨을 마운트합니다

System Manager를 사용하여 SVM(스토리지 가상 머신) 네임스페이스의 분기점에 볼륨을 마운트할 수 있습니다.

.이 작업에 대해
* 경로에 있는 직접 상위 볼륨의 언어 설정과 다른 언어 설정을 사용하여 볼륨을 연결 경로에 마운트하는 경우, NFSv3 클라이언트는 일부 문자가 올바르게 디코딩되지 않을 수 있으므로 일부 파일에 액세스할 수 없습니다.
+
즉시 상위 디렉토리가 루트 볼륨인 경우에는 이 문제가 발생하지 않습니다.

* SnapLock 볼륨은 SVM의 루트 아래에서만 마운트할 수 있습니다.
* SnapLock 볼륨 아래에 일반 볼륨을 마운트할 수 없습니다.


.단계
. Storage * > * Junction Path * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 볼륨을 마운트할 SVM을 선택합니다.
. Mount * 를 클릭한 다음 마운트할 볼륨을 선택합니다.
. * 선택 사항: * 기본 교차점 이름을 변경하려면 새 이름을 지정합니다.
. 찾아보기 * 를 클릭한 다음 볼륨을 마운트할 접합 경로를 선택합니다.
. 확인 * 을 클릭한 다음 * 마운트 * 를 클릭합니다.
. Details * 탭에서 새 접합 경로를 확인합니다.




== FlexVol 볼륨을 마운트 해제합니다

System Manager의 스토리지 창에 있는 교차점 경로 옵션을 사용하여 SVM(스토리지 가상 시스템) 네임스페이스의 분기점에서 FlexVol 볼륨을 마운트 해제할 수 있습니다.

.단계
. Storage * > * Junction Path * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 볼륨을 마운트 해제할 SVM을 선택합니다.
. 마운트 해제할 볼륨을 선택한 다음 * 마운트 해제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 마운트 해제 * 를 클릭합니다.




== 엑스포트 정책을 변경합니다

볼륨이 생성되면 SVM(스토리지 가상 머신)의 루트 볼륨에 대한 기본 엑스포트 정책이 자동으로 상속됩니다. System Manager를 사용하여 볼륨에 연결된 기본 엑스포트 정책을 변경하여 데이터에 대한 클라이언트 액세스를 재정의할 수 있습니다.

.단계
. Storage * > * Junction Path * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 수정할 볼륨이 있는 SVM을 선택합니다.
. 볼륨을 선택한 다음 * 내보내기 정책 변경 * 을 클릭합니다.
. 내보내기 정책을 선택한 다음 * 변경 * 을 클릭합니다.
. Junction Path * 창의 * Export Policy * 열에 볼륨에 적용한 엑스포트 정책이 표시되는지 확인합니다.


.결과
기본 엑스포트 정책은 선택한 엑스포트 정책으로 대체됩니다.



== 접합 경로 창

Junction Path 메뉴를 사용하여 SVM(스토리지 가상 머신)의 NAS 네임스페이스를 관리할 수 있습니다.



=== 명령 버튼

* * 마운트 *
+
SVM 네임스페이스의 교차점에 볼륨을 마운트할 수 있는 볼륨 마운트 대화 상자를 엽니다.

* * 마운트 해제 *
+
볼륨 마운트 해제 대화 상자를 엽니다. 이 대화 상자에서 상위 볼륨에서 볼륨을 마운트 해제할 수 있습니다.

* * 수출 정책 변경 *
+
볼륨과 관련된 기존 엑스포트 정책을 변경할 수 있는 엑스포트 정책 변경 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 접합 경로 목록

* * 경로 *
+
마운트된 볼륨의 연결 경로를 지정합니다. 접합 경로를 클릭하여 관련 볼륨 및 qtree를 볼 수 있습니다.

* * 스토리지 객체 *
+
접합 경로에 마운트된 볼륨의 이름을 지정합니다. 볼륨에 포함된 qtree도 볼 수 있습니다.

* * 정책 내보내기 *
+
마운트된 볼륨의 내보내기 정책을 지정합니다.

* * 보안 스타일 *
+
볼륨의 보안 스타일을 지정합니다. 가능한 값으로는 UNIX(UNIX 모드 비트), NTFS(CIFS ACL용) 및 혼합(혼합 NFS 및 CIFS 사용 권한)이 있습니다.





=== 세부 정보 탭

이름, 스토리지 객체의 유형, 마운트된 객체의 접속 경로, 엑스포트 정책과 같이 선택한 볼륨 또는 qtree에 대한 일반 정보를 표시합니다. 선택한 개체가 qtree인 경우 공간 하드 제한값, 공간 소프트 제한값 및 공간 사용에 대한 세부 정보가 표시됩니다.
