---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: System Manager를 사용하여 공유를 생성, 편집 및 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 공유를 관리합니다
:allow-uri-read: 


ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 공유를 생성, 편집 및 관리할 수 있습니다.



== CIFS 공유를 생성합니다

System Manager를 사용하여 CIFS 공유를 생성하면 CIFS 사용자가 액세스할 수 있는 폴더, qtree 또는 볼륨을 지정할 수 있습니다.

.시작하기 전에
CIFS를 설정하고 시작하기 전에 CIFS 라이센스를 설치해야 합니다.

.단계
. 스토리지 * > * 공유 * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 CIFS 공유를 생성할 SVM을 선택합니다.
. 공유 생성 * 을 클릭합니다.
. Create Share * 창에서 * Browse * 를 클릭하고 공유할 폴더, qtree 또는 볼륨을 선택합니다.
. 새 CIFS 공유의 이름을 지정합니다.
. * 선택 사항: * SMB 3.0 이상을 지원하는 클라이언트가 무중단 작업 중에 지속적으로 파일을 열 수 있도록 하려면 * Hyper-V 및 SQL*에 대한 지속적인 가용성 사용 확인란을 선택합니다.
+
이 옵션을 사용하여 연 파일은 페일오버, 반환 및 LIF 마이그레이션과 같은 운영 중단 이벤트로부터 보호됩니다.

+
System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.

. SMB 3.0 암호화를 활성화하려면 이 공유에 액세스하는 동안 데이터 암호화 * 확인란을 선택합니다.
. 공유에 대한 설명 또는 설명을 입력한 다음 * 생성 * 을 클릭합니다.


.결과
CIFS 공유는 그룹의 ""모든 사용자에 대한 모든 권한""으로 설정된 액세스 권한으로 생성됩니다.



== 공유 액세스를 중지합니다

폴더, qtree 또는 볼륨에 대한 공유 네트워크 액세스를 제거하려는 경우 System Manager를 사용하여 공유를 중지할 수 있습니다.

.시작하기 전에
CIFS 라이센스를 설치해야 합니다.

.단계
. 스토리지 * > * 공유 * 를 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 중지할 CIFS 공유가 있는 SVM을 선택합니다.
. 공유 목록에서 공유를 중지할 공유를 선택한 다음 * 공유 중지 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * Stop * (중지 *)을 클릭합니다.
. 공유가 * Shares * 창에 더 이상 표시되지 않는지 확인합니다.




== 홈 디렉토리 공유를 생성합니다

System Manager를 사용하여 홈 디렉토리 공유를 생성하고 홈 디렉토리 검색 경로를 관리할 수 있습니다.

.시작하기 전에
CIFS를 설정하고 시작해야 합니다.

.단계
. 스토리지 * > * 공유 * 를 클릭합니다.
. Create Home Directory * 를 클릭한 다음 사용자가 디렉터리에 매핑되는 방법을 결정하는 패턴 정보를 제공합니다.
. Create * 를 클릭합니다.
. 생성한 홈 디렉토리가 * Shares * 창에 나열되는지 확인합니다.




== 공유 설정을 편집합니다

System Manager를 사용하여 심볼 링크 설정, 사용자 또는 그룹의 공유 액세스 권한 및 공유에 대한 액세스 유형과 같은 공유 설정을 수정할 수 있습니다. 또한 Hyper-V를 통한 공유의 지속적인 가용성을 설정하거나 해제하고 ABE(액세스 기반 열거)를 설정 또는 해제할 수 있습니다. System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.

.단계
. 스토리지 * > * 공유 * 를 클릭합니다.
. 공유 목록에서 수정할 공유를 선택한 다음 * 편집 * 을 클릭합니다.
. Edit Share Settings * 대화 상자에서 필요에 따라 공유 설정을 수정합니다.
+
.. General * 탭에서 Hyper-V를 통해 공유를 지속적으로 사용할 수 있도록 설정합니다
+
지속적인 가용성을 활성화하면 SMB 3.0을 지원하는 SMB 3.0 및 클라이언트가 무중단 운영 중에 지속적으로 파일을 열 수 있습니다. 영구적으로 열려 있는 파일은 페일오버, 반환 및 LIF 마이그레이션과 같은 운영 중단 이벤트로부터 보호됩니다.

.. 사용 권한 * 탭에서 사용자 또는 그룹을 추가한 다음 사용 권한을 할당하여 액세스 유형을 지정합니다.
.. 옵션 * 탭에서 필요한 옵션을 선택합니다.


. 저장 후 닫기 * 를 클릭합니다.
. 공유 * 창에서 선택한 공유에 대한 변경 사항을 확인합니다.




== ONTAP에서 동적 홈 디렉터리를 활성화하는 방법

ONTAP 홈 디렉터리를 사용하면 연결된 사용자와 변수 집합을 기반으로 서로 다른 디렉터리에 매핑되는 SMB 공유를 구성할 수 있습니다. 각 사용자에 대해 별도의 공유를 생성하는 대신 몇 가지 홈 디렉토리 매개 변수를 사용하여 하나의 공유를 구성하여 진입점(공유)과 홈 디렉토리(SVM의 디렉토리) 간의 사용자 관계를 정의할 수 있습니다.

게스트 사용자로 로그인한 사용자는 홈 디렉토리가 없으며 다른 사용자의 홈 디렉토리에 액세스할 수 없습니다. 사용자가 디렉토리에 매핑되는 방식을 결정하는 변수는 네 가지입니다.

* * 공유 이름 *
+
사용자가 연결하는 공유의 이름입니다. 이 공유에 대한 홈 디렉토리 속성을 설정해야 합니다.

+
공유 이름에는 다음 동적 이름을 사용할 수 있습니다.

+
** `%w` (사용자의 Windows 사용자 이름)
** `%d` (사용자의 Windows 도메인 이름)
** `%u` (사용자의 매핑된 UNIX 사용자 이름)


+
모든 홈 디렉토리에서 공유 이름을 고유하게 만들려면 공유 이름에 가 포함되어 있어야 합니다/`%w` 또는 을 누릅니다 `%u` 변수. 공유 이름에는 둘 다 포함될 수 있습니다 `%d` 및/`%w` 변수(예: `%d`/`%w`), 또는 공유 이름에 정적 부분과 가변 부분(예: home_/`%w`)를 클릭합니다.

* * 공유 경로 *
+
이 경로는 공유에 의해 정의되고 공유 이름 중 하나와 연관되며, SVM의 루트에서 사용자의 전체 홈 디렉토리 경로를 생성하기 위해 각 검색 경로에 추가됩니다. 정적(예: `home`), dynamic(예: `%w`) 또는 두 가지 조합(예: `eng/%w`)를 클릭합니다.

* * 검색 경로 *
+
ONTAP에서 홈 디렉토리를 검색하도록 지정하는 SVM 루트의 절대 경로 세트입니다. 를 사용하여 하나 이상의 검색 경로를 지정할 수 있습니다 `vserver cifs home-directory search-path add` 명령. 여러 개의 검색 경로를 지정하면 ONTAP는 유효한 경로를 찾을 때까지 지정된 순서대로 경로를 시도합니다.

* * 디렉토리 *
+
사용자를 위해 생성한 사용자의 홈 디렉토리입니다. 디렉터리 이름은 일반적으로 사용자의 이름입니다. 검색 경로로 정의된 디렉토리 중 하나에 홈 디렉토리를 생성해야 합니다.



예를 들어, 다음 설정을 고려합니다.

* 사용자: John Smith
* 사용자 도메인: Acme
* 사용자 이름: jsmith
* SVM 이름: vs1
* 홈 디렉토리 공유 이름 #1: home_ `%w` - 공유 경로: `%w`
* 홈 디렉토리 공유 이름 #2: `%w` - 공유 경로: `%d/%w`
* 검색 경로 #1: `/vol0home/home`
* 검색 경로 #2: `/vol1home/home`
* 검색 경로 #3: `/vol2home/home`
* 홈 디렉토리: `/vol1home/home/jsmith`


시나리오 1: 사용자가 에 연결합니다 `\\vs1\home_jsmith`. 이는 첫 번째 홈 디렉토리 공유 이름과 일치하고 상대 경로를 생성합니다 `jsmith`. 이제 ONTAP는 라는 디렉토리를 검색합니다 `jsmith` 각 검색 경로를 순서대로 확인:

* `/vol0home/home/jsmith` 존재하지 않습니다. 검색 경로 #2로 이동합니다.
* `/vol1home/home/jsmith` 이(가) 있습니다. 따라서 검색 경로 #3이 선택되지 않았습니다. 사용자가 홈 디렉토리에 연결되었습니다.


시나리오 2: 사용자가 에 연결합니다 `\\vs1\jsmith`. 이렇게 하면 두 번째 홈 디렉토리 공유 이름과 일치하고 상대 경로가 생성됩니다 `acme/jsmith`. 이제 ONTAP는 라는 디렉토리를 검색합니다 `acme/jsmith` 각 검색 경로를 순서대로 확인:

* `/vol0home/home/acme/jsmith` 존재하지 않습니다. 검색 경로 #2로 이동합니다.
* `/vol1home/home/acme/jsmith` 존재하지 않습니다. 검색 경로 #3으로 이동합니다.
* `/vol2home/home/acme/jsmith` 존재하지 않습니다. 홈 디렉토리가 없으므로 연결이 실패합니다.




== 공유 창

공유 창을 사용하여 공유를 관리하고 공유에 대한 정보를 볼 수 있습니다.



=== 명령 버튼

* * 공유 생성 *
+
공유를 생성할 수 있는 공유 생성 대화 상자를 엽니다.

* * 홈 디렉토리 생성 *
+
새 홈 디렉토리 공유를 생성할 수 있는 홈 디렉토리 공유 생성 대화 상자를 엽니다.

* * 편집 *
+
선택한 공유의 속성을 수정할 수 있는 설정 편집 대화 상자를 엽니다.

* * 공유 중지 *
+
선택한 개체를 공유하지 않습니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 공유 목록

공유 목록에는 각 공유의 이름과 경로가 표시됩니다.

* * 공유 이름 *
+
공유 이름을 표시합니다.

* * 경로 *
+
공유된 기존 폴더, qtree 또는 볼륨의 전체 경로 이름을 표시합니다. 경로 구분 기호는 역슬래시 또는 슬래시일 수 있지만 ONTAP는 모든 경로 구분 기호를 슬래시 로 표시합니다.

* * 홈 디렉토리 *
+
홈 디렉토리 공유의 이름을 표시합니다.

* * 설명 *
+
공유에 대한 추가 설명을 표시합니다(있는 경우).

* * 지속적으로 사용 가능한 공유 *
+
지속적인 가용성을 위해 공유가 설정되었는지 여부를 표시합니다. System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.





=== 세부 정보 영역

공유 목록 아래의 영역에는 각 공유에 대한 공유 속성 및 액세스 권한이 표시됩니다.

* * 속성 *
+
** 이름
+
공유 이름을 표시합니다.

** oplocks 상태입니다
+
공유가 임시 잠금(oplocks)을 사용하는지 여부를 지정합니다.

** 검색 가능
+
Windows 클라이언트가 공유를 검색할 수 있는지 여부를 지정합니다.

** 스냅샷 표시
+
클라이언트에서 스냅샷 복사본을 볼 수 있는지 여부를 지정합니다.

** 지속적으로 사용 가능한 공유
+
지속적인 가용성을 위해 공유를 설정하거나 해제할지 여부를 지정합니다. System Manager 9.6부터 FlexGroup 볼륨의 지속적인 가용성이 지원됩니다.

** 액세스 기반 열거
+
공유에 대해 ABE(액세스 기반 열거)를 사용할지 여부를 지정합니다.

** BranchCache입니다
+
공유에서 BranchCache를 설정 또는 해제할지 여부를 지정합니다.

** SMB 암호화
+
SMB 3.0을 사용한 데이터 암호화가 SVM(스토리지 가상 머신) 레벨에서 활성화되는지 공유 레벨에서 활성화되는지를 지정합니다. SVM 레벨에서 SMB 암호화가 활성화된 경우 SMB 암호화는 모든 공유에 적용되며 값이 SVM 레벨에서 Enabled로 표시됩니다.

** 이전 버전
+
클라이언트에서 이전 버전을 보고 복원할 수 있는지 여부를 지정합니다.



* * 공유 액세스 제어 *
+
공유에 대한 도메인 사용자, 도메인 그룹, 로컬 사용자 및 로컬 그룹의 액세스 권한을 표시합니다.



* 관련 정보 *

xref:task_setting_up_cifs.adoc[CIFS를 설정하는 중입니다]
