---
permalink: online-help-96-97/concept_how_data_ontap_name_service_switch_configuration_works.html 
sidebar: sidebar 
keywords: ontap, name, service, switch, configuration, works, unix, system, online, help 
summary: ONTAP는 UNIX 시스템의 /etc/nsswitch.conf 파일에 해당하는 테이블에 이름 서비스 구성 정보를 저장합니다. 환경에 맞게 적절하게 구성할 수 있도록 표의 기능과 ONTAP에서 표의 사용 방법을 이해해야 합니다. 
---
= 시스템 관리자 - ONTAP 9.7 및 이전 버전의 ONTAP 네임 서비스 스위치 구성에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager Classic(ONTAP 9.7 이하 버전에서 사용 가능)은 에 해당하는 테이블에 네임 서비스 구성 정보를 저장합니다 `/etc/nsswitch.conf` UNIX 시스템의 파일입니다. 환경에 맞게 적절하게 구성할 수 있도록 표의 기능과 ONTAP에서 표의 사용 방법을 이해해야 합니다.

ONTAP 이름 서비스 스위치 테이블은 ONTAP가 특정 유형의 이름 서비스 정보에 대한 정보를 검색하기 위해 어떤 이름 서비스 소스를 참조합니다. ONTAP는 SVM별로 개별 네임 서비스 스위치 테이블을 유지 관리합니다.



== 데이터베이스 유형

이 테이블에는 다음과 같은 각 데이터베이스 유형에 대해 별도의 이름 서비스 목록이 저장됩니다.

|===
| 데이터베이스 유형입니다 | 다음에 대한 이름 서비스 소스를 정의합니다. | 유효한 소스는... 


 a| 
호스트
 a| 
호스트 이름을 IP 주소로 변환
 a| 
파일, DNS



 a| 
그룹
 a| 
사용자 그룹 정보를 찾는 중입니다
 a| 
파일, NIS, LDAP



 a| 
암호
 a| 
사용자 정보를 찾는 중입니다
 a| 
파일, NIS, LDAP



 a| 
넷그룹
 a| 
넷그룹 정보를 찾는 중입니다
 a| 
파일, NIS, LDAP



 a| 
이름맵
 a| 
사용자 이름 매핑 중
 a| 
파일, LDAP

|===


== 소스 유형

소스는 해당 정보를 검색하는 데 사용할 이름 서비스 소스를 지정합니다.

|===
| 원본 유형 지정... | 에서 정보를 조회하려면... | 관리 대상 명령 제품군... 


 a| 
파일
 a| 
로컬 소스 파일
 a| 
`vserver services name-service unix-user`

`vserver services name-service unix-group`

`vserver services name-service netgroup`

`vserver services name-service dns hosts`



 a| 
NIS를 선택합니다
 a| 
SVM의 NIS 도메인 구성에 지정된 외부 NIS 서버
 a| 
`vserver services name-service nis-domain`



 a| 
LDAP를 지원합니다
 a| 
SVM의 LDAP 클라이언트 구성에 지정된 외부 LDAP 서버
 a| 
`vserver services name-service ldap`



 a| 
DNS
 a| 
SVM의 DNS 구성에 지정된 외부 DNS 서버
 a| 
`vserver services name-service dns`

|===
데이터 액세스 및 SVM 관리 인증 모두에 NIS 또는 LDAP를 사용하려는 경우에도 포함되어 있어야 합니다 `files` NIS 또는 LDAP 인증이 실패할 경우 로컬 사용자를 폴백으로 구성합니다.

* 관련 정보 *

xref:task_editing_svm_settings.adoc[SVM 설정 편집]
