---
permalink: online-help-96-97/concept_cluster_peers.html 
sidebar: sidebar 
keywords: cluster, peer, data, replication, snapmirror, snapvault, flexcache, syncmirror, configuration, system, manager, modify, passphrase, lif, configure, remote, change, encryption, status, online, help 
summary: 피어링된 클러스터는 SnapMirror 기술 및 SnapVault 기술을 사용하는 데이터 복제 및 MetroCluster 구성에서 FlexCache 볼륨 및 SyncMirror 기술을 사용한 데이터 복제에 필요합니다. System Manager를 사용하면 피어링된 클러스터가 두 클러스터 간에 리소스를 조정하고 공유할 수 있도록 두 클러스터를 피어링할 수 있습니다. 
---
= System Manager를 사용하는 클러스터 피어 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
피어링된 클러스터가 서로 간에 리소스를 조정하고 공유할 수 있도록 ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하여 2개의 클러스터를 피어링할 수 있습니다. 피어링된 클러스터는 SnapMirror 기술 및 SnapVault 기술을 사용하는 데이터 복제 및 MetroCluster 구성에서 FlexCache 볼륨 및 SyncMirror 기술을 사용한 데이터 복제에 필요합니다.



== 피어링 패스프레이즈를 생성합니다

System Manager 9.6부터는 로컬 클러스터 IPspace용 암호를 생성하고 피어링 관계를 생성할 때 원격 클러스터에서 동일한 암호를 사용할 수 있습니다.

.단계
. 구성 * > * 클러스터 피어 * 를 클릭합니다.
. Generate 피어링 Passphrase * 를 클릭합니다.
+
피어링 패스구문 생성 대화 상자가 표시됩니다.

. 다음 필드를 작성합니다.
+
** * IPspace *: 풀다운 메뉴에서 IPspace를 선택합니다.
** * Passphrase Validity *: 드롭다운 메뉴에서 패스프레이즈를 유효하게 할 기간을 선택합니다.
** * SVM 권한 *: 다음 중 하나를 선택합니다.
+
*** * 모든 SVM * 이 클러스터에 액세스할 수 있음을 나타냅니다.
*** * 클러스터에 액세스할 수 있는 특정 SVM을 나타내기 위해 SVM * 이 선택되었습니다. 지정할 필드에서 SVM 이름을 강조 표시합니다.




. * 선택 사항: * 원격 클러스터의 유효 클러스터 버전이 ONTAP 9.6 이전인 경우 확인란을 선택합니다. 그렇지 않으면 클러스터 피어링을 생성하지 못합니다.
. 암호를 생성하려면 * Generate * (생성 *)를 클릭합니다.
+
성공적인 생성을 위해 암호를 식별하는 메시지가 표시됩니다.

. 암호를 이메일로 보내거나 복사하려면 다음 작업 중 하나를 수행합니다.
+
** 이메일 암호 세부 정보 * 를 클릭합니다.
** 암호 복사 * 를 클릭합니다.






== 클러스터 피어 암호를 수정합니다

클러스터 피어 생성 중에 제공되는 암호를 수정할 수 있습니다.

.단계
. [[1단계]] * 구성 * > * 클러스터 피어 * 를 클릭합니다.
. 피어링된 클러스터를 선택하고 * Edit * 를 클릭합니다
+
드롭다운 메뉴가 표시됩니다.

. Local Cluster Passphrase * 를 클릭합니다.
+
Edit Local Cluster Passphrase 대화 상자가 표시됩니다.

. [[step4]] * 암호 입력 * 필드에 새 암호를 입력한 다음 * 적용 * 을 클릭합니다.
+
[NOTE]
====
암호의 최소 필수 길이는 8자입니다.

====
+
암호가 즉시 수정됩니다. 그러나 올바른 인증 상태가 표시되기 전에 지연이 있을 수 있습니다.

. 원격 클러스터에 로그인하여 단계를 수행합니다 link:#step1["1"] 부터 까지 link:#step4["4"] 원격 클러스터의 암호를 수정합니다.
+
로컬 클러스터의 인증 상태는 로 표시됩니다 `ok_and_offer` 을 눌러 원격 클러스터의 암호를 수정합니다.





== 원격 클러스터에 대해 구성된 LIF를 수정합니다

System Manager를 사용하여 원격 클러스터에 대해 구성된 IPspace 및 인터클러스터 논리 인터페이스(LIF)를 수정할 수 있습니다. 새 인터클러스터 IP 주소를 추가하거나 기존 IP 주소를 제거할 수 있습니다.

.시작하기 전에
클러스터 피어 관계를 생성하려면 인터클러스터 IP 주소가 하나 이상 있어야 합니다.

.단계
. 구성 * > * 클러스터 * > * 구성 업데이트 * 를 클릭합니다.
. 피어링된 클러스터를 선택하고 * Edit * 를 클릭합니다
+
드롭다운 메뉴가 표시됩니다.

. 피어 클러스터 네트워크 매개 변수 * 를 클릭합니다.
+
피어 네트워크 매개 변수 편집 대화 상자가 표시됩니다.

. 필요한 경우 다음 필드를 수정합니다.
+
** * IPspace *: 풀다운 메뉴에서 IPspace를 선택합니다.
** * 클러스터 간 LIF *: 인터클러스터 IP 주소를 추가 또는 제거합니다. 여러 IP 주소를 쉼표로 구분하여 추가할 수 있습니다.


. Modify * 를 클릭합니다.
. Cluster 피어 * 창에서 변경한 내용을 확인합니다.




== 피어링 암호화 상태를 변경합니다

System Manager를 사용하여 선택한 클러스터의 피어링 암호화 상태를 변경할 수 있습니다.

.이 작업에 대해
암호화 상태는 활성화 또는 비활성화할 수 있습니다. 암호화 변경 * 을 선택하여 상태를 사용 가능에서 사용 안 함으로 또는 사용 안 함 에서 사용으로 변경할 수 있습니다.

.단계
. 구성 * > * 클러스터 피어 * 를 클릭합니다.
. 피어링된 클러스터를 선택하고 * Edit * 를 클릭합니다
+
드롭다운 메뉴가 표시됩니다.

. 암호화 변경 * 을 클릭합니다.
+
암호화 상태가 "해당 없음"인 경우 이 작업을 사용할 수 없습니다.

+
암호화 변경 대화 상자가 표시됩니다. 토글 단추는 현재 암호화 상태를 나타냅니다.

. 토글 버튼을 밀어 피어링 암호화 상태를 변경하고 계속 진행합니다.
+
** 현재 암호화 상태가 ""없음""인 경우 전환 버튼을 밀어 상태를 ""TLS_PSK""로 변경하여 암호화를 활성화할 수 있습니다.
** 현재 암호화 상태가 "'TLS_PSK''인 경우 전환 버튼을 밀어 상태를 "'없음''으로 변경하여 암호화를 비활성화할 수 있습니다.


. 피어링 암호화를 활성화 또는 비활성화한 후, 새 암호를 생성하여 피어링된 클러스터에 제공하거나 피어링된 클러스터에서 이미 생성된 기존 암호를 적용할 수 있습니다.
+
[NOTE]
====
로컬 사이트에서 사용되는 암호가 원격 사이트에서 사용되는 암호와 일치하지 않으면 클러스터 피어링 관계가 제대로 작동하지 않습니다.

====
+
다음 중 하나를 선택합니다.

+
** * 암호 생성 *: 로 이동합니다 link:#step6["6단계"].
** *이미 암호문이 있습니다. *: 로 이동합니다 link:#step9["9단계"].


. [[step6]] * 암호 생성 * 을 선택한 경우 필요한 필드를 입력합니다.
+
** * IPspace *: 드롭다운 메뉴에서 IPspace를 선택합니다.
** * Passphrase Validity *: 드롭다운 메뉴에서 패스프레이즈를 유효하게 할 기간을 선택합니다.
** * SVM 권한 *: 다음 중 하나를 선택합니다.
+
*** 모든 SVM * 이 클러스터에 액세스할 수 있음을 나타냅니다.
*** * 클러스터에 액세스할 수 있는 특정 SVM을 나타내기 위해 SVM * 이 선택되었습니다. 지정할 필드에서 SVM 이름을 강조 표시합니다.




. * 선택 사항: * 원격 클러스터의 유효 클러스터 버전이 ONTAP 9.6 이전인 경우 확인란을 선택합니다. 그렇지 않으면 암호가 생성되지 않습니다.
. 적용 * 을 클릭합니다.
+
패스프레이즈는 관계에 대해 생성되고 표시됩니다. 암호문을 복사하거나 이메일로 보낼 수 있습니다.

+
로컬 클러스터의 인증 상태는 로 표시됩니다 `ok_and_offer` 원격 클러스터에 암호를 제공할 때까지 선택한 암호 유효 기간 동안

. [[step9]] 원격 클러스터에 새 암호를 이미 생성한 경우 다음 하위 단계를 수행하십시오.
+
.. 암호 * 가 이미 있습니다 * 를 클릭합니다.
.. 원격 클러스터에서 생성된 것과 동일한 암호를 * Passphrase * 필드에 입력합니다.
.. 적용 * 을 클릭합니다.






== 클러스터 피어 관계를 삭제합니다

관계가 더 이상 필요하지 않은 경우 System Manager를 사용하여 클러스터 피어 관계를 삭제할 수 있습니다. 피어 관계의 각 클러스터에서 클러스터 피어링 관계를 삭제해야 합니다.

.단계
. [[1단계]] * 구성 * > * 클러스터 피어 * 를 클릭합니다.
. 관계를 삭제할 클러스터 피어를 선택한 다음 * 삭제 * 를 클릭합니다.
. [[3단계]] 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.
. 원격 클러스터에 로그인하여 단계를 수행합니다 link:#step1["1"] 부터 까지 link:#step3["3"] 로컬 클러스터와 원격 클러스터 간의 피어 관계를 삭제합니다.
+
로컬 클러스터와 원격 클러스터에서 관계가 삭제될 때까지 피어 관계의 상태가 "비정상"으로 표시됩니다.





== Cluster 피어의 창입니다

클러스터 피어 창을 사용하여 피어 클러스터 관계를 관리할 수 있으며, 이 창에서 클러스터 간에 데이터를 이동할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
원격 클러스터와의 관계를 생성할 수 있는 클러스터 피어링 생성 대화 상자를 엽니다.

* * 편집 *
+
다음과 같은 선택 항목이 있는 드롭다운 메뉴를 표시합니다.

+
** * 로컬 클러스터 암호 *
+
Edit Local Cluster Passphrase 대화 상자를 엽니다. 이 대화 상자에서는 로컬 클러스터를 검증하기 위해 새 암호를 입력할 수 있습니다.

** 피어 클러스터 네트워크 매개 변수 *
+
IPspace를 수정하고 인터클러스터 LIF IP 주소를 추가하거나 제거할 수 있는 피어 클러스터 네트워크 매개 변수 편집 대화 상자를 엽니다.

+
여러 IP 주소를 쉼표로 구분하여 추가할 수 있습니다.

** * 암호화 변경 *
+
선택한 피어 클러스터에 대한 암호화 변경 대화 상자를 엽니다. 피어링된 관계 암호화를 변경하는 동안 새 암호를 생성하거나 원격 피어링된 클러스터에서 이미 생성된 암호를 제공할 수 있습니다.

+
암호화 상태가 "해당 없음"인 경우 이 작업을 사용할 수 없습니다.



* * 삭제 *
+
선택한 피어 클러스터 관계를 삭제할 수 있는 클러스터 피어 관계 삭제 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.

* * SVM 권한 관리 *
+
SVM이 SVM 피어링 요청을 자동으로 수용할 수 있도록 지원

* * 피어링 패스구문 생성 *
+
IPspace를 지정하고, 암호 유효 기간을 설정하고, 사용 권한이 부여된 SVM을 지정하여 로컬 클러스터 IPspace에 대한 암호를 생성할 수 있습니다.

+
원격 클러스터에서 피어링을 위해 동일한 암호를 사용합니다.





=== 피어 클러스터 목록

* 피어 클러스터 *
+
관계에서 피어 클러스터의 이름을 지정합니다.

* * 가용성 *
+
피어 클러스터를 통신에 사용할 수 있는지 여부를 지정합니다.

* * 인증 상태 *
+
피어 클러스터의 인증 여부를 지정합니다.

* * 로컬 클러스터 IPspace *
+
로컬 클러스터 피어 관계와 연결된 IPspace를 표시합니다.

* * 피어 클러스터 인터클러스터 IP 주소 *
+
인터클러스터 피어 관계와 연결된 IP 주소를 표시합니다.

* * 마지막 업데이트 시간 *
+
피어 클러스터가 마지막으로 수정된 시간을 표시합니다.

* * 암호화 *
+
피어링 관계의 암호화 상태를 표시합니다.

+
[NOTE]
====
System Manager 9.6부터는 두 클러스터 간의 피어링 관계를 설정할 때 피어링을 기본적으로 암호화합니다

====
+
** * 해당 없음 *: 암호화는 관계에 적용되지 않습니다.
** * 없음 *: 피어링 관계는 암호화되지 않습니다.
** * TLS_PSK *: 피어링 관계가 암호화됩니다.



