---
permalink: online-help-96-97/concept_high_availability.html 
sidebar: sidebar 
keywords: high, availability, system, manager, hardware, redundancy, nondisruptive, operations, fault, tolerance 
summary: 'System Manager를 사용하면 무중단 운영과 내결함성을 지원하는 데 필요한 하드웨어 이중화를 제공하는 고가용성(HA) 쌍을 생성할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 고가용성 쌍을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 HA 쌍을 사용하면 무중단 운영 및 내결함성을 위해 필요한 하드웨어 이중화를 제공하는 고가용성(HA) 쌍을 생성할 수 있습니다.



== 고가용성 창

고가용성 창에는 ONTAP의 모든 HA 쌍에 대한 고가용성(HA) 상태, 상호 연결 상태 및 테이크오버 또는 반환 상태가 그림으로 표시됩니다. 고가용성 창을 사용하여 테이크오버 작업 또는 반환 작업을 수동으로 시작할 수도 있습니다.

HA 쌍 이미지를 클릭하여 Takeover/Giveback 상태 및 상호 연결 상태와 같은 세부 정보를 볼 수 있습니다.

색상은 HA 쌍 상태를 나타냅니다.

* 녹색: HA Pair 및 인터커넥트가 최적으로 구성되었으며 테이크오버 또는 반환에 사용할 수 있음을 나타냅니다.
+
녹색은 또한 Takeover가 진행 중이고, Giveback이 진행 중이며, 반환 상태를 기다리고 있음을 나타냅니다.

* 빨간색: 테이크오버 실패와 같은 다운그레이드된 상태를 나타냅니다.
* 노란색: 상호 연결 상태가 중단되었음을 나타냅니다.


한 클러스터의 여러 HA 쌍이 동시에 스토리지 페일오버 작업에 관련되어 있을 경우 표시되는 클러스터 상태는 HA 쌍의 상태와 심각도에 따라 달라집니다. 클러스터 상태를 표시하는 동안 Takeover가 진행 중, Giveback이 진행 중, Giveback을 기다리는 동안 다음과 같은 심각도 순서를 고려해야 합니다.



=== 작업

HA 2노드에서 노드 상태에 따라 테이크오버 또는 반환과 같은 작업을 수행할 수 있습니다.

* 테이크오버 `node_name`
+
파트너 노드에서 유지보수가 필요한 경우 테이크오버 작업을 수행할 수 있습니다.

* 반환 `node_name`
+
인수된 파트너 노드가 반환 대기 중이거나 부분 반환 상태인 경우 반환 작업을 수행할 수 있습니다.

* 자동 반환 활성화 또는 비활성화
+
자동 반환 작업을 설정하거나 해제합니다.

+
[NOTE]
====
자동 반환은 기본적으로 활성화되어 있습니다.

====




=== 명령 버튼

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.

+
[NOTE]
====
High Availability 창에 표시되는 정보는 60초마다 자동으로 새로 고쳐집니다.

====


* 관련 정보 *

xref:task_monitoring_ha_pairs.adoc[HA 쌍 모니터링]
