---
permalink: online-help-96-97/concept_using_space_reservation_for_luns.html 
sidebar: sidebar 
keywords: understand, space, reservation, lun, volume, guarantee, online, help 
summary: '공간 예약 설정(볼륨 보장과 결합)이 LUN에 대해 공간을 별도로 설정하는 방식에 미치는 영향을 이해하면 공간 예약 비활성화의 영향과 특정 LUN 및 볼륨 설정 조합이 유용하지 않은 이유를 이해하는 데 도움이 됩니다.' 
---
= System Manager - ONTAP 9.7 및 이전 버전의 LUN에 대한 공간 예약 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)에서 공간 예약 설정(볼륨 보장과 결합)이 LUN에 공간을 별도로 설정하는 방식에 미치는 영향을 이해하면 공간 예약을 사용하지 않도록 설정하는 데 따른 영향을 이해하는 데 도움이 됩니다. 또한 특정 조합의 LUN 및 볼륨 설정이 유용하지 않은 이유를 이해하는 데 도움이 됩니다.

LUN에 공간 예약 기능(공간 예약 LUN)이 설정되어 있고 포함된 볼륨에 볼륨 보장이 있는 경우 생성 시 볼륨의 여유 공간이 LUN용으로 예약됩니다. 이 예약 공간의 크기는 LUN의 크기에 따라 결정됩니다. 볼륨의 다른 스토리지 개체(다른 LUN, 파일, 스냅샷 복사본 등)에서는 이 공간을 사용할 수 없습니다.

LUN에 공간 예약이 사용되지 않는 경우(비공간 예약 LUN), 생성 시 해당 LUN에 대해 공간이 예약되지 않습니다. LUN에 대한 쓰기 작업에 필요한 스토리지는 충분한 여유 공간을 사용할 수 있는 경우 필요할 때 볼륨으로부터 할당됩니다.

공간 예약 LUN이 NONE-Guaranteed 볼륨에 생성된 경우 LUN은 공간이 예약되지 않은 LUN과 동일하게 작동합니다. 이는 보장된 볼륨 중 어느 것도 LUN에 할당할 공간이 없기 때문입니다. 볼륨 자체는 이 LUN을 쓸 때만 공간을 할당할 수 있습니다. 보장하지는 않기 때문입니다. 따라서 보장된 볼륨이 아닌 볼륨에 공간 예약 LUN을 생성하는 것은 권장되지 않습니다. 이 구성 조합을 사용하면 실제로 불가능한 쓰기 보증이 될 수 있습니다.

공간 예약이 "기본값"으로 설정되면 ONTAP 공간 예약 설정이 LUN에 적용됩니다. 새 볼륨이 생성되는 경우 ONTAP 공간 예약 설정도 컨테이너 볼륨에 적용됩니다.
