---
permalink: online-help-96-97/concept_ethernet_ports.html 
sidebar: sidebar 
keywords: system, manager, manager, ethernet, port, create, online, help, create, interface, group, lacp, vlan, settings, duplex, mode, speed, mtu, size,  port, nodes, fcp, 
summary: System Manager를 사용하여 이더넷 포트를 생성하고 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 이더넷 포트를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서는 사용 가능)을 사용하여 이더넷 포트를 생성 및 관리할 수 있습니다.



== 인터페이스 그룹을 생성합니다

System Manager를 사용하여 집선 네트워크 포트의 기능을 결합하여 클라이언트에 단일 인터페이스를 제공하는 단일 모드, 정적 멀티모드 또는 동적 멀티모드(LACP) 인터페이스 그룹을 생성할 수 있습니다.

.시작하기 전에
사용 가능한 포트는 브로드캐스트 도메인 또는 인터페이스 그룹에 속하지 않거나 VLAN을 호스팅하는 가용 포트여야 합니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. 인터페이스 그룹 만들기 * 를 클릭합니다.
. 인터페이스 그룹 만들기 * 대화 상자에서 다음 설정을 지정합니다.
+
** 인터페이스 그룹의 이름입니다
** 노드
** 인터페이스 그룹에 포함하려는 포트입니다
** 포트의 사용 모드: 단일 모드, 정적 다중 모드 또는 동적 멀티모드(LACP)
** 네트워크 로드 분산: IP 기반, MAC 주소 기반, 순차 또는 포트
** 필요한 경우 인터페이스 그룹의 브로드캐스트 도메인입니다


. Create * 를 클릭합니다.




== VLAN 인터페이스를 생성합니다

System Manager를 사용하여 동일한 네트워크 도메인 내에서 별도의 브로드캐스트 도메인을 유지 관리하기 위해 VLAN을 생성할 수 있습니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. VLAN 만들기 * 를 클릭합니다.
. VLAN 생성 * 대화 상자에서 노드, 물리적 인터페이스 및 브로드캐스트 도메인(필요한 경우)을 선택합니다.
+
물리적 인터페이스 목록에는 이더넷 포트 및 인터페이스 그룹만 포함됩니다. 이 목록에는 다른 인터페이스 그룹 또는 기존 VLAN에 있는 인터페이스가 표시되지 않습니다.

. VLAN 태그를 입력한 다음 * 추가 * 를 클릭합니다.
+
고유한 VLAN 태그를 추가해야 합니다.

. Create * 를 클릭합니다.




== 이더넷 포트 설정을 편집합니다

System Manager를 사용하여 이중 모드 및 속도 설정과 같은 이더넷 포트 설정을 편집할 수 있습니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. 물리적 포트를 선택한 다음 * 편집 * 을 클릭합니다.
. 이더넷 포트 편집* 대화 상자에서 이중 모드 및 속도 설정을 둘 중 하나로 수정합니다 `manual` 또는 `automatic`.
. 편집 * 을 클릭합니다.




== 인터페이스 그룹 설정을 편집합니다

System Manager를 사용하여 인터페이스 그룹에 포트를 추가하고, 인터페이스 그룹에서 포트를 제거하고, 인터페이스 그룹에 있는 포트의 사용 모드 및 로드 분산 패턴을 수정할 수 있습니다.

.이 작업에 대해
브로드캐스트 도메인에 할당된 인터페이스 그룹의 MTU 설정은 수정할 수 없습니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. 인터페이스 그룹을 선택한 다음 * 편집 * 을 클릭합니다.
. 필요에 따라 인터페이스 그룹 설정을 수정한 다음 * 저장 후 닫기 * 를 클릭합니다.




== VLAN의 MTU 크기를 수정합니다

브로드캐스트 도메인에 속하지 않는 VLAN 인터페이스의 MTU 크기를 수정하려면 System Manager를 사용하여 크기를 변경할 수 있습니다.

.이 작업에 대해
관리 포트 e0M의 MTU 크기를 수정하면 안 됩니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. 수정할 VLAN을 선택한 다음 * 편집 * 을 클릭합니다.
. Edit VLAN * 대화 상자에서 필요에 따라 MTU 크기를 수정한 다음 * Save * 를 클릭합니다.




== VLAN을 삭제합니다

System Manager를 사용하여 네트워크 포트에 구성된 VLAN을 삭제할 수 있습니다. NIC를 슬롯에서 제거하기 전에 VLAN을 삭제해야 할 수 있습니다. VLAN을 삭제하면 VLAN을 사용하는 모든 페일오버 규칙 및 그룹에서 VLAN이 자동으로 제거됩니다.

.시작하기 전에
VLAN에 연결된 LIF가 없어야 합니다.

.단계
. 네트워크 * > * 이더넷 포트 * 를 클릭합니다.
. 삭제할 VLAN을 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.




== 포트 및 어댑터

포트는 노드 아래에 그룹화되며 노드는 선택한 프로토콜 범주에 따라 표시됩니다. 예를 들어, 데이터가 FC 프로토콜을 사용하여 처리되는 경우 FCP 어댑터를 사용하는 노드만 표시됩니다. 호스팅된 인터페이스 수를 사용하면 로드가 적은 포트를 선택할 수 있습니다.

* 관련 정보 *

https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 관리"]

https://docs.netapp.com/us-en/ontap/concepts/index.html["ONTAP 개념"]

xref:reference_network_window.adoc[네트워크 창]
