---
permalink: online-help-96-97/concept_aggregates.html 
sidebar: sidebar 
keywords: aggregates, system, manager, security, backup, performance, data, sharing, classic, online, help, window 
summary: System Manager를 사용하여 애그리게이트를 만들어 사용자의 다양한 보안, 백업, 성능 및 데이터 공유 요구사항을 지원할 수 있습니다. 
---
= System Manager로 애그리게이트 관리 - ONTAP 9.7 이하
:allow-uri-read: 


ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 사용자의 다양한 보안, 백업, 성능 및 데이터 공유 요구사항을 지원하는 애그리게이트를 만들 수 있습니다.



== 애그리게이트 창

애그리게이트 창을 사용하여 애그리게이트에 대한 정보를 생성, 표시 및 관리할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
Aggregate 생성 대화 상자를 엽니다. 이 대화 상자에서 Aggregate를 생성할 수 있습니다.

* * 편집 *
+
Aggregate 편집 대화 상자를 엽니다. 이 대화 상자에서 Aggregate의 이름이나 Aggregate에 제공할 RAID 보호 수준을 변경할 수 있습니다.

* * 삭제 *
+
선택한 애그리게이트를 삭제합니다.

+
[NOTE]
====
루트 애그리게이트에 대해 이 버튼을 사용할 수 없습니다.

====
* * 추가 작업 *
+
에서는 다음 옵션을 제공합니다.

* * 상태를 * 로 변경합니다
+
선택한 애그리게이트의 상태를 다음 상태 중 하나로 변경합니다.

+
** 온라인
+
이 애그리게이트에 포함된 볼륨에 대한 읽기 및 쓰기 액세스가 허용됩니다.

** 오프라인
+
읽기 및 쓰기 액세스가 허용되지 않습니다.

** 제한
+
패리티 재구성과 같은 일부 작업은 허용되지만 데이터 액세스는 허용되지 않습니다.



* * 용량 추가 *
+
용량(HDD 또는 SSD)을 기존 애그리게이트에 추가할 수 있도록 지원

* * 캐시 추가 *
+
캐시 디스크(SSD)를 기존 HDD 애그리게이트 또는 Flash Pool 애그리게이트에 추가할 수 있습니다.

+
All-Flash 최적화 속성을 가진 노드가 포함된 클러스터에서는 이 버튼을 사용할 수 없습니다.

* * 미러 *
+
애그리게이트를 미러링할 수 있습니다.

* * 볼륨 이동 *
+
FlexVol 볼륨을 이동할 수 있습니다.

* * 클라우드 계층 연결 * 을 선택합니다
+
클라우드 계층을 애그리게이트에 연결할 수 있도록 지원

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 집계 목록

각 애그리게이트의 이름 및 공간 사용 정보가 표시됩니다.

* * 상태 *
+
집계 상태를 표시합니다.

* * 이름 *
+
애그리게이트의 이름을 표시합니다.

* * 노드 *
+
Aggregate의 디스크가 할당된 노드의 이름을 표시합니다.

+
이 필드는 클러스터 수준에서만 사용할 수 있습니다.

* * 유형 *
+
집계 유형을 표시합니다.

+
All-Flash 최적화 속성을 가진 노드가 포함된 클러스터에는 이 필드가 표시되지 않습니다.

* * 사용됨(%) *
+
Aggregate에 사용된 공간의 비율을 표시합니다.

* * 사용 가능한 공간 *
+
Aggregate의 사용 가능한 공간을 표시합니다.

* * 사용된 공간 *
+
Aggregate의 데이터에 사용되는 공간의 크기를 표시합니다.

* * 총 공간 *
+
Aggregate의 총 공간을 표시합니다.

* * FabricPool *
+
선택한 애그리게이트를 클라우드 계층에 연결할지 여부를 표시합니다.

* * 클라우드 계층 *
+
선택한 애그리게이트는 클라우드 계층에 연결된 경우 클라우드 계층의 이름이 표시됩니다.

* * 볼륨 수 *
+
Aggregate와 연결된 볼륨의 수를 표시합니다.

* * 디스크 수 *
+
Aggregate를 생성하는 데 사용되는 디스크 수를 표시합니다.

* * Flash Pool *
+
Flash Pool 애그리게이트의 총 캐시 크기가 표시됩니다. NA 값은 Aggregate가 Flash Pool Aggregate가 아님을 나타냅니다.

+
All-Flash 최적화 속성을 가진 노드가 포함된 클러스터에는 이 필드가 표시되지 않습니다.

* * 미러링 *
+
Aggregate가 미러링되는지 여부를 표시합니다.

* * SnapLock 유형 *
+
Aggregate의 SnapLock 유형을 표시합니다.





=== 세부 정보 영역

선택한 Aggregate에 대한 정보를 보려면 Aggregate를 선택하십시오. 세부 정보 표시 를 클릭하여 선택한 애그리게이트에 대한 자세한 정보를 볼 수 있습니다.

* * 개요 탭 *
+
선택한 Aggregate에 대한 자세한 정보를 표시하고 애그리게이트의 공간 할당, 애그리게이트의 공간 절약, IOPS 및 총 데이터 전송 성능의 그림 표현을 표시합니다.

* * 디스크 정보 탭 *
+
디스크 이름, 디스크 유형, 물리적 크기, 사용 가능한 크기, 디스크 위치 등의 디스크 레이아웃 정보를 표시합니다. 디스크 상태, 플렉스 이름, 플렉스 상태, RAID 그룹, RAID 유형, 및 선택한 애그리게이트의 스토리지 풀(있는 경우)이 있습니다. 다중 경로 구성을 위해 디스크 기본 경로와 연결되어 있는 디스크 포트 및 디스크 이름과 디스크 보조 경로도 표시됩니다.

* 볼륨 탭 *
+
Aggregate의 총 볼륨 수, 총 애그리게이트 공간 및 Aggregate에 커밋된 공간에 대한 세부 정보를 표시합니다.

* * 성능 탭 *
+
처리량 및 IOPS를 포함하여 애그리게이트의 성능 메트릭을 보여주는 그래프를 표시합니다. 처리량 및 IOPS를 위해 읽기, 쓰기, 총 전송에 대한 성능 메트릭 데이터가 표시되고, SSD와 HDD의 데이터는 별도로 기록됩니다.

+
클라이언트 시간대 또는 클러스터 시간대를 변경하면 성능 메트릭 그래프에 영향을 줍니다. 업데이트된 그래프를 보려면 브라우저를 새로 고쳐야 합니다.



* 관련 정보 *

xref:task_provisioning_storage_through_aggregates.adoc[애그리게이트를 통한 스토리지 프로비저닝]

xref:task_deleting_aggregates.adoc[애그리게이트 삭제]

xref:task_editing_aggregates.adoc[집계 편집]
