---
permalink: online-help-96-97/concept_nodes.html 
sidebar: sidebar 
keywords: node, system, manager, view, detail, cluster, online, help 
summary: System Manager를 사용하여 클러스터에 있는 노드의 세부 정보를 볼 수 있습니다. 
---
= System Manager로 노드 관리 - ONTAP 9.7 이하
:allow-uri-read: 


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 클러스터의 노드 세부 정보를 볼 수 있습니다.



== ComplianceClock 시간을 초기화합니다

System Manager를 사용하여 ComplianceClock 시간을 현재 클러스터 시간으로 초기화할 수 있습니다. SnapLock 집계를 생성하려면 ComplianceClock 시간을 초기화해야 합니다.

.시작하기 전에
SnapLock 라이센스가 설치되어 있어야 합니다.

.이 작업에 대해
ComplianceClock 시간이 초기화된 후에는 수정하거나 중지할 수 없습니다.

.단계
. 스토리지 * > * 노드 * 를 클릭합니다.
. 노드를 선택한 다음 * ComplianceClock * 초기화 를 클릭합니다.
. ComplianceClock * 초기화 대화 상자에서 * 예 * 를 클릭하여 ComplianceClock 시간을 현재 클러스터 시간으로 초기화합니다.




== 노드 창

노드 창을 사용하여 클러스터의 노드 세부 정보를 볼 수 있습니다.



=== 명령 버튼

* * ComplianceClock 초기화 *
+
선택한 노드의 ComplianceClock을 시스템 시계의 현재 값으로 초기화합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 노드 목록

* * 이름 *
+
노드의 이름을 표시합니다.

* * 시/도 *
+
노드의 상태(노드가 가동 상태인지 중단 상태인지 여부)를 표시합니다.

* * 가동 시간 *
+
노드가 가동되는 기간을 표시합니다.

* * ONTAP 버전 *
+
노드에 설치된 ONTAP 버전을 표시합니다.

* * 모델 *
+
노드의 플랫폼 모델 번호를 표시합니다.

* * 시스템 ID *
+
노드의 ID를 출력한다.

* * 일련 번호 *
+
노드의 일련 번호를 표시합니다.





=== 세부 정보 영역

선택한 노드에 대한 자세한 정보를 표시합니다.

* * 세부 정보 탭 *
+
노드 이름, 노드 상태 및 노드가 가동되는 기간과 같이 선택한 노드와 관련된 정보를 표시합니다.

* * 성능 탭 *
+
선택한 노드의 처리량, IOPS, 지연 시간을 표시합니다.

+
클라이언트 시간대 또는 클러스터 시간대를 변경하면 성능 메트릭 그래프에 영향을 줍니다. 업데이트된 그래프를 보려면 브라우저를 새로 고쳐야 합니다.


