---
permalink: online-help-96-97/reference_dashboard_window.html 
sidebar: sidebar 
keywords: system, manager, dashboard, window, multiple, panel, online, help 
summary: 대시보드 창에는 시스템 및 성능에 대한 요약 정보를 제공하는 여러 패널이 포함되어 있습니다. 
---
= System Manager용 대시보드 창 - ONTAP 9.7 이전 버전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)의 대시보드 창에는 여러 패널이 포함되어 있어 시스템 및 성능에 대한 누적 정보를 한 눈에 확인할 수 있습니다.

대시보드 창을 사용하여 중요한 경고 및 알림, 애그리게이트 및 볼륨의 효율성 및 용량, 클러스터에서 사용 가능한 노드, 고가용성(HA) 쌍의 노드 상태, 가장 활성화된 애플리케이션 및 개체 등에 대한 정보를 볼 수 있습니다. 클러스터 또는 노드의 성능 메트릭과

* * 경고 및 알림 *
+
긴급 EMS 이벤트, 오프라인 노드 세부 정보, 손상된 디스크 세부 정보, 위험이 높은 라이센스 권한, 오프라인 네트워크 포트 세부 정보 등 모든 경고를 빨간색으로 표시합니다. 클러스터 수준에서 지난 24시간 동안 발생한 상태 모니터링 알림, 중간 위험이 있는 라이센스 권한, 할당되지 않은 디스크 세부 정보, 마이그레이션된 LIF 수, 실패한 볼륨 이동 작업 등 모든 알림을 노란색으로 표시합니다. 또한 볼륨 이동 작업에 대한 관리자의 개입이 지난 24시간 동안 필요했으며

+
Alerts and Notifications(경고 및 알림) 패널에는 View-all(모두 보기) 링크가 표시되는 범위를 벗어나는 최대 3개의 경고와 알림이 표시됩니다. 모두 보기 링크를 클릭하여 알림 및 알림에 대한 자세한 정보를 볼 수 있습니다.

+
경고 및 알림 패널의 새로 고침 간격은 1분입니다.

* * 클러스터 개요 *
+
거의 용량에 도달한 Aggregate 및 볼륨, 클러스터 또는 노드의 스토리지 효율성, 상위 볼륨의 보호 세부 정보를 표시합니다.

+
용량 탭에는 용량이 거의 표시된 상위 온라인 애그리게이트가 사용된 공간의 내림차순으로 표시됩니다.

+
Capacity(용량) 탭은 사용된 용량 초과 필드에 유효한 값을 입력할 때 사용된 용량이 가장 큰 볼륨 수에 대한 링크를 제공합니다. 또한 클러스터에서 사용 가능한 비활성(콜드) 데이터의 양도 표시됩니다.

+
효율성 탭에는 클러스터 또는 노드의 스토리지 효율성 절약 효과가 표시됩니다. 사용된 총 논리적 공간, 사용된 총 물리적 공간 및 전체 절감 효과를 볼 수 있습니다. 클러스터 또는 특정 노드를 선택하여 스토리지 효율성 절약 효과를 볼 수 있습니다. System Manager 9.5에서 스냅샷 복사본에 사용되는 공간은 사용된 총 논리적 공간, 사용된 총 물리적 공간 및 전체 축소에 대한 값에 _not_포함되어 있습니다. 그러나 System Manager 9.6부터 Snapshot 복사본에 사용되는 공간은 사용되는 총 논리적 공간, 사용된 총 물리적 공간 및 전체 절감 효과에 포함되어 있습니다.

+
클러스터 개요 패널의 새로 고침 간격은 15분입니다.

+
보호 탭에는 정의된 보호 관계가 없는 클러스터 전체 볼륨에 대한 정보가 표시됩니다. 다음 기준을 충족하는 FlexVol 볼륨 및 FlexGroup 볼륨만 표시됩니다.

+
** 볼륨은 RW 볼륨이며 온라인 상태입니다.
** 볼륨이 포함된 애그리게이트는 온라인 상태입니다.
** 볼륨에 보호 관계가 있으며 아직 초기화되지 않았습니다.
Volumes 창으로 이동하여 정의된 보호 관계가 없는 볼륨을 볼 수 있습니다.


+
보호 탭에는 정의된 보호 관계가 없는 볼륨의 수가 가장 많은 5개의 SVM이 표시됩니다.

* * 노드 *
+
클러스터에서 사용 가능한 노드의 수와 이름, HA Pair에 있는 노드의 상태를 그림 형식으로 표시합니다. HA Pair의 노드 상태를 보려면 커서를 노드의 그림 표시 위에 배치해야 합니다.

+
노드 링크를 사용하여 모든 노드에 대한 자세한 정보를 볼 수 있습니다. 그림 표시를 클릭하여 노드 모델과 노드에서 사용할 수 있는 애그리게이트, 스토리지 풀, 쉘프 및 디스크 수를 확인할 수도 있습니다. 노드 관리 링크를 사용하여 노드를 관리할 수 있습니다. HA 쌍 내에서 HA 관리 링크를 사용하여 노드를 관리할 수 있습니다.

+
노드 패널의 새로 고침 간격은 15분입니다.

* * 응용 프로그램 및 개체 *
+
Applications and Objects(응용 프로그램 및 개체) 패널을 사용하여 클러스터의 응용 프로그램, 클라이언트 및 파일에 대한 정보를 표시할 수 있습니다.

+
애플리케이션 탭에는 클러스터의 상위 5개 애플리케이션에 대한 정보가 표시됩니다. IOPS 및 지연 시간(낮은 애플리케이션에서 높은 애플리케이션까지 또는 높은 애플리케이션에서 낮은 애플리케이션까지) 또는 용량(낮은 애플리케이션에서 높은 애플리케이션까지 또는 높은 애플리케이션에서 낮은 애플리케이션까지)을 기준으로 상위 5개 애플리케이션을 볼 수 있습니다.

+
응용 프로그램에 대한 자세한 내용을 보려면 특정 막대 차트를 클릭해야 합니다. 용량에 대한 총 공간, 사용된 공간 및 사용 가능한 공간이 표시되고, IOPS 세부 정보가 IOPS에 표시되며, 지연 시간에 대한 세부 정보가 표시됩니다.

+
세부 정보 보기 * 를 클릭하여 특정 응용 프로그램의 응용 프로그램 창을 열 수 있습니다.

+
Objects 탭에는 클러스터의 상위 5개 활성 클라이언트 및 파일에 대한 정보가 표시됩니다. IOPS 또는 처리량을 기준으로 상위 5개의 활성 클라이언트 및 파일을 볼 수 있습니다.

+
[NOTE]
====
이 정보는 CIFS 및 NFS 프로토콜에 대해서만 표시됩니다.

====
+
응용 프로그램 및 개체 패널의 새로 고침 간격은 1분입니다.

* * 성능 *
+
지연 시간, IOPS 및 처리량을 기준으로 클러스터의 평균 성능 메트릭, 읽기 성능 메트릭 및 쓰기 성능 메트릭을 표시합니다. 평균 성능 메트릭은 기본적으로 표시됩니다. 읽기 또는 쓰기 를 클릭하여 각각 읽기 성능 메트릭 또는 쓰기 성능 메트릭을 볼 수 있습니다. 클러스터 또는 노드의 성능 메트릭을 볼 수 있습니다.

+
ONTAP에서 클러스터 성능에 대한 정보를 검색할 수 없는 경우 해당 그래프를 볼 수 없습니다. 이 경우 System Manager에 특정 오류 메시지가 표시됩니다.

+
성능 패널의 차트에 대한 새로 고침 간격은 15초입니다.





== 대시보드를 사용하여 클러스터 모니터링

System Manager의 대시보드를 사용하면 클러스터의 상태와 성능을 모니터링할 수 있습니다. 또한 대시보드에서 하드웨어 문제와 스토리지 구성 문제도 확인할 수 있습니다.

.단계
. 상태 및 성능 대시보드 패널을 보려면 * 대시보드 * 탭을 클릭하십시오.

