---
permalink: online-help-96-97/reference_svm_dashboard_window.html 
sidebar: sidebar 
keywords: svm, dashboard, detail, online, help 
summary: '대시보드는 SVM(스토리지 가상 시스템) 및 성능에 대한 요약 정보를 제공합니다. 대시보드 창을 사용하여 구성된 프로토콜, 용량 근접한 볼륨 및 성능과 같은 SVM과 관련된 중요 정보를 볼 수 있습니다.' 
---
= System Manager의 SVM 대시보드 창 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)의 대시보드 창에서는 SVM(스토리지 가상 시스템) 및 성능에 대한 누적 정보를 한눈에 확인할 수 있습니다. 대시보드 창을 사용하여 구성된 프로토콜, 용량 근접한 볼륨 및 성능과 같은 SVM과 관련된 중요 정보를 볼 수 있습니다.



== SVM 세부 정보

이 창에는 Protocol Status 패널, Volumes About Capacity 패널, Applications 패널 및 Performance 패널과 같은 다양한 패널을 통해 SVM에 대한 세부 정보가 표시됩니다.

* * 프로토콜 상태 *
+
SVM용으로 구성된 프로토콜의 개요를 제공합니다. 프로토콜 이름을 클릭하여 구성을 볼 수 있습니다.

+
프로토콜이 구성되지 않았거나 SVM에 프로토콜 라이센스를 사용할 수 없는 경우 프로토콜 이름을 클릭하여 프로토콜을 구성하거나 프로토콜 라이센스를 추가할 수 있습니다.

* * 용량이 거의 다 되었습니다 *
+
용량 사용률이 80% 이상인 볼륨에 대한 정보를 즉시 주의 또는 수정 조치가 필요한 표시합니다.

* * 응용 프로그램 *
+
SVM의 상위 5개 애플리케이션에 대한 정보를 표시합니다. 상위 5개 애플리케이션은 IOPS(낮은 애플리케이션에서 높은 애플리케이션까지, 높은 애플리케이션부터 낮은 애플리케이션까지) 또는 용량(낮은 애플리케이션에서 높은 애플리케이션까지, 높은 애플리케이션에서 낮은 애플리케이션까지)을 기준으로 볼 수 있습니다. 응용 프로그램에 대한 자세한 내용을 보려면 특정 막대 차트를 클릭해야 합니다. 용량의 경우, 총 공간, 사용된 공간 및 사용 가능한 공간이 표시되고 IOPS의 경우 IOPS 세부 정보가 표시됩니다. L2/L3 애플리케이션의 경우 지연 시간 메트릭도 표시됩니다.

+
[NOTE]
====
애플리케이션 창에 표시되는 사용된 크기가 CLI에서 사용된 크기와 같지 않습니다.

====
+
세부 정보 보기 * 를 클릭하여 특정 응용 프로그램의 응용 프로그램 창을 열 수 있습니다. SVM을 위한 모든 애플리케이션을 보려면 * 모든 애플리케이션 보기 * 를 클릭하십시오.

+
애플리케이션 패널의 새로 고침 간격은 1분입니다.

* * SVM 성능 *
+
지연 시간, IOPS를 비롯한 SVM의 프로토콜 성능 메트릭을 표시합니다.

+
ONTAP에서 SVM 성능에 대한 정보를 검색할 수 없는 경우 각 그래프를 볼 수 없습니다. 이 경우 System Manager에 특정 오류 메시지가 표시됩니다.

+
SVM 성능 패널의 업데이트 간격은 15초입니다.


