---
permalink: online-help-96-97/reference_luns_window.html 
sidebar: sidebar 
keywords: online, help, lun, management, window, command, button, initiator, portset, group, online, help 
summary: LUN 창을 사용하여 LUN을 생성 및 관리하고 LUN에 대한 정보를 표시할 수 있습니다. 이니시에이터 그룹 및 이니시에이터 ID를 추가, 편집 또는 삭제할 수도 있습니다. 
---
= System Manager의 LUN 창 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 이하에서 사용 가능한 ONTAP System Manager 클래식 의 LUN 창을 사용하여 LUN을 생성 및 관리하고 LUN에 대한 정보를 표시할 수 있습니다. 이니시에이터 그룹 및 이니시에이터 ID를 추가, 편집 또는 삭제할 수도 있습니다.



== LUN Management 탭

이 탭에서는 LUN 설정을 생성, 클론 복제, 삭제, 이동 또는 편집할 수 있습니다. LUN을 스토리지 QoS(서비스 품질) 정책 그룹에 할당할 수도 있습니다.



== 명령 버튼

* * 생성 *
+
LUN 생성 마법사를 엽니다. 이 마법사를 사용하면 LUN을 생성할 수 있습니다.

+
기존 LUN이 없는 AFF 플랫폼의 클러스터에서 FC SAN에 최적화된 LUN 생성 대화 상자가 열리면 하나 이상의 FC SAN에 최적화된 LUN을 설정할 수 있습니다.

* * 클론 *
+
선택한 LUN을 클론 복제할 수 있는 클론 LUN 대화 상자를 엽니다.

* * 편집 *
+
LUN 편집 대화 상자를 엽니다. 이 대화 상자에서 선택한 LUN의 설정을 편집할 수 있습니다.

* * 삭제 *
+
선택한 LUN을 삭제합니다.

* * 상태 *
+
선택한 LUN의 상태를 온라인 또는 오프라인 으로 변경할 수 있습니다.

* * 이동 *
+
선택한 LUN을 동일한 SVM(스토리지 가상 머신) 내의 새 볼륨 또는 기존 볼륨 또는 qtree로 이동할 수 있는 LUN 이동 대화 상자를 엽니다.

* * 스토리지 QoS *
+
하나 이상의 LUN을 새 정책 그룹 또는 기존 정책 그룹에 할당할 수 있는 서비스 품질 세부 정보 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== LUN 목록

* * 이름 *
+
LUN의 이름을 표시합니다.

* * SVM *
+
LUN이 생성되는 SVM(스토리지 가상 머신)의 이름을 표시합니다.

* * 컨테이너 경로 *
+
LUN이 포함된 파일 시스템(볼륨 또는 qtree)의 이름을 표시합니다.

* * 공간 예약 *
+
공간 예약을 활성화하거나 비활성화할지 여부를 지정합니다.

* * 사용 가능한 크기 *
+
LUN에서 사용 가능한 공간을 표시합니다.

* * 총 크기 *
+
LUN의 총 공간을 표시합니다.

* * % 사용 *
+
사용된 총 공간(백분율)을 표시합니다.

* * 유형 *
+
LUN 유형을 지정합니다.

* * 상태 *
+
LUN의 상태를 지정합니다.

* * 정책 그룹 *
+
LUN이 할당된 스토리지 QoS 정책 그룹의 이름을 표시합니다. 기본적으로 이 열은 숨겨져 있습니다.

* * 응용 프로그램 *
+
LUN에 할당된 애플리케이션의 이름을 표시합니다.

* * 설명 *
+
LUN에 대한 설명을 표시합니다.





== 세부 정보 영역

LUN 목록 아래의 영역에는 선택한 LUN과 관련된 세부 정보가 표시됩니다.

* * 세부 정보 탭 *
+
LUN 일련 번호, LUN이 클론인지 여부, LUN 설명, LUN이 할당되는 정책 그룹, 정책 그룹의 최소 처리량, 정책 그룹의 최대 처리량, LUN 이동 작업에 대한 세부 정보 등을 표시합니다. LUN에 할당된 애플리케이션을 나타냅니다. 또한 선택한 LUN과 연결된 이니시에이터 그룹 및 이니시에이터에 대한 세부 정보를 볼 수 있습니다.

* * 성능 탭 *
+
데이터 속도, IOPS, 응답 시간을 비롯한 LUN의 성능 메트릭 그래프를 표시합니다.

+
클라이언트 시간대 또는 클러스터 시간대를 변경하면 성능 메트릭 그래프에 영향을 줍니다. 브라우저를 새로 고쳐 업데이트된 그래프를 봅니다.





== 이니시에이터 그룹 탭

이 탭에서는 이니시에이터 그룹 및 이니시에이터 ID의 설정을 생성, 삭제 또는 편집할 수 있습니다.



== 명령 버튼

* * 생성 *
+
이니시에이터 그룹 생성 대화 상자를 엽니다. 이 대화 상자에서 이니시에이터 그룹을 생성하여 특정 LUN에 대한 호스트 액세스를 제어할 수 있습니다.

* * 편집 *
+
선택한 이니시에이터 그룹의 설정을 편집할 수 있는 이니시에이터 그룹 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 이니시에이터 그룹을 삭제합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 이니시에이터 그룹 목록

* * 이름 *
+
이니시에이터 그룹의 이름을 표시합니다.

* * 유형 *
+
이니시에이터 그룹에서 지원하는 프로토콜의 유형을 지정합니다. 지원되는 프로토콜은 iSCSI, FC/FCoE 또는 혼합(iSCSI 및 FC/FCoE)입니다.

* * 운영 체제 *
+
이니시에이터 그룹의 운영 체제를 지정합니다.

* * 포트 세트 *
+
이니시에이터 그룹과 연결된 를 표시합니다.

* * 이니시에이터 수 *
+
이니시에이터 그룹에 추가된 이니시에이터 수를 표시합니다.





== 세부 정보 영역

이니시에이터 그룹 목록 아래의 영역에는 선택한 이니시에이터 그룹에 추가된 이니시에이터 및 이니시에이터 그룹에 매핑된 LUN에 대한 세부 정보가 표시됩니다.



== Portsets 탭

이 탭에서는 포트 세트의 설정을 생성, 삭제 또는 편집할 수 있습니다.



== 명령 버튼

* * 생성 *
+
LUN에 대한 액세스를 제한하는 포트 세트를 생성할 수 있는 포트 세트 생성 대화 상자를 엽니다.

* * 편집 *
+
포트 세트 편집 대화 상자를 엽니다. 이 대화 상자에서 포트셋 와 연결할 네트워크 인터페이스를 선택할 수 있습니다.

* * 삭제 *
+
선택한 포트셋 삭제

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== Portsets 목록

* * Portset 이름 *
+
포트셋 이름을 표시합니다.

* * 유형 *
+
포트셋 가 지원하는 프로토콜 유형을 지정합니다. 지원되는 프로토콜은 iSCSI, FC/FCoE 또는 혼합(iSCSI 및 FC/FCoE)입니다.

* * 인터페이스 수 *
+
포트셋 관련 네트워크 인터페이스 수를 표시합니다.

* * 이니시에이터 그룹 수 *
+
포트셋 관련 이니시에이터 그룹의 수를 표시합니다.





== 세부 정보 영역

Portsets 목록 아래의 영역에는 선택한 포트셋 관련 네트워크 인터페이스 및 이니시에이터 그룹에 대한 세부 정보가 표시됩니다.

* 관련 정보 *

xref:task_creating_luns.adoc[LUN 생성 중]

xref:task_deleting_luns.adoc[LUN을 삭제하는 중입니다]

xref:task_creating_initiator_groups.adoc[이니시에이터 그룹을 생성하는 중입니다]

xref:task_editing_luns.adoc[LUN 편집]

xref:task_editing_initiator_groups.adoc[이니시에이터 그룹 편집]

xref:task_editing_initiators.adoc[이니시에이터 편집]

xref:task_bringing_luns_online.adoc[LUN을 온라인 상태로 전환하는 중입니다]

xref:task_taking_luns_offline.adoc[LUN을 오프라인 상태로 전환하는 중입니다]

xref:task_cloning_luns.adoc[LUN 클론 복제]
