---
permalink: online-help-96-97/reference_cifs_window.html 
sidebar: sidebar 
keywords: cifs, window, configuration, tab, domain, symlink, branchcache, online, help 
summary: CIFS 창을 사용하여 CIFS 서버를 구성하고, 도메인 컨트롤러를 관리하고, 심볼 UNIX 매핑을 관리하고, BranchCache를 구성할 수 있습니다. 
---
= System Manager의 CIFS 창 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager(ONTAP 9.7 및 이전 버전에서 사용 가능)에서 CIFS 창을 사용하여 CIFS 서버를 구성하고, 도메인 컨트롤러를 관리하고, 기호 UNIX 매핑을 관리하고, BranchCache를 구성할 수 있습니다.



== Configuration(구성) 탭

Configuration 탭에서는 CIFS 서버를 생성하고 관리할 수 있습니다.

* * 서버 *
+
CIFS 서버의 상태, 서버 이름, 인증 모드, Active Directory 도메인의 이름 및 SMB 다중 채널 상태를 지정합니다.

* * 홈 디렉토리 *
+
홈 디렉토리 경로 및 PC 사용자 이름이 홈 디렉토리 항목에 매핑되는 방식을 결정하는 스타일을 지정합니다.

* * 명령 버튼 *
+
** 설정
+
CIFS 설정 마법사를 엽니다. 이 마법사를 사용하면 SVM(스토리지 가상 머신)에서 CIFS를 설정할 수 있습니다.

** 옵션
+
SMB 3.0 서명을 설정 또는 해제하고, SMB 3.0 암호화를 설정 또는 해제하고, WINS(Windows Internet Name Service) 서버를 추가할 수 있는 CIFS 옵션 대화 상자를 표시합니다.

+
SMB 서명은 CIFS 서버와 클라이언트 간의 네트워크 트래픽이 손상되지 않도록 합니다.

** 삭제
+
CIFS 서버를 삭제할 수 있습니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.







== 도메인 탭

도메인 탭에서는 CIFS 도메인 컨트롤러를 확인 및 재설정하고 기본 도메인 컨트롤러를 추가 또는 삭제할 수 있습니다. 이 탭을 사용하여 CIFS 그룹 정책 구성을 관리할 수도 있습니다.

* 서버 *
+
CIFS 지원 SVM에서 검색된 인증 서버 및 기본 도메인 컨트롤러에 대한 정보를 표시합니다.

+
또한 검색된 서버에 대한 정보를 재설정하거나, 기본 도메인 컨트롤러를 추가하거나, 도메인 컨트롤러를 삭제하거나, 도메인 컨트롤러 목록을 새로 고칠 수 있습니다.

* * 그룹 정책 *
+
CIFS 서버에서 그룹 정책 구성을 확인, 설정 또는 해제할 수 있습니다. 정책 상태가 변경된 경우 그룹 정책을 다시 로드할 수도 있습니다.





== Symlink 탭

symlinks 탭에서는 CIFS 사용자에 대한 UNIX 심볼 링크 매핑을 관리할 수 있습니다.

* * 경로 매핑 *
+
CIFS에 대한 심볼 링크 매핑 목록을 표시합니다.

* * 명령 버튼 *
+
** 생성
+
UNIX 심볼 링크 매핑을 만들 수 있는 새 symlink 경로 매핑 만들기 대화 상자를 엽니다.

** 편집
+
CIFS 공유 및 경로를 수정할 수 있는 symlink 경로 매핑 편집 대화 상자를 엽니다.

** 삭제
+
심볼 링크 매핑을 삭제할 수 있습니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.







== BranchCache 탭

BranchCache 탭을 사용하면 CIFS 지원 SVM에서 BranchCache 설정을 설정 및 관리할 수 있습니다.

BranchCache 서비스 상태, 해시 스토어의 경로, 해시 스토어의 크기, 운영 모드, 서버 키 및 BranchCache 버전을 볼 수 있습니다.

* * 명령 버튼 *
+
** 설정
+
CIFS 서버에 대한 BranchCache를 구성할 수 있는 BranchCache 설정 대화 상자를 엽니다.

** 편집
+
BranchCache 구성의 속성을 수정할 수 있는 BranchCache 설정 수정 대화 상자를 엽니다.

** 삭제
+
BranchCache 구성을 삭제할 수 있습니다.

** 새로 고침
+
창에서 정보를 업데이트합니다.





* 관련 정보 *

xref:task_setting_up_cifs.adoc[CIFS를 설정하는 중입니다]

xref:task_editing_cifs_general_properties.adoc[CIFS에 대한 일반 속성을 편집합니다]

xref:task_adding_home_directory_paths.adoc[홈 디렉토리 경로를 추가하는 중입니다]

xref:task_deleting_home_directory_paths.adoc[홈 디렉토리 경로를 삭제하는 중입니다]

xref:task_resetting_cifs_domain_controllers.adoc[CIFS 도메인 컨트롤러를 재설정하는 중입니다]
