---
permalink: online-help-96-97/reference_svm_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, window, svm, online, help, command, button, peer 
summary: '스토리지 가상 시스템 창을 사용하여 SVM(스토리지 가상 머신)을 관리하고 이러한 가상 머신에 대한 정보를 표시할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이전의 스토리지 가상 시스템 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manger Classic(ONTAP 9.7 이하에서 사용 가능)에서 스토리지 가상 머신 창을 사용하여 SVM(스토리지 가상 머신)을 관리하고 해당 정보를 표시할 수 있습니다.

System Manager를 사용하여 DR(재해 복구)용으로 구성된 SVM은 관리(생성, 삭제, 시작 또는 중지)할 수 없습니다. 또한 애플리케이션 인터페이스에서 재해 복구를 위해 구성된 SVM과 연관된 스토리지 객체를 볼 수 없습니다.



== 명령 버튼

* * 생성 *
+
SVM(Storage Virtual Machine) 설정 마법사를 열어서 새 SVM을 생성할 수 있습니다.

* * 편집 *
+
선택한 SVM의 이름 서비스 스위치, 이름 매핑 스위치, 애그리게이트 목록과 같은 속성을 수정할 수 있는 스토리지 가상 시스템 편집 대화 상자를 엽니다.

* * 삭제 *
+
선택한 SVM을 삭제합니다.

* * 시작 *
+
선택한 SVM을 시작합니다.

* * 중지 *
+
선택한 SVM을 중지합니다.

* * SVM 설정 *
+
선택한 SVM에 대한 스토리지, 정책 및 구성을 관리합니다.

* * 보호 작업 *
+
에서는 다음 옵션을 제공합니다.

+
** * 초기화 *
+
SVM 관계를 초기화하여 소스 SVM에서 타겟 SVM으로 기본 전송을 수행할 수 있습니다.

** * 업데이트 *
+
소스 SVM에서 타겟 SVM으로 데이터를 업데이트할 수 있습니다.

** * 대상 SVM 활성화 *
+
대상 SVM을 활성화할 수 있습니다.

** * 소스 SVM에서 재동기화 * 를 참조하십시오
+
끊어진 관계의 재동기화를 시작할 수 있습니다.

** * 대상 SVM에서 재동기화(역재동기화) *
+
대상 SVM에서 소스 SVM으로 관계를 재동기화할 수 있습니다.

** * 소스 SVM 재활성화 *
+
소스 SVM을 다시 활성화할 수 있습니다.



* * 새로 고침 *
+
창에서 정보를 업데이트합니다.

* * 추적 파일 액세스 *
+
선택한 SVM에서 지정된 사용자 이름으로 파일 또는 공유의 액세스 가능성을 추적할 수 있습니다.





== SVM 목록

SVM 목록에는 각 SVM의 이름과 허용되는 프로토콜이 표시됩니다.

System Manager를 사용하면 데이터 SVM만 볼 수 있습니다.

* * 이름 *
+
SVM의 이름을 표시합니다.

* * 시/도 *
+
실행 중, 시작 중, 중지 또는 중지 등의 SVM 상태를 표시합니다.

* * 하위 유형 *
+
SVM의 하위 유형을 표시하며, 이는 다음 중 하나입니다.

+
** 기본값
+
SVM이 데이터 지원 SVM으로 지정하도록 지정합니다.

** DP - 대상
+
SVM이 재해 복구용으로 구성되도록 지정합니다.

** 동기화 소스
+
SVM이 MetroCluster 구성의 운영 사이트에 있다고 지정합니다.

** SYNC - 대상입니다
+
SVM이 MetroCluster 구성의 정상 작동하는 사이트에 있다고 지정합니다.



* * 허용된 프로토콜 *
+
각 SVM에 CIFS, NFS와 같은 허용된 프로토콜을 표시합니다.

* IPspace *
+
관련 SVM의 IPspace를 표시합니다.

* * 볼륨 유형 *
+
각 SVM에 FlexVol 볼륨과 같은 허용되는 볼륨 유형을 표시합니다.

* * 보호됨 *
+
SVM이 보호되는지 여부를 표시합니다.

* * 구성 상태 *
+
SVM의 구성 상태가 잠겨 있는지 여부를 표시합니다.





== 세부 정보 영역

SVM 목록 아래의 영역에는 허용되는 볼륨 유형, 언어, 스냅샷 정책과 같은 선택한 SVM에 대한 자세한 정보가 표시됩니다.

이 SVM에 허용되는 프로토콜을 구성할 수도 있습니다. SVM을 생성하는 동안 프로토콜을 구성하지 않은 경우 프로토콜 링크를 클릭하여 프로토콜을 구성할 수 있습니다.

System Manager를 사용하여 재해 복구용으로 구성된 anSVM용 프로토콜을 구성할 수는 없습니다.

[NOTE]
====
SVM에 대해 FCP 서비스가 이미 시작된 경우 FC/FCoE 링크를 클릭하면 네트워크 인터페이스 창이 열립니다.

====
색상은 프로토콜 구성의 상태를 나타냅니다.

|===
| 상태 | 설명 


 a| 
녹색
 a| 
LIF가 존재하며 프로토콜이 구성됩니다. 링크를 클릭하여 구성 세부 정보를 볼 수 있습니다.

[NOTE]
====
구성이 부분적으로 완료되었을 수 있습니다. 그러나 서비스가 실행 중입니다. LIF를 생성하고 네트워크 인터페이스 창에서 구성을 완료할 수 있습니다.

====


 a| 
노란색
 a| 
다음 중 하나를 나타냅니다.

* LIF가 존재합니다. 서비스가 생성되었지만 실행되고 있지 않습니다.
* LIF가 존재합니다. 서비스가 생성되지 않았습니다.
* 서비스가 생성됩니다. LIF가 없습니다.




 a| 
회색
 a| 
프로토콜이 구성되지 않았습니다. 프로토콜 링크를 클릭하여 프로토콜을 구성할 수 있습니다.



 a| 
회색 테두리
 a| 
프로토콜 라이센스가 만료되었거나 누락되었습니다. 프로토콜 링크를 클릭하여 라이센스 페이지에 라이센스를 추가할 수 있습니다.

|===
관리 인터페이스를 추가하고 보호 관계, 보호 정책, NIS 도메인 등의 세부 정보를 볼 수도 있습니다.

Details * 영역에는 SVM용 Public SSL 인증서를 볼 수 있는 링크도 포함되어 있습니다. 이 링크를 클릭하면 다음 작업을 수행할 수 있습니다.

* 인증서 세부 정보, 일련 번호, 시작 날짜 및 만료 날짜를 확인합니다.
* 인증서를 클립보드에 복사합니다.
* 인증서 세부 정보를 이메일로 보냅니다.




== 피어 스토리지 가상 시스템 영역

선택한 SVM에서 피어링된 SVM 목록과 피어 관계를 사용 중인 애플리케이션에 대한 세부 정보를 표시합니다.
