---
permalink: online-help-96-97/reference_application_provisioning_settings.html 
sidebar: sidebar 
keywords: application, provisioning, setting, microsoft, sql, database, applications, san, mongodb, oracle, host, access, initiator, sap, hana, smb 
summary: '데이터베이스, 서버 또는 가상 데스크톱에 대한 기본 템플릿 또는 고급 템플릿을 설정할 때는 System Manager에 세부 정보를 제공해야 합니다. 응용 프로그램을 프로비저닝한 후에는 세부 정보를 편집하고 크기 조정(크기 증가만)을 지정할 수 있습니다. 이 섹션에서는 각 템플릿의 필드에 대해 설명합니다. 특정 애플리케이션의 설정을 프로비저닝하거나 편집하는 데 필요한 필드만 표시됩니다.' 
---
= System Manager의 애플리케이션 프로비저닝 설정 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)에서 데이터베이스, 서버 또는 가상 데스크톱에 대한 기본 템플릿 또는 향상된 템플릿을 설정할 때 세부 정보를 제공해야 합니다. 응용 프로그램을 프로비저닝한 후에는 세부 정보를 편집하고 크기 조정(크기 증가만)을 지정할 수 있습니다. 이 섹션에서는 각 템플릿의 필드에 대해 설명합니다. 특정 애플리케이션의 설정을 프로비저닝하거나 편집하는 데 필요한 필드만 표시됩니다.



== SAN 기반 Microsoft SQL 데이터베이스 애플리케이션에 대한 세부 정보

SAN을 통해 Microsoft SQL 데이터베이스 응용 프로그램을 프로비저닝하거나 설정을 편집하려면 다음 정보를 입력합니다.

* * 데이터베이스 이름 *
+
필수: 구성 중인 데이터베이스의 이름입니다. 이 문자열은 각 데이터베이스의 스토리지를 프로비저닝할 때 접두사로 사용됩니다.

* * 데이터베이스 크기 *
+
필수: 데이터베이스 크기(MB, GB, TB 또는 PB 단위).

* * 데이터베이스용 ONTAP 서비스 레벨 *
+
필수: 데이터베이스의 서비스 수준입니다.

* * 로그 크기 *
+
필수: 데이터베이스 로그의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * 로그*용 ONTAP 서비스 수준
+
필수: 로그의 서비스 수준입니다.

* * Tempdb *
+
필수: MB, GB, TB 또는 PB 단위의 tempdb 데이터베이스 크기입니다.

* * 프로토콜 내보내기 *
+
필수: 내보내기 프로토콜은 SAN입니다

* * SQL Server의 서버 코어 수 *
+
데이터베이스 서버의 CPU 코어 수를 2씩 증가시킵니다.

* * SPAN HA 컨트롤러 노드 *
+
노드의 고가용성 쌍에서 스토리지 객체를 생성해야 하는지 여부를 지정합니다.





== SAP HANA 데이터베이스 프로비저닝에 대한 세부 정보

* * 액티브 SAP HANA 노드 *
+
활성 SAP HANA 노드 수 최대 노드 수는 16개입니다.

* * HANA 노드당 메모리 크기 *
+
단일 SAP HANA 노드의 메모리 크기입니다.

* * HANA 노드당 데이터 디스크 크기 *
+
각 노드의 데이터 디스크 크기입니다.

+
[NOTE]
====
0으로 설정하면 위의 메모리 크기 필드가 데이터 영역의 크기를 계산하는 데 사용됩니다.

====




== SMB를 통한 Microsoft SQL 데이터베이스 애플리케이션에 대한 세부 정보

SMB를 통해 Microsoft SQL 데이터베이스 응용 프로그램을 프로비저닝하거나 설정을 편집하려면 다음 정보를 입력합니다.

* * 데이터베이스 이름 *
+
필수: 구성 중인 데이터베이스의 이름입니다. 이 문자열은 각 데이터베이스의 스토리지를 프로비저닝할 때 접두사로 사용됩니다.

* * 데이터베이스 크기 *
+
필수: 데이터베이스 크기(MB, GB, TB 또는 PB 단위).

* * 데이터베이스 서비스 수준 *
+
필수: 데이터베이스의 서비스 수준입니다.

* * SQL Server의 서버 코어 수 *
+
데이터베이스 서버의 CPU 코어 수를 2씩 증가시킵니다.

* * 로그 크기 *
+
필수: 데이터베이스 로그의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * 로그 서비스 수준 *
+
필수: 로그의 서비스 수준입니다.

* * Tempdb * 에 대한 프로비저닝
+
필수: tempdb가 프로비저닝되었는지 여부를 나타냅니다.

* * 프로토콜 내보내기 *
+
필수: 내보내기 프로토콜은 SMB 또는 SAN입니다.

+
SVM용으로 구성된 CIFS에 대해 클러스터에 라이센스가 부여된 경우에만 SMB를 선택할 수 있습니다.

* * 사용자에게 액세스 권한 부여 *
+
필수: 애플리케이션의 액세스 레벨.

* * 권한 *
+
필수: 응용 프로그램의 사용 권한 수준입니다.





== SQL Server 계정에 대한 세부 정보입니다

SQL Server 계정에 대한 모든 권한을 제공하려면 다음 정보를 입력합니다.

[NOTE]
====
설치 계정이 허용됩니다 `SeSecurityPrivilege`.

====
* * SQL Server 서비스 계정 *
+
필수: 기존 도메인 계정입니다. 로 지정하십시오 `domain\user`.

* * SQL Server 에이전트 서비스 계정 *
+
선택 사항: 이 도메인 계정입니다. SQL Server 에이전트 서비스가 구성된 경우 domain\user 형식으로 지정하십시오.





== Oracle 데이터베이스 애플리케이션에 대한 세부 정보

Oracle 데이터베이스 애플리케이션을 프로비저닝하거나 설정을 편집하려면 다음 정보를 입력합니다.

* * 데이터베이스 이름 *
+
필수: 구성 중인 데이터베이스의 이름입니다. 이 문자열은 각 데이터베이스의 스토리지를 프로비저닝할 때 접두사로 사용됩니다.

* * 데이터 파일 크기 *
+
필수: 데이터 파일의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * 데이터 파일의 ONTAP 서비스 수준 *
+
필수: 데이터 파일의 서비스 레벨입니다.

* * Redo 로그 그룹 크기 *
+
필수: redo 로그 그룹의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * Redo 로그 그룹*에 대한 ONTAP 서비스 수준
+
필수: redo 로그 그룹의 서비스 수준입니다.

* * 보관 로그 크기 *
+
필수: 아카이브 로그의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * 아카이브 로그의 ONTAP 서비스 수준 *
+
필수: 아카이브 그룹의 서비스 수준입니다.

* * 프로토콜 내보내기 *
+
내보내기 프로토콜: SAN 또는 NFS

* * 이니시에이터 *
+
이니시에이터 그룹에 포함된 이니시에이터(WWPN 또는 IQN)의 쉼표로 구분된 목록입니다.

* * 호스트에 대한 액세스 권한 부여 *
+
응용 프로그램에 대한 액세스 권한을 부여할 호스트 이름입니다.





== MongoDB 애플리케이션 세부 정보

다음 정보를 입력하여 MongoDB 애플리케이션을 프로비저닝하거나 설정을 편집합니다.

* * 데이터베이스 이름 *
+
필수: 구성 중인 데이터베이스의 이름입니다. 이 문자열은 각 데이터베이스의 스토리지를 프로비저닝할 때 접두사로 사용됩니다.

* * 데이터 세트 크기 *
+
필수: 데이터 파일의 크기(MB, GB, TB 또는 PB 단위)입니다.

* * 데이터 세트에 대한 ONTAP 서비스 수준 *
+
필수: 데이터 파일의 서비스 레벨입니다.

* * 복제 계수 *
+
필수: 복제 수입니다.

* * 운영 호스트 매핑 *
+
필수: 운영 호스트의 이름입니다.

* * 복제본 호스트 1에 대한 매핑 *
+
필수: 첫 번째 호스트 복제본의 이름입니다.

* * 복제 호스트 2에 대한 매핑 *
+
필수: 두 번째 호스트 복제본의 이름입니다.





== 가상 데스크톱 응용 프로그램에 대한 세부 정보

가상 데스크톱 인프라(VDI)를 프로비저닝하거나 설정을 편집하려면 다음 정보를 입력합니다.

* * 평균 데스크톱 크기(SAN 가상 데스크톱에 사용됨) *
+
이 크기는 각 볼륨의 씬 프로비저닝 크기를 MB, GB, TB 또는 PB 단위로 결정하는 데 사용됩니다.

* * 데스크탑 크기 *
+
MB, GB, TB 또는 PB 단위로 프로비저닝해야 하는 볼륨의 크기를 결정하는 데 사용됩니다.

* * 데스크탑용 ONTAP 서비스 수준 *
+
필수: 데이터 파일의 서비스 레벨입니다.

* * 데스크탑 수 *
+
이 번호는 생성된 볼륨의 수를 결정하는 데 사용됩니다.

+
[NOTE]
====
이 방법은 가상 시스템을 프로비저닝하는 데 사용되지 않습니다.

====
* * 하이퍼바이저 선택 *
+
이러한 볼륨에 사용되는 하이퍼바이저이며 하이퍼바이저는 올바른 데이터 저장소 프로토콜을 결정합니다. 옵션은 VMware, Hyper-V 또는 XenServer/KVM입니다.

* * 데스크탑 지속성 *
+
데스크톱이 영구적 또는 비영구인지 여부를 결정합니다. 데스크톱 지속성을 선택하면 스냅샷 일정 및 사후 처리 중복제거 정책과 같은 볼륨의 기본값이 설정됩니다. 모든 볼륨에 대해 인라인 효율성이 기본적으로 활성화됩니다.

+
[NOTE]
====
이러한 정책은 프로비저닝 후 수동으로 수정할 수 있습니다.

====
* * 데이터 저장소 접두사 *
+
입력한 값은 데이터 저장소의 이름과 해당하는 경우 내보내기 정책 이름 또는 공유 이름을 생성하는 데 사용됩니다.

* * 프로토콜 내보내기 *
+
내보내기 프로토콜: SAN 또는 NFS

* * 이니시에이터 *
+
이니시에이터 그룹에 포함된 이니시에이터(WWPN 또는 IQN)의 쉼표로 구분된 목록입니다.

* * 호스트에 대한 액세스 권한 부여 *
+
응용 프로그램에 대한 액세스 권한을 부여할 호스트 이름입니다.





== 이니시에이터 세부 정보

이니시에이터를 설정하려면 다음 정보를 입력합니다.

* * 이니시에이터 그룹 *
+
기존 그룹을 선택하거나 새 그룹을 만들 수 있습니다.

* * 이니시에이터 그룹 이름 *
+
새 이니시에이터 그룹의 이름입니다.

* * 이니시에이터 *
+
이니시에이터 그룹에 포함된 이니시에이터(WWPN 또는 IQN)의 쉼표로 구분된 목록입니다.



다음 필드는 _ SAP HANA_Provisioning에만 적용됩니다.

* * 초기자 OS 유형 *
+
새 이니시에이터 그룹의 운영 체제 유형입니다.

* * FCP Portset *
+
이니시에이터 그룹이 바인딩된 FCP





== 호스트 액세스 구성

볼륨에 대한 호스트 액세스를 구성하려면 다음 정보를 입력합니다.

* * 볼륨 내보내기 구성 *
+
생성 중에 볼륨에 적용할 엑스포트 정책을 선택합니다. 옵션은 다음과 같습니다.

+
** 모두 허용
+
이 옵션은 모든 클라이언트에 대한 읽기-쓰기 액세스를 허용하는 내보내기 규칙이 생성됨을 의미합니다.

** 사용자 지정 정책을 생성합니다
+
이 옵션을 사용하면 읽기-쓰기 액세스를 수신할 호스트 IP 주소 목록을 지정할 수 있습니다.



+
[NOTE]
====
나중에 System Manager 워크플로우를 사용하여 볼륨 엑스포트 정책을 수정할 수 있습니다.

====
* * 호스트 IP 주소 *
+
쉼표로 구분된 IP 주소 목록입니다.

+
[NOTE]
====
NFS 기반 시스템의 경우 데이터 저장소 접두사를 사용하여 새 내보내기 정책이 생성되고 IP 목록에 대한 액세스 권한을 부여하기 위해 해당 접두사에 규칙이 생성됩니다.

====




== 애플리케이션 세부 정보

응용 프로그램이 추가되면 응용 프로그램 세부 정보 창의 * 개요 * 탭에서 구성 설정을 볼 수 있습니다. 설정된 애플리케이션 유형에 따라 NFS 또는 CIFS 액세스 및 권한 등의 기타 세부 정보가 표시됩니다.

* * 유형 *
+
생성된 일반 애플리케이션, 데이터베이스 또는 가상 인프라의 유형입니다.

* * SVM *
+
애플리케이션이 생성된 서버 가상 머신의 이름입니다.

* * 크기 *
+
볼륨의 총 크기입니다.

* * 이용 가능 *
+
볼륨에서 현재 사용 가능한 공간의 크기입니다.

* * 보호 *
+
구성된 데이터 보호 유형입니다.



사용된 공간, IOPS 및 지연 시간에 대한 성능 세부 정보를 보려면 * Components * 및 * Volumes * 창을 확장할 수 있습니다.

[NOTE]
====
구성 요소 창에 표시되는 사용된 크기가 CLI에 표시되는 사용된 크기와 다릅니다.

====