---
permalink: online-help-96-97/reference_disks_window.html 
sidebar: sidebar 
keywords: command, button, disk, window, inventory, detail, online, help 
summary: 디스크 창을 사용하여 스토리지 시스템의 모든 디스크를 볼 수 있습니다. 
---
= System Manager의 디스크 창 - ONTAP 9.7 이하
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서는 사용할 수 있음)의 디스크 창을 사용하여 스토리지 시스템의 모든 디스크를 볼 수 있습니다.



== 명령 버튼

* * 배정 *
+
디스크 소유권을 노드에 할당하거나 다시 할당합니다.

+
이 버튼은 선택한 디스크의 컨테이너 유형이 할당되지 않았거나 스페어가 있거나 공유된 경우에만 활성화됩니다.

* * 예비 부품 없음*
+
모든 데이터를 지우고 스페어 디스크 및 어레이 LUN을 포맷합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 탭



== 요약

스페어 디스크 및 할당된 디스크의 크기를 비롯하여 클러스터의 디스크에 대한 자세한 정보를 표시합니다. 이 탭에는 HDD의 스페어 디스크, 애그리게이트 및 루트 애그리게이트에 대한 정보와 스페어 디스크, 스토리지 풀의 디스크, 애그리게이트, Flash Pool 애그리게이트, 캐시 디스크의 루트 애그리게이트(SSD)에 대한 정보도 그래픽으로 표시됩니다.

All-Flash 최적화 퍼스낼리티가 있는 시스템에서는 HDD 패널이 표시되지 않습니다.

세부 정보 패널은 파티션되고 분할되지 않은 스페어 디스크(디스크 유형, 노드, 디스크 크기, RPM, 체크섬, 사용 가능한 디스크 수 및 여유 용량), 표 형식.



== 인벤토리

* * 이름 *
+
디스크 이름을 표시합니다.

* * 컨테이너 유형 *
+
디스크가 사용되는 용도를 표시합니다. 가능한 값은 집계, 파손, 외부, 레이블 유지 관리, 유지 관리, 공유, 스페어, 할당되지 않음, 볼륨, 알 수 없음, 지원되지 않습니다.

* * 파티션 유형 *
+
디스크의 파티션 유형을 표시합니다.

* * 노드 이름 *
+
Aggregate가 포함된 노드의 이름을 표시합니다.

+
이 필드는 클러스터 수준에서만 사용할 수 있습니다.

* * 홈 소유자 *
+
이 디스크가 할당된 홈 노드의 이름을 표시합니다.

* * 현재 소유자 *
+
현재 이 디스크를 소유하고 있는 노드의 이름을 표시합니다.

* * 루트 소유자 *
+
현재 이 디스크의 루트 파티션을 소유하고 있는 노드의 이름을 표시합니다.

* * 데이터 소유자 *
+
현재 이 디스크의 데이터 파티션을 소유하고 있는 노드의 이름을 표시합니다.

* * Data1 소유자 *
+
현재 디스크의 data1 파티션을 소유하고 있는 노드의 이름을 표시합니다.

* * Data2 소유자 *
+
디스크의 data2 파티션을 현재 소유하고 있는 노드의 이름을 표시합니다.

* * 스토리지 풀 *
+
디스크가 연결된 스토리지 풀의 이름을 표시합니다.

* * 유형 *
+
디스크 유형을 표시합니다.

* * 펌웨어 버전 *
+
디스크의 펌웨어 버전을 표시합니다.

* * 모델 *
+
디스크의 모델을 표시합니다.

* RPM *
+
옵션을 선택하면 디스크 드라이브의 유효 속도가 표시됩니다 `raid.mix.hdd.rpm.capacity` 가 활성화되고 옵션을 선택하면 디스크 드라이브의 실제 속도가 표시됩니다 `raid.mix.hdd.rpm.capacity` 이(가) 비활성화됩니다.

+
이 필드는 SSD에 적용되지 않습니다.

* * 유효 크기 *
+
디스크에서 사용 가능한 공간을 표시합니다.

* * 물리적 공간 *
+
디스크의 총 물리적 공간을 표시합니다.

* * 쉘프 *
+
물리 디스크가 있는 쉘프를 표시합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 베이 *
+
물리적 디스크의 쉘프 내에 있는 베이를 표시합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 풀 *
+
선택한 디스크가 할당된 풀의 이름을 표시합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 체크섬 *
+
체크섬의 유형을 표시합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 캐리어 ID *
+
지정된 다중 디스크 캐리어 내에 있는 디스크에 대한 정보를 지정합니다. ID는 64비트 값입니다.

+
이 필드는 기본적으로 숨겨져 있습니다.





== 재고 세부 정보 영역

인벤토리 탭 아래의 영역에는 집계 또는 볼륨(해당하는 경우), 공급업체 ID, 제로화 상태(백분율), 디스크 일련 번호, 디스크 고장 시 오류 세부 정보 등 선택한 디스크에 대한 자세한 정보가 표시됩니다. 공유 디스크의 경우 Inventory details 영역에 루트 및 비루트 애그리게이트를 포함한 모든 애그리게이트의 이름이 표시됩니다.

* 관련 정보 *

xref:task_viewing_disk_information.adoc[디스크 정보 보기]
