---
permalink: online-help-96-97/reference_cluster_update_window.html 
sidebar: sidebar 
keywords: online, help, cluster, update, window, tab, update, command, button, history, tab 
summary: 클러스터 업데이트 창을 사용하여 자동화된 클러스터 업데이트를 중단 없이 수행하거나 단일 노드 클러스터를 중단 없이 업데이트할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하가 포함된 클러스터 업데이트 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 업데이트 창을 사용하여 자동화된 클러스터 업데이트를 중단 없이 수행하거나 ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)로 단일 노드 클러스터를 중단 없이 업데이트할 수 있습니다.



== 탭

* * 클러스터 업데이트 *
+
자동화된 클러스터 업데이트를 중단 없이 수행하거나 단일 노드 클러스터를 중단 없이 업데이트할 수 있습니다.

* * 기록 업데이트 *
+
이전 클러스터 업데이트의 세부 정보를 표시합니다.





== Cluster Update 탭

클러스터 업데이트 탭을 사용하면 중단 없이 자동화된 클러스터 업데이트를 수행하거나 단일 노드 클러스터를 중단 없이 업데이트할 수 있습니다.



== 명령 버튼

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.

* * 를 선택합니다
+
업데이트할 소프트웨어 이미지의 버전을 선택할 수 있습니다.

+
** 클러스터 버전 세부 정보: 사용 중인 현재 클러스터 버전과 노드 또는 고가용성(HA) 쌍의 버전 세부 정보를 표시합니다.
** 사용 가능한 소프트웨어 이미지: 업데이트할 기존 소프트웨어 이미지를 선택할 수 있습니다.
+
또는 NetApp Support 사이트에서 소프트웨어 이미지를 다운로드하고 업데이트 이미지를 추가할 수 있습니다.



* * 검증 *
+
업데이트를 위한 소프트웨어 이미지 버전과 비교하여 클러스터를 확인 및 확인할 수 있습니다. 사전 업데이트 검증에서는 클러스터가 업데이트할 준비가 된 상태인지 확인합니다. 유효성 검사가 오류와 함께 완료되면 표에 다양한 구성 요소의 상태와 오류에 대한 필요한 수정 조치가 표시됩니다.

+
유효성 검사가 성공적으로 완료된 경우에만 업데이트를 수행할 수 있습니다.

* * 업데이트 *
+
클러스터의 모든 노드 또는 클러스터의 HA 쌍을 선택한 소프트웨어 이미지 버전으로 업데이트할 수 있습니다. 업데이트가 진행 중인 동안 업데이트를 일시 중지하도록 선택한 다음 업데이트를 취소하거나 다시 시작할 수 있습니다.

+
오류가 발생하면 업데이트가 일시 중지되고 오류 메시지가 교정 단계와 함께 표시됩니다. 개선 단계를 수행한 후 업데이트를 재개하거나 업데이트를 취소할 수 있습니다. 업데이트가 성공적으로 완료되면 노드 이름, 가동 시간, 상태 및 ONTAP 버전으로 테이블을 볼 수 있습니다.





== 기록 업데이트 탭

클러스터 업데이트 기록에 대한 세부 정보를 표시합니다.



== 기록 목록을 업데이트합니다

* * 이미지 버전 *
+
노드를 업데이트할 ONTAP 이미지의 버전을 지정합니다.

* * 에 설치된 소프트웨어 업데이트
+
업데이트가 설치되는 디스크 유형을 지정합니다.

* * 상태 *
+
소프트웨어 이미지 업데이트의 상태(업데이트 성공 여부 또는 취소 여부)를 지정합니다.

* * 시작 시간 *
+
업데이트가 시작된 시간을 지정합니다.

* * 완료 시간 *
+
업데이트가 완료된 시간을 지정합니다.

+
이 필드는 기본적으로 숨겨져 있습니다.

* * 업데이트 소요 시간 *
+
업데이트가 완료될 때까지 걸리는 시간을 지정합니다.

* * 이전 버전 *
+
업데이트 전에 노드의 ONTAP 버전을 지정합니다.

* * 업데이트된 버전 *
+
업데이트 후 노드의 ONTAP 버전을 지정합니다.


