---
permalink: online-help-96-97/reference_trace_file_access_window.html 
sidebar: sidebar 
keywords: system, manager, commnd, button, trace, file, access, window, online, help, cif, entry, list 
summary: System Manager 9.6부터, CIFS 또는 NFS 프로토콜을 사용하여 SVM에서 파일 및 공유에 액세스하는 데 문제가 있을 때 Trace File Access 창을 사용하여 문제를 진단할 수 있습니다. 
---
= System Manager의 Trace File Access 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 9.6부터, CIFS 또는 NFS 프로토콜을 사용하여 SVM에서 파일 및 공유에 액세스하는 데 문제가 있을 때 파일 액세스 추적 창을 사용하여 문제를 진단할 수 있습니다.



== 명령 버튼

* * 계속 *
+
선택한 SVM에서 파일 액세스 추적을 설정 및 시작하는 프로세스를 시작합니다.

* * 프로토콜 *
+
선택한 SVM에서 CIFS 또는 NFS를 통해 파일 및 공유에 액세스하는 데 사용되는 프로토콜을 선택할 수 있습니다.

* * 고급 옵션 아이콘 *
+
추적 범위를 좁히기 위해 추가 세부 정보를 지정할 수 있습니다.

* * 추적 결과에 표시 *
+
고급 옵션 대화 상자에서 추적 결과에 거부된 파일 액세스 요청만 표시할지, 아니면 모든 파일 액세스 요청(성공한 요청 및 거부된 요청)을 표시할지 여부를 지정할 수 있습니다.

* * 추적 시작 *
+
트레이스를 시작할 수 있습니다. 결과는 향후 60분 동안 제출된 파일 액세스 요청에 대한 액세스 문제를 보여줍니다.

* * 추적 중지 *
+
트레이스를 중지할 수 있습니다.

* * 권한 보기 *
+
사용 권한을 표시할 수 있습니다. CIFS 프로토콜을 사용할 때 유효한 파일 및 공유 권한을 표시할 수 있습니다. NFS 프로토콜을 사용할 때 유효한 파일 권한을 표시할 수 있습니다.

* * 클립보드로 복사 *
+
결과 테이블을 클립보드에 복사할 수 있습니다.

* * 트레이스 결과 내보내기 *
+
추적 결과를 쉼표로 구분된 값(.csv) 형식의 파일로 내보낼 수 있습니다.





== 입력 필드

* * 사용자 이름 *
+
추적할 파일 액세스 요청 오류를 수신한 사용자의 이름을 입력합니다.

* * 검색 추적 결과 *
+
검색 결과에서 찾을 특정 정보를 입력한 다음 * Enter * 를 클릭합니다.

* * 클라이언트 IP 주소 *
+
고급 옵션 대화 상자에서 추적 범위를 좁히기 위해 클라이언트의 IP 주소를 추가 세부 사항 으로 지정할 수 있습니다.

* * 파일 *
+
고급 옵션 대화 상자에서 액세스할 파일 또는 파일 경로를 추가 세부 사항 으로 지정하여 추적 범위를 좁힐 수 있습니다.



.CIFS 프로토콜 추적의 결과 목록입니다
CIFS 프로토콜을 지정하면 지정한 매개 변수를 기준으로 결과 목록에 추적에 대한 다음 데이터가 표시됩니다. 데이터는 시간순으로 역순으로 표시됩니다. 추적을 중지하면 다른 추적을 시작할 때까지 결과가 목록에 남아 있습니다.

* Share(공유): 시스템이 액세스를 시도한 공유의 이름입니다(성공 여부).
* 경로: 시스템에서 액세스를 시도한 파일의 파일 경로입니다(성공 여부).
* 클라이언트 IP 주소: 액세스 요청이 시작된 클라이언트의 IP 주소입니다.
* 원인: 파일 또는 공유에 대한 액세스 시도가 성공한 이유
+
[NOTE]
====
추적 결과에 "동기화", "읽기 제어", "읽기 속성", "실행", "EA 읽기"에 대한 액세스가 부여되지 않았다는 메시지가 표시되는 경우 "쓰기" 또는 "읽기" 메시지가 표시되면 나열된 권한 집합에 대해 원하는 액세스 권한이 부여되지 않았음을 나타냅니다. 실제 사용 권한 상태를 보려면 제공된 링크를 사용하여 사용 권한을 확인해야 합니다.

====


.NFS 프로토콜 추적의 결과 목록입니다
NFS 프로토콜을 지정하면 지정한 매개 변수를 기반으로 결과 목록에 추적에 대한 다음 데이터가 표시됩니다. 데이터는 시간순으로 역순으로 표시됩니다. 추적을 중지하면 다른 추적을 시작할 때까지 결과가 목록에 남아 있습니다.

* 경로: 시스템에서 액세스를 시도한 파일의 파일 경로입니다(성공 여부).
* 클라이언트 IP 주소: 액세스 요청이 시작된 클라이언트의 IP 주소입니다.
* 원인: 파일 또는 공유에 대한 액세스 시도가 성공한 이유
+
[NOTE]
====
추적 결과에 "동기화", "읽기 제어", "읽기 속성", "실행", "EA 읽기"에 대한 액세스가 부여되지 않았다는 메시지가 표시되는 경우 "쓰기" 또는 "읽기" 메시지가 표시되면 나열된 권한 집합에 대해 원하는 액세스 권한이 부여되지 않았음을 나타냅니다. 실제 사용 권한 상태를 보려면 제공된 링크를 사용하여 사용 권한을 확인해야 합니다.

====


* 관련 정보 *

https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB/CIFS 관리"]

xref:../nas-multiprotocol-config/index.html[SMB/CIFS 및 NFS 멀티 프로토콜 구성]
