---
permalink: online-help-96-97/reference_metrocluster_switchover_switchback_window.html 
sidebar: sidebar 
keywords: metrocluster, switchover, switchback, operations, window, command, button, other, action, online, help, status 
summary: 'System Manager 9.6부터 MetroCluster 스위치오버 및 스위치백 운영 윈도우를 사용하여 한 사이트 또는 클러스터(사이트 B)에서 다른 사이트 또는 클러스터(사이트 A)로 협상된(협상된) 스위치오버 또는 계획되지 않은 전환을 시작할 수 있습니다. 사이트 B에서 유지 관리 또는 수리를 수행한 후 사이트 A에서 사이트 B로 스위치백을 시작하고 이 창에서 작업 상태를 볼 수 있습니다.' 
---
= MetroCluster 전환 및 스위치백 작업 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6부터 MetroCluster 스위치오버 및 스위치백 운영 윈도우를 사용하여 한 사이트 또는 클러스터(사이트 B)에서 다른 사이트 또는 클러스터(사이트 A)로 협상된(협상된) 스위치오버 또는 계획되지 않은 전환을 시작할 수 있습니다. 사이트 B에서 유지 관리 또는 수리를 수행한 후 사이트 A에서 사이트 B로 스위치백을 시작하고 이 창에서 작업 상태를 볼 수 있습니다.



== 명령 버튼

* * 사이트 B에서 사이트 A * 로 전환
+
사이트 B를 사이트 A로 전환하는 프로세스를 시작합니다

* * 사이트 A를 사이트 B로 전환 *
+
사이트 A를 사이트 B로 다시 전환하는 프로세스를 시작합니다





== 기타 조치

* * 사이트 B 클러스터로 이동합니다 *
+
사이트 B의 클러스터 관리 IP 주소를 입력합니다

* * 계획되지 않은 전환 확인란 *
+
계획되지 않은 전환을 시작하려면 * 계획되지 않은 전환 계속 * 확인란을 선택합니다.





== 상태 영역

시스템 전환 또는 전환 프로세스가 진행됨에 따라 System Manager에 다음과 같은 방법으로 상태가 표시됩니다.

* * 진행선 그래픽 *
+
작업의 단계를 표시하고 완료된 단계를 나타냅니다. 이 단계는 전환, 사이트 B 운영 및 스위치백입니다.

* *** 세부 정보 표시 ***
+
MetroCluster 작업 진행으로 타임 스탬프가 설정된 시스템 이벤트 목록을 표시합니다.

* * 로컬: 사이트 A *
+
작업 단계를 진행하는 동안 사이트 A의 클러스터 구성 그래픽을 사이트 상태와 함께 표시합니다.

* * 원격: 사이트 B *
+
작업 단계를 진행하는 동안 사이트 B에서 클러스터의 상태를 포함한 사이트 B의 클러스터 구성 그래픽을 표시합니다.



사이트 B에 로그인하고 MetroCluster 전환 및 스위치백 작동 창을 볼 경우 사이트 A의 상태가 "비활성"으로 표시되고 사이트 B의 상태가 "WITCHOVER 모드"로 표시됩니다.
