---
permalink: online-help-96-97/reference_protection_window.html 
sidebar: sidebar 
keywords: command, buttons, protection, window, relationship, vault, mirror, online, help, ls 
summary: '보호 창을 사용하여 미러 관계, 볼트 관계, 미러 및 볼트 관계를 생성 및 관리하고 이러한 관계에 대한 세부 정보를 표시할 수 있습니다. 보호 창에는 로드 공유(LS) 관계 및 전환 데이터 보호(TDP) 관계가 표시되지 않습니다.' 
---
= System Manager 및 ONTAP 9.7 이하를 사용한 보호 윈도우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보호 창을 ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)과 함께 사용하여 미러 관계, 볼트 관계, 미러 및 볼트 관계를 생성 및 관리하고 이러한 관계에 대한 세부 정보를 표시할 수 있습니다. 보호 창에는 로드 공유(LS) 관계 및 전환 데이터 보호(TDP) 관계가 표시되지 않습니다.



== 명령 버튼

* * 생성 *
+
대상 볼륨에서 미러 관계, 볼트 관계 또는 미러 및 볼트 관계를 생성하는 데 사용할 수 있는 보호 관계 작성 대화 상자를 엽니다.

+
System Manager에서 보호 관계 생성 대화 상자에 DR(재해 복구)용으로 구성된 SVM(스토리지 가상 머신)은 표시되지 않습니다.

* * 편집 *
+
관계의 일정 및 정책을 편집하는 데 사용할 수 있는 보호 관계 편집 대화 상자를 엽니다.

+
볼트 관계, 미러 및 볼트 관계 또는 버전에 상관없이 유연한 미러 관계의 경우 정책 유형을 수정하여 관계 유형을 수정할 수 있습니다.

* * 삭제 *
+
관계를 삭제하는 데 사용할 수 있는 보호 관계 삭제 대화 상자를 엽니다.

* * 운영 *
+
보호 관계에 대해 수행할 수 있는 작업을 표시합니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





== 보호 관계 목록

* * 소스 스토리지 가상 머신 *
+
데이터가 미러링되거나 관계를 저장되어 있는 볼륨을 포함하는 SVM을 표시합니다.

* * 소스 볼륨 *
+
데이터를 미러링하거나 관계를 저장할 볼륨을 표시합니다.

* * 대상 볼륨 *
+
데이터를 미러링하거나 관계를 저장할 볼륨을 표시합니다.

* * 은(는) 건강합니다 *
+
관계가 정상 상태인지 여부를 표시합니다.

* * 개체 유형 *
+
볼륨, FlexGroup 또는 SVM과 같은 개체 유형의 관계를 표시합니다.

* * 관계 상태 *
+
SnapMirrored, Uninitialized 또는 Broken Off와 같은 관계 상태를 표시합니다.

* * 전송 상태 *
+
관계 상태를 표시합니다.

* * 관계 유형 *
+
대칭 복사, 볼트, 대칭 복사, 볼트와 같은 관계 유형을 표시합니다.

* * 지연 시간 *
+
지연 시간은 현재 시간과 타겟 시스템으로 성공적으로 전송된 마지막 스냅샷 복사본의 타임 스탬프의 차이입니다. 지연 시간은 소스 및 대상 시스템의 시계가 동기화되지 않는 한 항상 마지막으로 성공한 전송 기간보다 훨씬 오래 지속됩니다. 시간대 차이는 지연 시간으로 자동 계산됩니다.

* * 정책 이름 *
+
관계에 할당된 정책의 이름을 표시합니다.

* * 정책 유형 *
+
관계에 할당된 정책 유형을 표시합니다. 정책 유형은 StrictSync, Sync, Asynchronous Mirror, Asynchronous Vault 또는 Asynchronous Mirror Vault가 될 수 있습니다.





== 세부 정보 영역

* * 세부 정보 탭 *
+
소스 클러스터 및 타겟 클러스터, 데이터 전송 속도, 관계 상태, 네트워크 압축률에 대한 세부 정보, 데이터 전송 상태, 현재 데이터 전송 유형, 마지막 데이터 전송 유형, 최신 스냅샷 복사본, 및 최신 스냅샷 복사본의 타임스탬프입니다.

* * 정책 세부 정보 탭 *
+
선택한 보호 관계에 할당된 정책에 대한 세부 정보를 표시합니다. 이 탭에는 지정된 레이블과 일치하는 소스 볼륨의 SnapMirror 레이블 및 스냅샷 복사본 스케줄이 표시됩니다.

* Snapshot 복사본 탭 *
+
선택한 보호 관계에 대한 SnapMirror 레이블 속성이 있는 스냅샷 복사본의 수와 최신 스냅샷 복사본의 타임스탬프를 표시합니다.


