---
permalink: online-help-96-97/task_creating_svm.html 
sidebar: sidebar 
keywords: svm, create, storage, virtual, machine, online, help 
summary: 'SVM(Storage Virtual Machine) 창을 사용하여 완벽하게 구성된 SVM을 생성할 수 있습니다. SVM은 이러한 SVM에 스토리지 객체가 생성된 후 데이터를 제공합니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)에서는 SVM(스토리지 가상 머신) 창을 사용하여 완벽하게 구성된 SVM을 생성할 수 있습니다. SVM은 이러한 SVM에 스토리지 객체가 생성된 후 데이터를 제공합니다.

.시작하기 전에
* Aggregate를 생성해야 하며 애그리게이트는 온라인 상태여야 합니다.
* Aggregate가 SVM 루트 볼륨을 위한 충분한 공간을 가지고 있는지 확인해야 합니다.


.단계
. SVM의 이름을 입력합니다.
. SVM을 위한 데이터 프로토콜 선택:
+
|===
| 원하는 작업 | 그러면... 


 a| 
Active Directory를 사용하여 CIFS 서버를 구성하여 CIFS 프로토콜을 설정합니다
 a| 
.. Active Directory * 상자를 선택합니다.
.. Active Directory 관리자 이름을 입력합니다.
.. Active Directory 관리자 암호를 입력합니다.
.. CIFS 서버의 이름을 입력합니다.
.. Active Directory 도메인의 이름을 입력합니다.
.. 요구사항에 따라 이 SVM * 에서 * 하나의 데이터 LIF를 선택하거나, SVM * 상자에서 노드당 * 하나의 데이터 LIF를 선택합니다.
.. IP 주소, 넷마스크, 게이트웨이 및 포트와 같은 데이터 LIF 세부 정보를 제공합니다.
.. DNS 세부 정보를 제공합니다.




 a| 
작업 그룹을 사용하여 CIFS 서버를 구성하여 CIFS 프로토콜을 설정합니다
 a| 
.. Workgroup * 상자를 선택합니다.
.. 워크그룹의 이름을 입력합니다.
.. CIFS 서버의 이름을 입력합니다.
.. 요구사항에 따라 이 SVM * 에서 데이터 LIF * 하나를 선택하거나, SVM * 에서 노드당 데이터 LIF * 하나를 선택합니다.
.. IP 주소, 넷마스크, 게이트웨이 및 포트와 같은 데이터 LIF 세부 정보를 제공합니다.




 a| 
NFS 프로토콜을 사용하도록 설정합니다
 a| 
.. NFS * 상자를 선택합니다.
.. 요구사항에 따라 이 SVM * 에서 데이터 LIF * 하나를 선택하거나, SVM * 에서 노드당 데이터 LIF * 하나를 선택합니다.
.. IP 주소, 넷마스크, 게이트웨이 및 포트와 같은 데이터 LIF 세부 정보를 제공합니다.




 a| 
iSCSI 프로토콜을 활성화합니다
 a| 
.. iSCSI * 상자를 선택합니다.
.. IP 주소, 넷마스크, 게이트웨이 및 포트와 같은 데이터 LIF 세부 정보를 제공합니다.




 a| 
FC/FCoE 프로토콜 활성화
 a| 
.. FC/FCoE * 상자를 선택합니다.
.. FC 또는 FCoE 프로토콜용 FC/FCoE 포트를 선택합니다.
+
[NOTE]
====
각 노드에는 각 프로토콜(FC 및 FCoE)에 대해 올바르게 구성된 포트가 하나 이상 있어야 합니다.

====




 a| 
NVMe 프로토콜을 활성화하십시오
 a| 
.. NVMe * 상자를 선택합니다.
.. NVMe 프로토콜용 NVMe 포트를 선택하십시오.
+
[NOTE]
====
NVMe를 구성하려면 노드 중 하나에서 적어도 하나의 NVMe 가능 어댑터를 사용할 수 있어야 합니다.        또한 ONTAP 9.5부터 SVM과 연결된 HA 쌍의 각 노드에 대해 하나 이상의 NVMe LIF를 구성해야 합니다. 페어의 각 노드에 대해 최대 2개의 NVMe LIF를 생성할 수 있습니다.

====


|===
. * 선택 사항: * 고급 옵션 * 아이콘을 클릭하고 기본 언어, 보안 스타일, CIFS 서버 세부 정보 및 NFS 세부 정보와 같은 고급 옵션을 구성하는 세부 정보를 제공합니다.
. Submit and Continue * 를 클릭하여 SVM을 생성합니다.




== 다음 단계

제출 및 계속 * 을 클릭한 경우 요약 창에서 제공한 세부 정보를 확인한 다음 * 클러스터 관리 * 를 클릭하여 System Manager를 시작하거나 * 응용 프로그램 제공 * 을 클릭하여 스토리지 응용 프로그램을 프로비저닝하거나 * 구성 내보내기 * 를 클릭하여 구성 파일을 다운로드해야 합니다.
