---
permalink: online-help-96-97/task_adding_preferred_domain_controllers.html 
sidebar: sidebar 
keywords: system, manager, add, preferred, domain, controller, online, help, dns, edit, modify, delete 
summary: System Manager는 DNS를 통해 도메인 컨트롤러를 자동으로 검색합니다. 필요에 따라 특정 도메인의 기본 도메인 컨트롤러 목록에 하나 이상의 도메인 컨트롤러를 추가할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 기본 도메인 컨트롤러를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 선호하는 도메인 컨트롤러를 관리할 수 있습니다.



== 기본 도메인 컨트롤러를 추가합니다

System Manager는 DNS를 통해 도메인 컨트롤러를 자동으로 검색합니다. 필요에 따라 특정 도메인의 기본 도메인 컨트롤러 목록에 하나 이상의 도메인 컨트롤러를 추가할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 도메인 * 탭의 * 기본 도메인 컨트롤러 * 영역에서 * 추가 * 를 클릭합니다.
. 추가할 도메인 컨트롤러의 FQDN(정규화된 도메인 이름)과 IP 주소를 입력합니다.
+
도메인 컨트롤러의 IP 주소를 쉼표로 구분하여 입력하여 여러 도메인 컨트롤러를 추가할 수 있습니다.

. 저장 * 을 클릭합니다.
. 추가한 도메인 컨트롤러가 기본 도메인 컨트롤러 목록에 표시되는지 확인합니다.




== 기본 도메인 컨트롤러를 편집합니다

System Manager를 사용하여 특정 도메인에 대해 구성된 기본 도메인 컨트롤러의 IP 주소를 수정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 도메인 * 탭의 * 기본 도메인 컨트롤러 * 영역에서 편집할 도메인 컨트롤러를 두 번 클릭합니다.
. 도메인 컨트롤러의 IP 주소를 수정한 다음 * 저장 * 을 클릭합니다.




== 기본 도메인 컨트롤러를 삭제합니다

System Manager를 사용하면 SVM(스토리지 가상 머신) 컴퓨터 계정이 연결되는 기본 도메인 컨트롤러를 삭제할 수 있습니다. 특정 도메인 컨트롤러를 더 이상 사용하지 않으려는 경우 이 작업을 수행할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 도메인 * 탭의 * 기본 도메인 컨트롤러 * 영역에서 삭제할 도메인을 선택한 다음 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.

