---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: System Manager를 사용하여 클러스터에서 기존 정책 또는 일정을 선택하거나 새 정책 또는 일정을 만들어 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다. 
---
= System Manager-ONTAP 9.7 이하 버전을 사용하여 볼트 관계를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 대상 SVM에서 볼트 관계를 생성할 뿐만 아니라 볼트 관계를 업데이트, 재개, 중지, 초기화 및 삭제할 수 있습니다.



== 관계 편집

System Manager를 사용하여 클러스터에서 기존 정책 또는 일정을 선택하거나 새 정책 또는 일정을 만들어 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다.

.시작하기 전에
소스 및 대상 클러스터는 정상 피어 관계에 있어야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 정책 또는 일정을 수정하려는 볼트 관계를 선택하고 * 편집 * 을 클릭합니다.
. [관계 편집] * 대화 상자에서 적절한 작업을 선택합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
기존 정책을 선택합니다
 a| 
찾아보기 * 를 클릭한 다음 기존 정책을 선택합니다.    소스 볼륨에 연결된 스냅샷 정책과 일치하는 최대 레이블 수를 갖는 정책을 선택할 수 있습니다.



 a| 
새 정책을 생성합니다
 a| 
.. Create Policy * 를 클릭합니다.
.. 정책의 이름을 지정합니다.
.. 예약된 전송의 우선 순위를 설정합니다.
+
낮음 은 전송 우선 순위가 가장 낮으며 일반적으로 일반 우선 순위 전송 후에 예약됨을 나타냅니다. 기본적으로 우선 순위는 보통으로 설정됩니다.

.. 전송 중인 데이터를 압축하려면 * 네트워크 압축 사용 * 확인란을 선택합니다.
.. 볼트 정책에 대한 SnapMirror 레이블 및 대상 보존 수를 지정합니다.
+
새 SnapMirror 레이블을 사용하려면 소스 볼륨에 동일한 레이블이 있는 스냅샷 복사본이 생성되었는지 확인해야 합니다.

.. Create * 를 클릭합니다.


|===
. 관계의 일정을 지정합니다.
+
|===
| 만약... | 다음을 수행합니다. 


 a| 
기존 일정을 할당하려고 합니다
 a| 
목록에서 기존 일정을 선택합니다.



 a| 
새 스케줄을 생성하려고 합니다
 a| 
.. Create Schedule * 을 클릭합니다.
.. 스케줄의 이름을 지정합니다.
.. 다음 옵션 중 하나를 선택합니다.
+
*** * 기본 *
+
이 옵션을 선택하면 요일, 시간 및 전송 간격만 지정할 수 있습니다.

*** * 고급 *
+
이 옵션을 선택하여 cron 스타일 일정을 지정할 수 있습니다.



.. Create * 를 클릭합니다.




 a| 
일정을 지정하지 않으려는 경우
 a| 
없음 * 을 선택합니다.

|===
. 확인 * 을 클릭합니다.


* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]



== 관계 초기화

관계를 생성하는 동안 볼트 관계를 아직 초기화하지 않은 경우 System Manager를 사용하여 볼트 관계를 초기화할 수 있습니다. 소스 FlexVol 볼륨에서 타겟 FlexVol 볼륨으로 기본 데이터 전송이 시작됩니다.

.시작하기 전에
소스 및 대상 클러스터는 정상 피어 관계에 있어야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 초기화하려는 관계를 선택하고 * 작업 * > * 초기화 * 를 클릭합니다.
. Initialize * (초기화 *) 창에서 * Initialize * (* 초기화 *)를 클릭합니다.


.결과
스냅샷 복사본이 생성되어 타겟으로 전송됩니다.

이 스냅샷 복사본은 이후의 증분 스냅샷 복사본을 위한 기준으로 사용됩니다.

* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]



== 대상 SVM에서 관계 생성

System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 볼트 관계를 생성하고 볼트 정책을 할당하여 백업 볼트를 생성할 수 있습니다. 시스템에서 데이터가 손실되거나 손상된 경우 백업 데이터를 백업 볼트 대상에서 복원할 수 있습니다.

.시작하기 전에
* 소스 클러스터는 ONTAP 8.2.2 이상을 실행해야 합니다.
* 소스 클러스터와 대상 클러스터 모두에서 SnapVault 라이센스 또는 SnapMirror 라이센스를 활성화해야 합니다.
+
[NOTE]
====
일부 플랫폼의 경우 대상 클러스터에 SnapVault 라이센스 또는 SnapMirror 라이센스가 있고 DPO 라이센스가 활성화된 경우 소스 클러스터에 SnapVault 라이센스가 없거나 SnapMirror 라이센스가 활성화되어 있지 않아도 됩니다.

====
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 SVM에 사용 가능한 공간이 있어야 합니다.
* 소스 애그리게이트와 대상 애그리게이트는 64비트 애그리게이트로 이루어져야 합니다.
* 읽기/쓰기(RW) 유형의 소스 볼륨이 있어야 합니다.
* 볼트(XDP) 정책이 있어야 합니다.
+
볼트 정책이 없으면 볼트 정책을 작성하거나 자동으로 할당된 기본 볼트 정책(XDPDefault)을 수락해야 합니다.

* FlexVol 볼륨은 온라인과 읽기/쓰기가 가능해야 합니다.
* SnapLock 집계 유형은 같아야 합니다.
* ONTAP 9.2 이하를 실행하는 클러스터에서 SAML 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증을 활성화해야 합니다.


.이 작업에 대해
* System Manager는 계단식 관계를 지원하지 않습니다.
+
예를 들어, 관계의 대상 볼륨은 다른 관계의 소스 볼륨이 될 수 없습니다.

* MetroCluster 구성에서는 동기화 소스 SVM과 동기화 대상 SVM 간에 볼트 관계를 생성할 수 없습니다.
* MetroCluster 구성에서 동기화 소스 SVM 간에 볼트 관계를 생성할 수 있습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 지원 SVM의 볼륨으로 볼트 관계를 생성할 수 있습니다.
* 데이터 지원 SVM의 볼륨에서 동기화 소스 SVM의 데이터 보호(DP) 볼륨으로 볼트 관계를 생성할 수 있습니다.
* 비 SnapLock(운영) 볼륨과 SnapLock 대상(보조) 볼륨 간의 볼트 관계만 생성할 수 있습니다.
* 한 번에 최대 25개의 볼륨을 보호할 수 있습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 관계 * 창에서 * 생성 * 을 클릭합니다.
. SVM * 찾아보기 대화 상자에서 타겟 볼륨의 SVM을 선택합니다.
. [보호 관계 작성] * 대화 상자의 [관계 유형 *] 드롭다운 목록에서 * 볼트 * 를 선택합니다.
. 클러스터, SVM 및 소스 볼륨을 지정합니다.
+
지정된 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 지정된 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

. 볼륨 이름 접미사를 입력합니다.
+
대상 볼륨 이름을 생성하기 위해 소스 볼륨 이름에 볼륨 이름 접미사가 추가됩니다.

. SnapLock 볼륨을 생성하는 경우 기본 보존 기간을 지정합니다.
+
기본 보존 기간은 1일 ~ 70년 또는 Infinite 사이의 값으로 설정할 수 있습니다.

. * 선택 사항: * 찾아보기 * 를 클릭한 다음 볼트 정책을 변경합니다.
. 기존 일정 목록에서 관계의 일정을 선택합니다.
. * 선택 사항: * 관계 초기화 * 를 선택하여 볼트 관계를 초기화합니다.
. SnapLock 애그리게이트를 사용하도록 설정한 다음 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 선택합니다.
. FabricPool 지원 애그리게이트를 사용하도록 설정한 다음 적절한 계층화 정책을 선택합니다.
. 선택한 볼륨에 일치하는 레이블이 있는지 확인하려면 * Validate * 를 클릭합니다.
. Create * 를 클릭합니다.


.결과
대상 볼륨을 생성하도록 선택한 경우 다음 기본 설정으로 _DP_ 유형의 볼륨이 생성됩니다.

* 자동 확장 기능이 설정되어 있습니다.
* 사용자 기본 설정 또는 소스 볼륨 중복 제거 설정에 따라 중복 제거가 설정 또는 해제됩니다.
* 압축이 사용되지 않습니다.
* 언어 속성은 소스 볼륨의 언어 특성과 일치하도록 설정됩니다.


대상 볼륨과 소스 볼륨 사이에 볼트 관계가 생성됩니다. 관계를 초기화하기로 선택한 경우 기본 스냅샷 복사본이 대상 볼륨으로 전송됩니다.



== 관계 업데이트

System Manager를 사용하여 예약되지 않은 증분 업데이트를 수동으로 시작할 수 있습니다. 향후 정전, 예정된 유지보수 또는 데이터 마이그레이션으로 인한 데이터 손실을 방지하려면 수동 업데이트가 필요할 수 있습니다.

.시작하기 전에
볼트 관계를 초기화해야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 데이터를 업데이트할 관계를 선택하고 * 운영 * > * 업데이트 * 를 클릭합니다.
. 다음 옵션 중 하나를 선택합니다.
+
** 소스 볼륨과 타겟 볼륨 간의 최근 공통 스냅샷 복사본에서 증분 전송을 수행하려면 정책에 따라 * 를 선택합니다.
** 스냅샷 복사본 선택 * 을 선택하고 전송할 스냅샷 복사본을 지정합니다.


. * 선택 사항: * 전송에 사용되는 네트워크 대역폭을 제한하고 최대 전송 속도를 지정하려면 * 전송 대역폭을 * 로 제한합니다.
. Update * 를 클릭합니다.
. 세부 정보 * 탭에서 전송 상태를 확인합니다.




== 관계 삭제

System Manager를 사용하여 소스 볼륨과 타겟 볼륨 간의 볼트 관계를 엔드하고 소스에서 스냅샷 복사본을 릴리즈할 수 있습니다.

.이 작업에 대해
관계를 해제하면 소스 볼륨의 볼트 관계에 사용되는 기본 스냅샷 복사본이 영구적으로 제거됩니다. 볼트 관계를 다시 작성하려면 CLI(명령줄 인터페이스)를 사용하여 소스 볼륨에서 재동기화 작업을 실행해야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 볼트 관계를 삭제할 볼륨을 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.
+
또한 기본 스냅샷 복사본 릴리즈 확인란을 선택하여 소스 볼륨의 볼트 관계에 사용되는 기본 스냅샷 복사본을 삭제할 수도 있습니다.

+
관계가 해제되지 않은 경우 소스 클러스터에서 릴리스 작업을 실행하기 위해 CLI를 사용하여 소스 볼륨에서 볼트 관계로 생성된 기본 스냅샷 복사본을 삭제해야 합니다.





== 관계를 재개합니다

System Manager를 사용하여 정지된 볼트 관계를 재개할 수 있습니다. 관계를 재개하면 대상 FlexVol 볼륨에 대한 정상적인 데이터 전송이 재개되고 모든 볼트 작업이 다시 시작됩니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 데이터 전송을 재개할 관계를 선택하고 * 작업 * > * 재개 * 를 클릭합니다.
. Resume* 창에서 * Resume * 을 클릭합니다.


.결과
정상적인 데이터 전송이 다시 시작됩니다. 관계에 대해 예약된 전송이 있는 경우 다음 일정에서 전송이 시작됩니다.



== 관계를 중지합니다

볼트 관계를 중지하여 시스템 관리자를 사용하여 대상 FlexVol 볼륨에 대한 데이터 전송을 비활성화할 수 있습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 예약된 데이터 전송을 중지할 관계를 선택하고 * 작업 * > * 정지 * 를 클릭합니다.
. 정지 * 창에서 * 정지 * 를 클릭합니다.


.결과
진행 중인 전송이 없으면 전송 상태가 중지 로 표시됩니다. 전송이 진행 중인 경우 전송은 영향을 받지 않으며 전송이 완료될 때까지 전송 상태가 정지 상태로 표시됩니다.

* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
