---
permalink: online-help-96-97/task_creating_snaplock_volumes.html 
sidebar: sidebar 
keywords: create, snaplock, volume, online, help, system, manager 
summary: System Manager를 사용하여 SnapLock 규정 준수 볼륨 또는 SnapLock 엔터프라이즈 볼륨을 생성할 수 있습니다. 볼륨을 생성할 때 보존 시간을 설정하고 볼륨의 데이터에 대해 WORM 상태 설정을 자동으로 수행할지 여부를 선택할 수도 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SnapLock 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하여 SnapLock 규정 준수 볼륨 또는 SnapLock 엔터프라이즈 볼륨을 생성할 수 있습니다. 볼륨을 생성할 때 보존 시간을 설정하고 볼륨의 데이터에 대해 WORM 상태 설정을 자동으로 수행할지 여부를 선택할 수도 있습니다.

.시작하기 전에
* SnapLock 라이센스가 설치되어 있어야 합니다.
* SnapLock 애그리게이트는 온라인 상태여야 합니다.
* 암호화된 볼륨을 만들려면 System Manager를 사용하여 볼륨 암호화 라이센스를 설치해야 하며 CLI(Command-Line Interface)를 사용하여 ""key-manager setup""을 활성화해야 합니다.
+
""Key-manager setup""을 활성화한 후 웹 브라우저를 새로 고쳐야 합니다.



.이 작업에 대해
* 전체 SnapLock 엔터프라이즈 볼륨 또는 SnapLock 엔터프라이즈 볼륨의 파일을 삭제할 수 있지만 SnapLock 엔터프라이즈 볼륨의 파일 내 데이터만 삭제할 수는 없습니다.
* 데이터가 볼륨에 커밋된 경우 SnapLock Compliance 볼륨을 삭제할 수 없습니다.
* Cloud Volumes ONTAP에서는 볼륨을 암호화할 수 없습니다.
* 소스 볼륨에서 암호화가 활성화되고 대상 클러스터에서 ONTAP 9.3 이전의 ONTAP 소프트웨어 버전을 실행 중인 경우 기본적으로 타겟 볼륨에서 암호화가 비활성화됩니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. Create * > * Create FlexVol * 를 클릭합니다.
. 볼륨을 생성할 스토리지 가상 시스템(SVM)을 찾아 선택합니다.
. 볼륨의 기본 이름을 변경하려면 * 볼륨 생성 * 대화 상자에서 새 이름을 지정합니다.
+
볼륨을 생성한 후에는 SnapLock 준수 볼륨의 이름을 변경할 수 없습니다.

. 볼륨의 컨테이너 애그리게이트를 선택합니다.
+
SnapLock 볼륨을 생성하려면 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 선택해야 합니다. 볼륨은 Aggregate에서 SnapLock 유형을 상속하며, 볼륨이 생성된 후에는 SnapLock 유형을 변경할 수 없으므로 올바른 Aggregate를 선택해야 합니다.

. 볼륨 암호화를 활성화하려면 * 볼륨 암호화 * 확인란을 선택합니다.
+
이 옵션은 볼륨 암호화 라이센스를 활성화했으며 해당 플랫폼이 암호화를 지원할 수 있는 경우에만 사용할 수 있습니다.

. 이 볼륨을 생성할 스토리지 유형을 선택합니다.
+
SnapMirror 대상 볼륨을 만드는 경우 * 데이터 보호 * 를 선택해야 합니다. 이 볼륨에 대한 읽기 전용 액세스 권한이 제공됩니다.

. 스냅샷 복사본을 위해 예약할 볼륨 크기와 총 볼륨 크기의 비율을 지정합니다.
+
스냅샷 복사본에 대해 예약된 기본 공간은 SAN 볼륨 및 VMware 볼륨에 대해 0%입니다. NAS 볼륨의 경우 기본값은 5%입니다.

. * 선택 사항: * 씬 프로비저닝 * 을 선택하여 볼륨에 대한 씬 프로비저닝을 활성화합니다.
+
씬 프로비저닝이 설정된 경우 데이터가 볼륨에 기록될 때에만 aggregate에서 볼륨에 공간이 할당됩니다.

. * 선택 사항: * 볼륨에서 중복 제거를 활성화하려면 * 스토리지 효율성 * 탭에서 필요한 사항을 변경합니다.
+
System Manager에서는 기본 중복 제거 일정을 사용합니다. 지정된 볼륨 크기가 중복 제거를 실행하는 데 필요한 제한을 초과하면 볼륨이 생성되고 중복제거가 활성화되지 않습니다.

. SnapLock * 탭을 선택한 후 다음 단계를 수행하십시오.
+
.. * 선택 사항: * 자동 커밋 기간을 지정합니다.
+
파일이 WORM 상태로 커밋되기 전에 지정하는 기간 동안 볼륨에 있는 파일은 변경되지 않습니다. 파일을 WORM 상태로 수동으로 설정하려면 자동 커밋 설정으로 * 지정되지 않음 * 을 선택해야 합니다.

+
값은 5분에서 10년 사이여야 합니다.

.. 최소 보존 기간 및 최대 보존 기간을 지정합니다.
+
값은 1일 ~ 70년 또는 무한대의 범위에 있어야 합니다.

.. 기본 보존 기간을 선택합니다.
+
기본 보존 기간은 지정된 최소 보존 기간 및 최대 보존 기간 이내여야 합니다.



. * 선택 사항: * 서비스 품질 * 탭에서 * 스토리지 서비스 품질 관리 * 확인란을 선택하여 FlexVol 볼륨의 스토리지 QoS를 활성화하여 워크로드 성능을 관리합니다.
. 스토리지 QoS 정책 그룹을 생성하거나 기존 정책 그룹을 선택하여 FlexVol 볼륨의 I/O(Input/Output) 성능을 제어합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
스토리지 QoS 정책 그룹을 생성합니다
 a| 
.. 새 정책 그룹 * 을 선택합니다.
.. 정책 그룹 이름을 지정합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.







 a| 
기존 정책 그룹을 선택합니다
 a| 
.. 기존 정책 그룹 * 을 선택한 다음 * 선택 * 을 클릭하여 정책 그룹 선택 대화 상자에서 기존 정책 그룹을 선택합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.



+
정책 그룹이 둘 이상의 개체에 할당된 경우 지정한 최대 처리량은 객체 간에 공유됩니다.



|===
. 볼륨 보호를 위해 * 보호 * 탭에서 * 볼륨 보호 * 를 활성화합니다.
. Protection * 탭에서 * Replication * 유형을 선택합니다.
+
|===
| 복제 유형을 다음과 같이 선택한 경우 | 수행할 작업... 


 a| 
비동기식
 a| 
.. * 선택 사항: * 복제 유형 및 관계 유형을 모르는 경우 * 도움말 선택 * 을 클릭하고 값을 지정한 다음 * 적용 * 을 클릭합니다.
.. 관계 유형을 선택합니다.
+
관계 유형은 대칭 복사, 볼트, 대칭 복사 및 볼트 중 선택할 수 있습니다.

.. 타겟 볼륨으로 클러스터 및 SVM을 선택합니다.
+
선택한 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 선택한 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

.. 필요한 경우 볼륨 이름 접미사를 수정합니다.




 a| 
동기식이다
 a| 
.. * 선택 사항: * 복제 유형 및 관계 유형을 모르는 경우 * 도움말 선택 * 을 클릭하고 값을 지정한 다음 * 적용 * 을 클릭합니다.
.. 동기화 정책을 선택합니다.
+
동기화 정책은 StrictSync 또는 Sync 일 수 있습니다.

.. 타겟 볼륨으로 클러스터 및 SVM을 선택합니다.
+
선택한 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 선택한 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

.. 필요한 경우 볼륨 이름 접미사를 수정합니다.


|===
. Create * 를 클릭합니다.
. 생성한 볼륨이 * Volume * 창의 볼륨 목록에 포함되어 있는지 확인합니다.


.결과
이 볼륨은 UNIX 스타일 보안 및 소유자에 대한 UNIX 700 "read write execute" 권한으로 생성됩니다.
