---
permalink: online-help-96-97/task_creating_svms.html 
sidebar: sidebar 
keywords: create, svm, system, manager, cluster, online, help 
summary: 'System Manager를 사용하면 데이터를 즉시 제공할 수 있도록 완벽하게 구성된 SVM(스토리지 가상 머신)을 생성할 수 있습니다. 클러스터는 하나 이상의 SVM을 가질 수 있습니다.' 
---
= System Manager로 SVM 생성 - ONTAP 9.7 이전 버전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하면 데이터를 즉시 제공할 수 있도록 완벽하게 구성된 SVM(스토리지 가상 머신)을 생성할 수 있습니다. 클러스터는 하나 이상의 SVM을 가질 수 있습니다.

.시작하기 전에
* 클러스터에는 온라인 상태에 루트가 아닌 Aggregate가 하나 이상 있어야 합니다.
* Aggregate는 SVM 루트 볼륨을 위한 충분한 공간을 가져야 합니다.
* CIFS 생성 및 인증 실패를 방지하려면 NTP를 구성 및 활성화하여 클러스터 전체에서 시간을 동기화해야 합니다.
* SVM에 구성하려는 프로토콜은 라이센스를 받아야 합니다.
* 보안 DDNS가 작동하려면 CIFS 프로토콜을 구성해야 합니다.


.이 작업에 대해
* SVM을 생성하는 동안 다음 작업을 수행할 수 있습니다.
+
** SVM을 생성하고 완벽하게 구성합니다.
** SVM에 허용되는 볼륨 유형을 구성합니다.
** 최소한의 네트워크 구성으로 SVM을 생성 및 구성합니다.
** SVM 관리자에게 관리 권한을 위임합니다.


* SVM의 이름을 지정하려면 영숫자 문자 및 ""의 특수 문자를 사용할 수 있습니다.`" (period), "`--"(하이픈) 및 ""_"(밑줄).
+
SVM 이름은 알파벳 또는 ""_"(밑줄)로 시작해야 하며 47자를 초과할 수 없습니다.

+
[NOTE]
====
vs0.example.com 과 같은 SVM 이름으로 FQDN(정규화된 도메인 이름)을 사용해야 합니다.

====
* 언어 설정이 동일한 볼륨 간에만 SnapMirror 관계를 설정할 수 있습니다.
+
SVM의 언어에 따라 SVM의 모든 NAS 볼륨에 대한 파일 이름 및 데이터를 표시하는 데 사용되는 문자 세트가 결정됩니다.

* SnapLock 애그리게이트를 SVM의 루트 애그리게이트로 사용할 수 없습니다.


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. Create * 를 클릭합니다.
. SVM(Storage Virtual Machine) 설정 * 창에서 다음 세부 정보를 지정합니다.
+
** SVM 이름
** SVM에 할당된 IPSpace
** 허용되는 볼륨 유형입니다
** 허용되는 프로토콜입니다
** SVM 언어
** 루트 볼륨의 보안 스타일입니다
** 루트 애그리게이트
+
모든 SVM에 대한 기본 언어 설정은 C.UTF-8입니다.

+
기본적으로 최대 여유 공간이 있는 애그리게이트는 SVM의 루트 볼륨의 컨테이너로 선택됩니다. 선택한 프로토콜에 따라 기본 보안 스타일과 루트 애그리게이트가 선택됩니다.

+
CIFS 프로토콜을 선택하거나 CIFS 프로토콜을 다른 프로토콜과 조합하면 보안 스타일이 NTFS로 설정됩니다. NFS, iSCSI, NVMe 또는 FC/FCoE 또는 이러한 프로토콜 조합을 선택하는 경우 보안 스타일이 UNIX로 설정됩니다.

+
[NOTE]
====
NVMe에서는 프로토콜의 조합을 허용하지 않습니다.

====


+
MetroCluster 구성에서는 클러스터에 포함된 애그리게이트만 표시됩니다.

. DNS 서비스를 구성할 DNS 도메인 이름과 이름 서버 IP 주소를 지정합니다.
+
기본값은 기존 SVM 구성에서 선택됩니다.

. * 선택 사항: * 프로토콜을 사용하여 데이터 LIF가 데이터에 액세스하도록 구성할 때 타겟 별칭, 서브넷 및 노드당 LIF 수를 지정합니다.
+
LIF의 포트 수를 수정하려면 * 검토 또는 LIF 구성 수정(고급 설정) * 확인란을 선택할 수 있습니다.

+
세부 정보 영역의 노드 목록에서 노드를 선택하여 특정 노드에 있는 포트셋 세부 정보를 편집할 수 있습니다.

. * 선택 사항: * SVM 자격 증명을 제공하여 SVM 관리자를 위한 SnapDrive 및 SnapManager와 같은 호스트 측 애플리케이션을 사용합니다.
. * 선택 사항: * NVMe 이외의 프로토콜의 경우 * SVM 관리를 위한 새 LIF 생성 * 을 클릭한 다음, 새 관리 LIF의 서브넷 유무에 관계없이 포트 세트와 IP 주소를 지정하여 SVM 관리를 위한 새로운 LIF를 생성합니다.
+
CIFS 및 NFS 프로토콜의 경우 데이터 LIF는 기본적으로 관리 액세스를 가집니다. 필요한 경우에만 새 관리 LIF를 생성해야 합니다. iSCSI 및 FC의 경우 데이터 프로토콜과 관리 프로토콜이 동일한 LIF를 공유할 수 없기 때문에 SVM 관리 LIF가 필요합니다.

. * 선택 사항: * NVMe 프로토콜의 경우, ONTAP 9.5부터 SVM 설정 마법사의 두 번째 페이지에서 각 노드에 대해 최소 하나의 LIF를 구성합니다. * NVMe 프로토콜 구성 *
+
HA Pair의 각 노드에 대해 LIF를 하나 이상 구성해야 합니다. 노드당 두 개의 LIF도 지정할 수 있습니다. 설정 아이콘을 클릭하여 하나 또는 두 개의 LIF 구성 간에 전환합니다.

. 제출 및 계속 * 을 클릭합니다.
+
SVM은 지정된 구성으로 생성됩니다.



.결과
생성한 SVM은 자동으로 시작됩니다. 루트 볼륨 이름이 로 자동으로 생성됩니다 `SVM name_root`. 기본적으로 은(는) 입니다 `vsadmin` 사용자 계정이 만들어지고 잠김 상태입니다.



== 다음 단계

데이터 액세스를 허용하려면 SVM에서 프로토콜을 하나 이상 구성해야 합니다.
