---
permalink: online-help-96-97/task_creating_flexclone_volumes.html 
sidebar: sidebar 
keywords: create, flexclone, volume, system, manager, online, help 
summary: 기존 FlexVol 볼륨의 쓰기 가능한 시점 복사본이 필요한 경우 System Manager를 사용하여 FlexClone 볼륨을 생성할 수 있습니다. 테스트할 볼륨의 복사본을 만들거나 운영 데이터에 대한 액세스 권한을 부여하지 않고 추가 사용자에게 볼륨에 대한 액세스를 제공할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 FlexClone 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 기존 FlexVol 볼륨의 쓰기 가능한 시점 복사본이 필요한 경우 FlexClone 볼륨을 생성할 수 있습니다. 테스트할 볼륨의 복사본을 만들거나 운영 데이터에 대한 액세스 권한을 부여하지 않고 추가 사용자에게 볼륨에 대한 액세스를 제공할 수 있습니다.

.시작하기 전에
* FlexClone 라이센스는 스토리지 시스템에 설치해야 합니다.
* 복제할 볼륨은 온라인이어야 하며 루트가 아닌 볼륨이어야 합니다.


.이 작업에 대해
SnapMirror 대상의 FlexClone 볼륨을 만드는 데 사용되는 기본 스냅샷 복사본은 통화 중으로 표시되며 삭제할 수 없습니다. FlexClone 볼륨이 최신 스냅샷 복사본이 아닌 스냅샷 복사본에서 생성되었으며 해당 스냅샷 복사본이 소스 볼륨에 더 이상 존재하지 않으면 대상 볼륨에 대한 모든 SnapMirror 업데이트가 실패합니다.

.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 볼륨 목록에서 클론 복제할 FlexVol 볼륨을 선택합니다.
. 추가 작업 * > * 클론 * > * 생성 * > * 볼륨 * 을 클릭합니다.
. 생성할 FlexClone 볼륨의 이름을 입력합니다.
. * 선택 사항: * 새 FlexClone 볼륨에 대한 씬 프로비저닝을 설정하려면 * 씬 프로비저닝 * 을 선택합니다.
+
기본적으로 이 설정은 상위 볼륨의 설정과 동일합니다.

. FlexClone 볼륨을 만들기 위해 기본 스냅샷 복사본으로 사용할 스냅샷 복사본을 만들거나 기존 스냅샷 복사본을 선택합니다.
. 클론 * 을 클릭합니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
