---
permalink: online-help-96-97/task_preparing_for_switchover_switchback_operations.html 
sidebar: sidebar 
keywords: prepare, switchover, switchback, operation, system, manager, online, help 
summary: System Manager 9.6을 사용하여 스위치오버 작업을 수행하기 전에 해당 사이트에서 필요한 단계가 수행되었는지 확인해야 합니다. 
---
= 스위치오버 및 스위치백 작업을 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식 9.6을 사용하여 스위치오버 작업을 수행하기 전에 해당 사이트에서 필요한 단계가 수행되었는지 확인해야 합니다.

.단계
. 사이트 B의 재해를 복구하는 경우 다음 단계를 수행해야 합니다.
+
.. 손상된 디스크 또는 하드웨어를 복구하거나 교체합니다.
.. 전원을 복원합니다.
.. 발생한 오류 문제를 해결하십시오.
.. 재해 사이트를 표시합니다.


. 클러스터에 다음 조건이 있는지 확인합니다.
+
** 계획된 전환을 수행하는 경우 두 사이트가 모두 활성 상태입니다.
** MetroCluster 시스템은 구성 유형 ""IP_Fabric""을 사용합니다.
** 두 사이트 모두 2노드 구성으로 작동합니다(각 클러스터에 2개 노드). 단일 노드 또는 4노드 구성이 있는 사이트는 System Manager를 사용하여 스위치오버 및 스위치백 작업에 지원되지 않습니다.


. 로컬 사이트(사이트 A)에서 원격 사이트(사이트 B)를 시작하는 경우 사이트 B에서 System Manager 9.6 이상 버전을 실행하고 있는지 확인합니다.




== 시스템 관리자 - ONTAP 9.7 이전 버전을 사용하여 MetroCluster 로컬 사이트(사이트 A)의 이름을 바꿉니다

ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 클러스터의 MetroCluster 로컬 사이트(사이트 A)의 이름을 바꿀 수 있습니다.

.단계
. 구성 * > * 구성 업데이트 * 를 클릭합니다.
. Update cluster name * 을 클릭합니다.
. 텍스트 상자의 이름을 업데이트한 다음 * 제출 * 을 클릭합니다.
+
MetroCluster 사이트 A 상태가 표시되면 업데이트된 이름을 볼 수 있습니다.

. 원격 사이트(사이트 B)에서 MetroCluster 사이트 A의 업데이트된 이름을 볼 때 표시하려면 원격 사이트(사이트 B)의 CLI 내에서 다음 명령을 실행합니다. `cluster peer modify-local-name`

