---
permalink: online-help-96-97/task_updating_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: nondisruptive, upgrades, NDU, cluster, system, manager, online, help 
summary: 'System Manager를 사용하면 클라이언트 데이터에 대한 액세스를 중단하지 않고 ONTAP 8.3.1 이상을 실행하는 고가용성 \(HA\) 쌍의 클러스터 또는 개별 노드를 특정 버전의 ONTAP 소프트웨어로 업데이트할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 클러스터를 중단 없이 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 이하에서 사용 가능한 ONTAP System Manager 클래식(ONTAP 9.7 버전 사용 가능)을 사용하면 클라이언트 데이터에 대한 액세스를 방해하지 않고 ONTAP 8.3.1 이상을 실행하는 고가용성(HA) 쌍의 클러스터 또는 개별 노드를 특정 버전의 소프트웨어로 업데이트할 수 있습니다.

.시작하기 전에
* 모든 노드는 HA Pair에 있어야 합니다.
* 모든 노드가 정상 상태여야 합니다.
* 노드가 이미지에 액세스할 수 있도록 NetApp Support 사이트에서 네트워크의 HTTP 서버 또는 FTP 서버로 소프트웨어 이미지를 복사해야 합니다.
+
link:task_obtaining_ontap_software_images.html["ONTAP 소프트웨어 이미지를 가져오는 중입니다"]



.이 작업에 대해
* 클러스터 관리 LIF를 호스팅하는 노드를 업데이트하는 동안 System Manager에서 다른 작업을 수행하려고 하면 오류 메시지가 표시될 수 있습니다.
+
작업을 수행하기 전에 업데이트가 완료될 때까지 기다려야 합니다.

* 8개 미만의 노드가 있는 클러스터에 대해 롤링 업데이트가 수행되고 8개 이상의 노드가 있는 클러스터에 대해 일괄 업데이트가 수행됩니다.
+
롤링 업데이트에서 클러스터의 노드가 한 번에 하나씩 업데이트됩니다. 일괄 업데이트에서 여러 노드가 동시에 업데이트됩니다.

* LTS(Long-Term Service) 릴리스로 ONTAP 소프트웨어를 LTS+1(LTS 릴리즈)로 중단 없이 업데이트할 수 있습니다.
+
예를 들어, ONTAP 9.1 및 ONTAP 9.3이 LTS 릴리즈인 경우 중단 없이 클러스터를 ONTAP 9.1에서 ONTAP 9.3으로 업데이트할 수 있습니다.

* System Manager 9.6부터 NVMe 프로토콜이 System Manager 9.5에 구성되어 있고 System Manager 9.5에서 System Manager 9.6으로 업그레이드를 수행하는 경우, 라이센스 없이 NVMe 프로토콜을 사용할 수 있는 유예 기간이 90일이 없습니다. ONTAP 9.5에서 9.6으로 업그레이드할 때 유예 기간이 유효한 경우, NVMe 기능을 계속 사용할 수 있도록 유예 기간을 유효한 NVMeoF 라이센스로 교체해야 합니다.
+
이 기능은 MetroCluster 구성에서 사용할 수 없습니다.

* NVMe 프로토콜이 System Manager 9.5에 구성되어 있지 않고 System Manager 9.5에서 System Manager 9.6으로 업데이트를 수행하는 경우 유예 기간이 제공되지 않으며 NVMe 프로토콜을 사용하려면 NVMe 라이센스를 설치해야 합니다.
+
이 기능은 MetroCluster 구성에서 사용할 수 없습니다.

* ONTAP 9.5부터 NVMe 프로토콜을 사용하여 HA 쌍의 각 노드에 대해 하나 이상의 NVMe LIF를 구성해야 합니다. 노드당 최대 2개의 NVMe LIF를 생성할 수도 있습니다. ONTAP 9.5로 업그레이드할 때는 NVMe 프로토콜을 사용하여 HA 쌍의 각 노드에 대해 최소 하나의 NVMe LIF를 정의해야 합니다.


.단계
. 구성 * > * 클러스터 * > * 업데이트 * 를 클릭합니다.
. Update * (업데이트 *) 탭에서 새 이미지를 추가하거나 사용 가능한 이미지를 선택합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
로컬 클라이언트에서 새 소프트웨어 이미지를 추가합니다
 a| 
.. 로컬 클라이언트에서 추가 * 를 클릭합니다.
.. 소프트웨어 이미지를 검색한 다음 * 열기 * 를 클릭합니다.




 a| 
NetApp Support 사이트에서 새 소프트웨어 이미지를 추가합니다
 a| 
.. 서버에서 추가 * 를 클릭합니다.
.. 새 소프트웨어 이미지 추가 대화 상자에서 NetApp Support 사이트에서 다운로드한 이미지를 저장한 HTTP 서버 또는 FTP 서버의 URL을 입력합니다.
+
익명 FTP의 경우 에서 URL을 지정해야 합니다 `+ftp://anonymous@ftpserver+` 형식.

.. 추가 * 를 클릭합니다.




 a| 
사용 가능한 이미지를 선택합니다
 a| 
나열된 이미지 중 하나를 선택합니다.

|===
. Validate * 를 클릭하여 사전 업데이트 검증 검사를 실행하여 클러스터가 업데이트 준비 상태인지 확인합니다.
+
검증 작업에서는 클러스터 구성 요소를 점검하여 업데이트를 중단 없이 완료할 수 있는지 확인하고 모든 오류 또는 경고를 표시합니다. 또한 소프트웨어를 업데이트하기 전에 수행해야 하는 모든 필수 개선 조치가 표시됩니다.

+
[NOTE]
====
업데이트를 진행하기 전에 오류에 대해 필요한 모든 개선 조치를 수행해야 합니다. 경고에 대한 개선 조치를 무시할 수 있지만 업데이트를 진행하기 전에 모든 개선 조치를 수행하는 것이 가장 좋습니다.

====
. 다음 * 을 클릭합니다.
. Update * 를 클릭합니다.
+
유효성 검사가 다시 수행됩니다.

+
** 검증이 완료되면 테이블에 오류 및 경고와 함께 진행하기 전에 수행해야 할 모든 필수 개선 조치가 표시됩니다.
** 유효성 검사가 경고와 함께 완료되면 * 경고와 함께 업데이트 계속 * 확인란을 선택한 다음 * 계속 * 을 클릭합니다.
유효성 검사가 완료되고 업데이트가 진행 중인 경우 오류로 인해 업데이트가 일시 중지될 수 있습니다. 오류 메시지를 클릭하여 세부 정보를 확인한 다음 업데이트를 다시 시작하기 전에 수정 조치를 수행할 수 있습니다.


+
업데이트가 성공적으로 완료되면 노드가 재부팅되며 System Manager 로그인 페이지로 리디렉션됩니다. 노드를 재부팅하는 데 시간이 오래 걸리는 경우 브라우저를 새로 고쳐야 합니다.

. System Manager에 로그인하고 * 구성 * > * 클러스터 * > * 업데이트 * > * 업데이트 기록 * 을 클릭한 다음 세부 정보를 확인하여 클러스터가 선택한 버전으로 성공적으로 업데이트되었는지 확인합니다.


* 관련 정보 *

xref:concept_how_you_update_cluster_nondisruptively.adoc[클러스터를 중단 없이 업데이트하는 방법]
