---
permalink: online-help-96-97/task_creating_luns.html 
sidebar: sidebar 
keywords: create, lun, system, manager, qtree, online, help 
summary: '여유 공간이 있을 경우 System Manager를 사용하여 기존 애그리게이트, 볼륨 또는 qtree에 대한 LUN을 생성할 수 있습니다. 기존 볼륨에 LUN을 생성하거나 LUN에 대한 새 FlexVol 볼륨을 생성할 수 있습니다. 또한 스토리지 QoS(서비스 품질)를 활성화하여 워크로드 성능을 관리할 수도 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 LUN을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전 을 사용하면 사용 가능한 여유 공간이 있을 때 기존 애그리게이트, 볼륨 또는 qtree용 LUN을 생성할 수 있습니다. 기존 볼륨에 LUN을 생성하거나 LUN에 대한 새 FlexVol 볼륨을 생성할 수 있습니다. 또한 스토리지 QoS(서비스 품질)를 활성화하여 워크로드 성능을 관리할 수도 있습니다.

.이 작업에 대해
LUN ID를 지정하면 System Manager에서 LUN ID를 추가하기 전에 LUN ID의 유효성을 검사합니다. LUN ID를 지정하지 않으면 ONTAP 소프트웨어가 자동으로 LUN ID를 할당합니다.

LUN 멀티프로토콜 유형을 선택할 때는 각 유형 사용 지침을 고려해야 합니다. LUN 다중 프로토콜 유형 또는 운영 체제 유형에 따라 LUN의 데이터 레이아웃과 LUN의 최소 및 최대 크기가 결정됩니다. LUN을 생성한 후에는 LUN 호스트 운영 체제 유형을 수정할 수 없습니다.

MetroCluster 구성에서 LUN에 대한 FlexVol 볼륨을 생성하기 위한 다음과 같은 애그리게이트만 표시합니다.

* 정상 모드에서는 운영 사이트에서 동기식 소스 SVM이나 데이터 제공 SVM에 볼륨을 생성할 때 운영 사이트의 클러스터에 속한 애그리게이트만 표시됩니다.
* 스위치 오버 모드에서는 동기식-타겟 SVM 또는 활성 사이트의 데이터 지원 SVM에 볼륨을 생성할 때 SVM만 표시됩니다.


.단계
. 스토리지 * > * LUN * 을 클릭합니다.
. LUN 관리 * 탭에서 * 생성 * 을 클릭합니다.
. LUN을 생성할 SVM을 찾아 선택합니다.
. LUN 생성 마법사 * 에서 LUN의 이름, 크기, 유형, 설명을 지정하고 * 공간 예약 * 을 선택한 후 * 다음 * 을 클릭합니다.
. LUN에 사용할 새 FlexVol 볼륨을 생성하거나 기존 볼륨 또는 qtree를 선택한 후 * 다음 * 을 클릭합니다.
. LUN에 대한 호스트 액세스를 제어하려면 이니시에이터 그룹을 추가하고 * 다음 * 을 클릭합니다.
. LUN의 워크로드 성능을 관리하려면 * 스토리지 서비스 품질 관리 * 확인란을 선택합니다.
. 새 스토리지 QoS 정책 그룹을 생성하거나 기존 정책 그룹을 선택하여 LUN의 입출력 성능을 제어합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
새 정책 그룹을 생성합니다
 a| 
.. 새 정책 그룹 * 을 선택합니다
.. 정책 그룹 이름을 지정합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS 및 B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""Unlimited""를 값으로 표시하고 이 값은 대/소문자를 구분합니다.
+
지정하는 단위는 최대 처리량에 영향을 주지 않습니다.







 a| 
기존 정책 그룹을 선택합니다
 a| 
.. 기존 정책 그룹 * 을 선택한 다음 * 선택 * 을 클릭하여 정책 그룹 선택 대화 상자에서 기존 정책 그룹을 선택합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS 및 B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""Unlimited""를 값으로 표시하고 이 값은 대/소문자를 구분합니다.
+
지정하는 단위는 최대 처리량에 영향을 주지 않습니다.



+
정책 그룹이 둘 이상의 개체에 할당된 경우 지정한 최대 처리량은 객체 간에 공유됩니다.



|===
. LUN summary * 창에서 지정된 세부 정보를 검토한 후 * Next * 를 클릭합니다.
. 세부 정보를 확인한 다음 * 마침 * 을 클릭하여 마법사를 완료합니다.


* 관련 정보 *

xref:reference_luns_window.adoc[LUN 창]

xref:concept_lun_multiprotocol_type_guidelines.adoc[LUN 멀티프로토콜 유형 사용 지침]
