---
permalink: online-help-96-97/task_creating_nvme_namespace.html 
sidebar: sidebar 
keywords: system, manager, create, nvme, namespace, svm, logical, blocks, online, help 
summary: 'System Manager를 사용하여 하나 이상의 NVMe 네임스페이스를 생성하고 SVM(스토리지 가상 머신)의 호스트 또는 호스트 세트에 각각 연결할 수 있습니다. NVMe 네임스페이스는 논리 블록으로 포맷할 수 있는 메모리 양입니다. 각 네임스페이스를 NVMe 하위 시스템에 매핑할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 NVMe 네임스페이스를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 하나 이상의 NVMe 네임스페이스를 만들고 각 네임스페이스를 SVM(스토리지 가상 시스템)의 호스트 또는 호스트 세트에 연결할 수 있습니다. NVMe 네임스페이스는 논리 블록으로 포맷할 수 있는 메모리 양입니다. 각 네임스페이스를 NVMe 하위 시스템에 매핑할 수 있습니다.

.시작하기 전에
SVM은 NVMe 프로토콜로 이미 구성되어 있어야 합니다. 네임스페이스를 매핑하려면 데이터 프로토콜 NVMe를 사용하는 LIF 중 하나 이상이 네임스페이스를 소유한 노드에 존재해야 합니다.

.단계
. 스토리지 * > * NVMe * > * NVMe 네임스페이스 * 를 클릭합니다.
. 네임스페이스가 포함된 SVM을 선택합니다.
. HA 쌍의 각 노드에 대해 하나 이상의 NVMe LIF가 구성되어 있는지 확인합니다. 노드당 최대 2개의 NVMe LIF를 생성할 수 있다.
. 네임스페이스 크기(1MB~16TB)를 구성합니다.
. 블록 크기를 입력합니다.
+
System Manager 9.5의 경우 블록 크기는 기본적으로 4KB이며 이 필드는 표시되지 않습니다.

+
System Manager 9.6의 경우 블록 크기를 4KB 또는 512바이트로 지정할 수 있습니다.

. 기존 볼륨을 선택하거나 애그리게이트를 선택하여 새 볼륨을 생성합니다.
+
SVM에서 + 기호를 클릭하여 추가 네임스페이스(최대 250)를 설정합니다.

. 이 네임스페이스와 연결될 NVMe 하위 시스템을 선택합니다.
+
다음 옵션 중에서 선택할 수 있습니다.

+
** 없음: 매핑된 서브시스템이 없습니다.
** 기존 서브시스템 사용: 나열된 서브시스템은 선택한 SVM을 기반으로 합니다.
** 새 하위 시스템 만들기: 새 하위 시스템을 만들고 모든 새 네임스페이스에 매핑할 수 있습니다.


. 호스트 운영 체제를 선택합니다.
. 제출 * 을 클릭합니다.


* 관련 정보 *

xref:reference_nvme_namespaces_window.adoc[NVMe 네임스페이스 창]
