---
permalink: online-help-96-97/task_deleting_volumes.html 
sidebar: sidebar 
keywords: online, help, delete, volumes, system, manager, flexvol, volume 
summary: 볼륨에 포함된 데이터가 더 이상 필요하지 않거나 볼륨에 포함된 데이터를 다른 위치로 복사한 경우 System Manager를 사용하여 FlexVol 볼륨을 삭제할 수 있습니다. 볼륨을 삭제하면 볼륨의 모든 데이터가 제거되고 해당 데이터를 복구할 수 없습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 볼륨을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에 포함된 데이터가 더 이상 필요하지 않거나 볼륨에 포함된 데이터를 다른 위치로 복사한 경우 ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)을 사용하여 FlexVol 볼륨을 삭제할 수 있습니다. 볼륨을 삭제하면 볼륨의 모든 데이터가 제거되고 해당 데이터를 복구할 수 없습니다.

.시작하기 전에
FlexVol 볼륨을 삭제하기 전에 다음 조건이 존재해야 합니다.

* 볼륨은 마운트 해제되어야 하며 오프라인 상태여야 합니다.
* FlexClone 볼륨은 상위 볼륨에서 분리되거나 FlexVol 볼륨이 복제된 경우 폐기되어야 합니다.
* 볼륨이 하나 이상의 SnapMirror 관계에 있는 경우 SnapMirror 관계를 삭제해야 합니다.


.이 작업에 대해
FlexVol 볼륨을 삭제할 때 다음과 같은 제한 사항에 유의해야 합니다.

* 전체 SnapLock 엔터프라이즈 볼륨 또는 SnapLock 엔터프라이즈 볼륨의 파일을 삭제할 수 있지만 SnapLock 엔터프라이즈 볼륨의 파일 내 데이터만 삭제할 수는 없습니다.
* 데이터가 볼륨에 커밋된 경우 SnapLock Compliance 볼륨을 삭제할 수 없습니다.
* FlexVol에 qtree와 볼륨이 모두 포함되어 있으면 qtree가 디렉토리로 표시됩니다. 볼륨을 삭제할 때 실수로 Qtree를 삭제하지 않도록 주의해야 합니다.
* 원본 볼륨과 FlexCache 볼륨을 연결한 경우 원본 볼륨을 삭제하려면 먼저 FlexCache 볼륨을 삭제해야 합니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 삭제할 볼륨이 상주하는 SVM(스토리지 가상 머신)을 선택합니다.
. 삭제할 볼륨을 선택합니다.
+
[NOTE]
====
삭제할 올바른 볼륨을 선택했는지 확인합니다. 볼륨을 삭제하면 볼륨의 모든 데이터가 제거되고 해당 데이터를 복구할 수 없습니다.

====
. 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
