---
permalink: online-help-96-97/task_editing_mirror_vault_relationships.html 
sidebar: sidebar 
keywords: edit, mirror, vault, relationship, system, manager, online, help 
summary: 선택한 정책 또는 스케줄을 수정하여 System Manager를 사용하여 미러 및 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 미러 및 볼트 관계를 관리합니다
:allow-uri-read: 


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)을 사용하여 미러 및 볼트 관계를 관리할 수 있습니다. 편집, 삭제, 초기화, 업데이트, 정지, 대칭 복사 및 볼트 관계를 다시 시작하고 중단하십시오. 대상 SVM에서 미러 및 소산 관계를 생성하는 것 외에 재동기화 또는 역방향 재동기화 작업을 수행할 수도 있습니다.



== 관계 편집

선택한 정책 또는 스케줄을 수정하여 System Manager를 사용하여 미러 및 볼트 관계를 편집할 수 있습니다. 그러나 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다.

.시작하기 전에
소스 및 대상 클러스터는 정상 피어 관계에 있어야 합니다.

.이 작업에 대해
정책 유형을 수정하여 버전에 상관없이 유연한 미러 관계, 볼트 관계, 미러 및 볼트 관계의 관계 유형을 수정할 수 있습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 수정하려는 대칭 복사 및 볼트 관계를 선택한 다음 * 편집 * 을 클릭합니다.
. [관계 편집] * 대화 상자에서 적절한 작업을 선택합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
기존 정책을 선택합니다
 a| 
찾아보기 * 를 클릭한 다음 기존 정책을 선택합니다.    소스 볼륨에 연결된 스냅샷 정책과 일치하는 최대 레이블 수를 갖는 정책을 선택할 수 있습니다.



 a| 
새 정책을 생성합니다
 a| 
.. Create Policy * 를 클릭합니다.
.. 정책의 이름을 지정합니다.
.. 예약된 전송의 우선 순위를 설정합니다.
+
낮음 은 전송 우선 순위가 가장 낮으며 일반적으로 일반 우선 순위 전송 후에 예약됨을 나타냅니다. 기본적으로 우선 순위는 보통으로 설정됩니다.

.. 전송 중인 데이터를 압축하려면 * 네트워크 압축 사용 * 확인란을 선택합니다.
.. 볼트 정책에 대한 SnapMirror 레이블 및 대상 보존 수를 지정합니다.
+
새 SnapMirror 레이블을 사용하려면 소스 볼륨에 동일한 레이블이 있는 스냅샷 복사본이 생성되었는지 확인해야 합니다.

.. Create * 를 클릭합니다.


|===
. 관계의 일정을 지정합니다.
+
|===
| 만약... | 다음을 수행합니다. 


 a| 
기존 일정을 할당하려고 합니다
 a| 
찾아보기 * 를 클릭한 다음 기존 일정을 선택합니다.



 a| 
새 스케줄을 생성하려고 합니다
 a| 
.. Create Schedule * 을 클릭합니다.
.. 스케줄의 이름을 지정합니다.
.. 다음 옵션 중 하나를 선택합니다.
+
*** * 기본 *
+
이 옵션을 선택하면 요일, 시간 및 전송 간격만 지정할 수 있습니다.

*** * 고급 *
+
이 옵션을 선택하여 cron 스타일 일정을 지정할 수 있습니다.



.. Create * 를 클릭합니다.




 a| 
일정을 지정하지 않으려는 경우
 a| 
없음 * 을 선택합니다.

|===
. 확인 * 을 클릭합니다.




== 관계를 수동으로 업데이트합니다

System Manager를 사용하여 예약되지 않은 증분 업데이트를 수동으로 시작할 수 있습니다. 향후 정전, 예정된 유지보수 또는 데이터 마이그레이션으로 인한 데이터 손실을 방지하려면 수동 업데이트가 필요할 수 있습니다.

.시작하기 전에
미러 및 볼트 관계는 초기화되고 SnapMirrored 상태여야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 데이터를 업데이트할 미러 관계를 선택한 다음 * 운영 * > * 업데이트 * 를 클릭합니다.
. 다음 옵션 중 하나를 선택합니다.
+
** 소스 볼륨과 타겟 볼륨 간의 최근 공통 스냅샷 복사본에서 증분 전송을 수행하려면 정책에 따라 * 를 선택합니다.
** 스냅샷 복사본 선택 * 을 선택하고 전송할 스냅샷 복사본을 지정합니다.


. 전송에 사용되는 네트워크 대역폭을 제한하려면 * 전송 대역폭 제한 * 을 선택하고 최대 전송 속도를 지정합니다.
. Update * 를 클릭합니다.
. 세부 정보 * 탭에서 전송 상태를 확인합니다.




== 관계 초기화

관계를 생성하는 동안 관계를 초기화하지 않은 경우 System Manager를 사용하여 미러 및 볼트 관계를 초기화할 수 있습니다. 관계를 초기화할 때 데이터의 전체 베이스라인 전송이 소스 볼륨에서 대상으로 수행됩니다.

.시작하기 전에
소스 및 대상 클러스터는 정상 피어 관계에 있어야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 초기화하려는 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 초기화 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * Initialize * 를 클릭합니다.
. Protection * 창에서 관계 상태를 확인합니다.


.결과
스냅샷 복사본이 생성되어 타겟으로 전송됩니다.

이 스냅샷 복사본은 이후의 증분 스냅샷 복사본을 위한 기준으로 사용됩니다.



== 대상 SVM에서 관계를 생성합니다

System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 미러링 및 소산 관계를 생성할 수 있습니다. 이 관계를 생성하면 소스 볼륨에서 대상 볼륨으로 데이터를 정기적으로 전송하여 데이터를 보다 안전하게 보호할 수 있습니다. 또한 소스 볼륨의 백업을 생성하여 데이터를 장기간 보존할 수도 있습니다.

.시작하기 전에
* 타겟 클러스터에서 ONTAP 8.3.2 이상이 실행되고 있어야 합니다.
* 소스 클러스터와 대상 클러스터에서 SnapMirror 라이센스가 활성화되어야 합니다.
+
[NOTE]
====
일부 플랫폼의 경우 대상 클러스터에 SnapMirror 라이센스 및 DPO(데이터 보호 최적화) 라이센스가 활성화되어 있는 경우 소스 클러스터에 SnapMirror 라이센스가 활성화되어 있지 않아도 됩니다.

====
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 SVM에 사용 가능한 공간이 있어야 합니다.
* 소스 애그리게이트와 대상 애그리게이트는 64비트 애그리게이트로 이루어져야 합니다.
* 읽기/쓰기(RW) 유형의 소스 볼륨이 이미 있어야 합니다.
* SnapLock 집계 유형은 같아야 합니다.
* ONTAP 9.2 이하를 실행하는 클러스터에서 SAML 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증을 활성화해야 합니다.


.이 작업에 대해
* System Manager는 계단식 관계를 지원하지 않습니다.
+
예를 들어, 관계의 대상 볼륨은 다른 관계의 소스 볼륨이 될 수 없습니다.

* MetroCluster 구성에서는 동기화 소스 SVM과 동기화 대상 SVM 간에 미러링 및 소산 관계를 생성할 수 없습니다.
* MetroCluster 구성에서 동기화 소스 SVM 간에 미러 및 소산 관계를 생성할 수 있습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 지원 SVM의 볼륨으로 미러 및 소산 관계를 생성할 수 있습니다.
* 데이터 지원 SVM의 볼륨에서 동기화 소스 SVM의 DP 볼륨으로 미러 및 소산 관계를 생성할 수 있습니다.
* 한 번에 최대 25개의 볼륨을 보호할 수 있습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 관계 * 창에서 * 생성 * 을 클릭합니다.
. SVM * 찾아보기 대화 상자에서 타겟 볼륨의 SVM을 선택합니다.
. [보호 관계 작성] * 대화 상자의 [관계 유형 *] 드롭다운 목록에서 * [미러] 및 [볼트 *]를 선택합니다.
. 클러스터, SVM 및 소스 볼륨을 지정합니다.
+
지정된 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 지정된 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

. 볼륨 이름 접미사를 입력합니다.
+
대상 볼륨 이름을 생성하기 위해 소스 볼륨 이름에 볼륨 이름 접미사가 추가됩니다.

. * 선택 사항: * 찾아보기 * 를 클릭한 다음 미러 및 볼트 정책을 변경합니다.
+
소스 볼륨에 연결된 스냅샷 정책과 일치하는 최대 레이블 수를 갖는 정책을 선택할 수 있습니다.

. 기존 일정 목록에서 관계의 일정을 선택합니다.
. * 선택 사항: * 관계 초기화 * 를 선택하여 관계를 초기화합니다.
. FabricPool 지원 애그리게이트를 사용하도록 설정한 다음 적절한 계층화 정책을 선택합니다.
. 선택한 볼륨에 일치하는 레이블이 있는지 확인하려면 * Validate * 를 클릭합니다.
. Create * 를 클릭합니다.




== 관계를 재동기화합니다

System Manager를 사용하여 이전에 파손된 미러 및 볼트 관계를 다시 설정할 수 있습니다. 재동기화 작업을 수행하여 소스 볼륨을 비활성화한 재재해에서 복구할 수 있습니다.

.시작하기 전에
소스 및 타겟 클러스터와 소스 및 타겟 SVM(스토리지 가상 머신)이 피어 관계에 있어야 합니다.

.이 작업에 대해
재동기화 작업을 수행하기 전에 다음 사항에 유의해야 합니다.

* 재동기화 작업을 수행하면 대상 볼륨의 컨텐츠가 소스의 컨텐츠로 덮어쓰여집니다.
+
[NOTE]
====
재동기화 작업을 수행하면 기본 스냅샷 복제본이 생성된 후 대상 볼륨에 기록된 최신 데이터가 손실될 수 있습니다.

====
* 보호 창의 마지막 전송 오류 필드에서 재동기화 작업을 권장하는 경우 먼저 관계를 끊은 다음 재동기화 작업을 수행해야 합니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 재동기화하려는 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 재동기화 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 재동기화 * 를 클릭합니다.




== 관계를 다시 동기화합니다

System Manager를 사용하여 이전에 손상된 미러 및 볼트 관계를 다시 설정할 수 있습니다. 역방향 재동기화 작업에서는 소스 볼륨과 타겟 볼륨의 기능이 반전됩니다. 소스를 복구 또는 교체하고 소스를 업데이트하고 시스템의 원래 구성을 다시 설정하는 동안 대상 볼륨을 사용하여 데이터를 제공할 수 있습니다.

.시작하기 전에
소스 볼륨이 온라인 상태여야 합니다.

.이 작업에 대해
* 역방향 재동기화를 수행하면 소스 볼륨의 컨텐츠가 대상 볼륨의 컨텐츠로 덮어쓰여집니다.
+
[NOTE]
====
재동기화 작업을 수행하면 소스 볼륨에서 데이터가 손실될 수 있습니다.

====
* 역재동기화를 수행하면 관계 정책이 MirrorAndVault로 설정되고 스케줄이 None으로 설정됩니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 대칭 복사하려는 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 역재동기화 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 역방향 재동기화 * 를 클릭합니다.




== 관계 끊기

소스 볼륨을 사용할 수 없게 되고 클라이언트 응용 프로그램이 대상 볼륨의 데이터에 액세스하도록 하려는 경우 System Manager를 사용하여 미러 및 볼트 관계를 중단할 수 있습니다. 소스 볼륨을 복구 또는 교체하고 소스 볼륨을 업데이트하고 시스템의 원래 구성을 다시 설정하는 동안 대상 볼륨을 사용하여 데이터를 제공할 수 있습니다.

.시작하기 전에
* 미러 및 볼트 관계가 중지 상태 또는 유휴 상태여야 합니다.
* 대상 볼륨은 대상 SVM(스토리지 가상 시스템) 네임스페이스에 마운트되어야 합니다.


.이 작업에 대해
ONTAP 시스템과 SolidFire 스토리지 시스템 간의 미러 관계를 분리할 수 있습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 분리하려는 대칭 복사 및 볼트 관계를 선택한 다음 * 작업 * > * 분리 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * Break * (휴식 *)를 클릭합니다.


.결과
대칭 복사 및 볼트 관계가 손상되었습니다. 타겟 볼륨 유형이 데이터 보호(DP)에서 읽기 전용으로 읽기/쓰기로 변경됩니다. 시스템은 나중에 사용할 수 있도록 미러 및 볼트 관계의 기본 스냅샷 복사본을 저장합니다.



== 관계를 재개합니다

중지된 미러 및 볼트 관계가 있는 경우 System Manager를 사용하여 관계를 다시 시작할 수 있습니다. 관계를 재개하면 대상 볼륨에 대한 정상적인 데이터 전송이 재개되고 모든 보호 작업이 다시 시작됩니다.

.이 작업에 대해
CLI(Command-Line Interface)에서 손상된 미러 및 볼트 관계를 중지했다면 System Manager에서 관계를 재개할 수 없습니다. CLI를 사용하여 관계를 재개해야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 재개할 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 재개 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * Resume * 을 클릭합니다.


.결과
정상적인 데이터 전송이 다시 시작됩니다. 관계에 대해 예약된 전송이 있는 경우 다음 일정에서 전송이 시작됩니다.



== 관계 삭제

System Manager를 사용하여 소스 볼륨과 타겟 볼륨 간의 미러 및 소산 관계를 종료 하고 소스 볼륨에서 스냅샷 복사본을 릴리즈할 수 있습니다.

.이 작업에 대해
* 관계를 삭제하기 전에 미러와 볼트 관계를 끊는 것이 가장 좋습니다.
* 관계를 다시 생성하려면 CLI(Command-Line Interface)를 사용하여 소스 볼륨에서 재동기화 작업을 실행해야 합니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 삭제할 대칭 복사 및 볼트 관계를 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.
+
또한 기본 스냅샷 복사본 릴리즈 확인란을 선택하여 소스 볼륨의 미러 및 소산 관계에 사용되는 기본 스냅샷 복사본을 삭제할 수 있습니다.

+
관계가 릴리즈되지 않은 경우 소스 클러스터에서 릴리즈 작업을 실행하려면 CLI를 사용하여 소스 볼륨에서 미러 및 소산 관계에 대해 생성한 기본 스냅샷 복사본을 삭제해야 합니다.



.결과
관계가 삭제되고 소스 볼륨의 기본 스냅샷 복사본이 영구적으로 삭제됩니다.



== 관계를 중지합니다

System Manager를 사용하여 대상 볼륨을 정지하여 스냅샷 복사본을 생성하기 전에 대상을 안정화할 수 있습니다. 일시 중지 작업을 수행하면 활성 데이터 전송이 완료되며 미러 및 볼트 관계에 대한 향후 전송이 비활성화됩니다.

.시작하기 전에
미러와 볼트 관계는 스냅미러 상태여야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 정지할 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 정지 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 정지 * 를 클릭합니다.


.결과
진행 중인 전송이 없으면 전송 상태가 로 표시됩니다 `Quiesced`. 전송이 진행 중인 경우 전송은 영향을 받지 않으며 전송 상태는 로 표시됩니다 `Quiescing` 전송이 완료될 때까지
