---
permalink: online-help-96-97/task_restoring_volume_mirror_vault_relationship.html 
sidebar: sidebar 
keywords: restore, volume, mirror, vault, relationship, online, help, snapshot, copy, system, manager 
summary: 소스 데이터가 손상되어 더 이상 사용할 수 없는 경우 System Manager를 사용하여 스냅샷 복사본을 소스 볼륨 또는 다른 볼륨으로 복원할 수 있습니다. 원래 데이터를 타겟 볼륨의 스냅샷 복사본으로 대체할 수 있습니다. 
---
= 시스템 관리자-ONTAP 9.7 이전 버전을 사용하여 미러 및 볼트 관계의 볼륨을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 소스 데이터가 손상되어 더 이상 사용할 수 없는 경우 소스 볼륨 또는 다른 볼륨으로 스냅샷 복사본을 복원할 수 있습니다. 원래 데이터를 타겟 볼륨의 스냅샷 복사본으로 대체할 수 있습니다.

.시작하기 전에
* 소스 클러스터와 타겟 클러스터 또는 소스 볼륨과 타겟 볼륨이 포함된 노드에서 SnapMirror 라이센스 및 SnapVault 라이센스를 활성화해야 합니다.
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 복원 작업에 선택한 소스 애그리게이트 또는 기타 애그리게이트는 64비트 애그리게이트여야 합니다.
* ONTAP 9.2 이하를 실행하는 클러스터에서 SAML 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증도 활성화해야 합니다.


.이 작업에 대해
* MetroCluster 구성에서는 소스 스토리지 가상 시스템(SVM)과 타겟 SVM 간의 미러 및 소산 관계에 있는 볼륨을 복구할 수 없습니다.
* 다음 설정에 대해 대칭 복사 및 볼트 관계를 복원할 수 있습니다.
+
** MetroCluster 구성에서 동기식 소스 SVM 간에 사용
** 동기화 소스 SVM의 볼륨에서 기본 SVM으로
** 기본 SVM의 볼륨에서 동기화 소스 SVM의 DP 볼륨으로 이동합니다




.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 복원하려는 미러 및 볼트 관계를 선택한 다음 * 작업 * > * 복원 * 을 클릭합니다.
. Restore * 대화 상자에서 관계의 소스 볼륨으로 데이터를 복원하거나 다른 볼륨을 선택합니다.
+
|===
| 데이터를 다음 상태로 복원하려는 경우... | 수행할 작업... 


 a| 
소스 볼륨입니다
 a| 
.. 소스 볼륨 * 을 선택합니다.
.. link:#step6["6단계로 이동합니다"].




 a| 
기타 모든 볼륨
 a| 
Other volume * 을 선택한 다음 클러스터와 SVM을 선택합니다.

|===
. 데이터를 새 볼륨 또는 기존 볼륨으로 복원:
+
|===
| 데이터를 다음 상태로 복원하려는 경우... | 수행할 작업... 


 a| 
새 볼륨
 a| 
"destination_SVM_name_destination_volume_name_restore" 형식으로 표시되는 기본 이름을 변경하려면 새 이름을 지정한 다음 해당 볼륨의 포함된 애그리게이트를 선택합니다.



 a| 
기존 볼륨
 a| 
볼륨 선택 * 옵션을 선택합니다.

소스 볼륨 이외의 볼륨이나 일부 데이터가 포함된 읽기/쓰기 볼륨과 공통 스냅샷 복사본을 선택해야 합니다.

소스 볼륨과 언어 속성이 동일한 볼륨만 나열됩니다.

|===
. 최신 스냅샷 복사본 또는 복원하려는 특정 스냅샷 복사본을 선택합니다.
. [[step6]] 스냅샷 복사본에서 볼륨을 복원하려면 확인 확인란을 선택합니다.
. * 선택 사항: * [네트워크 압축 사용] * 확인란을 선택하여 복원 작업 중에 전송되는 데이터를 압축합니다.
. 복원 * 을 클릭합니다.

