---
permalink: online-help-96-97/task_viewing_flexgroup_volume_information.html 
sidebar: sidebar 
keywords: flexgroup, volume, graphical, online, help, system, manager 
summary: 시스템 관리자를 사용하여 FlexGroup 볼륨에 대한 정보를 볼 수 있습니다. 할당된 공간, 보호 상태 및 FlexGroup 볼륨의 성능에 대한 그래픽 표시를 볼 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 FlexGroup 볼륨 정보를 확인하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 FlexGroup 볼륨에 대한 정보를 볼 수 있습니다. 할당된 공간, 보호 상태 및 FlexGroup 볼륨의 성능에 대한 그래픽 표시를 볼 수 있습니다.

.이 작업에 대해
또한 FlexGroup 볼륨에 사용할 수 있는 스냅샷 복사본, FlexGroup 볼륨에 대한 데이터 보호 관계, 평균 성능 메트릭, 읽기 성능 메트릭, 지연 시간, IOPS, 처리량을 기준으로 FlexGroup 볼륨의 쓰기 성능 메트릭 등을 확인할 수 있습니다.

.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 표시된 FlexGroup 볼륨 목록에서 정보를 보려는 FlexGroup 볼륨을 선택합니다.
+
FlexGroup 볼륨, FlexGroup 볼륨에 할당된 공간, FlexGroup 볼륨의 보호 상태 및 FlexGroup 볼륨에 대한 성능 정보가 표시됩니다.

. FlexGroup 볼륨에 대한 자세한 내용을 보려면 * 자세한 정보 표시 * 링크를 클릭하십시오.
. FlexGroup 볼륨의 스냅샷 복사본을 보려면 * Snapshot 복사본 * 탭을 클릭합니다.
. FlexGroup 볼륨의 데이터 보호 관계를 보려면 * 데이터 보호 * 탭을 클릭합니다.
. 스토리지 효율성 설정을 보려면 * 스토리지 효율성 * 탭을 클릭하십시오.
. 성능 * 탭을 클릭하여 지연 시간, IOPS 및 처리량을 기준으로 FlexGroup 볼륨의 평균 성능 메트릭, 읽기 성능 메트릭 및 쓰기 성능 메트릭을 확인할 수 있습니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
