---
permalink: online-help-96-97/task_configuring_iscsi_protocol_on_svms.html 
sidebar: sidebar 
keywords: system, manager, iscsi, protocol, svm, online, help, lif, portset 
summary: 'SVM(스토리지 가상 시스템)에서 iSCSI 프로토콜을 구성하여 System Manager를 통해 블록 레벨 데이터 액세스를 제공할 수 있습니다. iSCSI LIF 및 포트 세트를 생성한 다음 포트 세트에 LIF를 추가할 수 있습니다. LIF는 가장 적합한 어댑터에 생성되며 데이터 경로 이중화를 위해 포트 세트에 할당됩니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SVM에서 iSCSI 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 블록 레벨 데이터 액세스를 제공하기 위해 SVM(스토리지 가상 머신)에서 iSCSI 프로토콜을 구성할 수 있습니다. iSCSI LIF 및 포트 세트를 생성한 다음 포트 세트에 LIF를 추가할 수 있습니다. LIF는 가장 적합한 어댑터에 생성되며 데이터 경로 이중화를 위해 포트 세트에 할당됩니다.

.시작하기 전에
* 클러스터에서 iSCSI 라이센스를 활성화해야 합니다.
+
SVM에서 iSCSI 프로토콜이 활성화되어 있지 않으면 스토리지 가상 시스템 편집 창을 사용하여 SVM용 프로토콜을 활성화할 수 있습니다.

* 클러스터의 모든 노드가 정상 상태여야 합니다.
* 각 노드에는 2개 이상의 데이터 포트가 있어야 하고 포트 상태는 이어야 합니다 `up`.


.이 작업에 대해
* SVM을 생성하는 동안 iSCSI 프로토콜을 구성하거나 나중에 구성할 수 있습니다.
* SnapLock 애그리게이트는 자동으로 볼륨을 생성하는 것으로 간주되지 않습니다.


.단계
. SVM을 생성하는 동안 iSCSI 프로토콜을 구성하지 않은 경우 * 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * iSCSI * 를 클릭합니다.
. * 선택 사항: * 네트워크 액세스 * 섹션에서 iSCSI 대상의 별칭을 지정합니다.
+
별칭 이름의 최대 문자 수는 128자입니다. 타겟 별칭을 지정하지 않으면 SVM 이름이 별칭으로 사용됩니다.

. 단일 노드에 할당할 수 있는 iSCSI LIF 수를 지정합니다.
+
노드당 최소 LIF 수는 1개입니다. 최대 개수는 에 있는 모든 포트의 최소값입니다 `up` 노드 전반의 상태. 최대값이 홀수이면 이전 짝수가 최대값으로 간주됩니다. 최소 및 최대 값 범위에서 짝수를 선택할 수 있습니다.

+
4노드 클러스터에는 노드1, 노드2 및 노드3가 있으며 각각 6개의 포트가 있습니다 `up` state 및 node4에 7개의 포트가 있습니다 `up` 상태. 클러스터의 유효 최대값은 6입니다.

+
노드에 할당할 LIF 수가 2개 이상인 경우 각 LIF에 적어도 하나의 포트셋 를 할당해야 합니다.

. iSCSI LIF를 생성하려면 서브넷 세부 정보를 포함한 네트워크 세부 정보를 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 아직 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
... 대상 필드의 기본값을 사용하지 않으려면 새 대상 값을 지정합니다.
+
대상 값을 지정하지 않으면 대상 필드는 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.



+
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.

.. 확인 * 을 클릭합니다.


|===
. 브로드캐스트 도메인을 선택합니다.
. 어댑터 유형을 선택합니다.
+
클러스터에 NIC 카드가 구성되어 있는 경우 * NIC * 를 선택해야 합니다.

+
클러스터에 CNS 카드가 구성되어 있는 경우 * CNA * 를 선택해야 합니다.

+
클러스터에서 ifgrp를 구성한 경우 * 인터페이스 그룹 * 을 선택해야 합니다.

+
[NOTE]
====
ifgrp 포트는 브로드캐스트 도메인에 추가해야 합니다.

====
. * 선택 사항: * LUN 크기, LUN의 OS 유형 및 호스트 이니시에이터 세부 정보를 지정하여 iSCSI 프로토콜을 구성할 때 iSCSI 스토리지에 대한 LUN을 프로비저닝합니다.
. 자동으로 생성된 iSCSI LIF의 구성을 확인하거나 수정하려면 * LIF 구성 검토 또는 수정(고급 설정) * 을 선택합니다.
+
LIF 이름과 홈 포트만 수정할 수 있습니다. 기본적으로 포트 세트는 최소값으로 설정됩니다. 고유한 항목을 지정해야 합니다. 중복된 LIF 이름을 지정하면 System Manager에서 중복된 LIF 이름에 숫자 값이 추가됩니다.

+
선택된 포트셋 기반의 LIF는 노드 장애 또는 포트 장애 시 이중화를 보장하기 위해 라운드 로빈 방법을 사용하여 포트 세트 전체에 분산됩니다.

. 제출 및 계속 * 을 클릭합니다.


.결과
iSCSI LIF 및 포트 세트는 지정된 구성으로 생성됩니다. LIF는 선택한 포트셋 기반의 포트 세트 간에 분산됩니다. 모든 LIF가 성공적으로 생성되면 iSCSI 서비스가 시작됩니다.

LIF 생성이 실패하면 네트워크 인터페이스 창을 사용하여 LIF를 생성하고 LUN 창을 사용하여 LIF를 포트 세트에 연결한 다음 iSCSI 창을 사용하여 iSCSI 서비스를 시작할 수 있습니다.
