---
permalink: online-help-96-97/task_configuring_fc_fcoe_protocol_on_svms.html 
sidebar: sidebar 
keywords: online, help, configure, fc, protocol, fcoe, svm, online, help, system, manager 
summary: 'SAN 호스트용 SVM(스토리지 가상 시스템)에서 FC 프로토콜과 FCoE 프로토콜을 구성할 수 있습니다. LIF는 가장 적합한 어댑터에 생성되며 데이터 경로 이중화를 위해 포트 세트에 할당됩니다. 요구사항에 따라 System Manager를 사용하여 FC 프로토콜이나 FCoE 프로토콜을 구성하거나 두 프로토콜을 모두 구성할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SVM에서 FC 프로토콜 및 FCoE 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SAN 호스트용 SVM(스토리지 가상 머신)에서 FC 프로토콜과 FCoE 프로토콜을 구성할 수 있습니다. LIF는 가장 적합한 어댑터에 생성되며 데이터 경로 이중화를 위해 포트 세트에 할당됩니다. 요구사항에 따라 System Manager를 사용하여 FC 프로토콜이나 FCoE 프로토콜을 구성하거나 두 프로토콜을 모두 구성할 수 있습니다.

.시작하기 전에
* 클러스터에서 FCP 라이센스가 활성화되어 있어야 합니다.
* 클러스터의 모든 노드가 정상 상태여야 합니다.
* 각 노드에는 각 프로토콜(FC 및 FCoE)에 대해 2개 이상의 올바르게 구성된 포트가 있어야 합니다.


.이 작업에 대해
* SVM을 생성하는 동안 FC 프로토콜과 FCoE 프로토콜을 구성하거나 나중에 프로토콜을 구성할 수 있습니다.
+
SVM에서 프로토콜이 허용되지 않는 경우 스토리지 가상 시스템 편집 창을 사용하여 SVM용 프로토콜을 활성화할 수 있습니다.

* SnapLock 애그리게이트는 자동으로 볼륨을 생성하는 것으로 간주되지 않습니다.


.단계
. SVM을 생성하는 동안 프로토콜을 구성하지 않은 경우 * Storage * > * SVM * 탭을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * FC/FCoE * 를 클릭합니다.
. Data Interface Configuration * 섹션에서 해당 옵션을 선택하여 FC 프로토콜 및 FCoE 프로토콜에 대한 데이터 LIF를 구성합니다.
. 각 프로토콜에 대해 노드당 데이터 LIF 수를 지정합니다.
+
노드당 최소 LIF 수는 1개입니다. 최대 개수는 에 있는 모든 포트의 최소값입니다 `up` 노드 전반의 상태. 최대값이 홀수이면 이전 짝수가 최대값으로 간주됩니다. 최소 및 최대 값 범위에서 짝수를 선택할 수 있습니다.

+
4노드 클러스터에는 노드1, 노드2 및 노드3가 있으며 각각 6개의 포트가 있습니다 `up` state 및 node4에 7개의 포트가 있습니다 `up` 상태. 클러스터의 유효 최대값은 6입니다.

+
노드에 할당할 LIF 수가 2개 이상인 경우 각 LIF에 적어도 하나의 포트셋 를 할당해야 합니다.

. 자동으로 생성된 LIF 구성을 확인하거나 수정하려면 * 인터페이스 연결 검토 또는 편집 * 을 선택합니다.
+
LIF 이름과 홈 포트만 수정할 수 있습니다. 중복 항목을 지정하지 않도록 해야 합니다.

. * 선택 사항: * LUN 크기, LUN의 OS 유형 및 호스트 이니시에이터 세부 정보를 제공하여 프로토콜을 구성할 때 FC 스토리지 또는 FCoE 스토리지에 대한 LUN을 프로비저닝합니다.
. 제출 및 계속 * 을 클릭합니다.


.결과
데이터 LIF 및 포트 세트는 지정된 구성으로 생성됩니다. LIF는 포트 세트 간에 적절하게 배포됩니다. 하나 이상의 프로토콜에 대한 모든 LIF가 성공적으로 생성된 경우 FCP 서비스가 시작됩니다.

LIF 생성에 실패하면 LIF를 생성하고 FC/FCoE 창에서 FCP 서비스를 시작할 수 있습니다.

* 관련 정보 *

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]
