---
permalink: online-help-96-97/task_obtaining_ontap_software_images.html 
sidebar: sidebar 
keywords: online, help, obtain, ontap, software, image, netapp, support, site, online, help 
summary: ONTAP 9.4 이상의 경우 NetApp Support 사이트에서 로컬 폴더로 ONTAP 소프트웨어 이미지를 복사할 수 있습니다. ONTAP 9.3 이전 버전에서 업그레이드하려면 ONTAP 소프트웨어 이미지를 네트워크의 HTTP 서버 또는 FTP 서버로 복사해야 합니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 ONTAP 소프트웨어 이미지를 얻습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)으로 ONTAP 소프트웨어 이미지를 얻을 수 있습니다. ONTAP 9.4 이상의 경우 NetApp Support 사이트에서 로컬 폴더로 ONTAP 소프트웨어 이미지를 복사할 수 있습니다. ONTAP 9.3 이전 버전에서 업그레이드하려면 ONTAP 소프트웨어 이미지를 네트워크의 HTTP 서버 또는 FTP 서버로 복사해야 합니다.

.이 작업에 대해
클러스터를 ONTAP의 타겟 릴리즈로 업그레이드하려면 소프트웨어 이미지에 액세스해야 합니다. 플랫폼 모델의 소프트웨어 이미지, 펌웨어 버전 정보 및 최신 펌웨어는 NetApp Support 사이트에서 제공됩니다. 다음과 같은 중요 정보를 확인해야 합니다.

* 소프트웨어 이미지는 플랫폼 모델에 따라 다릅니다.
+
클러스터에 맞는 올바른 이미지를 얻어야 합니다.

* 소프트웨어 이미지에는 특정 버전의 ONTAP가 릴리스되었을 때 사용할 수 있는 최신 버전의 시스템 펌웨어가 포함되어 있습니다.
* NetApp 볼륨 암호화가 있는 시스템을 ONTAP 9.5 이상으로 업그레이드할 경우 NetApp 볼륨 암호화를 포함하는 비제한 국가의 ONTAP 소프트웨어 이미지를 다운로드해야 합니다.
+
제한된 국가에서 ONTAP 소프트웨어 이미지를 사용하여 NetApp 볼륨 암호화를 사용하는 시스템을 업그레이드하면 시스템 패닉이 발생하고 볼륨에 대한 액세스가 손실됩니다.

* ONTAP 9.3에서 9.7로 업그레이드하는 경우 ONTAP 9.5 및 9.7용 소프트웨어 이미지를 복사해야 합니다.


.단계
. NetApp Support 사이트의 * 소프트웨어 다운로드 * 영역에서 타겟 ONTAP 소프트웨어를 찾습니다.
. 소프트웨어 이미지를 복사합니다.
+
** ONTAP 9.3 이하 버전의 경우 소프트웨어 이미지(예: `93_q_image.tgz`) NetApp Support 사이트에서 이미지를 제공할 HTTP 서버 또는 FTP 서버의 디렉토리로 이동합니다
** ONTAP 9.4 이상의 경우 소프트웨어 이미지(예: `97_q_image.tgz`) NetApp Support 사이트에서 이미지를 제공할 HTTP 서버 또는 FTP 서버의 디렉토리 또는 로컬 폴더로 이동합니다.



