---
permalink: online-help-96-97/task_creating_initiator_groups.html 
sidebar: sidebar 
keywords: create, initiator, group, system, manager, lun, online, help, manage, delete, edit, add 
summary: System Manager를 사용하여 이니시에이터 그룹을 생성할 수 있습니다. 이니시에이터 그룹을 통해 특정 LUN에 대한 호스트 액세스를 제어할 수 있습니다. portset을 사용하여 이니시에이터가 액세스할 수 있는 LIF를 제한할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 이니시에이터 그룹을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하여 이니시에이터 그룹을 관리할 수 있습니다. 이니시에이터 그룹을 통해 특정 LUN에 대한 호스트 액세스를 제어할 수 있습니다. portset을 사용하여 이니시에이터가 액세스할 수 있는 LIF를 제한할 수 있습니다.



== 이니시에이터 그룹을 생성합니다

.단계
. 스토리지 * > * LUN * 을 클릭합니다.
. 이니시에이터 그룹 * 탭에서 * 생성 * 을 클릭합니다.
. 이니시에이터 그룹 생성 * 대화 상자의 * 일반 * 탭에서 그룹에 대해 이니시에이터 그룹 이름, 운영 체제, 호스트 별칭 이름, 포트셋 및 지원되는 프로토콜을 지정합니다.
. Create * 를 클릭합니다.




== 이니시에이터 그룹을 삭제합니다

System Manager의 이니시에이터 그룹 탭을 사용하여 이니시에이터 그룹을 삭제할 수 있습니다.

.시작하기 전에
이니시에이터 그룹에 매핑된 모든 LUN은 수동으로 매핑 해제해야 합니다.

.단계
. 스토리지 * > * LUN * 을 클릭합니다.
. 이니시에이터 그룹 * 탭에서 삭제할 이니시에이터 그룹을 하나 이상 선택한 다음 * 삭제 * 를 클릭합니다.
. 삭제 * 를 클릭합니다.
. 삭제한 이니시에이터 그룹이 * 이니시에이터 그룹 * 탭에 더 이상 표시되지 않는지 확인합니다.




== 이니시에이터를 추가합니다

System Manager를 사용하여 이니시에이터를 이니시에이터 그룹에 추가할 수 있습니다. 이니시에이터는 LUN이 속한 이니시에이터 그룹이 해당 LUN에 매핑될 때 LUN에 대한 액세스를 제공합니다.

.단계
. 스토리지 * > * LUN * 을 클릭합니다.
. LUN 관리 * 탭에서 이니시에이터를 추가할 이니시에이터 그룹을 선택하고 * 편집 * 을 클릭합니다.
. 이니시에이터 그룹 편집 * 대화 상자에서 * 이니시에이터 * 를 클릭합니다.
. 추가 * 를 클릭합니다.
. 이니시에이터 이름을 지정하고 * OK * 를 클릭합니다.
. 저장 후 닫기 * 를 클릭합니다.




== 이니시에이터 그룹에서 이니시에이터를 삭제합니다

System Manager의 이니시에이터 그룹 탭을 사용하여 이니시에이터를 삭제할 수 있습니다. 이니시에이터 그룹에서 이니시에이터를 삭제하려면 이니시에이터 그룹에서 이니시에이터를 분리해야 합니다.

.시작하기 전에
삭제하려는 이니시에이터가 포함된 이니시에이터 그룹에 매핑된 모든 LUN은 수동으로 매핑 해제해야 합니다.

.단계
. 스토리지 * > * LUN * 을 클릭합니다.
. 이니시에이터 그룹 * 탭에서 이니시에이터를 삭제할 이니시에이터 그룹을 선택한 다음 * 편집 * 을 클릭합니다.
. 이니시에이터 그룹 편집 * 대화 상자에서 * 이니시에이터 * 탭을 클릭합니다.
. 텍스트 상자에서 이니시에이터를 선택하여 삭제하고 * Save * 를 클릭합니다.
+
이니시에이터가 이니시에이터 그룹에서 분리되어 있습니다.



* 관련 정보 *

xref:reference_luns_window.adoc[LUN 창]
