---
permalink: online-help-96-97/task_deleting_svms.html 
sidebar: sidebar 
keywords: system, manager, delete, svm, online, help, storage, virtual, machine 
summary: 'System Manager를 사용하면 스토리지 시스템 구성에서 더 이상 필요하지 않은 SVM(스토리지 가상 머신)을 삭제할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하면 스토리지 시스템 구성에서 더 이상 필요하지 않은 SVM(스토리지 가상 머신)을 삭제할 수 있습니다.

.시작하기 전에
다음 작업을 완료해야 합니다.

. 모든 볼륨에 대해 스냅샷 복사본, 데이터 보호(DP) 미러링 및 로드 공유(LS) 미러를 비활성화했습니다
+
[NOTE]
====
CLI(Command-Line Interface)를 사용하여 LS 미러를 비활성화해야 합니다.

====
. SVM을 삭제하는 경우 SVM에 속한 모든 igroup을 수동으로 삭제했습니다
. 모든 포트 세트를 삭제했습니다
. 루트 볼륨을 포함하여 SVM의 모든 볼륨을 삭제했습니다
. LUN을 매핑하지 않고 오프라인 상태로 전환하고 삭제했습니다
. SVM을 삭제하는 경우 CIFS 서버를 삭제했습니다
. SVM과 관련된 맞춤형 사용자 계정 및 역할을 삭제했습니다
. CLI를 사용하여 SVM과 관련된 NVMe 서브시스템을 삭제했습니다.
. SVM을 중지했습니다


.이 작업에 대해
SVM을 삭제할 때 SVM과 연결된 다음 객체도 삭제됩니다.

* LIF, LIF 페일오버 그룹 및 LIF 라우팅 그룹
* 엑스포트 정책
* 효율성 정책


Kerberos를 사용하도록 구성된 SVM을 삭제하거나 SVM을 수정하여 다른 SPN(Service Principal Name)을 사용하는 경우, SVM의 원래 서비스 보안 주체는 Kerberos 영역에서 자동으로 삭제 또는 비활성화되지 않습니다. 보안 주체를 수동으로 삭제하거나 비활성화해야 합니다. 보안 주체를 삭제하거나 비활성화하려면 Kerberos 영역 관리자의 사용자 이름과 암호가 있어야 합니다.

첫 번째 SVM을 삭제하기 전에 SVM에서 다른 SVM으로 데이터를 이동하려는 경우 SnapMirror 기술을 사용하면 됩니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. 삭제할 SVM을 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 삭제 * 를 클릭합니다.

