---
permalink: online-help-96-97/task_creating_flexcache_volumes.html 
sidebar: sidebar 
keywords: online, help, create, flexcache, volume, system, manager 
summary: System Manager 9.6부터 FlexCache 볼륨을 만들 수 있습니다. 
---
= FlexCache 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6부터 FlexCache 볼륨을 만들 수 있습니다.

.이 작업에 대해
FlexCache 볼륨을 생성하려면 먼저 FlexCache 용량 라이센스가 있어야 합니다.

.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. 볼륨 * 창에서 * 생성 * > * FlexCache * 을 클릭합니다.
+
FlexCache 볼륨 생성 창이 표시됩니다.

. * 선택 사항: * 오리진 볼륨 * 영역의 다음 필드는 FlexCache 볼륨을 생성하려는 원본 볼륨의 값을 표시합니다. 수정할 수 있습니다.
+
** * 클러스터 *: 드롭다운 메뉴를 사용하여 원본 볼륨과 연관된 클러스터를 선택합니다.
** * SVM *: 드롭다운 메뉴를 사용하여 원래 볼륨이 포함된 SVM을 선택합니다.
+
피어링되지 않고 피어링이 허용된 SVM을 선택하는 경우 System Manager를 통해 명시적으로 피어링할 수 있습니다.

** * 볼륨 *: 드롭다운 메뉴를 사용하여 볼륨 이름을 선택하거나 필드에 이름을 입력합니다.


. FlexCache 볼륨 * 영역의 다음 필드에는 만들고 있는 FlexCache 볼륨의 기본값이 표시됩니다. 수정할 수 있습니다.
+
** * SVM *: 드롭다운 메뉴를 사용하여 FlexCache 볼륨을 생성할 SVM을 선택합니다. FlexCache 라이센스 용량이 가득 찼거나 거의 꽉 찬 경우 * FlexCache 라이센스 관리 * 를 선택하여 라이센스를 수정할 수 있습니다.
** * 새 볼륨 이름 *: FlexCache 볼륨의 이름을 입력합니다.
** * 크기 *: 측정 단위를 포함하여 FlexCache 볼륨의 크기를 지정합니다.
+
크기 필드는 기본적으로 설정되어 있습니다. 지정하는 크기는 라이센스 용량 크기를 초과할 수 없습니다.



. FlexCache 볼륨을 만들려면 * 저장 * 을 클릭합니다.
+
볼륨 * 창으로 돌아가 볼륨 목록에서 FlexCache 볼륨을 볼 수 있습니다.



* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
