---
permalink: online-help-96-97/task_editing_svm_settings.html 
sidebar: sidebar 
keywords: online, help, system, manager, edit, svm, settings 
summary: 'System Manager를 사용하면 네임 서비스 스위치, 이름 매핑 스위치 및 애그리게이트 목록과 같은 SVM(스토리지 가상 머신)의 속성을 편집할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM 설정을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 방식을 사용하여 네임 서비스 스위치, 이름 매핑 스위치, 애그리게이트 목록과 같은 SVM(스토리지 가상 머신)의 속성을 편집할 수 있습니다.

.이 작업에 대해
* 다음 SVM 속성 값을 편집할 수 있습니다.
+
** 네임 서비스 스위치
** 데이터 제공을 위해 사용되는 프로토콜입니다
+
[NOTE]
====
SVM에 구성된 CIFS 프로토콜은 해당 SVM에서 프로토콜을 해제하더라도 계속해서 데이터를 제공합니다.

====
** 볼륨을 생성하는 데 사용할 수 있는 애그리게이트 목록입니다
+
[NOTE]
====
FlexVol 볼륨의 경우 관리를 SVM 관리자에게 위임된 경우에만 애그리게이트를 할당할 수 있습니다.

====


* System Manager에서는 명령줄 인터페이스 또는 구성되지 않고 ONTAP에서 기본값으로 설정하지 않은 SVM 서비스에 대해 생성된 SVM에 대한 이름 서비스 스위치 및 이름 매핑 스위치를 표시하지 않습니다.
+
서비스 탭이 비활성화되어 있기 때문에 명령줄 인터페이스를 사용하여 서비스를 볼 수 있습니다.

+
System Manager에서는 System Manager를 사용하여 SVM을 생성하거나 SVM 서비스를 ONTAP에서 기본값으로 설정한 경우에만 SVM의 이름 서비스 스위치와 이름 매핑 스위치를 표시합니다.



.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * 편집 * 을 클릭합니다.
. Details * 탭에서 필요한 데이터 프로토콜을 수정합니다.
. 리소스 할당 * 탭에서 다음 방법 중 하나를 선택하여 볼륨 생성을 위임합니다.
+
|===
| 볼륨 생성을 프로비저닝하는 경우... | 그러면... 


 a| 
모든 애그리게이트에서
 a| 
볼륨 생성 위임 안 함 * 옵션을 선택합니다.



 a| 
특정 애그리게이트로 전환 가능
 a| 
.. Delegate volume creation * 옵션을 선택합니다.
.. 볼륨 생성을 위임하는 데 필요한 애그리게이트를 선택합니다.


|===
. Service* 탭에서 필요한 데이터베이스 유형에 대한 이름 서비스 스위치 소스와 이름 서비스 정보를 검색하기 위해 참조해야 하는 순서를 지정합니다.
+
각 데이터베이스 유형의 기본값은 다음과 같습니다.

+
** 호스트: 파일, DNS
** 이름 맵: 파일
** 그룹:파일
** 넷그룹: 파일
** passwd: 파일


. 저장 후 닫기 * 를 클릭합니다.


* 관련 정보 *

xref:concept_how_data_ontap_name_service_switch_configuration_works.adoc[ONTAP 네임 서비스 스위치 구성의 작동 방식]
