---
permalink: online-help-96-97/task_setting_up_cluster_using_template_file.html 
sidebar: sidebar 
keywords: set, up, cluster, template, file, system, manager, online, help, autosupport 
summary: 'System Manager에서 제공하는 템플릿 파일을 사용하여 클러스터를 생성하고, 노드 관리 및 클러스터 관리 네트워크를 설정한 다음, 이벤트 알림을 설정하여 클러스터를 설정할 수 있습니다. (ONTAP 시스템 관리자 9.6부터는 AutoSupport가 지원되지 않습니다.) 템플릿 파일은 .xlsx 형식 또는 .csv 형식으로 다운로드할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 및 이전 버전에서 템플릿 파일을 사용하여 클러스터를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)에서 제공되는 템플릿 파일을 사용하여 클러스터를 생성하고, 노드 관리 및 클러스터 관리 네트워크를 설정한 다음, 이벤트 알림을 설정하여 클러스터를 설정할 수 있습니다. (ONTAP System Manager 9.6부터 AutoSupport는 지원되지 않습니다.) 에서 서식 파일을 다운로드할 수 있습니다 `.xlsx` 형식 또는 `.csv` 형식.

.이 작업에 대해
* 클러스터에서 ONTAP 9.1 이상을 지원하는 경우 ONTAP 9.1 이상을 실행 중인 스토리지 시스템만 추가할 수 있습니다.
* 파일을 업로드할 때 모든 필드가 자동으로 채워지지 않습니다.
+
암호 및 클러스터 관리 포트와 같은 일부 필드의 값을 수동으로 입력해야 합니다.



.단계
. 웹 브라우저를 열고 구성했던 노드 관리 IP 주소를 입력합니다. `+https://node-management-IP+`
+
** 클러스터에 대한 자격 증명을 설정한 경우 로그인 페이지가 표시됩니다.
+
로그인하려면 자격 증명을 입력해야 합니다.

** 클러스터에 대한 자격 증명을 설정하지 않은 경우 Guided Setup 창이 표시됩니다.


. 를 다운로드합니다 `.xlsx` 템플릿 파일 또는 `.csv` 템플릿 파일.
. 템플릿 파일에 필요한 모든 값을 제공하고 파일을 저장합니다.
+
[NOTE]
====
** 템플릿에 있는 값 이외의 다른 열은 편집하지 마십시오.
** 템플릿 파일의 버전을 변경하지 마십시오.


====
. 찾아보기 * 를 클릭하고 업데이트된 템플릿 파일을 선택합니다.
+
** 템플릿 파일은 에서만 업로드할 수 있습니다 `.csv` 형식. 에서 서식 파일을 다운로드한 경우 `.xlsx` 형식을 사용하려면 파일을 로 저장해야 합니다 `.csv` 파일을 클릭한 다음 파일을 업로드합니다.
** 이 파일에 사용된 인코딩이 인지 확인해야 합니다 `UTF8`. 그렇지 않으면 값이 읽혀지지 않습니다.


. 업로드 * 를 클릭합니다.
+
템플릿 파일에서 제공한 세부 정보는 클러스터 설정 프로세스를 완료하는 데 사용됩니다.

. 클러스터의 세부 정보를 보려면 * Guided Setup * 아이콘을 클릭하십시오.
. 클러스터 * 창에서 세부 정보를 확인한 다음 * 제출 및 계속 * 을 클릭합니다.
+
필요한 경우 클러스터 세부 정보를 편집할 수 있습니다.

+
두 번째로 Cluster 창에 로그인하면 기본적으로 * Feature Licenses * 필드가 활성화됩니다. 새 기능 라이센스 키를 추가하거나 미리 채워진 라이센스 키를 유지할 수 있습니다.

. 네트워크* 창에서 세부 정보를 확인한 다음 * 제출 및 계속 * 을 클릭합니다.
+
필요한 경우 네트워크 세부 정보를 편집할 수 있습니다.

. Support * 창에서 세부 정보를 확인한 다음 * Submit and Continue * 를 클릭합니다.
+
필요한 경우 지원 세부 정보를 편집할 수 있습니다.

. Storage * 창에서 세부 정보를 확인하고 애그리게이트를 생성하거나 클러스터 설정을 종료합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
스토리지를 프로비저닝하고 SVM을 생성하지 않고 클러스터 설정을 종료합니다
 a| 
이 단계 건너뛰기 * 를 클릭합니다.



 a| 
애그리게이트를 사용하여 스토리지를 프로비저닝하고 SVM 생성
 a| 
제출 및 계속 * 을 클릭합니다.

|===
+
필요한 경우 지원 세부 정보를 편집할 수 있습니다.

. SVM(Storage Virtual Machine) * 생성 창에서 세부 정보를 확인하고 * 제출 및 계속 * 을 클릭합니다.
+
필요한 경우 SVM 이름을 편집하고, 다른 데이터 프로토콜을 선택하고, 네트워크 인터페이스 및 어댑터 세부 정보를 수정할 수 있습니다.

. 스토리지 * 창에서 * 이 단계 건너뛰기 * 를 클릭한 경우 * 요약 * 창에서 세부 정보를 확인한 다음 * 클러스터 관리 * 를 클릭하여 System Manager를 시작합니다.
. Storage * 창에서 * Submit and Continue * 를 클릭한 경우 SVM 창에서 세부 정보를 확인하고 * Submit and Continue * 를 클릭합니다.
+
필요한 경우 SVM 세부 정보를 편집할 수 있습니다.

. Summary * 창의 모든 세부 정보를 확인한 다음 * Provision an Application * 을 클릭하여 애플리케이션에 대한 스토리지 용량을 할당하거나 * Manage Your Cluster * 를 클릭하여 클러스터 설정 프로세스를 완료하고 System Manager를 실행하거나 * Export Configuration * 을 클릭하여 구성 파일을 다운로드합니다.


* 관련 정보 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/System_Manager_Cluster_Guided_Setup_Templates["System Manager 클러스터 가이드 설치 템플릿"]
