---
permalink: online-help-96-97/task_creating_fc_san_optimized_luns.html 
sidebar: sidebar 
keywords: create, fc, san, optimized, lun, system, manager, online, help 
summary: AFF 플랫폼에서 클러스터를 초기 설정할 때 System Manager를 사용하여 하나 이상의 FC SAN에 최적화된 LUN을 생성할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 FC SAN에 최적화된 LUN을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 AFF 플랫폼에서 클러스터를 초기 설정할 때 FC SAN에 최적화된 LUN을 하나 이상 생성할 수 있습니다.

.시작하기 전에
* 이름이 AFF_SAN_DEFAULT_SVM인 SVM(스토리지 가상 시스템)을 하나만 생성하고 이 SVM에 LUN이 없는지 확인해야 합니다.
* 하드웨어 설정이 성공적으로 완료되었는지 확인해야 합니다.
+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]



.이 작업에 대해
* 이 방법은 두 개 이상의 노드가 있는 클러스터의 초기 설정 중에만 사용할 수 있습니다.
+
System Manager에서는 처음 두 노드만 사용하여 LUN을 생성합니다.

* 각 LUN은 별도의 볼륨에 생성됩니다.
* 볼륨이 씬 프로비저닝되었습니다.
* 생성된 LUN에서 공간 예약이 비활성화되었습니다.
* 대부분의 클러스터 구성은 공장에서 이미 완료되었으며 최적의 스토리지 효율성과 성능을 위해 최적화되었습니다.
+
이러한 구성은 수정할 수 없습니다.



.단계
. 클러스터 관리자 자격 증명을 사용하여 System Manager에 로그인합니다.
+
이 방법을 사용하여 LUN을 생성한 후에는 이 방법을 다시 사용할 수 없습니다.

+
LUN을 생성하지 않고 대화 상자를 닫은 경우 LUN 탭으로 이동하고 * 생성 * 을 클릭하여 대화 상자에 다시 액세스해야 합니다.

. LUN 생성 * 대화 상자의 * LUN 세부 정보 * 영역에서 애플리케이션 유형을 지정합니다.
+
|===
| 애플리케이션 유형이... | 그러면... 


 a| 
오라클
 a| 
.. 데이터베이스 이름과 크기를 지정합니다.
.. Oracle RAC(Real Application Clusters)를 구축한 경우 * Oracle RAC * 확인란을 선택합니다.
+
2개의 RAC 노드만 지원됩니다. Oracle RAC에 이니시에이터 그룹에 최소 2개의 이니시에이터가 추가되어 있는지 확인해야 합니다.





 a| 
SQL
 a| 
데이터베이스의 수와 각 데이터베이스의 크기를 지정합니다.



 a| 
기타
 a| 
.. 각 LUN의 이름과 크기를 지정합니다.
.. 더 많은 LUN을 생성하려면 * LUN 추가 * 를 클릭한 다음 각 LUN의 이름과 크기를 지정합니다.


|===
+
선택한 애플리케이션 유형에 따라 데이터, 로그, 바이너리 및 임시 LUN이 생성됩니다.

. 다음 이니시에이터에 매핑 * 영역에서 다음 단계를 수행합니다.
+
.. 이니시에이터 그룹 이름과 운영 체제 유형을 지정합니다.
.. 드롭다운 목록에서 호스트 이니시에이터 WWPN을 선택하거나 텍스트 상자에 이니시에이터를 입력하여 호스트 이니시에이터 WWPN을 추가합니다.
.. 이니시에이터의 별칭을 추가합니다.


+
이니시에이터 그룹은 하나만 생성됩니다.

. Create * 를 클릭합니다.
+
생성된 LUN과 함께 요약 표가 표시됩니다.

. 닫기 * 를 클릭합니다.


* 관련 정보 *

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]
