---
permalink: online-help-96-97/task_configuring_cifs_nfs_protocols_on_svms.html 
sidebar: sidebar 
keywords: system, manager, configuring, cifs, nfs, protocols, svm, online, help 
summary: 'System Manager를 사용하면 SVM(스토리지 가상 머신)에서 CIFS 및 NFS 프로토콜을 구성하여 NAS 클라이언트에 파일 레벨 데이터 액세스를 제공할 수 있습니다. CIFS 프로토콜을 설정하려면 데이터 LIF 및 CIFS 서버를 생성해야 합니다. NFS 프로토콜을 사용하도록 설정하려면 NIS 세부 정보와 데이터 LIF를 지정할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM에서 CIFS 및 NFS 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SVM(스토리지 가상 머신)에서 CIFS 및 NFS 프로토콜을 구성하여 NAS 클라이언트에 파일 레벨 데이터 액세스를 제공할 수 있습니다. CIFS 프로토콜을 설정하려면 데이터 LIF 및 CIFS 서버를 생성해야 합니다. NFS 프로토콜을 사용하도록 설정하려면 NIS 세부 정보와 데이터 LIF를 지정할 수 있습니다.

.시작하기 전에
* SVM에서 구성 또는 활성화할 프로토콜은 라이센스를 받아야 합니다.
+
구성할 프로토콜이 SVM에서 활성화되어 있지 않으면 스토리지 가상 시스템 편집 창을 사용하여 SVM용 프로토콜을 활성화할 수 있습니다.

* CIFS 프로토콜을 구성하려면 Active Directory, 조직 단위 및 관리 계정 자격 증명이 있어야 합니다.


.이 작업에 대해
SnapLock 애그리게이트는 자동으로 볼륨을 생성하는 것으로 간주되지 않습니다.

.단계
. SVM을 생성하는 동안 프로토콜을 구성하지 않은 경우 * 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 구성할 프로토콜을 클릭합니다.
. 데이터 LIF 구성 * 섹션에서 CIFS와 NFS 모두에 대해 동일한 데이터 LIF 구성을 유지하려면 * NFS 클라이언트에 대한 CIFS 데이터 LIF 구성 유지 * 확인란을 선택합니다.
+
CIFS와 NFS 모두에 대해 동일한 데이터 LIF 구성을 유지하지 않을 경우 CIFS 및 NFS에 대해 IP 주소와 포트를 별도로 지정해야 합니다.

. 다음 옵션 중 하나를 선택하여 IP 주소를 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 아직 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
... 대상 필드의 기본값을 사용하지 않으려면 새 대상 값을 지정합니다.
+
대상 값을 지정하지 않으면 대상 필드는 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.



+
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.

.. 확인 * 을 클릭합니다.


|===
. 데이터 LIF를 생성할 포트를 지정합니다.
+
.. 찾아보기 * 를 클릭합니다.
.. 네트워크 포트 또는 어댑터 선택 * 대화 상자에서 포트를 선택합니다.
.. 확인 * 을 클릭합니다.


. 다음 단계를 수행하여 CIFS 서버를 구성합니다.
+
.. CIFS 서버를 생성하려면 다음 정보를 지정합니다.
+
*** CIFS 서버 이름입니다
*** CIFS 서버와 연결할 Active Directory입니다
*** CIFS 서버와 연결할 Active Directory 도메인 내의 OU(조직 구성 단위)입니다
+
기본적으로 이 매개 변수는 CN=Computers로 설정됩니다.

*** OU에 CIFS 서버를 추가할 수 있는 충분한 권한이 있는 관리 계정의 자격 증명입니다


.. * 선택 사항: * 이 SVM의 모든 공유에 액세스하는 동안 * 데이터 암호화 * 를 선택하여 SVM의 모든 공유에 대해 SMB 3.0 암호화를 사용합니다.
.. 공유 이름, 공유 크기 및 액세스 권한을 지정하여 프로토콜을 구성할 때 CIFS 스토리지에 대한 볼륨을 프로비저닝합니다.
.. 이 공유에 액세스하는 동안 데이터 암호화 * 를 선택하여 특정 공유에 대해 SMB 3.0 암호화를 활성화합니다.


. * 선택 사항: * NIS 서비스 구성:
+
.. SVM에서 NIS 서비스를 구성하려면 NIS 서버의 IP 주소와 NIS 도메인 이름을 지정합니다.
.. "NIS" 이름 서비스 소스를 추가할 적절한 데이터베이스 유형을 선택합니다.
.. 내보내기 이름, 크기 및 권한을 지정하여 NFS 스토리지에 대한 볼륨을 프로비저닝합니다.


. 제출 및 계속 * 을 클릭합니다.


.결과
CIFS 서버와 NIS 도메인은 지정된 구성으로 구성되며 데이터 LIF가 생성됩니다. 기본적으로 데이터 LIF는 관리 액세스 권한을 가집니다. 요약 페이지에서 구성 세부 정보를 볼 수 있습니다.
