---
permalink: online-help-96-97/task_setting_up_network.html 
sidebar: sidebar 
keywords: set, up, network, cluster, node, service, processor, dns, ntp, online, help 
summary: 네트워크를 설정하면 클러스터, 노드 및 서비스 프로세서를 관리할 수 있습니다. 네트워크 창을 사용하여 DNS 및 NTP 세부 정보를 설정할 수도 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 네트워크 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 네트워크를 설정하여 클러스터, 노드 및 서비스 프로세서를 관리할 수 있습니다. 네트워크 창을 사용하여 DNS 및 NTP 세부 정보를 설정할 수도 있습니다.

.시작하기 전에
클러스터를 설정해야 합니다.

.이 작업에 대해
* 실행 중인 노드만 클러스터 생성에 대해 나열됩니다.
+
해당 노드에 대한 LIF를 생성할 수 있습니다.

* IP 주소 범위를 사용하지 않도록 설정하고 클러스터 관리, 노드 관리 및 서비스 프로세서 관리 네트워크에 대한 개별 IP 주소를 입력할 수 있습니다.




== IP 주소 범위가 활성화된 경우 네트워크를 설정합니다

IP 주소 범위를 설정하여 네트워크를 설정할 수 있습니다. IP 주소 범위를 사용하면 동일한 넷마스크 범위 또는 다른 넷마스크 범위에 있는 IP 주소를 입력할 수 있습니다.

.단계
. IP 주소 범위 * 필드에 IP 주소 범위를 입력한 다음 * 적용 * 을 클릭합니다.
+
|===
| 옵션을 선택합니다 | 설명 


 a| 
동일한 넷마스크에 IP 주소 범위가 있습니다
 a| 
IP 주소 범위를 입력한 다음 * 적용 * 을 클릭합니다.

IP 주소는 클러스터 관리, 노드 관리 및 서비스 프로세서 관리 네트워크에 순차적으로 적용됩니다.



 a| 
다양한 넷마스크의 IP 주소 범위가 있습니다
 a| 
각 IP 주소 범위를 별도의 줄에 입력한 다음 * 적용 * 을 클릭합니다.

클러스터 관리 및 기타 IP 주소에 적용되는 첫 번째 IP 주소는 노드 관리 및 서비스 프로세서 관리 네트워크에 순차적으로 적용됩니다.

|===
+
[NOTE]
====
클러스터 관리, 노드 관리 및 서비스 프로세서 관리의 IP 주소 범위를 입력한 후에는 이러한 필드에서 IP 주소 값을 수동으로 수정할 수 없습니다. 모든 IP 주소가 IPv4 주소인지 확인해야 합니다.

====
. 넷마스크 및 게이트웨이 세부 정보를 입력합니다.
. Port * 필드에서 클러스터 관리용 포트를 선택합니다.
. 노드 관리의 * 포트 * 필드가 * e0M * 으로 채워지지 않은 경우 포트 세부 정보를 입력합니다.
+
[NOTE]
====
기본적으로 포트 필드에는 e0M이 표시됩니다.

====
. 서비스 프로세서 관리의 경우 기본값을 재정의하는 경우 필수 게이트웨이 세부 정보를 입력했는지 확인하십시오.
. DNS 세부 정보 * 필드를 활성화한 경우 DNS 서버 세부 정보를 입력합니다.
. NTP 세부 정보 * 필드를 활성화한 경우 NTP 서버 세부 정보를 입력합니다.
+
[NOTE]
====
대체 NTP 서버 세부 정보를 제공하는 것은 선택 사항입니다.

====
. 제출 * 을 클릭합니다.




=== 다음 단계

클러스터 설정을 계속하려면 지원 페이지에 이벤트 알림을 입력하십시오.



== IP 주소 범위가 비활성화된 경우 네트워크를 설정합니다

IP 주소 범위를 사용하지 않도록 설정하고 클러스터 관리, 노드 관리 및 서비스 공급자 네트워크에 대한 개별 IP 주소를 입력하여 네트워크를 설정할 수 있습니다.

.이 작업에 대해
네트워크 페이지에서 * IP 주소 범위 * 가 비활성화되어 있으면 클러스터 관리, 노드 관리 및 서비스 프로세서 네트워크의 개별 IP 주소를 입력합니다.

.단계
. Cluster Management IP Address * 필드에 클러스터 관리 IP 주소를 입력합니다.
. 클러스터 관리에 대한 넷마스크 세부 정보를 입력합니다.
. * 선택 사항: * 클러스터 관리를 위한 게이트웨이 세부 정보를 입력합니다.
. Port * 필드에서 클러스터 관리용 포트를 선택합니다.
. 노드를 관리할 넷마스크 및 게이트웨이 세부 정보를 제공하려면 클러스터 관리 * 의 넷마스크 및 게이트웨이 구성 * 보존 확인란의 선택을 취소한 다음 넷마스크 및 게이트웨이 세부 정보를 입력합니다.
. Node Management * 필드에 노드 관리 IP 주소를 입력합니다.
. 노드 관리의 * 포트 * 필드가 * e0M * 으로 채워지지 않은 경우 포트 세부 정보를 입력합니다.
+
[NOTE]
====
기본적으로 포트 필드에는 e0M이 표시됩니다.

====
. 서비스 프로세서 관리 넷마스크 및 게이트웨이 세부 정보를 입력합니다.
. 서비스 프로세서 관리 * 필드에 서비스 프로세서 IP 관리 주소를 입력합니다.
. DNS 세부 정보 * 필드를 활성화한 경우 DNS 서버 세부 정보를 입력합니다.
. NTP 세부 정보 * 필드를 활성화한 경우 NTP 서버 세부 정보를 입력합니다.
+
[NOTE]
====
대체 NTP 서버 세부 정보를 제공하는 것은 선택 사항입니다.

====
. 제출 * 을 클릭합니다.




=== 다음 단계

클러스터 설정을 계속하려면 지원 페이지에 이벤트 알림을 입력하십시오.

* 관련 정보 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/What_is_a_Service_Processor_and_how_do_I_use_it%3F["서비스 프로세서란 무엇이며 어떻게 사용합니까?"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_and_troubleshoot_NTP_on_clustered_Data_ONTAP_8.2_and_later_using_CLI["CLI를 사용하여 clustered Data ONTAP 8.2 이상에서 NTP를 구성 및 문제 해결하는 방법"]

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]

xref:reference_network_window.adoc[네트워크 창]

xref:reference_configuration_updates_window.adoc[Configuration Updates(구성 업데이트) 창]

xref:reference_date_time_window.adoc[날짜 및 시간 창]

xref:reference_service_processors_window.adoc[서비스 프로세서 창]
