---
permalink: online-help-96-97/task_restoring_volume_from_snapshot_copy.html 
sidebar: sidebar 
keywords: restore, volume, snapshot, copy, system, manager, online, help 
summary: System Manager를 사용하면 이전에 생성한 스냅샷 복사본에 기록되어 있는 상태로 볼륨을 복원하여 손실된 정보를 검색할 수 있습니다. 스냅샷 복사본에서 볼륨을 복원하면 복원 작업에서 기존 볼륨 구성을 덮어씁니다. 스냅샷 복사본이 생성된 후 볼륨의 데이터에 대한 모든 변경 사항은 손실됩니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 스냅샷 복사본에서 볼륨을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 볼륨을 이전에 생성한 스냅샷 복사본에 기록된 상태로 복원하여 손실된 정보를 검색할 수 있습니다. 스냅샷 복사본에서 볼륨을 복원하면 복원 작업에서 기존 볼륨 구성을 덮어씁니다. 스냅샷 복사본이 생성된 후 볼륨의 데이터에 대한 모든 변경 사항은 손실됩니다.

.시작하기 전에
* SnapRestore 라이센스가 시스템에 설치되어 있어야 합니다.
* 복원하려는 FlexVol 볼륨에 LUN이 포함되어 있으면 LUN을 마운트 해제하거나 매핑 해제해야 합니다.
* 복원된 볼륨에 사용할 수 있는 공간이 충분해야 합니다.
* 볼륨에 액세스하는 사용자에게 볼륨을 되돌리려고 하고 선택한 스냅샷 복사본의 데이터가 볼륨의 현재 데이터를 대체한다는 알림이 전달되어야 합니다.


.이 작업에 대해
* 복원하려는 볼륨에 다른 볼륨에 대한 연결 지점이 있는 경우 이러한 연결 지점에 마운트된 볼륨은 복원되지 않습니다.
* SnapLock 컴플라이언스 볼륨의 스냅샷 복사본은 복원할 수 없습니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 스냅샷 복사본에서 복원할 볼륨을 선택합니다.
. More Actions * > * Manage Snapshots * > * Restore * 를 클릭합니다.
. 적절한 스냅샷 복사본을 선택한 다음 * 복원 * 을 클릭합니다.
. 확인 확인란을 선택한 다음 * 복원 * 을 클릭합니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
