---
permalink: online-help-96-97/task_creating_flexvol_volumes.html 
sidebar: sidebar 
keywords: flexvol, create, volume, online, help 
summary: System Manager의 볼륨 생성 대화 상자를 사용하여 데이터에 대한 FlexVol 볼륨을 생성할 수 있습니다. 루트 볼륨에 데이터를 저장하는 대신 항상 데이터에 대해 별도의 볼륨을 생성해야 합니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 FlexVol 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)에서 볼륨 생성 대화 상자를 사용하여 데이터에 대한 FlexVol 볼륨을 생성할 수 있습니다. 루트 볼륨에 데이터를 저장하는 대신 항상 데이터에 대해 별도의 볼륨을 생성해야 합니다.

.시작하기 전에
* 클러스터에는 루트가 아닌 애그리게이트와 SVM(스토리지 가상 머신)이 포함되어야 합니다.
* 읽기/쓰기 볼륨을 생성하려면 SVM용 프로토콜을 구성해야 하며 SnapMirror 라이센스 또는 SnapVault 라이센스를 설치해야 합니다.
+
프로토콜을 구성하지 않았지만 이러한 라이센스 중 하나를 설치한 경우 데이터 보호(DP) 볼륨만 생성할 수 있습니다.

* 암호화된 볼륨을 만들려면 System Manager를 사용하여 볼륨 암호화 라이센스를 설치해야 하며 CLI(Command-Line Interface)를 사용하여 ""key-manager setup""을 활성화해야 합니다.
+
""Key-manager setup""을 활성화한 후 웹 브라우저를 새로 고쳐야 합니다.



.이 작업에 대해
* 읽기/쓰기(RW) 볼륨에 대해서만 스토리지 서비스 품질(QoS)을 활성화할 수 있습니다.
* MetroCluster 구성에서 동기화 소스 SVM에 DP 볼륨을 생성하면 동기화 대상 SVM에서 볼륨이 복제되지 않습니다.
* MetroCluster 구성에서 DP 볼륨을 생성할 때 소스 볼륨은 타겟 SVM에 복제(미러링 또는 볼트)되지 않습니다.
* MetroCluster 구성에서 시스템 관리자는 볼륨을 생성할 때 다음 애그리게이트만 표시합니다.
+
** 정상 모드에서는 운영 사이트에서 동기식 소스 SVM이나 데이터 제공 SVM에 볼륨을 생성할 때 운영 사이트의 클러스터에 속한 애그리게이트만 표시됩니다.
** 스위치 오버 모드에서는 동기식-타겟 SVM 또는 활성 사이트의 데이터 지원 SVM에 볼륨을 생성할 때 SVM만 표시됩니다.


* Cloud Volumes ONTAP에서는 볼륨을 암호화할 수 없습니다.
* 소스 볼륨에서 암호화가 활성화되고 대상 클러스터에서 ONTAP 9.3 이전의 ONTAP 소프트웨어 버전을 실행 중인 경우 기본적으로 타겟 볼륨에서 암호화가 비활성화됩니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. Create * > * Create FlexVol * 를 클릭합니다.
. 볼륨을 생성할 SVM을 찾아 선택합니다.
+
Create Volume(볼륨 생성) 대화 상자가 표시됩니다. 대화 상자에는 다음과 같은 탭이 있습니다.

+
** 일반
** 스토리지 효율성
** SnapLock
** 서비스 품질
** 보호


. 일반 * 탭에서 다음 단계를 수행하십시오.
+
.. FlexVol 볼륨의 이름을 지정합니다.
.. FabricPool * 버튼을 클릭하여 볼륨이 FabricPool 볼륨임을 지정합니다.
.. Aggregate를 선택하려면 * 선택 * 을 클릭합니다.
+
볼륨이 FabricPool FlexVol 볼륨인 경우에는 FabricPool 지원 애그리게이트만 선택할 수 있으며, 해당 볼륨이 FabricPool이 아닌 FlexVol 볼륨인 경우에는 FabricPool 지원 애그리게이트가 아닌 애그리게이트만 선택할 수 있습니다. 암호화된 애그리게이트(NAE)를 선택하면 생성하는 볼륨이 애그리게이트의 암호화를 상속합니다.

.. 스토리지 유형을 선택합니다.
.. 체적 크기와 측정 단위를 지정합니다.
.. 스냅샷 복사본을 위해 예약해야 하는 공간을 지정합니다.
.. 공간 예약 * 드롭다운 메뉴에서 공간 예약 옵션을 선택합니다.
.. 볼륨 암호화를 활성화하려면 * 볼륨 암호화 * 확인란을 선택합니다. 이 옵션은 볼륨 암호화 라이센스를 활성화했으며 해당 플랫폼이 암호화를 지원할 수 있는 경우에만 사용할 수 있습니다.


. Storage Efficiency * 탭에서 다음 단계를 수행하십시오.
+
.. 이 볼륨을 생성할 스토리지 유형을 선택합니다.
+
SnapMirror 대상 볼륨을 생성하는 경우 * 데이터 보호 * 를 선택해야 합니다. 이 볼륨에 대한 읽기 전용 액세스 권한이 제공됩니다.

.. 볼륨에 대한 계층화 정책을 지정합니다.
.. 스냅샷 복사본을 위해 예약할 볼륨 크기와 총 볼륨 크기의 비율을 지정합니다.
+
스냅샷 복사본을 위해 예약된 기본 공간은 SAN 볼륨 및 VMware 볼륨의 경우 0%입니다. NAS 볼륨의 경우 기본값은 5%입니다.

.. 볼륨에 대해 * Default *, * Thin Provisioned * 또는 * Thick Provisioned * 를 선택합니다.
+
씬 프로비저닝이 설정된 경우 데이터가 볼륨에 기록될 때에만 aggregate에서 볼륨에 공간이 할당됩니다.

+
[NOTE]
====
*** AFF 스토리지 시스템의 경우 씬 프로비저닝의 값은 "기본값"이고, 다른 스토리지 시스템의 경우 일반 프로비저닝의 값은 "기본값"입니다.
*** FabricPool 지원 애그리게이트의 경우 씬 프로비저닝의 가치는 "기본값"입니다.


====
.. 볼륨에 대해 중복 제거를 사용할지 여부를 지정합니다.
+
System Manager에서는 기본 중복 제거 일정을 사용합니다. 지정된 볼륨 크기가 중복 제거를 실행하는 데 필요한 제한을 초과하면 볼륨이 생성되고 중복제거가 활성화되지 않습니다.

+
All-Flash에 최적화된 퍼스낼리티를 갖춘 시스템의 경우 인라인 압축 및 를 참조하십시오 `auto` 중복 제거 일정은 기본적으로 설정됩니다.



. 서비스 품질 * 탭에서 다음 단계를 수행하십시오.
+
.. FlexVol 볼륨에 대한 스토리지 QoS를 활성화하여 워크로드 성능을 관리하려면 * 스토리지 서비스 품질 관리 * 확인란을 선택합니다.
.. 새 스토리지 QoS 정책 그룹을 생성하거나 기존 정책 그룹을 선택하여 FlexVol 볼륨의 I/O(Input/Output) 성능을 제어합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
새 정책 그룹을 생성합니다
 a| 
... 새 정책 그룹 * 을 선택합니다.
... 정책 그룹 이름을 지정합니다.
... 최소 처리량 제한을 지정합니다.
+
**** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 정책 그룹의 최소 처리량 제한을 설정할 수 있습니다.
**** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
**** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



... 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
**** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
**** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
**** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.







 a| 
기존 정책 그룹을 선택합니다
 a| 
... 기존 정책 그룹 * 을 선택한 다음 * 선택 * 을 클릭하여 정책 그룹 선택 대화 상자에서 기존 정책 그룹을 선택합니다.
... 최소 처리량 제한을 지정합니다.
+
**** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 정책 그룹의 최소 처리량 제한을 설정할 수 있습니다.
**** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
**** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



... 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
**** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
**** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
**** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.



+
정책 그룹이 둘 이상의 개체에 할당된 경우 지정한 최대 처리량은 객체 간에 공유됩니다.



|===


. 보호 * 탭에서 다음 단계를 수행하십시오.
+
.. 볼륨 보호 * 의 활성화 여부를 지정합니다.
+
비 FabricPool FlexGroup 볼륨은 FabricPool FlexGroup 볼륨으로 보호할 수 있습니다.

+
FlexGroup 볼륨은 FabricPool이 아닌 FabricPool FlexGroup 볼륨으로 보호할 수 있습니다.

.. Replication * 유형을 선택합니다.


+
|===
| 복제 유형을 다음과 같이 선택한 경우 | 수행할 작업... 


 a| 
비동기식
 a| 
.. * 선택 사항: * 복제 유형 및 관계 유형을 모르는 경우 * 도움말 선택 * 을 클릭하고 값을 지정한 다음 * 적용 * 을 클릭합니다.
.. 관계 유형을 선택합니다.
+
관계 유형은 대칭 복사, 볼트, 대칭 복사 및 볼트 중 선택할 수 있습니다.

.. 타겟 볼륨으로 클러스터 및 SVM을 선택합니다.
+
선택한 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 선택한 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

.. 필요한 경우 볼륨 이름 접미사를 수정합니다.




 a| 
동기식이다
 a| 
.. * 선택 사항: * 복제 유형 및 관계 유형을 모르는 경우 * 도움말 선택 * 을 클릭하고 값을 지정한 다음 * 적용 * 을 클릭합니다.
.. 동기화 정책을 선택합니다.
+
동기화 정책은 StrictSync 또는 Sync 일 수 있습니다.

.. 타겟 볼륨으로 클러스터 및 SVM을 선택합니다.
+
선택한 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 선택한 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

.. 필요한 경우 볼륨 이름 접미사를 수정합니다.


|===
. Create * 를 클릭합니다.
. 생성한 볼륨이 * Volume * 창의 볼륨 목록에 포함되어 있는지 확인합니다.
+
이 볼륨은 UNIX 스타일 보안 및 소유자에 대한 UNIX 700 "read write execute" 권한으로 생성됩니다.



* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
