---
permalink: online-help-96-97/task_editing_application.html 
sidebar: sidebar 
keywords: edit, application, online, help, provisioned, snapshot, copy 
summary: 프로비저닝된 애플리케이션을 편집하여 스토리지 크기를 늘리거나 애플리케이션의 스냅샷 복사본을 관리할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 애플리케이션을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 프로비저닝된 애플리케이션을 편집하여 스토리지 크기를 늘리거나 애플리케이션의 스냅샷 복사본을 관리할 수 있습니다.

.이 작업에 대해
클러스터 관리자는 애플리케이션을 프로비저닝한 후 이를 편집하여 스토리지 크기를 수정할 수 있습니다. 애플리케이션의 스냅샷 복사본을 생성, 복원, 삭제할 수도 있습니다. 다음 예제 절차에서는 * NAS Container * 응용 프로그램을 편집하는 방법에 대해 설명합니다.

.단계
. 응용 프로그램 및 계층 * > * 응용 프로그램 * 을 클릭합니다
. NAS 컨테이너 애플리케이션의 이름을 클릭합니다.
+
[NOTE]
====
응용 프로그램 목록을 보는 동안 다른 사용자가 CLI 또는 REST API를 사용하여 새 응용 프로그램을 추가하는 경우 목록을 스크롤할 때 해당 새 응용 프로그램을 볼 수 없습니다.

====
+
애플리케이션 세부 정보: NAS 창의 * 개요 * 탭에 애플리케이션 설정이 표시됩니다.

. 편집 * 을 클릭합니다.
+
Edit NAS Container: NAS(NAS 컨테이너 편집: NAS)에는 현재 스토리지 크기 설정과 * NFS Access - Grant Access to Host *(NFS 액세스 - 호스트 액세스 권한 부여) 주소가 표시됩니다.

. 스토리지 총 크기 * 값을 수정합니다.
. 크기 단위 필드의 드롭다운 메뉴에서 을 선택하여 올바른 크기 단위(바이트, MB, GB 또는 TB)를 지정합니다.
. ONTAP 서비스 수준 * 필드의 드롭다운 메뉴에서 값을 선택합니다.
. 저장 * 을 클릭합니다.
. 응용 프로그램 세부 정보: NAS* 창으로 돌아가** 스냅샷 복사본** 탭을 선택합니다.
+
프로비저닝된 이 애플리케이션의 스냅샷 복사본 목록이 표시됩니다. 검색 * 필드를 사용하여 이름별로 스냅샷 복사본을 검색할 수 있습니다.

. 필요에 따라 다음 작업을 수행하여 스냅샷 복사본을 관리합니다.
+
|===
| 작업 | 작업 


 a| 
생성
 a| 
새 스냅샷 복사본을 생성하려면 * 생성 * 을 클릭합니다.



 a| 
복원
 a| 
복원할 스냅샷 복사본 옆의 확인란을 클릭한 다음 * 복원 * 을 클릭합니다.



 a| 
삭제
 a| 
삭제할 스냅샷 복사본 옆의 확인란을 클릭한 다음 * 삭제 * 를 클릭합니다.

|===

