---
permalink: online-help-96-97/task_enabling_storage_efficiency_on_volume.html 
sidebar: sidebar 
keywords: system, manager, enable, storage, efficiency, volume, deduplication, online, help 
summary: System Manager를 사용하면 스토리지 효율성을 높이고, 중복제거 및 데이터 압축을 모두 구성하거나, 볼륨에 대해서만 중복 제거를 구성하여 스토리지 공간을 절약할 수 있습니다. 볼륨을 생성할 때 스토리지 효율성을 설정하지 않은 경우 나중에 볼륨을 편집하여 이 작업을 수행할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 볼륨에서 스토리지 효율성 실현
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하면 스토리지 효율성을 높이고, 중복제거 및 데이터 압축을 모두 구성하거나, 스토리지 공간을 절약하기 위해 볼륨에 대해서만 중복 제거를 구성할 수 있습니다. 볼륨을 생성할 때 스토리지 효율성을 설정하지 않은 경우 나중에 볼륨을 편집하여 이 작업을 수행할 수 있습니다.

.시작하기 전에
* 볼륨이 온라인 상태여야 합니다.
* 정책 기반 중복제거 일정을 사용하려면 효율성 정책을 생성해야 합니다.


.이 작업에 대해
* 백그라운드 중복제거가 활성화되어 있는 경우에만 백그라운드 압축을 활성화할 수 있습니다.
* 백그라운드 압축 및 백그라운드 중복제거를 각각 사용하거나 사용하지 않고 인라인 압축 및 인라인 중복제거를 사용할 수 있습니다.
* All-Flash 최적화 속성을 가진 애그리게이트 및 Flash Pool 애그리게이트에 포함된 볼륨에 대해서만 인라인 중복제거를 사용할 수 있습니다.
* System Manager 9.6부터는 FlexGroup DP 볼륨의 스토리지 효율성 편집이 지원됩니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 스토리지 효율성을 활성화할 볼륨을 선택한 다음 * Edit * 를 클릭합니다.
. 볼륨 편집 * 대화 상자에서 * 스토리지 효율성 * 을 클릭합니다.
. Background Deduplication * 확인란을 선택합니다.
. 다음 방법 중 하나를 선택하여 중복 제거를 실행합니다.
+
|===
| 중복 제거를 실행하려는 경우... | 그러면... 


 a| 
구성하는 데 사용됩니다
 a| 
.. 정책 기반 * 옵션이 선택되어 있는지 확인합니다.
.. SELECT * 를 클릭한 다음 스토리지 효율성 정책을 선택합니다.
.. 확인 * 을 클릭합니다.




 a| 
필요 시
 a| 
On-demand * 옵션을 선택합니다.

|===
. 백그라운드 압축을 활성화하려면 * Background Compression * 확인란을 선택합니다.
+
All-Flash 최적화 속성을 가진 애그리게이트에 포함된 볼륨에 대해 백그라운드 압축을 활성화할 수는 없습니다.

. 볼륨에 쓰는 동안 데이터를 압축하려면 * Inline Compression * 확인란을 선택합니다.
+
기본적으로 인라인 압축은 All-Flash 최적화 퍼스낼리티가 포함된 애그리게이트에 포함되어 있는 볼륨에 대해 활성화됩니다.

. 데이터가 디스크에 기록되기 전에 데이터 중복 제거를 실행하려면 * Inline Deduplication * 확인란을 선택합니다.
+
기본적으로 인라인 중복제거는 All-Flash 최적화 퍼스낼리티가 포함된 애그리게이트에 포함된 볼륨에서 활성화됩니다.

. 저장 후 닫기 * 를 클릭합니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]
