---
permalink: online-help-96-97/task_editing_local_windows_group_properties.html 
sidebar: sidebar 
keywords: online, help, edit, local, windows, group, properties, active, directory 
summary: System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 그룹에 할당된 권한과 그룹을 쉽게 식별할 수 있도록 그룹 설명을 수정할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 로컬 Windows 그룹을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하여 로컬 Windows 그룹을 관리할 수 있습니다. 그룹 속성, 구성원 자격, 계정을 수정하고 특정 권한을 그룹에 할당할 수 있습니다.



== 로컬 Windows 그룹 속성을 편집합니다

System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 그룹에 할당된 권한과 그룹을 쉽게 식별할 수 있도록 그룹 설명을 수정할 수 있습니다.

.이 작업에 대해
로컬 Windows 그룹에 구성원을 추가하거나 로컬 Windows 그룹에서 구성원을 제거할 때 다음 사항을 염두에 두어야 합니다.

* special_everyone_group에 사용자를 추가하거나 이 그룹에서 사용자를 제거할 수 없습니다.
* 로컬 Windows 그룹을 다른 로컬 Windows 그룹에 추가할 수 없습니다.


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 * 편집 * 을 클릭합니다.
. 그룹의 이름과 새 그룹을 식별할 설명을 지정합니다.
. 그룹에 권한 집합을 할당합니다.
+
사전 정의된 지원되는 권한 집합에서 권한을 선택할 수 있습니다.

. 그룹에 사용자를 추가하려면 * 추가 * 를 클릭합니다.
. Add Members* 창에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM(스토리지 가상 시스템)에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.


. 편집 * 을 클릭합니다.


.결과
로컬 Windows 그룹 설정이 수정되고 변경 사항이 * Groups * (그룹 *) 탭에 표시됩니다.



== 로컬 Windows 그룹을 만듭니다

System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 머신)에 포함된 데이터에 대한 액세스 권한을 부여하는 데 사용할 수 있는 로컬 Windows 그룹을 생성할 수 있습니다. 관리 작업을 수행할 때 그룹의 구성원이 보유한 사용자 권한 또는 기능을 정의하는 권한도 할당할 수 있습니다.

.시작하기 전에
SVM용으로 CIFS 서버를 구성해야 합니다.

.이 작업에 대해
* 로컬 도메인 이름을 사용하거나 사용하지 않고 그룹 이름을 지정할 수 있습니다.
+
로컬 도메인은 SVM용 CIFS 서버의 이름입니다. 예를 들어 SVM의 CIFS 서버 이름이 "'cifs_server''이고 "'engineering'' 그룹을 생성하려면 그룹 이름으로 "'engineering' 또는 "'cifs_server\engineering' 중 하나를 지정할 수 있습니다.

+
그룹 이름의 일부로 로컬 도메인을 사용할 때는 다음 규칙이 적용됩니다.

+
** 그룹이 적용되는 SVM에 대해 로컬 도메인 이름만 지정할 수 있습니다.
+
예를 들어, 로컬 CIFS 서버 이름이 "'CIFS_server''인 경우 그룹 이름으로 "'CORP_SERVER\group1''을 지정할 수 없습니다.

** 그룹 이름에 ""BUILTIN""을(를) 로컬 도메인으로 사용할 수 없습니다.
+
예를 들어, 이름이 ""BUILTIN\group1""인 그룹을 만들 수 없습니다.

** 그룹 이름에서 Active Directory 도메인을 로컬 도메인으로 사용할 수 없습니다.
+
예를 들어 ""AD_DOM\group1""이라는 그룹을 만들 수 없습니다. 여기서 ""AD_DOM""은 Active Directory 도메인의 이름입니다.



* 이미 존재하는 그룹 이름은 사용할 수 없습니다.
* 지정하는 그룹 이름은 다음 요구 사항을 충족해야 합니다.
+
** 256자를 초과할 수 없습니다
** 마침표로 끝나서는 안 됩니다
** 쉼표를 포함해서는 안 됩니다
** 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
** 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 * 생성 * 을 클릭합니다.
. 그룹 만들기 * 대화 상자에서 그룹의 이름과 새 그룹을 식별하는 데 도움이 되는 설명을 지정합니다.
. 그룹에 권한 집합을 할당합니다.
+
사전 정의된 지원되는 권한 집합에서 권한을 선택할 수 있습니다.

. 그룹에 사용자를 추가하려면 * 추가 * 를 클릭합니다.
. 그룹에 구성원 추가 * 대화 상자에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.
** 확인 * 을 클릭합니다.


. Create * 를 클릭합니다.


.결과
로컬 Windows 그룹이 생성되어 그룹 창에 나열됩니다.



== Windows 로컬 그룹에 사용자 계정을 추가합니다

System Manager를 사용하여 로컬 사용자, Active Directory 사용자 또는 Active Directory 그룹(사용자가 해당 그룹과 연결된 권한을 보유하도록 하려는 경우)을 Windows 로컬 그룹에 추가할 수 있습니다.

.시작하기 전에
* 그룹에 사용자를 추가하려면 그룹이 있어야 합니다.
* 사용자를 그룹에 추가하려면 사용자가 있어야 합니다.


.이 작업에 대해
로컬 Windows 그룹에 구성원을 추가할 때는 다음 사항을 염두에 두어야 합니다.

* special_everyone_group에 사용자를 추가할 수 없습니다.
* 로컬 Windows 그룹을 다른 로컬 Windows 그룹에 추가할 수 없습니다.
* System Manager를 사용하면 사용자 이름에 공백이 포함된 사용자 계정을 추가할 수 없습니다.
+
CLI(Command-Line Interface)를 사용하여 사용자 계정의 이름을 바꾸거나 사용자 계정을 추가할 수 있습니다.



.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 사용자를 추가할 그룹을 선택한 다음 * 구성원 추가 * 를 클릭합니다.
. Add Members* 창에서 다음 작업 중 하나를 수행합니다.
+
** 특정 로컬 그룹에 추가할 Active Directory 사용자 또는 Active Directory 그룹을 지정합니다.
** SVM(스토리지 가상 시스템)에서 사용 가능한 로컬 사용자 목록에서 사용자를 선택합니다.


. 확인 * 을 클릭합니다.


.결과
추가한 사용자가 * Groups * 탭의 Userstab에 나열됩니다.



== 로컬 Windows 그룹의 이름을 바꿉니다

System Manager를 사용하면 로컬 Windows 그룹의 이름을 변경하여 그룹을 보다 쉽게 식별할 수 있습니다.

.이 작업에 대해
* 새 그룹 이름은 이전 그룹 이름과 동일한 도메인에 만들어야 합니다.
* 그룹 이름은 다음 요구 사항을 충족해야 합니다.
+
** 256자를 초과할 수 없습니다
** 마침표로 끝나서는 안 됩니다
** 쉼표를 포함해서는 안 됩니다
** 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
** 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 이름을 바꿀 그룹을 선택한 다음 * 이름 바꾸기 * 를 클릭합니다.
. 그룹 이름 바꾸기 * 창에서 그룹의 새 이름을 지정합니다.


.결과
로컬 그룹 이름이 변경되고 그룹이 그룹 창에 새 이름으로 나열됩니다.



== 로컬 Windows 그룹을 삭제합니다

SVM(스토리지 가상 시스템)에 포함된 데이터에 대한 액세스 권한을 확인하거나 그룹 멤버에 SVM 사용자 권한(권한)을 할당하는 데 그룹이 더 이상 필요하지 않은 경우 System Manager를 사용하여 스토리지 가상 시스템(SVM)에서 로컬 Windows 그룹을 삭제할 수 있습니다.

.이 작업에 대해
* 로컬 그룹을 제거하면 그룹의 구성원 기록이 제거됩니다.
* 파일 시스템이 변경되지 않았습니다.
+
이 그룹을 참조하는 파일 및 디렉토리의 Windows 보안 설명자는 조정되지 않습니다.

* 특별그룹인 Everyone은 삭제할 수 없습니다.
* BUILTIN\Administrators 및 BUILTIN\Users와 같은 기본 제공 그룹은 삭제할 수 없습니다.


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 그룹 * 탭에서 삭제할 그룹을 선택한 다음 * 삭제 * 를 클릭합니다.
. 삭제 * 를 클릭합니다.


.결과
로컬 그룹은 구성원 기록과 함께 삭제됩니다.



== 로컬 Windows 사용자 계정을 만듭니다

System Manager를 사용하면 SMB 연결을 통해 SVM(스토리지 가상 시스템)에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 Windows 사용자 계정을 만들 수 있습니다. CIFS 세션을 생성할 때 인증에 로컬 Windows 사용자 계정을 사용할 수도 있습니다.

.시작하기 전에
* SVM용으로 CIFS 서버를 구성해야 합니다.


.이 작업에 대해
로컬 Windows 사용자 이름은 다음 요구 사항을 충족해야 합니다.

* 20자를 초과할 수 없습니다
* 마침표로 끝나서는 안 됩니다
* 쉼표를 포함해서는 안 됩니다
* 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
* 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다


암호는 다음 기준을 충족해야 합니다.

* 6자 이상이어야 합니다
* 사용자 계정 이름을 포함해서는 안 됩니다
* 다음 4개 범주 중 3개 이상의 문자를 포함해야 합니다.
+
** 영어 대문자(A ~ Z)
** 영어 소문자(a ~ z)
** 기본 10자리(0 ~ 9)
** 특수 문자:~! @#0^& *_-+="\|()[]:;"<>,. ? /




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 * 생성 * 을 클릭합니다.
. 로컬 사용자의 이름을 지정합니다.
. 로컬 사용자의 전체 이름과 이 새 사용자를 식별하는 데 도움이 되는 설명을 지정합니다.
. 로컬 사용자의 암호를 입력하고 암호를 확인합니다.
+
암호는 암호 요구 사항을 충족해야 합니다.

. Add * (추가 *)를 클릭하여 그룹 멤버쉽을 사용자에게 할당합니다.
. Add Groups * 창의 SVM에서 사용 가능한 그룹 목록에서 그룹을 선택합니다.
. 사용자가 생성된 후 이 계정을 비활성화하려면 * 이 계정 비활성화 * 를 선택합니다.
. Create * 를 클릭합니다.


.결과
로컬 Windows 사용자 계정이 생성되고 선택한 그룹에 구성원이 할당됩니다. 사용자 계정이 * Users * 탭에 나열됩니다.



== 로컬 Windows 사용자 속성을 편집합니다

기존 사용자의 전체 이름 또는 설명을 변경하거나 사용자 계정을 활성화 또는 비활성화하려면 System Manager를 사용하여 로컬 Windows 사용자 계정을 수정할 수 있습니다. 사용자 계정에 할당된 그룹 구성원을 수정할 수도 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 * 편집 * 을 클릭합니다.
. Modify User * (사용자 수정 *) 창에서 필요한 내용을 변경합니다.
. Modify * 를 클릭합니다.


.결과
로컬 Windows 사용자 계정의 속성이 수정되어 * 사용자 * 탭에 표시됩니다.



== 사용자 계정에 그룹 구성원 자격을 할당합니다

특정 그룹에 연결된 권한을 사용자에게 부여하려면 System Manager를 사용하여 사용자 계정에 그룹 구성원 자격을 할당할 수 있습니다.

.시작하기 전에
* 그룹에 사용자를 추가하려면 그룹이 있어야 합니다.
* 사용자를 그룹에 추가하려면 사용자가 있어야 합니다.


.이 작업에 대해
special_everyone_group에 사용자를 추가할 수 없습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 그룹 구성원 자격을 할당할 사용자 계정을 선택한 다음 * 그룹에 추가 * 를 클릭합니다.
. Add Groups * (그룹 추가 *) 창에서 사용자 계정을 추가할 그룹을 선택합니다.
. 확인 * 을 클릭합니다.


.결과
사용자 계정에는 선택한 모든 그룹에 대한 구성원 자격이 할당되며 사용자는 이러한 그룹과 연결된 권한을 갖습니다.



== 로컬 Windows 사용자의 이름을 바꿉니다

System Manager를 사용하면 로컬 Windows 사용자 계정의 이름을 변경하여 로컬 사용자를 보다 쉽게 식별할 수 있습니다.

.이 작업에 대해
* 새 사용자 이름은 이전 사용자 이름과 동일한 도메인에 만들어야 합니다.
* 지정하는 사용자 이름은 다음 요구 사항을 충족해야 합니다.
+
** 20자를 초과할 수 없습니다
** 마침표로 끝나서는 안 됩니다
** 쉼표를 포함해서는 안 됩니다
** 다음 인쇄 가능한 문자를 포함해서는 안 됩니다."/\[]:|<>+=;? *@
** 인쇄할 수 없는 ASCII 범위 1에서 31 사이의 문자를 포함해서는 안 됩니다




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 이름을 바꿀 사용자를 선택한 다음 * 이름 바꾸기 * 를 클릭합니다.
. 사용자 이름 바꾸기 * 창에서 사용자의 새 이름을 지정합니다.
. 새 이름을 확인한 다음 * 이름 바꾸기 * 를 클릭합니다.


.결과
사용자 이름이 변경되고 새 이름이 * 사용자 * 탭에 나열됩니다.



== Windows 로컬 사용자의 암호를 재설정합니다

System Manager를 사용하여 Windows 로컬 사용자의 암호를 재설정할 수 있습니다. 예를 들어, 현재 암호가 손상되었거나 사용자가 암호를 잊어버린 경우 암호를 재설정할 수 있습니다.

.이 작업에 대해
설정한 암호는 다음 기준을 충족해야 합니다.

* 6자 이상이어야 합니다
* 사용자 계정 이름을 포함해서는 안 됩니다
* 다음 4개 범주 중 3개 이상의 문자를 포함해야 합니다.
+
** 영어 대문자(A ~ Z)
** 영어 소문자(a ~ z)
** 기본 10자리(0 ~ 9)
** 특수 문자:~! @#0^& *_-+="\|()[]:;"<>,. ? /




.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 암호를 재설정할 사용자를 선택한 다음 * 암호 설정 * 을 클릭합니다.
. 암호 재설정 * 대화 상자에서 사용자의 새 암호를 설정합니다.
. 새 암호를 확인한 다음 * Reset * (재설정 *)을 클릭합니다.




== 로컬 Windows 사용자 계정을 삭제합니다

사용자 계정이 SVM의 CIFS 서버에 대한 로컬 CIFS 인증을 위해 또는 SVM에 포함된 데이터에 대한 액세스 권한을 결정하는 데 더 이상 필요하지 않은 경우 System Manager를 사용하여 SVM(스토리지 가상 시스템)에서 로컬 Windows 사용자 계정을 삭제할 수 있습니다.

.이 작업에 대해
* Administrator와 같은 표준 사용자는 삭제할 수 없습니다.
* ONTAP는 로컬 그룹 데이터베이스, 로컬 사용자 멤버 자격 및 사용자 권한 데이터베이스에서 삭제된 로컬 사용자에 대한 참조를 제거합니다.


.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 호스트 사용자 및 그룹 * 창에서 * Windows * 를 클릭합니다.
. 사용자 * 탭에서 삭제할 사용자 계정을 선택한 다음 * 삭제 * 를 클릭합니다.
. 삭제 * 를 클릭합니다.


.결과
로컬 사용자 계정이 그룹 구성원 항목과 함께 삭제됩니다.



== Windows 창

System Manager를 사용하여 Windows 창을 사용할 수 있습니다. Windows 창을 통해 클러스터의 각 SVM(스토리지 가상 머신)에 대한 로컬 Windows 사용자 및 그룹 목록을 유지할 수 있습니다. 로컬 Windows 사용자 및 그룹을 인증 및 이름 매핑에 사용할 수 있습니다.



=== 사용자 탭

사용자 탭을 사용하여 SVM에 대한 로컬 Windows 사용자를 볼 수 있습니다.



=== 명령 버튼

* * 생성 *
+
SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 Windows 사용자 계정을 생성할 수 있는 사용자 생성 대화 상자를 엽니다.

* * 편집 *
+
사용자 편집 대화 상자를 엽니다. 이 대화 상자에서 그룹 구성원 자격 및 전체 이름과 같은 로컬 Windows 사용자 속성을 편집할 수 있습니다. 사용자 계정을 활성화하거나 비활성화할 수도 있습니다.

* * 삭제 *
+
더 이상 필요하지 않은 경우 SVM에서 로컬 Windows 사용자 계정을 삭제할 수 있는 사용자 삭제 대화 상자를 엽니다.

* * 그룹에 추가 *
+
사용자에게 해당 그룹과 관련된 권한을 부여하려면 사용자 계정에 그룹 구성원을 할당할 수 있는 그룹 추가 대화 상자를 엽니다.

* * 암호 설정 *
+
Windows 로컬 사용자의 암호를 재설정할 수 있는 암호 재설정 대화 상자를 엽니다. 예를 들어, 암호가 손상되었거나 사용자가 암호를 잊어버린 경우 암호를 재설정할 수 있습니다.

* * 이름 바꾸기 *
+
로컬 Windows 사용자 계정의 이름을 보다 쉽게 식별할 수 있도록 사용자 이름 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 사용자 목록

* * 이름 *
+
로컬 사용자의 이름을 표시합니다.

* * 전체 이름 *
+
로컬 사용자의 전체 이름을 표시합니다.

* * 계정이 비활성화됨 *
+
로컬 사용자 계정의 사용 여부를 표시합니다.

* * 설명 *
+
이 로컬 사용자에 대한 설명을 표시합니다.





=== 사용자 세부 정보 영역

* * 그룹 *
+
사용자가 구성원인 그룹의 목록을 표시합니다.





=== 그룹 탭

그룹 탭을 사용하여 SVM에 로컬 있는 Windows 그룹을 추가, 편집 또는 삭제할 수 있습니다.



=== 명령 버튼

* * 생성 *
+
SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스 권한을 부여하는 데 사용할 수 있는 로컬 Windows 그룹을 생성할 수 있는 그룹 생성 대화 상자를 엽니다.

* * 편집 *
+
그룹에 할당된 권한 및 그룹 설명과 같은 로컬 Windows 그룹 속성을 편집할 수 있는 그룹 편집 대화 상자를 엽니다.

* * 삭제 *
+
더 이상 필요하지 않은 경우 SVM에서 로컬 Windows 그룹을 삭제할 수 있는 그룹 삭제 대화 상자를 엽니다.

* * 구성원 추가 *
+
로컬 또는 Active Directory 사용자 또는 Active Directory 그룹을 로컬 Windows 그룹에 추가할 수 있는 구성원 추가 대화 상자를 엽니다.

* * 이름 바꾸기 *
+
로컬 Windows 그룹의 이름을 보다 쉽게 식별할 수 있도록 그룹 이름 바꾸기 대화 상자를 엽니다.

* * 새로 고침 *
+
창에서 정보를 업데이트합니다.





=== 그룹 목록

* * 이름 *
+
로컬 그룹의 이름을 표시합니다.

* * 설명 *
+
이 로컬 그룹에 대한 설명을 표시합니다.





=== 그룹 세부 정보 영역

* * 권한 *
+
선택한 그룹과 연결된 권한 목록을 표시합니다.

* 사용자 *
+
선택한 그룹과 연결된 로컬 사용자 목록을 표시합니다.


