---
permalink: online-help-96-97/task_assigning_volumes_to_storage_qos.html 
sidebar: sidebar 
keywords: assign, volumes, storage, qos, online, help, flexgroup, online, help, quality, serice 
summary: 'FlexGroup 볼륨 및 FlexVol 볼륨을 스토리지 QoS(서비스 품질) 정책 그룹에 할당하여 처리량을 제한할 수 있습니다. 새 볼륨에 스토리지 QoS를 할당하거나 System Manager를 사용하여 정책 그룹에 이미 할당된 볼륨의 스토리지 QoS 세부 정보를 수정할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 스토리지 QoS에 볼륨을 할당합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 FlexVol 볼륨 및 FlexGroup 볼륨을 스토리지 QoS(서비스 품질) 정책 그룹에 할당하여 처리량을 제한할 수 있습니다. 새 볼륨에 스토리지 QoS를 할당하거나 System Manager를 사용하여 정책 그룹에 이미 할당된 볼륨의 스토리지 QoS 세부 정보를 수정할 수 있습니다.

.이 작업에 대해
* 스토리지 QoS는 온라인 상태인 읽기/쓰기(RW) 볼륨에만 할당할 수 있습니다.
* 다음 스토리지 객체가 정책 그룹에 할당된 경우 볼륨에 스토리지 QoS를 할당할 수 없습니다.
+
** 볼륨의 상위 스토리지 가상 시스템(SVM
** 볼륨의 하위 LUN입니다
** 볼륨의 하위 파일


* 스토리지 QoS를 할당하거나 최대 10개의 볼륨에 대한 QoS 세부 정보를 동시에 수정할 수 있습니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 스토리지 QoS를 할당할 볼륨을 하나 이상 선택합니다.
. 추가 작업 * > * 스토리지 QoS * 를 클릭합니다.
. FlexVol 볼륨의 워크로드 성능을 관리하려면 * 서비스 품질 세부 정보 * 대화 상자에서 * 스토리지 서비스 품질 관리 * 확인란을 선택합니다.
+
선택한 볼륨 중 일부가 이미 정책 그룹에 할당된 경우 변경한 내용이 해당 볼륨의 성능에 영향을 줄 수 있습니다.

. 새 스토리지 QoS 정책 그룹을 생성하거나 기존 정책 그룹을 선택하여 FlexVol 볼륨의 I/O(Input/Output) 성능을 제어합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
새 정책 그룹을 생성합니다
 a| 
.. 새 정책 그룹 * 을 선택합니다.
.. 정책 그룹 이름을 지정합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.







 a| 
기존 정책 그룹을 선택합니다
 a| 
.. 기존 정책 그룹 * 을 선택한 다음 * 선택 * 을 클릭하여 정책 그룹 선택 대화 상자에서 기존 정책 그룹을 선택합니다.
.. 최소 처리량 제한을 지정합니다.
+
*** System Manager 9.5에서는 성능 기반 All-Flash 최적화 개인성에만 최소 처리량 제한을 설정할 수 있습니다. System Manager 9.6에서는 ONTAP Select 프리미엄 시스템의 최소 처리량 제한도 설정할 수 있습니다.
*** FabricPool 지원 애그리게이트에서 볼륨의 최소 처리량 한도를 설정할 수 없습니다.
*** 최소 처리량 값을 지정하지 않거나 최소 처리량 값이 0으로 설정되어 있으면 시스템은 자동으로 ""없음""을 값으로 표시합니다.
+
이 값은 대/소문자를 구분합니다.



.. 정책 그룹에 있는 개체의 워크로드가 지정된 처리량 제한을 초과하지 않도록 최대 처리량 제한을 지정합니다.
+
*** 최소 처리량 제한과 최대 처리량 제한은 단위 유형이 동일해야 합니다.
*** 최소 처리량 제한을 지정하지 않으면 IOPS, B/s, KB/s, MB/s 등의 최대 처리량 제한을 설정할 수 있습니다.
*** 최대 처리량값을 지정하지 않으면 시스템은 자동으로 ""무제한""을 값으로 표시합니다.
  를 누릅니다
이 값은 대/소문자를 구분합니다. 지정하는 단위는 최대 처리량에 영향을 주지 않습니다.


+
정책 그룹이 둘 이상의 개체에 할당된 경우 지정한 최대 처리량은 객체 간에 공유됩니다.



|===
. * 선택 사항: * 선택한 볼륨 목록을 검토하려면 볼륨 수를 지정하는 링크를 클릭한 다음 목록에서 볼륨을 제거하려면 * 폐기 * 를 클릭합니다.
+
이 링크는 여러 볼륨을 선택한 경우에만 표시됩니다.

. 확인 * 을 클릭합니다.

