---
permalink: online-help-96-97/task_provisioning_cache_by_adding_disks.html 
sidebar: sidebar 
keywords: ssd, system, manager, storage, pool, root, aggregate, provision, cache, online, help, ssd, disks, flash, pool 
summary: System Manager를 사용하면 SSD를 스토리지 풀 또는 전용 SSD로 추가하여 캐시를 프로비저닝할 수 있습니다. SSD를 추가하면 루트 이외의 Aggregate 또는 분할된 디스크가 없는 루트 Aggregate를 Flash Pool Aggregate로 변환하거나 기존 Flash Pool 애그리게이트의 캐시 크기를 늘릴 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SSD를 추가하여 캐시 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 SSD를 스토리지 풀 또는 전용 SSD로 추가하여 캐시를 프로비저닝할 수 있습니다. SSD를 추가하면 루트 이외의 Aggregate 또는 분할된 디스크가 없는 루트 Aggregate를 Flash Pool Aggregate로 변환하거나 기존 Flash Pool 애그리게이트의 캐시 크기를 늘릴 수 있습니다.

.이 작업에 대해
* 추가된 SSD 캐시는 애그리게이트 크기에 추가되지 않으며 최대 크기에서도 애그리게이트에 SSD RAID 그룹을 추가할 수 있습니다.
* System Manager를 사용하여 캐시를 추가할 때는 파티션이 설정된 SSD를 사용할 수 없습니다.




== SSD를 추가하여 애그리게이트에 캐시를 프로비저닝합니다

System Manager를 사용하면 기존의 비루트 HDD 애그리게이트 또는 분할된 디스크가 포함되지 않은 루트 애그리게이트를 Flash Pool 애그리게이트로 변환하여 스토리지 풀 또는 전용 SSD를 추가하여 캐시를 프로비저닝할 수 있습니다.

.시작하기 전에
* 애그리게이트는 온라인 상태여야 합니다.
* 스토리지 풀에 캐시 디스크로 할당할 수 있는 충분한 예비 SSD 또는 할당 유닛이 있어야 합니다.
* 클러스터의 모든 노드에서 ONTAP 8.3 이상이 실행되고 있어야 합니다.
+
클러스터가 혼합 버전 상태인 경우 명령줄 인터페이스를 사용하여 Flash Pool 애그리게이트를 생성한 다음 SSD 캐시를 프로비저닝할 수 있습니다.

* Flash Pool 애그리게이트로 변환할 수 있는 HDD로 구성된 유효한 64비트 비루트 애그리게이트를 식별해야 합니다.
* Aggregate는 어레이 LUN을 포함하지 않아야 합니다.


.이 작업에 대해
Flash Pool 애그리게이트 SSD 계층 크기 및 구성에 대한 플랫폼별 및 워크로드별 모범 사례를 알고 있어야 합니다.

.단계
. 다음 방법 중 하나를 선택합니다.
+
** Applications & Tiers * > * Storage Tiers * 를 클릭합니다.
** 스토리지 * > * 애그리게이트 및 디스크 * > * 애그리게이트 * 를 클릭합니다.


. Storage Tiers * 창에서 애그리게이트를 선택한 다음 * More Actions * > * Add Cache * 를 클릭합니다.
+
[NOTE]
====
FabricPool 지원 애그리게이트에서는 캐시 추가가 지원되지 않습니다.

====
. 캐시 추가 * 대화 상자에서 적절한 작업을 수행합니다.
+
|===
| 캐시 소스를 다음과 같이 선택한 경우 | 수행할 작업... 


 a| 
지원합니다
 a| 
.. 캐시를 가져올 수 있는 스토리지 풀을 선택합니다.
.. 캐시 크기를 지정합니다.
.. 필요한 경우 RAID 유형을 수정합니다.




 a| 
전용 SSD
 a| 
SSD 크기와 포함할 SSD 수를 선택하고, 선택적으로 RAID 구성을 수정합니다.

.. 변경 * 을 클릭합니다.
.. RAID 구성 변경 대화 상자에서 RAID 유형 및 RAID 그룹 크기를 지정한 다음 * 저장 * 을 클릭합니다.


|===
. 추가 * 를 클릭합니다.
+
미러링된 애그리게이트의 경우 선택한 디스크 수의 2배가 추가되는 정보와 함께 * Add Cache * (캐시 추가 *) 대화 상자가 표시됩니다.

. 캐시 추가 * 대화 상자에서 * 예 * 를 클릭합니다.


.결과
캐시 디스크가 선택한 Aggregate에 추가됩니다.



== SSD를 추가하여 Flash Pool 애그리게이트의 캐시 증가

System Manager를 사용하여 SSD를 스토리지 풀 또는 전용 SSD로 추가하여 Flash Pool 애그리게이트의 크기를 늘릴 수 있습니다.

.시작하기 전에
* Flash Pool 애그리게이트는 온라인 상태여야 합니다.
* 스토리지 풀에 캐시 디스크로 할당할 수 있는 충분한 예비 SSD 또는 할당 유닛이 있어야 합니다.


.단계
. 스토리지 * > * 애그리게이트 및 디스크 * > * 애그리게이트 * 를 클릭합니다.
. 애그리게이트 * 창에서 Flash Pool 애그리게이트를 선택한 다음 * 캐시 추가 * 를 클릭합니다.
. 캐시 추가 * 대화 상자에서 적절한 작업을 수행합니다.
+
|===
| 캐시 소스를 다음과 같이 선택한 경우 | 수행할 작업... 


 a| 
지원합니다
 a| 
캐시를 가져올 수 있는 스토리지 풀을 선택하고 캐시 크기를 지정합니다.



 a| 
전용 SSD
 a| 
SSD 크기와 포함할 SSD 수를 선택합니다.

|===
. 추가 * 를 클릭합니다.
+
미러링된 애그리게이트의 경우 Add Cache(캐시 추가) 대화 상자에 선택한 디스크 수의 2배가 추가될 정보가 표시됩니다.

. 캐시 추가 * 대화 상자에서 * 예 * 를 클릭합니다.


.결과
캐시 디스크가 선택한 Flash Pool 애그리게이트에 추가됩니다.

* 관련 정보 *

http://www.netapp.com/us/media/tr-4070.pdf["NetApp 기술 보고서 4070: Flash Pool 설계 및 구축"^]

xref:concept_how_storage_pool_works.adoc[스토리지 풀의 작동 방식]
