---
permalink: online-help-96-97/task_delegating_administration_to_svm_administrators.html 
sidebar: sidebar 
keywords: online, help, delegate, administration, svm, administrator 
summary: '기본 네트워크 구성을 사용하여 기능 SVM(스토리지 가상 시스템) 또는 SVM을 설정한 후에는 SVM 관리를 SVM 관리자에게 선택적으로 위임할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 SVM 관리자에게 관리 권한을 위임합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 기본 네트워크 구성을 사용하여 SVM(기능 스토리지 가상 시스템) 또는 SVM을 설정한 후 SVM 관리자에게 SVM 관리 권한을 선택적으로 위임할 수 있습니다.

.이 작업에 대해
SVM 관리자는 System Manager를 사용하여 위임된 SVM을 관리할 수 없습니다. 관리자는 CLI(Command-Line Interface)를 통해서만 관리할 수 있습니다.

.단계
. 관리자 세부 정보 * 섹션에서 에 대한 암호를 설정합니다 `vsadmin` 사용자 계정.
. SVM 관리를 위한 전용 LIF를 원하는 경우 * SVM 관리를 위한 LIF 생성 * 을 선택하고 네트워크 세부 정보를 지정합니다.
+
SAN 프로토콜에는 데이터 및 관리 프로토콜이 동일한 LIF를 공유할 수 없는 전용 SVM 관리 LIF가 필요합니다. SVM 관리 LIF는 데이터 포트에만 생성할 수 있습니다.

. iSCSI LIF를 생성하기 위한 서브넷 세부 정보를 비롯한 네트워크 세부 정보를 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
서브넷을 사용하여 IP 주소를 지정합니다
 a| 
.. 서브넷 사용 * 을 선택합니다.
.. 세부 정보 추가 대화 상자에서 IP 주소를 할당해야 하는 서브넷을 선택합니다.
+
인터클러스터 LIF의 경우 선택한 IPspace와 연결된 서브넷만 표시됩니다.

.. 인터페이스에 특정 IP 주소를 할당하려면 * 특정 IP 주소 사용 * 을 선택한 다음 IP 주소를 입력합니다.
+
지정한 IP 주소가 서브넷 범위에 아직 없는 경우 서브넷에 추가됩니다.

.. 확인 * 을 클릭합니다.




 a| 
서브넷을 사용하지 않고 수동으로 IP 주소를 지정합니다
 a| 
.. 서브넷 없이 * 를 선택합니다.
.. 세부 정보 추가 대화 상자에서 다음 단계를 수행합니다.
+
... IP 주소와 네트워크 마스크 또는 접두사를 지정합니다.
... 선택 사항: 게이트웨이를 지정합니다.
... 대상 필드의 기본값을 사용하지 않으려면 새 대상 값을 지정합니다.
+
사용자 지정 값을 지정하지 않으면 대상 필드가 IP 주소 패밀리를 기준으로 기본값으로 채워집니다.

+
라우트가 존재하지 않으면 게이트웨이와 목적지를 기반으로 새 루트가 자동으로 생성됩니다.



.. 확인 * 을 클릭합니다.


|===
. 데이터 LIF를 생성할 포트를 지정합니다.
+
.. 찾아보기 * 를 클릭합니다.
.. 네트워크 포트 또는 어댑터 선택 대화 상자에서 포트를 선택합니다.
.. 확인 * 을 클릭합니다.




.결과
를 클릭합니다 `vsadmin` 계정이 잠금 해제되고 암호로 구성됩니다.

의 기본 액세스 방법입니다 `vsadmin` 계정은 ONTAP API입니다 `(ontapi)` 및 SSH로 이동합니다 `(ssh)`. SVM 관리자는 관리 IP 주소를 사용하여 스토리지 시스템에 로그인할 수 있습니다.



== 다음 단계

스토리지 가상 시스템 편집 대화 상자를 사용하여 SVM에 애그리게이트를 할당해야 합니다.

[NOTE]
====
SVM에 할당된 애그리게이트가 없는 경우 SVM 관리자는 볼륨을 생성할 수 없습니다.

====