---
permalink: online-help-96-97/task_editing_mirror_relationships.html 
sidebar: sidebar 
keywords: system, manager, edit, mirror, relationships, online, help 
summary: System Manager를 사용하면 클러스터에서 기존 정책 또는 스케줄을 선택하거나 정책 또는 스케줄을 생성하여 미러 관계를 편집할 수 있습니다. 
---
= System Manager - ONTAP 9.7 이하를 사용하여 미러 관계를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하여 미러 관계를 관리할 수 있습니다. 업데이트, 생성, 중지, 초기화, 재설정, 중지된 미러 관계를 재개하는 것 외에도 미러 관계를 삭제 및 편집합니다.



== 관계 삭제

System Manager를 사용하여 미러 관계를 삭제하고 소스 볼륨과 타겟 볼륨 간의 미러 관계를 영구적으로 종료할 수 있습니다. 미러 관계가 삭제되면 소스 볼륨의 기본 스냅샷 복사본이 삭제됩니다.

.이 작업에 대해
관계를 삭제하기 전에 미러 관계를 끊는 것이 좋습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 삭제할 미러 관계를 선택하고 * 삭제 * 를 클릭합니다.
. 확인 확인란을 선택하여 미러 관계를 삭제하고 기본 스냅샷 복사본을 해제한 다음 * 삭제 * 를 클릭합니다.


.결과
관계가 삭제되고 소스 볼륨의 기본 스냅샷 복사본이 삭제됩니다.



== 관계를 재동기화합니다

System Manager를 사용하여 이전에 파손된 미러 관계를 다시 설정할 수 있습니다. 재동기화 작업을 수행하여 소스 볼륨을 비활성화한 재재해에서 복구할 수 있습니다.

.시작하기 전에
소스 클러스터와 타겟 클러스터, 소스 SVM 및 타겟 SVM이 피어 관계에 있어야 합니다.

.이 작업에 대해
* 재동기화 작업을 수행하면 소스 볼륨의 컨텐츠가 미러 대상의 컨텐츠를 덮어씁니다.
+
[NOTE]
====
** SnapLock 규정 준수 볼륨의 경우, 현재 볼륨에 대해 설정된 만료 시간까지, 공통 스냅샷 복사본을 참조하여 액티브 파일 시스템의 모든 데이터 변경이 잠긴 스냅샷 복사본에 유지됩니다.
+
볼륨 만료 시간이 경과되었거나 설정되지 않은 경우 스냅샷 복사본과 공통 스냅샷 복사본이 30일 동안 잠깁니다. 공통 스냅샷 복사본과 최신 잠금 스냅샷 복사본 간의 중간 스냅샷 복사본이 모두 삭제됩니다.

** SnapLock 규정 준수 볼륨 이외의 모든 볼륨에 대해 재동기화 작업을 수행하면 기본 스냅샷 복사본이 생성된 후 대상 볼륨에 기록되는 최신 데이터가 손실될 수 있습니다.


====
* 보호 창의 마지막 전송 오류 필드에서 재동기화 작업을 권장하는 경우 먼저 관계를 끊은 다음 재동기화 작업을 수행해야 합니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 재동기화할 미러 관계를 선택합니다.
. 작업 * > * 재동기화 * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 재동기화 * 를 클릭합니다.




== 중단된 관계를 다시 시작합니다

System Manager를 사용하여 중지된 미러 관계를 재개할 수 있습니다. 관계를 재개하면 미러 대상에 대한 정상적인 데이터 전송이 재개되고 모든 미러 작업이 다시 시작됩니다.

.이 작업에 대해
CLI(Command-Line Interface)에서 손상된 미러 관계를 중지했다면 System Manager에서 관계를 재개할 수 없습니다. CLI를 사용하여 관계를 재개해야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 재개할 미러 관계를 선택합니다.
. Operations * > * Resume * 을 클릭합니다.
. 확인 확인란을 선택하고 * Resume * 을 클릭합니다.


.결과
미러 대상에 대한 데이터 전송이 선택한 미러 관계에 대해 재개됩니다.



== 관계 업데이트

System Manager를 사용하여 예정되지 않은 대상 미러 업데이트를 시작할 수 있습니다. 예정된 정전, 예약된 유지 관리 또는 데이터 마이그레이션으로 인한 데이터 손실을 방지하려면 수동 업데이트를 수행해야 할 수 있습니다.

.시작하기 전에
미러 관계는 SnapMirrored 상태여야 합니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 데이터를 업데이트할 미러 관계를 선택하고 * 운영 * > * 업데이트 * 를 클릭합니다.
. 다음 옵션 중 하나를 선택합니다.
+
** 소스 볼륨과 타겟 볼륨 간의 최신 공통 스냅샷 복사본에서 증분 전송을 수행하려면 * On demand * 를 선택합니다.
** 스냅샷 복사본 선택 * 을 선택하고 전송할 스냅샷 복사본을 지정합니다.


. * 선택 사항: * 전송에 사용되는 네트워크 대역폭을 제한하고 최대 전송 속도를 지정하려면 * 전송 대역폭을 * 로 제한합니다.
. Update * 를 클릭합니다.
. 세부 정보 * 탭에서 전송 상태를 확인합니다.




== 관계를 중지합니다

System Manager를 사용하여 스냅샷 복사본을 생성하기 전에 미러 대상을 중지하여 안정화할 수 있습니다. 일시 중지 작업을 수행하면 활성 미러 전송이 완료되며 미러링 관계에 대한 향후 전송이 비활성화됩니다.

.이 작업에 대해
SnapMirrored 상태인 미러 관계만 중지할 수 있습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 일시 중지할 미러 관계를 선택합니다.
. 작업 * > * 정지 * 를 클릭합니다.
. 확인 확인란을 선택하고 * 정지 * 를 클릭합니다.




== 관계 초기화

미러 관계를 시작할 때는 해당 관계를 초기화해야 합니다. 관계 초기화는 소스 볼륨에서 대상으로 데이터의 전체 베이스라인 전송으로 구성됩니다. 미러 관계를 생성하는 동안 관계를 초기화하지 않은 경우 System Manager를 사용하여 미러 관계를 초기화할 수 있습니다.

.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 초기화할 미러 관계를 선택하십시오.
. Operations * > * Initialize * 를 클릭합니다.
. 확인 확인란을 선택하고 * Initialize * 를 클릭합니다.
. Protection * 창에서 미러 관계의 상태를 확인합니다.


.결과
스냅샷 복사본이 생성되어 타겟으로 전송됩니다. 이 스냅샷 복사본은 이후의 증분 스냅샷 복사본을 위한 기준으로 사용됩니다.



== 관계 편집

System Manager를 사용하면 클러스터에서 기존 정책 또는 스케줄을 선택하거나 정책 또는 스케줄을 생성하여 미러 관계를 편집할 수 있습니다.

.이 작업에 대해
* Data ONTAP 8.2.1의 볼륨과 ONTAP 8.3 이상의 볼륨 사이에 생성된 미러 관계는 편집할 수 없습니다.
* 기존 정책 또는 스케줄의 매개 변수는 편집할 수 없습니다.
* 정책 유형을 수정하여 버전에 상관없이 유연한 미러 관계, 볼트 관계, 미러 및 볼트 관계의 관계 유형을 수정할 수 있습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 정책 또는 스케줄을 수정할 미러 관계를 선택한 다음 * Edit * 를 클릭합니다.
. [관계 편집] * 대화 상자에서 기존 정책을 선택하거나 정책을 작성합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다. 


 a| 
기존 정책을 선택합니다
 a| 
찾아보기 * 를 클릭한 다음 기존 정책을 선택합니다.



 a| 
정책을 생성합니다
 a| 
.. Create Policy * 를 클릭합니다.
.. 정책의 이름을 지정합니다.
.. 예약된 전송의 우선 순위를 설정합니다.
+
낮음 은 전송 우선 순위가 가장 낮으며 일반적으로 일반 우선 순위 전송 후에 예약됨을 나타냅니다. 기본적으로 우선 순위는 보통으로 설정됩니다.

.. "'ALL_SOURCE_SNAPSHOTS" 규칙을 미러 정책에 포함하려면 * Transfer All Source Snapshot Copies * 확인란을 선택합니다. 이 규칙을 사용하면 소스 볼륨의 모든 스냅샷 복사본을 백업할 수 있습니다.
.. 전송 중인 데이터를 압축하려면 * 네트워크 압축 사용 * 확인란을 선택합니다.
.. Create * 를 클릭합니다.


|===
. 관계의 일정을 지정합니다.
+
|===
| 만약... | 다음을 수행합니다. 


 a| 
기존 일정을 할당하려고 합니다
 a| 
스케줄 목록에서 기존 스케줄을 선택합니다.



 a| 
스케줄을 생성하려고 합니다
 a| 
.. Create Schedule * 을 클릭합니다.
.. 스케줄의 이름을 지정합니다.
.. 기본 * 또는 * 고급 * 을 선택합니다.
+
*** Basic은 요일, 시간 및 전송 간격만 지정합니다.
*** Advanced는 cron 스타일의 스케줄을 생성합니다.


.. Create * 를 클릭합니다.




 a| 
일정을 지정하지 않으려는 경우
 a| 
없음 * 을 선택합니다.

|===
. 확인 * 을 클릭하여 변경 사항을 저장합니다.




== 대상 SVM에서 미러링 관계 생성

System Manager를 사용하여 대상 SVM(스토리지 가상 머신)에서 미러링 관계를 생성하고 정책 및 스케줄을 미러 관계에 할당할 수 있습니다. 미러 복제본을 사용하면 소스 볼륨의 데이터가 손상되거나 손실된 경우 데이터를 빠르게 사용할 수 있습니다.

.시작하기 전에
* 소스 클러스터는 ONTAP 8.2.2 이상을 실행해야 합니다.
* 소스 클러스터와 대상 클러스터에서 SnapMirror 라이센스가 활성화되어야 합니다.
+
[NOTE]
====
일부 플랫폼의 경우 대상 클러스터에 SnapMirror 라이센스 및 DPO(데이터 보호 최적화) 라이센스가 활성화되어 있는 경우 소스 클러스터에 SnapMirror 라이센스가 활성화되어 있지 않아도 됩니다.

====
* 볼륨을 미러링하는 동안 SnapLock 볼륨을 소스로 선택하면 SnapMirror 라이센스와 SnapLock 라이센스가 대상 클러스터에 설치되어 있어야 합니다.
* 소스 클러스터와 대상 클러스터는 정상 피어 관계에 있어야 합니다.
* 대상 SVM에 사용 가능한 공간이 있어야 합니다.
* 읽기/쓰기(RW) 유형의 소스 볼륨이 있어야 합니다.
* FlexVol 볼륨은 온라인이어야 하며 읽기/쓰기 유형이어야 합니다.
* SnapLock 집계 유형은 같은 유형이어야 합니다.
* ONTAP 9.2 이하 버전을 실행하는 클러스터에서 SAML(Security Assertion Markup Language) 인증이 활성화된 원격 클러스터로 연결하는 경우 원격 클러스터에서 암호 기반 인증을 활성화해야 합니다.


.이 작업에 대해
* System Manager는 계단식 관계를 지원하지 않습니다.
+
예를 들어, 관계의 대상 볼륨은 다른 관계의 소스 볼륨이 될 수 없습니다.

* MetroCluster 구성에서 동기화 소스 SVM과 동기화 대상 SVM 간에 미러 관계를 생성할 수 없습니다.
* MetroCluster 구성에서 동기화 소스 SVM 간에 미러 관계를 생성할 수 있습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 지원 SVM의 볼륨으로 미러 관계를 생성할 수 있습니다.
* 데이터 지원 SVM의 볼륨에서 동기화 소스 SVM의 데이터 보호(DP) 볼륨으로 미러 관계를 생성할 수 있습니다.
* 같은 유형의 SnapLock 볼륨에만 미러 관계를 생성할 수 있습니다.
+
예를 들어 소스 볼륨이 SnapLock 엔터프라이즈 볼륨인 경우 대상 볼륨도 SnapLock 엔터프라이즈 볼륨이어야 합니다. 대상 SVM에 사용 가능한 SnapLock 유형의 애그리게이트가 있는지 확인해야 합니다.

* 미러 관계를 위해 생성된 타겟 볼륨이 씬 프로비저닝되지 않습니다.
* 한 번에 최대 25개의 볼륨을 보호할 수 있습니다.
* 타겟 클러스터에서 소스 클러스터가 실행 중인 ONTAP 버전보다 이전 버전의 ONTAP를 실행 중인 경우 SnapLock 볼륨 간에 미러 관계를 생성할 수 없습니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 볼륨 관계 * 창에서 * 생성 * 을 클릭합니다.
. SVM * 찾아보기 대화 상자에서 타겟 볼륨의 SVM을 선택합니다.
. [보호 관계 작성] * 대화 상자의 [관계 유형 *] 드롭다운 목록에서 [미러 *]를 선택합니다.
. 클러스터, SVM 및 소스 볼륨을 지정합니다.
+
지정된 클러스터에서 ONTAP 9.3 이전 버전의 ONTAP 소프트웨어를 실행 중인 경우 피어링된 SVM만 나열됩니다. 지정된 클러스터에서 ONTAP 9.3 이상이 실행 중인 경우 피어링된 SVM 및 허용된 SVM이 나열됩니다.

. FlexVol 볼륨의 경우 볼륨 이름 접미사를 지정합니다.
+
대상 볼륨 이름을 생성하기 위해 소스 볼륨 이름에 볼륨 이름 접미사가 추가됩니다.

. 찾아보기 * 를 클릭한 다음 미러 정책을 변경합니다.
. 기존 일정 목록에서 관계의 일정을 선택합니다.
. 미러 관계를 초기화하려면 * 관계 초기화 * 를 선택합니다.
. FabricPool 지원 애그리게이트를 사용하도록 설정한 다음 적절한 계층화 정책을 선택합니다.
. Create * 를 클릭합니다.


.결과
대상 볼륨을 만들도록 선택한 경우, 소스 볼륨의 언어 특성과 일치하도록 설정된 언어 속성을 사용하여 _DP_ 유형의 대상 볼륨이 생성됩니다.

소스 볼륨과 타겟 볼륨 사이에 미러 관계가 생성됩니다. 관계를 초기화하기로 선택한 경우 기본 스냅샷 복사본이 대상 볼륨으로 전송됩니다.



== 미러 관계를 역재동기화합니다

System Manager를 사용하여 이전에 손상된 미러 관계를 다시 설정할 수 있습니다. 역방향 재동기화 작업에서는 소스 볼륨과 타겟 볼륨의 기능을 반대로 전환합니다.

.시작하기 전에
소스 볼륨이 온라인 상태여야 합니다.

.이 작업에 대해
* 소스 볼륨을 복구 또는 교체하고 소스 볼륨을 업데이트하고 시스템의 원래 구성을 다시 설정하는 동안 대상 볼륨을 사용하여 데이터를 제공할 수 있습니다.
* 역방향 재동기화를 수행하면 타겟 볼륨의 컨텐츠가 미러 소스의 컨텐츠를 덮어씁니다.
+
[NOTE]
====
** SnapLock 규정 준수 볼륨의 경우, 현재 볼륨에 대해 설정된 만료 시간까지, 공통 스냅샷 복사본을 참조하여 액티브 파일 시스템의 모든 데이터 변경이 잠긴 스냅샷 복사본에 유지됩니다.
+
볼륨 만료 시간이 경과되었거나 설정되지 않은 경우 스냅샷 복사본과 공통 스냅샷 복사본이 30일 동안 잠깁니다. 공통 스냅샷 복사본과 최신 잠금 스냅샷 복사본 간의 중간 스냅샷 복사본이 모두 삭제됩니다.

** SnapLock 규정 준수 볼륨 이외의 모든 볼륨에 대해 재동기화 작업을 수행하면 기본 스냅샷 복사본이 생성된 후 소스 볼륨에 기록되는 최신 데이터가 손실될 수 있습니다.


====
* 역재동기화를 수행하면 관계의 미러 정책이 DPDefault로 설정되고 미러 스케줄이 None으로 설정됩니다.


.단계
. 보호 * > * 볼륨 관계 * 를 클릭합니다.
. 반전할 미러 관계를 선택합니다.
. Operations * > * Reverse Resync * 를 클릭합니다.
. 확인 확인란을 선택한 다음 * 역방향 재동기화 * 를 클릭합니다.


* 관련 정보 *

xref:reference_protection_window.adoc[보호 윈도우]
