---
permalink: online-help-96-97/task_editing_volume_properties.html 
sidebar: sidebar 
keywords: edit, volume, properties, online, help, deduplication, system, manager 
summary: 'System Manager를 사용하여 볼륨 이름, 보안 스타일, 부분 예약 및 공간 보장과 같은 볼륨 속성을 수정할 수 있습니다. 스토리지 효율성 설정(중복제거 일정, 중복제거 정책 및 압축) 및 공간 재확보 설정을 수정할 수 있습니다.' 
---
= System Manager - ONTAP 9.7 이하를 사용하여 볼륨 속성을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 볼륨 이름, 보안 스타일, 부분 예약, 공간 보장 등의 볼륨 속성을 수정할 수 있습니다. 스토리지 효율성 설정(중복제거 일정, 중복제거 정책 및 압축) 및 공간 재확보 설정을 수정할 수 있습니다.

.시작하기 전에
볼륨 암호화를 사용하려면 System Manager를 사용하여 볼륨 암호화 라이센스를 설치해야 하며 CLI(Command-Line Interface)를 사용하여 ""key-manager setup""을 활성화해야 합니다. ""Key-manager setup""을 활성화한 후 웹 브라우저를 새로 고쳐야 합니다.

.이 작업에 대해
* 부분 예약 공간은 0% 또는 100%로 설정할 수 있습니다.
* 32비트 볼륨에서는 데이터 압축이 지원되지 않습니다.
* Data ONTAP 8.3.1 클러스터의 경우, AWS(Cloud Volumes ONTAP for AWS)에 인라인 압축과 백그라운드 압축을 모두 사용할 수 있습니다.
+
Data ONTAP Edge에는 압축이 지원되지 않습니다.

* SnapLock 준수 볼륨의 이름은 변경할 수 없습니다.


.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 편집할 볼륨이 있는 SVM(스토리지 가상 머신)을 선택합니다.
. 수정할 볼륨을 선택한 다음 * 편집 * 을 클릭합니다.
+
Edit Volume(볼륨 편집) 대화 상자가 표시됩니다.

. 일반 * 탭에서 필요에 따라 다음 속성을 수정합니다.
+
** 볼륨 이름을 변경합니다
** 볼륨 암호화를 활성화합니다
+
이 옵션은 볼륨 암호화 라이센스를 활성화했으며 해당 플랫폼이 암호화를 지원하는 경우에만 사용할 수 있습니다. CLI에서 Key-manager 설정을 수행할 수 있습니다.

** 볼륨의 보안 스타일을 변경합니다
** 씬 프로비저닝을 설정하거나 해제합니다


. Storage Efficiency * 탭을 클릭하고 다음 속성을 구성하여 스토리지 효율성을 설정합니다.
+
** 중복 제거
** 데이터 압축
All-Flash 최적화 속성을 가진 애그리게이트에 포함된 볼륨에 대해 백그라운드 압축을 활성화할 수는 없습니다. 이러한 볼륨에 대해 인라인 압축만 활성화할 수 있습니다.


+
All-Flash 최적화 속성을 가진 애그리게이트 또는 Flash Pool 애그리게이트의 볼륨에 포함된 볼륨에만 인라인 중복제거를 사용할 수 있습니다.

. SnapLock 볼륨의 경우 * SnapLock * 탭을 클릭하고 다음 단계를 수행하십시오.
+
.. 자동 커밋 기간을 지정합니다.
+
자동 커밋 기간은 파일이 WORM 상태로 커밋되기 전에 볼륨의 파일이 변경되지 않은 상태로 유지되는 기간을 결정합니다.

.. 최소 보존 기간 및 최대 보존 기간을 지정합니다.
+
값은 1일 ~ 70년 또는 무한대의 범위에 있어야 합니다.

.. 기본 보존 기간을 선택합니다.
+
기본 보존 기간은 지정된 최소 보존 기간 및 최대 보존 기간 이내여야 합니다.



. 고급 * 탭을 클릭하고 다음 속성을 활성화합니다.
+
** 볼륨에서 사용된 공간이 확장 임계값을 초과할 때 볼륨이 자동으로 증가하도록 하려면 * grow * 를 선택합니다.
** 사용된 공간의 크기에 따라 볼륨을 늘리거나 축소하려면 * 확대 또는 축소 * 를 선택합니다.
+
... 볼륨을 확장할 수 있는 최대 크기를 지정합니다.


** 다음 옵션 중 하나를 선택하여 이전 스냅샷 복사본을 자동으로 삭제할 수 있습니다.
+
*** 시도해 보십시오
+
다른 서브시스템에 의해 잠기지 않은 스냅샷 복사본을 삭제합니다.

*** 폐기
+
데이터 백업 기능에 의해 잠긴 스냅샷 복사본을 삭제합니다.

*** 중단하다
+
이 명령어는 데이터 전송을 방해할 수 있는 스냅샷 복사본을 삭제합니다.



** 볼륨에 할당할 캐싱 정책을 선택합니다.
+
이 옵션은 Flash Pool 애그리게이트의 FlexVol 볼륨에 대해서만 사용할 수 있습니다.

** 볼륨의 캐시된 데이터에 대한 보존 우선 순위를 선택합니다.
+
이 옵션은 Flash Pool 애그리게이트의 FlexVol 볼륨에 대해서만 사용할 수 있습니다.

** 볼륨에 설정할 부분 예약 공간을 지정합니다.
** 파일을 읽는 데 필요한 액세스 시간을 업데이트합니다.
+
이 옵션은 SnapLock 볼륨에 대해 비활성화되어 있습니다.



. 저장 후 닫기 * 를 클릭합니다.


* 관련 정보 *

xref:reference_volumes_window.adoc[볼륨 창]

xref:task_setting_up_cifs.adoc[CIFS를 설정하는 중입니다]
