---
permalink: online-help-96-97/task_adding_microsoft_sql_server_over_san_to_system_manager.html 
sidebar: sidebar 
keywords: add, microsoft, sql, server, san, system, manager, online, help, enhanced, tab 
summary: Enhanced 탭을 사용하여 SAN을 통한 Microsoft SQL Server의 인스턴스를 System Manager에 추가할 수 있습니다. 
---
= SAN을 통한 Microsoft SQL Server를 System Manager-ONTAP 9.7 이하에 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
고급 탭을 사용하여 SAN을 통한 Microsoft SQL Server의 인스턴스를 ONTAP System Manager 클래식(ONTAP 9.7 및 이전 버전에서 사용 가능)에 추가할 수 있습니다.

.이 작업에 대해
다음 절차에서는 SAN을 통해 System Manager에 * Microsoft SQL Server * 인스턴스를 추가하는 방법에 대해 설명합니다. 스토리지 가상 시스템(SVM)에서 구성되어야 하는 CIFS에 대한 라이센스가 클러스터에 부여된 경우에만 SMB를 엑스포트 프로토콜로 선택할 수 있습니다.

.단계
. 응용 프로그램 및 계층 * > * 응용 프로그램 * 을 클릭합니다
. Enhanced * (고급 *) 탭에서 * Add * (추가 *)를 클릭합니다
. 메뉴에서 * Microsoft SQL Server 인스턴스 * 를 선택합니다.
+
[NOTE]
====
드롭다운 목록에는 사용 가능한 모든 애플리케이션 유형과 템플릿 유형의 목록이 포함되어 있습니다.

====
+
Microsoft SQL Server 인스턴스 추가 창이 표시됩니다.

. 다음 세부 정보를 지정합니다.
+
** 데이터베이스 이름
** 데이터베이스 크기 및 필요한 ONTAP 서비스 수준입니다
** 서버 코어 수
** 로그 크기 및 필요한 ONTAP 서비스 수준입니다
** Tempdb에 대한 프로비저닝
+
Tempdb에 대해 서버를 프로비저닝해야 하는지 여부를 지정합니다.

** 내보내기 프로토콜(SMB 또는 SAN)
+
SAN을 지정합니다

** 호스트 운영 체제입니다
** LUN 형식입니다
** 호스트 매핑


. 응용 프로그램 추가 * 를 클릭합니다


.결과
SAN을 통한 Microsoft SQL Server 인스턴스가 System Manager에 추가됩니다.
