---
permalink: online-help-96-97/task_performing_switchback.html 
sidebar: sidebar 
keywords: metrocluster, perform, switchback, system, manager, online, help 
summary: 'System Manager 9.6부터는 시스템이 성공적인 스위치오버 작업을 완료한 후 원래 MetroCluster 사이트(사이트 B)로 제어를 복원하는 스위치백 작업을 수행할 수 있습니다.' 
---
= 스위치백을 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6부터는 시스템이 성공적인 스위치오버 작업을 완료한 후 원래 MetroCluster 사이트(사이트 B)로 제어를 복원하는 스위치백 작업을 수행할 수 있습니다.

.시작하기 전에
스위치백 작업을 수행하기 전에 다음 작업을 완료해야 합니다.

* 에서 MetroCluster 사이트를 준비해야 합니다 xref:task_performing_negotiated_planned_switchover.adoc[협상된(계획된) 전환 수행] 또는 xref:task_performing_unplanned_switchover.adoc[계획되지 않은 전환 수행].
* 복구 작업 중에 오류가 발생한 경우 표시된 지침에 따라 수정해야 합니다.
* 원격 사이트의 상태가 ""스위치백 준비 완료""로 표시되면 애그리게이트는 여전히 재동기화됩니다. 원격 사이트의 상태가 스위치백 준비가 되었음을 나타낼 때까지 기다려야 합니다.


.이 작업에 대해
스위치오버 작업이 성공하면 MetroCluster 스위치오버 및 스위치백 작업 창이 표시됩니다. 창에는 두 사이트의 상태가 표시되고 작업이 성공했음을 알리는 메시지가 표시됩니다.

.단계
. 사이트 A에서 사이트 B * 로 전환 을 클릭하여 스위치백 작업을 시작합니다.
+
스위치백 작업이 MetroCluster 컨트롤을 사이트 B로 되돌림하고 있으며 프로세스에 시간이 걸릴 수 있다는 경고 메시지가 표시됩니다.

. 계속하려면 * 예 * 를 클릭합니다.
. 스위치백 프로세스가 완료되면 다음 하위 단계 중 하나를 수행합니다.
+
** 스위치백 작업이 성공적으로 완료되면 * 완료 * 를 클릭하여 MetroCluster 작업이 완료되었음을 확인합니다.
+
[NOTE]
====
스위치백 작업이 완료되었다는 메시지가 표시될 때까지 System Manager에서는 작업이 완료되었다는 메시지를 계속 표시합니다. 스위치백 작업이 완료되었음을 확인할 때까지 다른 작업을 시작하거나 이후의 스위치오버 또는 스위치백 작업을 모니터링할 수 없습니다.

====
** 스위치백 작업이 성공하지 못하면 오류 메시지가 상태 영역의 맨 위에 표시됩니다. 필요한 경우 수정하고 * 사이트 A에서 사이트 B * 로 전환 을 클릭하여 프로세스를 다시 시도하십시오.



