---
permalink: online-help-96-97/task_provisioning_storage_through_aggregates.html 
sidebar: sidebar 
keywords: provision, storage, aggregates, snaplock, fabricpool, online, help, flash, pool 
summary: 스토리지 권장 사항에 따라 애그리게이트를 생성할 수 있으며, 요구사항에 따라 수동으로 생성할 수도 있습니다. System Manager를 사용하여 Flash Pool 애그리게이트, SnapLock 애그리게이트 및 FabricPool 지원 애그리게이트를 만들어 하나 이상의 볼륨에 스토리지를 제공할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 애그리게이트를 통해 스토리지를 프로비저닝합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 스토리지 권장 사항에 따라 또는 요구사항에 따라 수동으로 애그리게이트를 만들 수 있습니다. System Manager를 사용하여 Flash Pool 애그리게이트, SnapLock 애그리게이트 및 FabricPool 지원 애그리게이트를 만들어 하나 이상의 볼륨에 스토리지를 제공할 수 있습니다.

.시작하기 전에
Aggregate를 생성하려면 스페어 디스크가 충분해야 합니다.

.이 작업에 대해
System Manager를 사용하면 다음 작업을 수행할 수 없습니다.

* 크기가 다른 스페어 디스크가 충분하더라도 크기가 다른 디스크를 결합합니다.
+
처음에 동일한 크기의 디스크로 애그리게이트를 생성한 다음 나중에 다른 크기의 디스크를 추가할 수 있습니다.

* 서로 다른 체크섬 유형의 디스크를 결합합니다.
+
처음에 단일 체크섬 유형의 애그리게이트를 생성하고 나중에 다른 체크섬 유형의 스토리지를 추가할 수 있습니다.





== 스토리지 권장 사항을 기반으로 애그리게이트를 생성합니다

ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager 클래식 을 사용하면 스토리지 권장 사항을 기반으로 aggregate를 생성할 수 있습니다. System Manager는 스토리지 시스템의 구성을 분석하고 생성할 애그리게이트 수, 사용 가능한 노드 및 사용 가능한 스페어 디스크와 같은 스토리지 권장 사항을 제공합니다.

.이 작업에 대해
* Cloud Volumes ONTAP, ONTAP Select 및 MetroCluster 구성에서는 스토리지 권장 사항을 기반으로 애그리게이트를 생성할 수 없습니다.
* 오류(있는 경우)가 화면에 표시됩니다.
+
이러한 오류를 해결한 다음 스토리지 권장 사항을 기반으로 애그리게이트를 만들거나, 애그리게이트를 수동으로 생성할 수 있습니다.



.단계
. 다음 방법 중 하나를 사용하여 Aggregate를 생성합니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. 스토리지 권장 사항을 검토한 다음 * 제출 * 을 클릭합니다.
+
정보 대화 상자에 집계 상태가 표시됩니다.

. 백그라운드에서 실행 * 을 클릭하여 * 애그리게이트 * 창으로 이동합니다.
. 생성된 애그리게이트를 보려면 * Refresh * (새로 고침)를 클릭합니다.




== 수동으로 애그리게이트 생성

ONTAP System Manager 클래식(ONTAP 9.7 이하 버전에서 사용 가능)을 사용하면 HDD만 또는 SSD만 포함된 애그리게이트를 수동으로 생성할 수 있습니다.

.시작하기 전에
모든 디스크의 크기가 같아야 합니다.

.이 작업에 대해
* ONTAP Select에서 4노드 클러스터에 애그리게이트를 생성하는 경우, 미러링된 애그리게이트 옵션이 기본적으로 선택됩니다.
* ONTAP 9.0부터는 디스크 크기가 10TB보다 크거나 같은 애그리게이트를 생성할 수 있습니다.
* Aggregate 디스크의 디스크 유형이 FSA 또는 mSATA 이고 디스크 크기가 10TB보다 크거나 같은 경우 RAID-TEC만 사용할 수 있는 RAID 유형입니다.


.단계
. 다음 방법 중 하나를 사용하여 Aggregate를 생성합니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. Aggregate를 생성하려면:
+
.. Aggregate 이름, 디스크 유형 및 Aggregate에 포함할 디스크 또는 파티션의 수를 지정합니다.
+
최소 핫 스페어 규칙은 디스크 크기가 가장 큰 디스크 그룹에 적용됩니다.

.. * 선택 사항: * 애그리게이트의 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 * 대화 상자에서 RAID 유형 및 RAID 그룹 크기를 지정합니다.
+
공유 디스크는 RAID DP 및 RAID-TEC의 두 가지 RAID 유형을 지원합니다.

... 저장 * 을 클릭합니다.


.. Aggregate를 미러링하려면 * Mirror this aggregate * 확인란을 선택합니다.
+
MetroCluster 구성의 경우 미러링되지 않은 애그리게이트 생성이 제한됩니다. 따라서 MetroCluster 구성에서는 미러링 옵션이 기본적으로 활성화됩니다.



. Create * 를 클릭합니다.


.결과
애그리게이트는 지정된 구성으로 생성되며 애그리게이트 창의 애그리게이트 목록에 추가됩니다.



== Flash Pool Aggregate를 수동으로 생성합니다

ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 Flash Pool 애그리게이트를 수동으로 생성하거나, SSD를 추가하여 기존 HDD 애그리게이트를 Flash Pool 애그리게이트로 전환할 수 있습니다. 새 HDD 애그리게이트를 생성할 경우, SSD 캐시를 프로비저닝하고 Flash Pool 애그리게이트를 생성할 수 있습니다.

.시작하기 전에
* 플랫폼별 모범 사례와 Flash Pool 애그리게이트 SSD 계층 크기 및 구성에 대한 워크로드별 모범 사례를 알고 있어야 합니다.
* 모든 HDD가 Zeroed 상태여야 합니다.
* 애그리게이트에 SSD를 추가하려면 기존 SSD와 전용 SSD의 크기가 모두 같아야 합니다.


.이 작업에 대해
* Flash Pool 애그리게이트를 생성하는 동안에는 파티셔닝된 SSD를 사용할 수 없습니다.
* 캐시 소스가 스토리지 풀인 경우 애그리게이트를 미러링할 수 없습니다.
* ONTAP 9.0부터는 디스크 크기가 10TB보다 크거나 같은 애그리게이트를 생성할 수 있습니다.
* Aggregate 디스크의 디스크 유형이 FSA 또는 mSATA 이고 디스크 크기가 10TB보다 크거나 같은 경우, RAID-TEC는 RAID 유형에 사용할 수 있는 유일한 옵션입니다.


.단계
. 다음 방법 중 하나를 사용하여 Aggregate를 생성합니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. Create Aggregate * 창에서 Aggregate 이름, 디스크 유형 및 Aggregate의 HDD에 포함할 디스크 또는 파티션의 수를 지정합니다.
. Aggregate를 미러링하려면 * Mirror this aggregate * 확인란을 선택합니다.
+
MetroCluster 구성의 경우 미러링되지 않은 애그리게이트 생성이 제한됩니다. 따라서 MetroCluster 구성에서는 미러링 옵션이 기본적으로 활성화됩니다.

. 이 Aggregate와 함께 Flash Pool Cache 사용 * 을 클릭합니다.
. 캐시 소스 지정:
+
|===
| 캐시 소스를 선택하려는 경우... | 그러면... 


 a| 
지원합니다
 a| 
.. 캐시 소스로 * 스토리지 풀 * 을 선택합니다.
.. 캐시를 가져올 수 있는 스토리지 풀을 선택한 다음 캐시 크기를 지정합니다.
.. 필요한 경우 RAID 유형을 수정합니다.




 a| 
전용 SSD
 a| 
.. 캐시 소스로 * 전용 SSD * 를 선택합니다.
.. SSD 크기와 애그리게이트에 포함될 SSD 수를 선택합니다.
.. 필요한 경우 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 대화 상자에서 RAID 유형과 RAID 그룹 크기를 지정합니다.
... 저장 * 을 클릭합니다.




|===
. Create * 를 클릭합니다.


.결과
Flash Pool 애그리게이트는 지정된 구성으로 생성되며 애그리게이트 창의 애그리게이트 목록에 추가됩니다.



== SnapLock Aggregate를 수동으로 생성합니다

System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SnapLock 규정 준수 애그리게이트 또는 SnapLock 엔터프라이즈 애그리게이트를 수동으로 생성할 수 있습니다. 이러한 애그리게이트에는 ""WORM(Write Once, Read Many)" 기능을 제공하는 SnapLock 볼륨을 생성할 수 있습니다.

.시작하기 전에
SnapLock 라이센스가 추가되어야 합니다.

.이 작업에 대해
* MetroCluster 구성에서는 SnapLock 엔터프라이즈 애그리게이트만 생성할 수 있습니다.
* 어레이 LUN의 경우 SnapLock 엔터프라이즈 애그리게이트만 지원됩니다.
* ONTAP 9.0부터는 디스크 크기가 10TB보다 크거나 같은 애그리게이트를 생성할 수 있습니다.
* Aggregate 디스크의 디스크 유형이 FSA 또는 mSATA 이고 디스크 크기가 10TB보다 크거나 같은 경우, RAID-TEC는 RAID 유형에 사용할 수 있는 유일한 옵션입니다.
* ONTAP 9.1부터 AFF 플랫폼에 SnapLock 애그리게이트를 만들 수 있습니다.


.단계
. 다음 방법 중 하나를 사용하여 SnapLock Aggregate를 만듭니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. SnapLock 애그리게이트 생성하기:
+
.. Aggregate 이름, 디스크 유형 및 Aggregate에 포함할 디스크 또는 파티션의 수를 지정합니다.
+
Aggregate를 생성한 후에는 SnapLock Compliance Aggregate의 이름을 변경할 수 없습니다.

+
최소 핫 스페어 규칙은 디스크 크기가 가장 큰 디스크 그룹에 적용됩니다.

.. * 선택 사항: * 애그리게이트의 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 대화 상자에서 RAID 유형과 RAID 그룹 크기를 지정합니다.
+
공유 디스크는 RAID-DP와 RAID-TEC의 두 가지 RAID 유형을 지원합니다.

... 저장 * 을 클릭합니다.


.. SnapLock 유형을 지정합니다.
.. ComplianceClock 시스템을 초기화하지 않은 경우 * ComplianceClock * 초기화 확인란을 선택합니다.
+
ComplianceClock이 이미 노드에서 초기화된 경우에는 이 옵션이 표시되지 않습니다.

+
[NOTE]
====
현재 시스템 시간이 올바른지 확인해야 합니다. ComplianceClock은 시스템 클록을 기반으로 설정됩니다. ComplianceClock이 설정되면 ComplianceClock을 수정하거나 중지할 수 없습니다.

====
.. * 선택 사항: * 애그리게이트를 미러링하려면 * 이 애그리게이트 미러링 * 확인란을 선택합니다.
+
MetroCluster 구성의 경우 미러링되지 않은 애그리게이트 생성이 제한됩니다. 따라서 MetroCluster 구성에서는 미러링 옵션이 기본적으로 활성화됩니다.

+
기본적으로 미러링 옵션은 SnapLock 규정 준수 애그리게이트에 대해 비활성화되어 있습니다.



. Create * 를 클릭합니다.




== FabricPool 지원 애그리게이트를 수동으로 생성합니다

ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 FabricPool 지원 애그리게이트를 수동으로 생성하거나 클라우드 계층을 SSD 애그리게이트에 연결하여 기존 SSD 애그리게이트를 FabricPool 지원 애그리게이트로 변환할 수 있습니다.

.시작하기 전에
* 클라우드 계층을 생성하여 SSD 애그리게이트로 구성된 클러스터에 연결해야 합니다.
* 사내 클라우드 계층이 생성되었어야 합니다.
* 클라우드 계층과 애그리게이트 간에는 전용 네트워크 연결이 있어야 합니다.


.이 작업에 대해
다음 오브젝트 저장소를 클라우드 계층으로 사용할 수 있습니다.

* StorageGRID
* Alibaba Cloud(System Manager 9.6으로 시작)
* AWS(Amazon Web Services) S3(Simple Storage Service)
* AWS(Amazon Web Services) C2S(Commercial Cloud Service)
* Microsoft Azure Blob 저장소
* IBM 클라우드
* Google 클라우드


[NOTE]
====
* 온프레미스 Azure 서비스인 Azure Stack은 지원되지 않습니다.
* StorageGRID 이외의 클라우드 계층으로 오브젝트 저장소를 사용하려면 FabricPool 용량 라이센스가 있어야 합니다.


====
.단계
. 다음 방법 중 하나를 사용하여 FabricPool 지원 애그리게이트를 만들 수 있습니다.
+
** Applications & Tiers * > * Storage Tiers * > * Add Aggregate * 를 클릭합니다.
** 스토리지 * > * 집계 및 디스크 * > * 집계 * > * 생성 * 을 클릭합니다.


. Aggregate를 생성하려면 * Manually Create Aggregate * 옵션을 활성화합니다.
. FabricPool 지원 애그리게이트 생성:
+
.. Aggregate 이름, 디스크 유형 및 Aggregate에 포함할 디스크 또는 파티션의 수를 지정합니다.
+
[NOTE]
====
All-Flash(All SSD) 애그리게이트만 FabricPool 지원 애그리게이트를 지원합니다.

====
+
최소 핫 스페어 규칙은 디스크 크기가 가장 큰 디스크 그룹에 적용됩니다.

.. * 선택 사항: * 애그리게이트의 RAID 구성을 수정합니다.
+
... 변경 * 을 클릭합니다.
... RAID 구성 변경 대화 상자에서 RAID 유형과 RAID 그룹 크기를 지정합니다.
+
공유 디스크는 RAID-DP와 RAID-TEC의 두 가지 RAID 유형을 지원합니다.

... 저장 * 을 클릭합니다.




. FabricPool * 확인란을 선택한 다음 목록에서 클라우드 계층을 선택합니다.
. Create * 를 클릭합니다.


* 관련 정보 *

http://www.netapp.com/us/media/tr-4070.pdf["NetApp 기술 보고서 4070: Flash Pool 설계 및 구축"^]
