---
permalink: online-help-96-97/task_moving_flexvol_volumes_between_aggregates_or_nodes.html 
sidebar: sidebar 
keywords: move, flexcol, volume, aggregate, node, online, help, system, manager 
summary: System Manager를 사용하면 용량 활용률과 성능 향상을 위해 FlexVol 볼륨을 다른 애그리게이트 또는 노드로 중단 없이 이동할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 Aggregate와 노드 간에 FlexVol 볼륨을 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ONTAP 9.7 이하에서 사용 가능한 System Manager의 기존 버전을 사용하면 FlexVol 볼륨을 다른 Aggregate 또는 다른 노드로 중단 없이 이동하여 용량 활용률과 성능을 향상할 수 있습니다.

.시작하기 전에
데이터 보호(DP) 볼륨을 이동하는 경우 볼륨을 이동하기 전에 데이터 보호 미러링 관계를 초기화해야 합니다.

.이 작업에 대해
애그리게이트와 노드 간에 SnapLock 볼륨을 이동할 수 없습니다.

.단계
. 스토리지 * > * 볼륨 * 을 클릭합니다.
. SVM * 필드의 드롭다운 메뉴에서 * 모든 SVM * 을 선택합니다.
. 이동할 볼륨을 선택합니다.
. 추가 작업 * > * 이동 * 을 클릭합니다.
. 볼륨 이동 * 대화 상자에서 볼륨의 대상 애그리게이트 또는 노드를 선택한 다음 계층화 정책을 변경합니다.
+
[NOTE]
====
** 루트 볼륨의 계층화 정책은 변경할 수 없습니다.
** 루트 볼륨을 FabricPool로 이동할 수 없습니다.
** 읽기/쓰기 볼륨의 경우 볼륨 이동 중에 계층화 정책을 "백업"으로 설정할 수 있습니다.
+
이동 후 계층화 정책이 "스냅샷 전용"으로 변경됩니다.

** 소스 애그리게이트 및 대상 애그리게이트 모두에서 "이동 후 사용"에 표시되는 용량 계층 값은 예상 값입니다.
+
정확한 값을 보려면 집계 창으로 이동하여 특정 집계의 세부 정보를 확인해야 합니다.



====
. 이동 * 을 클릭합니다.




== 볼륨 이동을 위한 컷오버를 수동으로 트리거합니다

볼륨 이동 작업의 경우 볼륨이 컷오버 지연 단계로 전환되면 System Manager를 사용하여 컷오버를 수동으로 트리거할 수 있습니다. 해당 기간 내에 작업이 실패할 경우 시스템에서 컷오버 및 컷오버 작업을 수행할 기간을 설정할 수 있습니다.

.단계
. 스토리지 * > * SVM * 을 클릭합니다.
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 볼륨 * 탭을 클릭합니다.
. 볼륨 이동 작업이 시작된 볼륨을 확장합니다.
. 볼륨에 대한 자세한 내용을 보려면 * 자세한 정보 표시 * 링크를 클릭하십시오.
. 개요 * 탭에서 * 컷오버 * 를 클릭합니다.
. cutover * 대화 상자에서 * 고급 옵션 * 을 클릭합니다.
. * 선택 사항: * 컷오버 작업과 컷오버 윈도우 기간을 지정합니다.
. 확인 * 을 클릭합니다.

