---
permalink: online-help-96-97/task_configuring_nvme_protocol_on_svms.html 
sidebar: sidebar 
keywords: configure, nvme, protocol, svm, system, manager, namespaces, online, help 
summary: 'System Manager를 사용하여 SVM(스토리지 가상 머신)에서 NVMe 프로토콜을 구성할 수 있습니다. 그런 다음 네임스페이스를 만들고 NVMe 하위 시스템 및 호스트에 할당할 수 있습니다.' 
---
= System Manager-ONTAP 9.7 이하를 사용하여 SVM에서 NVMe 프로토콜을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 SVM(스토리지 가상 머신)에서 NVMe 프로토콜을 구성할 수 있습니다. 그런 다음 네임스페이스를 만들고 NVMe 하위 시스템 및 호스트에 할당할 수 있습니다.

.이 작업에 대해
NVMe를 사용하는 SVM에는 다른 프로토콜이 있어서는 안 됩니다. NVMe를 선택하면 나머지 프로토콜이 비활성화됩니다. SVM을 생성하는 동안 NVMe를 구성할 수도 있습니다.

.단계
. SVM을 생성할 때 NVMe 프로토콜을 구성하지 않은 경우 * 스토리지 * > * SVM * 을 클릭합니다
. SVM을 선택한 다음 * SVM 설정 * 을 클릭합니다.
. 프로토콜 * 창에서 * NVMe * 를 클릭합니다.
. 필요한 경우 링크를 클릭하여 프로토콜을 구성합니다.
+
[NOTE]
====
활성화된 다른 프로토콜이 있으면 이 프로토콜을 선택 취소해야 NVMe를 선택할 수 있습니다. NVMe를 다른 프로토콜과 결합할 수 없습니다.

====
. Edit Storage Virtual Machine * 창에서 * Resource Allocation * 을 클릭합니다.
. 리소스 할당 * 탭에서 볼륨 생성을 위임하지 않도록 선택하거나 볼륨을 자동으로 프로비저닝할 Aggregate를 선택할 수 있습니다.
. 서비스 * 탭을 클릭하여 이름 서비스 스위치 세부 정보를 구성합니다.
. 저장 후 닫기 * 를 클릭합니다
+
NVMe 프로토콜은 SVM에서 구성됩니다. 프로토콜을 구성한 후 * SVM 설정 * 을 사용하여 서비스를 시작하거나 중지할 수 있습니다



* 관련 정보 *

xref:concept_setting_up_nvme.adoc[NVMe 설정]
