---
permalink: online-help-96-97/task_performing_negotiated_planned_switchover.html 
sidebar: sidebar 
keywords: online, help, perform, negotiated, switchover, system, help 
summary: 'System Manager 9.6부터 MetroCluster 사이트의 협상된(계획된) 전환을 시작할 수 있습니다. 이 작업은 사이트에서 재해 복구 테스트 또는 계획된 유지 관리를 수행하려는 경우에 유용합니다.' 
---
= 협상된 전환 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6부터 MetroCluster 사이트의 협상된(계획된) 전환을 시작할 수 있습니다. 이 작업은 사이트에서 재해 복구 테스트 또는 계획된 유지 관리를 수행하려는 경우에 유용합니다.

.단계
. [[step1]] System Manager에서 클러스터 관리자 자격 증명을 사용하여 로컬 MetroCluster 사이트(사이트 A)에 로그온합니다.
. 구성 * > * MetroCluster * 을 클릭합니다
+
MetroCluster 스위치오버/스위치백 운영 창이 표시됩니다.

. 다음 * 을 클릭합니다.
+
MetroCluster 전환 및 스위치백 작업 창에는 작업 상태가 표시되고 시스템 관리자는 협상된 전환이 가능한지 여부를 확인합니다.

. 검증 프로세스가 완료되면 다음 하위 단계 중 하나를 수행합니다.
+
** 유효성 검사에 성공하면 단계를 진행합니다 link:#step5["5"].
** 검증이 실패했지만 사이트 B가 작동 중인 경우 하위 시스템이나 NVRAM 미러링의 문제가 동기화되지 않아 오류가 발생한 것입니다. 다음 프로세스 중 하나를 수행할 수 있습니다.
+
*** 오류의 원인이 되는 문제를 해결하고 * 닫기 * 를 클릭한 다음 단계에서 다시 시작합니다 link:#step1["1"].
*** 사이트 B 노드를 중지하고 * 닫기 * 를 클릭한 다음 의 단계를 수행합니다 xref:task_performing_unplanned_switchover.adoc[계획되지 않은 전환 수행].


** 유효성 검사에 실패하고 사이트 B가 다운되면 연결 문제가 있을 가능성이 높습니다. 사이트 B가 실제로 중지되었는지 확인한 다음 의 단계를 수행합니다 xref:task_performing_unplanned_switchover.adoc[계획되지 않은 전환 수행].


. [[5단계]] 스위치오버 * 를 클릭하여 사이트 B에서 사이트 A로 전환 * 을 시작합니다.
+
스위치오버 작업이 사이트 B의 모든 데이터 SVM을 중지하고 사이트 A에서 다시 시작한다는 경고 메시지가 표시됩니다

. 계속하려면 * 예 * 를 클릭합니다.
+
전환 프로세스가 시작됩니다. 사이트 A와 사이트 B의 상태는 해당 구성의 그래픽 표현 위에 표시됩니다. 전환 작업이 실패하면 오류 메시지가 표시됩니다. 닫기 * 를 클릭합니다. 오류를 수정하고 단계에서 다시 시작합니다 link:#step1["1"]

. System Manager에서 복구가 완료되었다는 것을 표시할 때까지 기다립니다.
+
복구가 완료되면 사이트 B가 작동하고 시스템이 스위치백 프로세스를 준비합니다.

+
스위치백 프로세스 준비가 완료되면 창 하단에 * 사이트 A에서 사이트 B * 로 스위치백 버튼이 활성화됩니다.

. 스위치백 작업을 계속하려면 의 단계를 수행하십시오 xref:task_performing_switchback.adoc[스위치백을 수행합니다].

