---
permalink: online-help-96-97/task_adding_capacity_disks.html 
sidebar: sidebar 
keywords: add, capacity, disk, online, help, aggregate 
summary: 용량 디스크를 추가하여 기존 비루트 애그리게이트 또는 디스크를 포함하는 루트 애그리게이트의 크기를 늘릴 수 있습니다. System Manager를 사용하여 선택한 ONTAP 디스크 유형의 HDD 또는 SSD를 추가하고 RAID 그룹 옵션을 수정할 수 있습니다. 
---
= System Manager-ONTAP 9.7 이하를 사용하여 용량 디스크를 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
용량 디스크를 추가하여 기존 비루트 애그리게이트 또는 디스크를 포함하는 루트 애그리게이트의 크기를 늘릴 수 있습니다. System Manager 클래식(ONTAP 9.7 이하에서 사용 가능)을 사용하면 선택한 ONTAP 디스크 유형의 HDD 또는 SSD를 추가하고 RAID 그룹 옵션을 수정할 수 있습니다.

.시작하기 전에
* 애그리게이트는 온라인 상태여야 합니다.
* 호환 가능한 스페어 디스크가 충분해야 합니다.


.이 작업에 대해
* Aggregate의 다른 디스크와 동일한 크기의 디스크를 추가하는 것이 가장 좋습니다.
+
Aggregate의 다른 디스크보다 작은 디스크를 추가하면 구성에서 이 애그리게이트가 최적화되지 않으므로 성능 문제가 발생할 수 있습니다.

+
Aggregate의 기존 RAID 그룹에서 사용할 수 있는 디스크보다 더 큰 디스크를 추가하면 디스크의 크기가 축소되고 해당 RAID 그룹의 다른 디스크에 비해 공간이 줄어듭니다. Aggregate에 새로운 RAID 그룹이 생성되고 유사한 크기의 디스크가 새 RAID 그룹에 남아 있는 경우, 디스크는 다운사이징되지 않습니다.

+
Aggregate의 다른 디스크와 크기가 다른 디스크를 추가하면 선택한 디스크가 추가되지 않을 수 있습니다. 대신 사용 가능한 크기가 90%에서 105% 사이인 다른 디스크가 자동으로 추가됩니다. 예를 들어 744GB 디스크의 경우 669GB ~ 781GB 범위의 모든 디스크를 선택할 수 있습니다. 이 범위의 모든 스페어 디스크에 대해 ONTAP는 먼저 분할된 디스크만 선택한 다음 분할되지 않은 디스크만 선택하고 마지막으로 분할된 디스크와 분할되지 않은 디스크를 모두 선택합니다.

* System Manager를 사용하여 다음 구성에 HDD를 추가할 수 없습니다.
+
** SSD만 포함하는 애그리게이트
** 파티셔닝된 디스크를 포함하는 루트 애그리게이트입니다
이러한 구성에 HDD를 추가하려면 명령줄 인터페이스를 사용해야 합니다.


* 공유 디스크는 RAID DP 및 RAID-TEC의 두 가지 RAID 유형을 지원합니다.
* 스토리지 풀에 SSD를 사용할 수 없습니다.
* RAID 그룹 유형이 RAID DP이고 크기가 10TB보다 크거나 같은 FSA 또는 mSATA 유형의 디스크를 추가하는 경우 에만 추가할 수 있습니다 `Specific RAID group`그리고, 끝은 아닙니다 `New RAID group` 또는 `All RAID groups`.
+
디스크 크기를 기존 애그리게이트의 기존 RAID 그룹에 있는 디스크 크기로 축소한 후 디스크가 추가됩니다.

* RAID 그룹 유형이 RAID-TEC이고 크기가 10TB보다 크거나 같은 FSA 또는 mSATA 유형의 디스크를 추가하는 경우 에 추가할 수 있습니다 `All RAID groups`, `New RAID group`, 및 `Specific RAID group`.
+
디스크 크기를 기존 애그리게이트의 기존 RAID 그룹에 있는 디스크 크기로 축소한 후 디스크가 추가됩니다.



.단계
. 다음 방법 중 하나를 선택합니다.
+
** Applications & Tiers * > * Storage Tiers * 를 클릭합니다.
** 스토리지 * > * 애그리게이트 및 디스크 * > * 애그리게이트 * 를 클릭합니다.


. Storage Tiers * 창에서 용량 디스크를 추가할 애그리게이트를 선택한 다음 menu: More Actions [Add Capacity] 를 클릭합니다.
. [용량 추가] * 대화 상자에서 다음 정보를 지정합니다.
+
.. 추가할 디스크 유형 * 옵션을 사용하여 용량 디스크의 디스크 유형을 지정합니다.
.. 디스크 수 또는 파티션 수 * 옵션을 사용하여 용량 디스크 수를 지정합니다.


. Add Disks to * 옵션을 사용하여 용량 디스크를 추가할 RAID 그룹을 지정합니다.
+
기본적으로 System Manager에서는 용량 디스크를 에 추가합니다 `All RAID groups`.

+
.. 변경 * 을 클릭합니다.
.. RAID Group Selection * 대화 상자에서 RAID 그룹을 로 지정합니다 `New RAID group` 또는 `Specific RAID group` Add Disks to * 옵션을 사용합니다.
+
공유 디스크는 에만 추가할 수 있습니다 `New RAID group` 옵션을 선택합니다.



. 추가 * 를 클릭합니다.
+
미러링된 애그리게이트의 경우 선택한 디스크 수의 2배가 추가되는 정보와 함께 * Add Capacity * (용량 추가) 대화 상자가 표시됩니다.

. 용량 추가 * 대화 상자에서 * 예 * 를 클릭하여 용량 디스크를 추가합니다.


.결과
용량 디스크가 선택한 Aggregate에 추가되고 애그리게이트 크기가 증가합니다.

* 관련 정보 *

xref:concept_what_compatible_spare_disks_are.adoc[호환되는 스페어 디스크입니다]
