---
permalink: fc-config-esxi/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, hba, esx, host, computer, virtual storage console, vsc 
summary: 'ONTAP System Manager의 기존 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 FC 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESX 호스트 컴퓨터의 FC HBA를 사용하여 LUN을 데이터 저장소로 사용할 수 있습니다.' 
---
= VSC 개요를 사용하여 ESXi용 FC 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager의 기존 인터페이스(ONTAP 9.7 이하)를 사용하면 SVM(스토리지 가상 머신)에서 FC 서비스를 빠르게 설정하고, LUN을 프로비저닝하고, ESX 호스트 컴퓨터의 FC HBA를 사용하여 LUN을 데이터 저장소로 사용할 수 있습니다.

다음 경우에 이 절차를 사용합니다.

* 지원되는 VSC(Virtual Storage Console for VMware vSphere)를 사용하여 ESX 호스트의 스토리지 설정을 구성하고 데이터 저장소를 프로비저닝하고 있습니다.
+
** VSC 7.0부터는 VSC가 의 일부입니다 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere용 ONTAP 툴"^] VSC, VASA(vStorage APIs for Storage Awareness) 공급자, VMware vSphere 기능을 위한 SRA(Storage Replication Adapter)를 포함하는 가상 어플라이언스
** 를 확인하십시오 https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"^] 현재 ONTAP 및 VSC 릴리스 간의 호환성을 확인합니다.


* 네트워크는 IPv4 주소 지정을 사용합니다.
* ESXi 5.x 및 기존 FC 스위치에서 기존 FC HBA를 사용하고 있습니다.
+
이 절차는 FCoE에 적용되지 않습니다.

* 클러스터의 각 노드에서 사용 가능한 FC 타겟 포트가 2개 이상 있습니다.
+
온보드 FC 및 UTA2("CNA") 포트뿐만 아니라 일부 어댑터를 구성할 수 있습니다. 이러한 포트 구성은 ONTAP CLI에서 수행되며 이 절차에서 다루지 않습니다.

* FC SAN 부팅을 구성하지 않습니다.
* 호스트에서 데이터 저장소를 생성하는 중입니다.
+
이 절차에서는 RDM(Raw Device Mapping) 디스크 또는 NPIV(N-Port ID Virtualization)를 사용하여 FC를 VM에 직접 제공하는 방법에 대해 다루지 않습니다.



자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: ONTAP용 VMware vSphere"^] VSC 릴리즈에 대한 설명서를 제공합니다.
