---
permalink: fc-config-esxi/task_creating_svm.html 
sidebar: sidebar 
keywords: storage, virutal, machine, svm, fc, target, host, access, lun, logical, lif, function, user, cluster, create a new svm 
summary: 스토리지 가상 머신은 호스트가 LUN에 액세스하는 데 사용하는 FC 타겟을 제공합니다. 
---
= 새 SVM을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 머신)은 호스트가 LUN에 액세스하는 데 사용되는 FC 타겟을 제공합니다. SVM을 생성할 때 LUN의 경로를 제공하는 논리 인터페이스(LIF)도 생성합니다. SVM을 생성하여 클러스터의 다른 사용자 데이터와 사용자 관리 기능을 분리할 수 있습니다.

.시작하기 전에
* FC 패브릭을 구성하고 원하는 물리적 포트를 패브릭에 연결해야 합니다.


.단계
. SVM * 창으로 이동합니다.
. Create * 를 클릭합니다.
. SVM(Storage Virtual Machine) 설정 * 창에서 SVM을 생성합니다.
+
.. SVM의 고유한 이름을 지정합니다.
+
이름은 FQDN(정규화된 도메인 이름)이거나 클러스터 전체에서 고유한 이름을 보장하는 다른 규칙을 따라야 합니다.

.. SVM이 속할 IPspace를 선택합니다.
+
클러스터에서 여러 IPspace를 사용하지 않는 경우 "기본" IPspace가 사용됩니다.

.. 기본 볼륨 유형을 계속 선택합니다.
+
SAN 프로토콜에서는 FlexVol 볼륨만 지원됩니다.

.. 모든 프로토콜을 즉시 구성하지 않으려는 경우에도 라이센스가 있고 SVM에서 사용할 수 있는 프로토콜을 모두 선택하십시오.
+
SVM 생성 시 NFS와 CIFS를 모두 선택하면 이러한 두 프로토콜이 동일한 LIF를 공유할 수 있습니다. 이 프로토콜을 나중에 추가해도 LIF를 공유할 수 없습니다.

+
CIFS가 선택한 프로토콜 중 하나인 경우 보안 스타일이 NTFS로 설정됩니다. 그렇지 않으면 보안 스타일이 UNIX로 설정됩니다.

.. 기본 언어 설정 C. UTF-8을 유지합니다.
.. SVM 루트 볼륨을 포함할 루트 애그리게이트를 선택합니다.
+
데이터 볼륨의 애그리게이트는 이후 단계에서 별도로 선택됩니다.

.. 제출 및 계속 * 을 클릭합니다.


+
SVM이 생성되지만 프로토콜이 아직 구성되지 않았습니다.

. CIFS 또는 NFS를 설정했기 때문에 * CIFS/NFS 프로토콜 구성 * 페이지가 나타나면 * 건너뛰기 * 를 클릭한 다음 CIFS 또는 NFS를 나중에 구성합니다.
. iSCSI를 활성화했기 때문에 * iSCSI 프로토콜 구성 * 페이지가 나타나면 * 건너뛰기 * 를 클릭한 다음 나중에 iSCSI를 구성합니다.
. FC 서비스 및 LIF를 * FC/FCoE 프로토콜 구성 * 페이지에서 구성합니다.
+
.. FC*용 데이터 LIF 구성 확인란을 선택합니다.
.. 를 입력합니다 `2` LIF per node * 필드에서.
+
가용성과 데이터 이동성을 보장하기 위해 각 노드에 두 개의 LIF가 필요합니다.

.. 나중에 VMware vSphere용 Virtual Storage Console에서 LUN을 프로비저닝하므로 옵션 * FCP 스토리지 * 영역에 대한 LUN 프로비저닝을 건너뜁니다.
.. 제출 및 계속 * 을 클릭합니다.


. SVM 관리 * 가 나타나면 이 SVM에 대한 별도의 관리자 구성을 구성하거나 연기합니다.
+
** Skip * (건너뛰기 *)을 클릭하고 나중에 필요에 따라 관리자를 구성합니다.
** 요청한 정보를 입력한 다음 * 제출 및 계속 * 을 클릭합니다.


. 요약 * 페이지를 검토하고 LIF 정보를 기록한 다음 * 확인 * 을 클릭합니다.

