---
permalink: iscsi-config-rhel/task_verifying_that_host_can_write_to_read_fom_lun.html 
sidebar: sidebar 
keywords: multipath, device, verify, host, data, verify that the host can write to and read from a multipath device 
summary: 다중 경로 장치를 사용하기 전에 호스트에서 다중 경로 장치에 데이터를 쓰고 다시 읽을 수 있는지 확인해야 합니다. 
---
= 호스트가 다중 경로 장치에 데이터를 쓰고 읽을 수 있는지 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다중 경로 장치를 사용하기 전에 호스트에서 다중 경로 장치에 데이터를 쓰고 다시 읽을 수 있는지 확인해야 합니다.

.시작하기 전에
액세스 중인 스토리지 클러스터 노드에 대해 Linux 호스트에서 DM 다중 경로를 구성해야 합니다.

.이 작업에 대해
다중 경로 장치가 해당하는 스토리지 클러스터 노드를 파트너 노드로 페일오버하는 경우 노드가 페일오버되는 동안 데이터 읽기를 확인해야 합니다. 스토리지 클러스터가 운영 환경에서 사용 중인 경우 이 검증이 가능하지 않을 수 있습니다.

.단계
. 지정된 다중 경로 장치에서 일부 I/O를 실행합니다.
+
`dd if=/dev/zero of=<multipath_device_name\>`

. 통계를 새로 고칠 시간(예: 2초 간격)을 지정하여 다중 경로 장치에서 I/O가 실행 중인지 확인합니다.
+
`iostat 2`

+
다중 경로 장치에서 I/O가 실행 중인 경우 다양한 I/O 카운터 출력이 동적으로 변경되어 다중 경로 장치에서 I/O가 성공적으로 실행되고 있음을 알 수 있습니다.

+
[listing]
----
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
            0.00    0.00    0.01    0.00    0.00   99.98

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.18         1.34         2.29     832606    1428026
dm-0              0.37         1.29         2.29     801530    1427984
dm-1              0.00         0.00         0.00       2576          0
dm-2              0.00         0.00         0.00       1770         24
sdd               0.17         1.18        17.87     734688   11128584
sde               0.17         1.18        18.01     734560   11219016
sdf               0.00         0.00         0.00       1344          0
sdg               0.00         0.00         0.00       1344          0
dm-3              0.68         4.71        71.96    2932496   44816008
sdh               0.17         1.18        18.22     734360   11343920
sdi               0.17         1.18        17.86     734272   11124488
sdj               0.00         0.00         0.00       1344          0
sdk               0.00         0.00         0.00       1344          0
.............
----
. 가능한 경우 를 실행합니다 `takeover` 스토리지 클러스터 노드에서 다음 명령을 실행합니다.
+
`storage failover takeover -ofnode <node_name\>`

. 를 다시 실행하여 다중 경로 장치에서 I/O가 계속 실행 중인지 확인합니다 `iostat` 명령.
. 를 실행합니다 `giveback` 스토리지 클러스터 노드에서 다음 명령을 실행합니다.
+
`storage failover giveback -ofnode <node_name\>`

. 확인합니다 `iostat` 출력을 사용하여 I/O가 여전히 실행 중인지 확인합니다.




== 다음 단계

테스트가 실패하면 iSCSI 서비스가 실행 중인지 확인하고 DM 다중 경로 구성 및 다중 경로 장치에 대한 iSCSI 경로를 다시 확인합니다.
