---
permalink: volume-move/task_planning_method_timing_volume_move.html 
sidebar: sidebar 
keywords: system, manager, volume, manual, cutover, lun, report, node, advance, procedure, command-line, interface, cli, plan, plan the method and timing of a volume move 
summary: 'ONTAP 9.7 이하와 ONTAP System Manager의 "클래식" 인터페이스를 사용하여 볼륨을 이동하고 수동 컷오버를 사용할지 여부를 결정할 수 있습니다. LUN 보고 노드를 업데이트해야 하는 경우 CLI(Command-Line Interface)의 고급 절차를 따라야 합니다. 필요한 경우 볼륨 이동 타이밍을 계획할 수도 있습니다.' 
---
= 볼륨 이동 방법 및 시간을 계획합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 이하와 ONTAP System Manager_CLASSIC_INTERFACE를 사용하여 볼륨을 이동하고 수동 컷오버를 사용할지 여부를 결정할 수 있습니다. LUN 보고 노드를 업데이트해야 하는 경우 CLI(Command-Line Interface)의 고급 절차를 따라야 합니다. 필요한 경우 볼륨 이동 타이밍을 계획할 수도 있습니다.

.이 작업에 대해
SnapMirror 또는 SnapVault 관계의 소스 볼륨은 볼륨이 미러링되는 동안 이동할 수 있습니다. 볼륨 이동 작업의 컷오버 단계에서 SnapMirror 서비스가 잠깐 정지됩니다.

타겟 볼륨도 이동할 수 있습니다. 반복 단계에서는 SnapMirror 또는 SnapVault 업데이트 및 볼륨 이동 작업이 동시에 실행됩니다. 컷오버 단계에서 컷오버가 가능한지 평가할 때, 우선 컷오버 및 SnapMirror 또는 SnapVault 업데이트 사이의 우선순위가 결정됩니다. 첫 번째 작업이 완료될 때까지 다른 작업이 차단됩니다.

.단계
. 수동 컷오버가 필요한지 여부를 결정합니다.
+
_cutover_는 이동 작업이 완료되고 ONTAP가 새 애그리게이트의 볼륨에서 데이터 제공을 시작하는 모멘트가 됩니다. 컷오버를 자동으로 수행하거나 수동으로 트리거할 수 있습니다.

+
회사의 표준 관행이 스토리지 시스템에서 변경 사항을 제어해야 하는 경우, 유지보수 윈도우 동안 이동 작업의 최종 컷오버를 수동으로 수행할 수 있습니다.

+
컷오버는 중단이 필요하지 않지만, 유지보수 윈도우를 사용하여 _ 이(가) 발생할 때를 제어할 수 있습니다.

+
[NOTE]
====
자동 컷오버를 선택하든 수동 컷오버를 선택하든 상관없이 볼륨 이동 작업은 중단 없이 수행됩니다.

====
. 볼륨에 LUN이 있고 클러스터에 4개 이상의 노드가 포함된 경우 볼륨이 다른 HA 쌍으로 이동되면 CLI를 사용하여 LUN 보고 노드를 업데이트합니다.
+
볼륨에 LUN이 없거나 클러스터에 노드가 2개만 포함된 경우 이 단계를 건너뛸 수 있습니다.

. * 선택 사항: * 다음 사항을 고려하여 시간을 계획합니다.
+
** 클라이언트 액세스와 전체 시스템 성능을 유지하는 방식으로 백그라운드에서 중단 없이 실행되도록 설계되었기 때문에 볼륨 이동 작업에 예상보다 시간이 더 걸릴 수 있습니다.
+
예를 들어, ONTAP는 볼륨 이동 작업에 사용할 수 있는 리소스를 조절합니다.

** 최대한 빨리 이동하려면 클러스터 활동이 적은 시간, 특히 다음 작업을 선택해야 합니다.
+
*** 볼륨에 대한 I/O 작업
*** 예를 들어 컨트롤러 CPU 사용량이 50% 미만인 경우 백그라운드 리소스를 사용하는 작업입니다
*** 클러스터 인터커넥트를 사용하는 작업입니다


** 볼륨이 오프라인, 제한 또는 제거, SnapMirror 재동기화, 중단, 제거 등의 작업의 영향을 받는 동안에는 이동을 시작할 수 없습니다. 복구할 수 있습니다.
+
이동을 시작하려면 이러한 특정 작업이 완료될 때까지 기다려야 합니다.

** 볼륨 이동 작업이 진행되는 동안 스위치오버가 발생할 수 있지만 MetroCluster 스위치백을 수행할 수 없습니다.
** 전환된 사이트에 속한 볼륨에 대해 볼륨 이동 작업이 진행 중인 경우 MetroCluster 전환이 차단됩니다. 남아 있는 사이트에 로컬로 있는 볼륨의 볼륨 이동 작업이 진행 중일 때는 스위치백이 차단되지 않습니다.
** 볼륨 이동 작업이 진행 중인 경우 강제 MetroCluster 전환이 발생할 수 있습니다.




.관련 정보
link:task_verifying_lun_reporting_nodes_after_moving_volume.html["볼륨 이동 후 LUN 보고 노드 확인"]
