---
permalink: peering/index.html 
sidebar: sidebar 
keywords: cluster, administrator, create, authenticated, peer, relationship, svm, enable, communicate, replicate, data 
summary: 클러스터 관리자는 클러스터와 SVM 간에 인증된 피어 관계를 생성하여 클러스터가 서로 통신하도록 함으로써 서로 다른 클러스터의 볼륨 간에 데이터를 복제할 수 있습니다. 
---
= 클러스터 및 SVM 피어링 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 관리자는 클러스터와 SVM 간에 인증된 피어 관계를 생성하여 클러스터가 서로 통신하도록 함으로써 서로 다른 클러스터의 볼륨 간에 데이터를 복제할 수 있습니다.  ONTAP 9.7 및 이전 ONTAP 9 릴리즈에서 제공되는 ONTAP System Manager_CLASSIC_INTERFACE를 사용하여 절차를 수행할 수 있습니다.

다음과 같은 경우 ONTAP System Manager_classic_interface를 사용하여 클러스터 피어 관계 및 SVM 피어 관계를 생성합니다.

* ONTAP 9.7 이하 ONTAP 9 릴리즈를 실행 중인 클러스터를 사용하고 있습니다.
* 인증된 클러스터 피어링 관계를 원합니다.
* 사용 가능한 모든 옵션을 탐색하는 것이 아니라 모범 사례를 사용하려고 합니다.
* ONTAP CLI(Command-Line Interface) 또는 자동화된 스크립팅 도구가 아니라 System Manager를 사용하려고 합니다.




== ONTAP에서 이 작업을 수행하는 다른 방법

ONTAP 9.3의 ONTAP System Manager는 클러스터 및 SVM 간에 피어 관계를 구성하는 방법을 단순화합니다. 클러스터 피어링 절차와 SVM 피어링 절차는 모든 ONTAP 9 버전에 사용할 수 있습니다. 해당 버전의 ONTAP에 적합한 절차를 사용해야 합니다.

|===


| 에서 이러한 작업을 수행하려면... | 자세한 내용은... 


 a| 
재설계된 System Manager(ONTAP 9.7 이상에서 사용 가능)
 a| 
* https://docs.netapp.com/us-en/ontap/concept_administration_overview.html["System Manager를 이용한 클러스터 관리"^]




 a| 
ONTAP CLI(명령줄 인터페이스)
 a| 
* https://docs.netapp.com/us-en/ontap/peering/index.html["CLI를 통한 클러스터 및 SVM 피어링 개요"^]
+
명령줄 인터페이스를 사용하여 클러스터 피어링 관계와 SVM 피어링 관계를 설정합니다.

* https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 관리"^]
+
명령줄 인터페이스를 사용하여 서브넷, 인터클러스터 LIF, 라우트, 방화벽 정책 및 기타 네트워킹 구성 요소를 구성합니다



|===