---
permalink: peering/task_preparing_for_cluster_peering.html 
sidebar: sidebar 
keywords: create, creating, cluster, peer, relationship, verify, time, synchronized, external, network, procotol, ntp, server, subnet, port, passphrase, prepare, prepare for cluster peering 
summary: 'ONTAP 9.7 이하 버전의 ONTAP System Manager "클래식" 인터페이스를 사용하여 클러스터 피어링 관계를 생성하기 전에, 각 클러스터의 시간이 외부 NTP(네트워크 시간 프로토콜) 서버와 동기화되는지 확인하고 사용하려는 서브넷, 포트 및 암호 문구를 결정해야 합니다.' 
---
= 클러스터 피어링을 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 이하 버전의 ONTAP System Manager_CLASSIC_INTERFACE를 사용하여 클러스터 피어링 관계를 생성하기 전에, 각 클러스터의 시간이 외부 NTP(네트워크 시간 프로토콜) 서버와 동기화되는지 확인하고 사용하려는 서브넷, 포트 및 암호 문구를 결정해야 합니다.

.단계
. ONTAP 9.2 이하를 실행 중인 경우 각 클러스터 피어 관계에 사용할 암호를 결정합니다.
+
암호는 8자 이상이어야 합니다.

+
|===


| 다음 사이의 관계에 대해... | 암호문은... 


 a| 
클러스터 A 및 클러스터 B
 a| 

|===
+
ONTAP 9.3부터 클러스터 피어 관계를 생성하는 동안 원격 클러스터에서 암호를 생성할 수 있습니다.

+
link:task_creating_cluster_peer_relationship_starting_with_ontap_9_3.html["클러스터 피어 관계 생성(ONTAP 9.3부터 시작)"]

. 인터클러스터 LIF에 사용할 서브넷, IP 주소 및 포트를 식별합니다.
+
기본적으로 IP 주소는 서브넷에서 자동으로 선택됩니다. IP 주소를 수동으로 지정하려면 IP 주소가 서브넷에서 이미 사용 가능한지 또는 나중에 서브넷에 추가될 수 있는지 확인해야 합니다. 서브넷에 대한 정보는 네트워크 탭에서 사용할 수 있습니다.

+
다음 표와 유사한 테이블을 만들어 클러스터에 대한 정보를 기록합니다.  다음 표에서는 각 클러스터에 4개의 노드가 있다고 가정합니다. 클러스터에 노드가 4개 이상인 경우 추가 정보를 위해 행을 추가합니다.

+
|===


|  | 클러스터 A | 클러스터 B 


 a| 
서브넷(ONTAP 9.2 이하)
 a| 
 a| 



 a| 
IP 주소(ONTAP 9.3부터 시작, ONTAP 9.2 이하의 경우 선택 사항)
 a| 
 a| 



 a| 
노드 1 포트
 a| 
 a| 



 a| 
노드 2 포트
 a| 
 a| 



 a| 
노드 3 포트
 a| 
 a| 



 a| 
노드 4 포트
 a| 
 a| 

|===

