---
permalink: volume-backup-snapvault/index.html 
sidebar: sidebar 
keywords: content, configure, snapvault, backup, relationship, volume, cluster, read-only, copies, copy, locate, destination, volume, restoring, restore, data, corrupt, lost, volume backup using snapvault overview 
summary: 서로 다른 클러스터에 있는 볼륨 간에 SnapVault 백업 관계를 빠르게 구성할 수 있습니다. SnapVault 백업에는 데이터가 손상되거나 손실될 때 데이터를 복구하는 데 사용할 수 있는 대상 볼륨에 있는 읽기 전용 백업 복사본 세트가 포함되어 있습니다. 
---
= SnapVault를 사용한 볼륨 백업 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서로 다른 클러스터에 있는 볼륨 간에 SnapVault 백업 관계를 빠르게 구성할 수 있습니다. SnapVault 백업에는 데이터가 손상되거나 손실될 때 데이터를 복구하는 데 사용할 수 있는 대상 볼륨에 있는 읽기 전용 백업 복사본 세트가 포함되어 있습니다.

다음과 같은 방법으로 볼륨에 대한 SnapVault 백업 관계를 생성하려는 경우 이 절차를 사용합니다.

* ONTAP 9를 실행하는 클러스터로 작업하고 있습니다.
* 클러스터 관리자입니다.
* 클러스터 피어 관계 및 SVM 피어 관계를 구성했습니다.
+
link:../peering/index.html["클러스터 및 SVM 피어링 구성"]

* 클러스터의 모든 노드가 동일한 버전의 ONTAP 9로 업그레이드된 후 SnapMirror 또는 SnapVault 라이센스를 활성화해야 합니다.
* 사용자 지정 정책을 생성하지 않고 기본 보호 정책 및 스케줄을 사용하려는 경우
* 단일 파일 또는 LUN 복원을 위한 데이터를 백업하지 않습니다.
* 사용 가능한 모든 옵션을 탐색하는 것이 아니라 모범 사례를 사용하려고 합니다.
* 많은 개념적 배경을 읽고 싶지 않습니다.
* ONTAP 명령줄 인터페이스 또는 자동화된 스크립팅 도구가 아니라 System Manager를 사용하려고 합니다.
* ONTAP 9.7 이상을 위한 ONTAP 시스템 관리자 UI가 아니라 ONTAP 9.7 이전 릴리즈용 System Manager 클래식 인터페이스를 사용하려는 경우


이러한 가정이 현재 상황에 맞지 않거나 보다 개념적인 배경 정보를 원하는 경우 다음 리소스를 참조하십시오.

link:http://www.netapp.com/us/media/tr-4183.pdf["NetApp 기술 보고서 4183: SnapVault 모범 사례"^]



== ONTAP에서 이 작업을 수행하는 다른 방법

[cols="2"]
|===
| 에서 이러한 작업을 수행하려면... | 이 콘텐츠 보기... 


| 재설계된 System Manager(ONTAP 9.7 이상에서 사용 가능) | link:https://docs.netapp.com/us-en/ontap/task_dp_configure_mirror.html["미러와 볼트를 구성합니다"^] 


| ONTAP 명령줄 인터페이스입니다 | link:https://docs.netapp.com/us-en/ontap/data-protection/create-replication-relationship-task.html["복제 관계를 생성합니다"^] 
|===