---
permalink: nas-multiprotocol-config/task_verifying_nfs_access_from_unix_administration_host.html 
sidebar: sidebar 
keywords: configure, nfs, access, storage, virtual, machine, svm, configuration, administration, host, read, data, verify, verify nfs access from a unix administration host 
summary: 'SVM(Storage Virtual Machine)에 대한 NFS 액세스를 구성한 후에는 NFS 관리 호스트에 로그인하고 SVM에서 데이터를 읽고 쓰는 방법으로 구성을 확인해야 합니다.' 
---
= UNIX 관리 호스트에서 NFS 액세스를 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(Storage Virtual Machine)에 대한 NFS 액세스를 구성한 후에는 NFS 관리 호스트에 로그인하고 SVM에서 데이터를 읽고 쓰는 방법으로 구성을 확인해야 합니다.

.시작하기 전에
* 클라이언트 시스템에는 이전에 지정한 내보내기 규칙에서 허용하는 IP 주소가 있어야 합니다.
* 루트 사용자에 대한 로그인 정보가 있어야 합니다.


.단계
. 클라이언트 시스템에 루트 사용자로 로그인합니다.
. 를 입력합니다 `cd /mnt/` 디렉토리를 마운트 폴더로 변경합니다.
. SVM의 IP 주소를 사용하여 새 폴더를 생성하고 마운트합니다.
+
.. 를 입력합니다 `mkdir /mnt/folder` 를 눌러 새 폴더를 만듭니다.
.. 를 입력합니다 `mount -t nfs -o nfsvers=3,hard IPAddress:/volume_name /mnt/folder` 이 새 디렉토리에 볼륨을 마운트합니다.
.. 를 입력합니다 `cd folder` 디렉토리를 새 폴더로 변경합니다.
+
다음 명령을 실행하면 test1이라는 폴더가 생성됩니다. test1 마운트 폴더의 192.0.2.130 IP 주소에 vol1 볼륨을 마운트하고 새 test1 디렉토리로 변경합니다.

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o nfsvers=3,hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. 새 파일을 만들고 파일이 있는지 확인한 후 다음 파일에 텍스트를 씁니다.
+
.. 를 입력합니다 `touch filename` 테스트 파일을 만듭니다.
.. 를 입력합니다 `ls -l filename` 파일이 있는지 확인합니다.
.. 를 입력합니다 `cat >filename`를 클릭하고 텍스트를 입력한 다음 Ctrl+D를 눌러 테스트 파일에 텍스트를 씁니다.
.. 를 입력합니다 `cat filename` 테스트 파일의 내용을 표시합니다.
.. 를 입력합니다 `rm filename` 테스트 파일을 제거합니다.
.. 를 입력합니다 `cd ..` 를 눌러 상위 디렉토리로 돌아갑니다.


+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


.결과
SVM에 대한 NFS 액세스를 설정했음을 확인했습니다.
