---
permalink: expansion/task_adding_nodes_to_cluster_using_system_manager.html 
sidebar: sidebar 
keywords: system, manager, increase, size, capabilities, capability, storage, node, automatic, ontap, add nodes to a cluster using system manager 
summary: System Manager를 사용하면 기존 클러스터에 노드를 추가하여 스토리지 시스템의 크기와 기능을 높일 수 있습니다. 유효 클러스터 버전이 ONTAP 9.2인 경우 System Manager에서 이 기능이 자동으로 활성화됩니다. 
---
= System Manager를 사용하여 클러스터에 노드를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager를 사용하면 기존 클러스터에 노드를 추가하여 스토리지 시스템의 크기와 기능을 높일 수 있습니다. 유효 클러스터 버전이 ONTAP 9.2인 경우 System Manager에서 이 기능이 자동으로 활성화됩니다.

.시작하기 전에
* 호환되는 새 노드를 클러스터에 케이블로 연결해야 합니다.
+
기본 브로드캐스트 도메인에 있는 포트만 네트워크 창에 나열됩니다.

* 클러스터의 모든 노드가 실행 중이어야 합니다.
* 모든 노드의 버전은 동일해야 합니다.


.단계
. 클러스터에 호환되는 새 노드를 추가합니다.
+
[cols="1,3"]
|===


| 만약... | 수행할 작업... 


 a| 
System Manager에 로그인하지 않았습니다
 a| 
.. System Manager에 로그인합니다.
+
[NOTE]
====
로그인 시 System Manager에서 호환되는 새 노드를 자동으로 감지합니다. System Manager에서 클러스터에 호환되는 새 노드를 추가하라는 메시지가 표시됩니다.

====
.. 클러스터에 노드 추가 * 를 클릭합니다.
.. 노드의 이름을 수정합니다.
.. 노드 라이센스를 지정합니다.
.. 제출 및 진행 * 을 클릭합니다.




 a| 
System Manager에 로그인했습니다
 a| 
.. 실행 중인 System Manager 버전에 따라 다음 단계 중 하나를 수행하십시오.
+
*** ONTAP 9.4 이하: * 구성 * > * 클러스터 확장 * 을 클릭합니다.
*** ONTAP 9.5부터: * 구성 * > * 클러스터 * > * 확장 * 을 클릭합니다
System Manager에서 새로 추가된 노드를 검색합니다. 경고가 표시되면 계속하기 전에 이를 수정해야 합니다. 호환되는 새 노드가 검색되면 다음 단계를 진행하십시오.


.. 노드의 이름을 수정합니다.
.. 노드 라이센스를 지정합니다.
.. 제출 및 진행 * 을 클릭합니다.


|===

