---
permalink: volume-disaster-prep/index.html 
sidebar: sidebar 
keywords: content, protect, source, volume, peer, ontap, cluster, preparation, disaster, recovery, configure, monitor, snapmirror, relationship, background, task, volume disaster recovery preparation overview 
summary: 재해 복구 준비를 위해 피어링된 ONTAP 클러스터에서 소스 볼륨을 빠르게 보호할 수 있습니다. 볼륨 재해 복구를 위해 피어링된 클러스터 간에 SnapMirror 관계를 구성 및 모니터링하려는 경우 이 콘텐츠를 사용해야 하며 작업에 대한 많은 개념적 배경이 필요하지 않습니다. 
---
= 볼륨 재해 복구 준비 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해 복구 준비를 위해 피어링된 ONTAP 클러스터에서 소스 볼륨을 빠르게 보호할 수 있습니다. 볼륨 재해 복구를 위해 피어링된 클러스터 간의 SnapMirror 관계를 구성하고 모니터링하려는 경우 이 절차를 사용해야 하며 작업에 대한 많은 개념적 배경이 필요하지 않습니다.

SnapMirror는 예약된 비동기식 블록 레벨 데이터 보호를 제공합니다. SnapMirror는 스냅샷 복사본을 복제하고 Qtree 및 LUN이 포함된 볼륨을 포함하여 중복제거, 데이터 압축 또는 둘 다 실행되는 NAS 또는 SAN 볼륨을 복제할 수 있습니다. SnapMirror 구성 정보는 ONTAP에서 클러스터의 모든 노드에 복제하는 데이터베이스에 저장됩니다.

다음 방법으로 볼륨 레벨 재해 복구를 위한 SnapMirror 관계를 생성하려는 경우 이 절차를 사용합니다.

* ONTAP 9를 실행하는 클러스터로 작업하고 있습니다.
* 클러스터 관리자입니다.
* 클러스터 피어 관계 및 SVM 피어 관계를 구성했습니다.
+
link:../peering/index.html["클러스터 및 SVM 피어링 구성"]

* 소스 및 대상 클러스터 모두에서 SnapMirror 라이센스를 활성화했습니다.
* 사용자 지정 정책을 만들지 않고 기본 정책 및 일정을 사용하려고 합니다.
* 사용 가능한 모든 옵션(ONTAP 9.7 이하)을 탐색하는 것이 아니라 모범 사례를 활용하고자 합니다.




== ONTAP에서 이 작업을 수행하는 다른 방법

|===


| 에서 이러한 작업을 수행하려면... | 자세한 내용은... 


| 재설계된 System Manager(ONTAP 9.7 이상에서 사용 가능) | link:https://docs.netapp.com/us-en/ontap/task_dp_prepare_mirror.html["미러링 및 보관 준비"^] 


| ONTAP 명령줄 인터페이스입니다 | link:https://docs.netapp.com/us-en/ontap/peering/create-cluster-relationship-93-later-task.html["클러스터 피어 관계 생성(ONTAP 9.3 이상)"^] 
|===